### ISSUE TITLE
New Component: ToggleList

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivesearch#1]
### Component Props

- **componentId** `String`  
    component ID.
- **appbaseField** `String`  
    DB field to be mapped for the query.
- **title** `String`  
    title of the component, optional.
- **data** `Object Array`  
    an object array of {label:label, value:value} kv pairs, label is displayed in the UI and value is the corresponding actual field value in the database. `Note`: label can be specified as either `String` or `HTML`.
- **multiSelect** `Boolean`  
    whether to allow multiple selections, `true` by default. 
- **defaultSelected** `String` or `Array`  
    pre-selected values, specified as one of String or Array type.
- **showCount** `Boolean`  
    whether to show the count next to the data label.

### CSS Styles API

`rbc-count-active`
`rbc-multiselect-active`
`rbc-title-active`

### Stories

1. Basic story
2. Story with passing label as a HTML markup
3. Without title attribute
4. With default Selected values
5. In a dark theme
6. Playground.

**Comment by metagrover** [comment]
Added here: 36d936bd96f87cdb56fa839473b4c8f547afd421 b53a132a44f4e07991f01297eef0387198c933ba
