### ISSUE TITLE
DynamicRangeSlider bug when no results

### ISSUE THREAD

**Issue by joergac** [appbaseio/reactivesearch#1001]
**Issue Type:**
bug

**Platform:**
web

**Description:**
When you search for something that returns no results, dynamicrangeslider's values (min+max) are set to 0. Removing the search should display all results but instead show no results since the mix and max are still set to zero.

**Minimal reproduction of the problem with instructions:**
https://codesandbox.io/embed/dynamicrangeslider-915dp

1. Open sandbox and search for something that returns no results.
2. Notice that SelectedFilters show 0,0 for the slider. (It shouldn't since I did not touch the slider)
![image](https://user-images.githubusercontent.com/47501888/58462355-61c69000-813a-11e9-979d-508e13a64d6c.png)
3. Remove both filters by using the X icon on the right of each one. (or use clear all)
![image](https://user-images.githubusercontent.com/47501888/58462386-7440c980-813a-11e9-99f7-74a06bd02d00.png)
4. Simply click on the slider
![image](https://user-images.githubusercontent.com/47501888/58462426-89b5f380-813a-11e9-8b28-5956cd2e0cc8.png)

**Reactivesearch version:** x.y.z
3.0.0-rc12

**Browser:** all

**Anything else:**
I think this is somewhat related to https://github.com/appbaseio/reactivesearch/issues/997. The slider updates when it shouldn't.

**Comment by bietkul** [comment]
Duplicates to #739
