### ISSUE TITLE
DynamicRangeSlider onChange is never called

### ISSUE THREAD

**Issue by joergac** [appbaseio/reactivesearch#1004]
**Issue Type:**
bug

**Platform:**
Web

**Description:**
The onChange method mentioned in the docs in never called on the DynamicRangeSlider component.

**Minimal reproduction of the problem with instructions:**
https://codesandbox.io/embed/dynamicrangeslider-iflh8

**Reactivesearch version:** x.y.z
3.0.0-rc12

**Browser:** all

**Comment by bietkul** [comment]
`onChange` must be used with `value` prop to implement the controlled behavior of components.
You should use `onValueChange` instead.
