### ISSUE TITLE
DynamicRangeSlider labels on SelectedFilters

### ISSUE THREAD

**Issue by joergac** [appbaseio/reactivesearch#1005]
**Issue Type:**
enhancement

**Platform:**
Web

**Description:**
Right now, there is no way to specify the labels of a DynamicRangeSlider on SelectedFilters. This is usually done using the `filterLabel` prop but is seems like it is not implemented yet. 

We could possibly use the already defined `rangeLabels` to avoid having to duplicate the labels.

I am using the slider to show prices and on the slider itself I am adding the currency symbol and making the to appear with 2 decimal points. I cannot use this right now since it will appear without currency symbol and no decimal points. 

**Screenshots:**

**Minimal reproduction of the problem with instructions:**

**Reactivesearch version:** x.y.z
3.0.0-rc12

**Browser:** all

**Anything else:**

**Comment by bietkul** [comment]
I think we can define one more prop `filterValue` which can be used by `SelectedFilters` component to render the custom filter values.

For example:

```
<DynamicRangeSlider
  filterValue={value => `${value} ₹`}
/>
```
What do you think?
@siddharthlatest @lakhansamani

**Comment by siddharthlatest** [comment]
> We could possibly use the already defined `rangeLabels` to avoid having to duplicate the labels.

This won't serve the purpose as they are the bounds, not the current values.

You can use the `render` prop of SelectedFilters to customize the label here. https://github.com/appbaseio/reactivesearch/blob/dev/packages/web/examples/CustomSelectedFilters/src/index.js.
