### ISSUE TITLE
Enhancement: Built-in support for search operators in *Search components

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivesearch#1006]
**Issue Type:**

Enhancement

**Platform:**

Web, applies to Native as well

**Description:**

We should support a prop, e.g. `searchOperators` which when set to true will use a [simple query string query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-simple-query-string-query.html) that offers built-in support of search operators similar to Google Search, e.g. + signifies AND operator, - signifies NOT operator, " signify to search for phrases, ( ) determine precedence and so on.

Re: prop syntax, one other option is to use the existing `queryFormat` prop and allow passing the value as "operators" to modify the query.

Note: This is already possible to do right now by using the `customQuery` / `defaultQuery` props, but this issue proposes to simplify the usage to be driven by a prop given how common the use-case can be.

**Reactivesearch version:**

3.0.0-rc.12

**Comment by joepio** [comment]
I've implemented something [similar](https://github.com/ontola/ori-search/blob/master/front/src/Components/SearchBar.tsx) in our project, but instead of having a prop that changes, I parse the query and if it contains special characters, I switch to `simple_query_string`.

**Comment by bietkul** [comment]
@joepio Great, from now on you can use `searchOperators` prop to achieve the same behavior.
