### ISSUE TITLE
v3: ReactiveList.onData doesn't always fire

### ISSUE THREAD

**Issue by csepulv** [appbaseio/reactivesearch#1007]
**Issue Type:**
Possible Bug

**Platform:**
Web

**Description:**
in `ReactiveList`, the `onData` callback is not called when `resultStats` change, but hits don't.

In `componentDidUpdate`, it is checking if a limited subset of props change.  But this list doesn't include the total number of items available.

See https://github.com/appbaseio/reactivesearch/blob/255e5a905f275a49490266bdf396b286950dc84d/packages/web/src/components/result/ReactiveList.js#L162-L170

Is this expected behavior? 

If you apply a filter, but the current page of results don't change, the total (i.e. result stats) will change, but current hits might not. I was trying to use `onData` to subscribe to change in data and resultStats, to use this info elsewhere. But onData doesn't fire as noted.

**Reactivesearch version:** x.y.z
`next` branch

**Comment by bietkul** [comment]
It's been fixed in the latest release.
