### ISSUE TITLE
No results in local ElasticSearch setup with VueJS

### ISSUE THREAD

**Issue by bitbit-gmbh** [appbaseio/reactivesearch#1012]
I can connect successfully to my local ElasticSearch instance, but I receive no results within my VueAPP.

This is my setup:

package.json:

"dependencies": {
    "@appbaseio/reactivesearch": "^3.0.0-rc.13",
    "core-js": "^2.6.5",
    "vue": "^2.6.10"
  },

I'm using ReactiveSearch for Web.

This is my local ElasticSearch Instance:

![2019-06-13_17h38_05](https://user-images.githubusercontent.com/9974678/59446547-02d36d00-8e02-11e9-82ac-b1a667477405.png)

This is an example GET on my local Instance:

GET localhost:9200/ssy_hafen/_search

![2019-06-13_17h39_59](https://user-images.githubusercontent.com/9974678/59446693-47f79f00-8e02-11e9-9d27-6cd7ea86a949.png)

And this is my VUE template:

![2019-06-13_17h50_40](https://user-images.githubusercontent.com/9974678/59447597-ca349300-8e03-11e9-8606-2cbdc68e26b6.png)

The Browser only outputs "Multilist", but nothing else on the page

I receive no console error, only when I change the url or the app to something which is not working.

Connecting to the example index from appbase.io in the getting Started Tutorial is working without problems. It will show the multi-list.

I'm on Firefox 67, Windows 10 with a locale nodejs Installation.

What am I'm doing wrong?

**Comment by mauxtin** [comment]
You have to use reactivesearch-vue, not reactivesearch.

https://www.npmjs.com/package/@appbaseio/reactivesearch-vue

**Comment by mauxtin** [comment]
You have to use reactivesearch-vue, not reactivesearch.

https://www.npmjs.com/package/@appbaseio/reactivesearch-vue

**Comment by bitbit-gmbh** [comment]
Ok, thanks, at least I get some results on "id_ssy_land". But when I use for example "hafen_ort" as dataField, I receive the following error in the console:

![image](https://user-images.githubusercontent.com/9974678/59610905-a3839e80-911a-11e9-83f6-2b6b2d126a51.png)

**Comment by mauxtin** [comment]
I cannot see an actual error there. Try checking the http response in the network tab.

**Comment by siddharthlatest** [comment]
@Dreamfish19 Can you share a codesandbox showing the issue?

**Comment by bitbit-gmbh** [comment]
@siddharthlatest Thanks for your support, it is running for now :-)
