### ISSUE TITLE
"TypeError: renderData is not a function" when renderDataAll

### ISSUE THREAD

**Issue by jrishabh55** [appbaseio/reactivesearch#1018]
**Issue Type:**
BUG

**Platform:**
WEB - vue

**Description:**
When using result components like reactive list, renderData is required event when we pass renderAllData function/slot element

above example with throw error
```
[Vue warn]: Error in render: "TypeError: renderData is not a function"
```

**Screenshots:**

http://prntscr.com/o3em5l

**Minimal reproduction of the problem with instructions:**

```
   <ReactiveList
            :react="{ and: ['column'] }"
            dataField="data_filed"
            componentId="componentId"
            sortBy="sortColumn"
            pagination
            :showResultStats="false"
            :renderDataAll="someFunction"
    />
```
-->

**Reactivesearch version:**  appbaseio/reactivesearch-vue@^1.0.0-beta.15

**Comment by mauxtin** [comment]
Try this
```
   <ReactiveList
            :react="{ and: ['column'] }"
            dataField="data_filed"
            componentId="componentId"
            sortBy="sortColumn"
            pagination
            :showResultStats="false"
    >
                    <div
                        slot="renderData"
                        slot-scope="{ item }"
                        :key="item._id"
                    >
                       {{ item }} 
                    </div>
   </ReactiveList>

```

**Comment by jrishabh55** [comment]
hey @mauxtin thanks for the reply,
Actually, this issue is not about a workaround, onAllResult has its own usages and its not working as it should, 

if renderAllResult is preset the lib should use it instead of throwing an error that renderResult is not a function

**Comment by bietkul** [comment]
@jrishabh55 We haven't defined typings for ReactiveSearch Vue, that is why you're getting this error.

**Comment by jrishabh55** [comment]
hey, @bietkul shouldn't this still work? I mean the renderAllResult doesn't get executed at all after the error comes up, Sorry for being so ignorant but as a user, i would still expect it to work even if types are not available it is used in vue component written in JS not TS

**Comment by bietkul** [comment]
It is `renderAllData` and it'll work well if you're not using Vue typescript.
Check the docs with the example [here](https://opensource.appbase.io/reactive-manual/vue/result-components/reactivelist.html)

**Comment by jrishabh55** [comment]
Hey,
yeah sorry for the wrong name, but yeah it actually never gets called, not sure why,

**Comment by bietkul** [comment]
Check this example [here](https://codesandbox.io/s/reactive-list-lclem)
