### ISSUE TITLE
Connecting to local Elastic cluster

### ISSUE THREAD

**Issue by cperlaAFX** [appbaseio/reactivesearch#1019]
I am unable to connect my reactivesearch app to a vanilla version of Elasticsearch running on my local machine despite following the documentation (ES version 6.4.3).

I am using node.js and reactivesearch for web following the book search tutorial: https://codeburst.io/how-to-build-an-e-commerce-search-ui-with-react-and-elasticsearch-a581c823b2c3. I have added the following configuration to my elasticsearch.yml file per the official reactivesearch documentation.

http.cors.enabled: true
http.cors.allow-credentials: true
http.cors.allow-origin: "http://reactive-search-app-domain.com:port"
http.cors.allow-headers: X-Requested-With, X-Auth-Token, Content-Type, Content-Length, Authorization, Access-Control-Allow-Headers, Accept

<ReactiveBase
        app="book_index"
	url="http://localhost:9200/"
      >
![es_connection_error](https://user-images.githubusercontent.com/42974293/59788207-3c402880-9299-11e9-9017-ef66b3e9cb6d.PNG)

**Comment by siddharthlatest** [comment]
@cperlaAFX Can you share the browser's console log and the specific error from the network request?

**Comment by cperlaAFX** [comment]
Here is the browser's console logs. I don't get a specific error when running npm start but am unable to search the app at localhost:3000.

index.js:1375 Warning: Unknown event handler property `onData`. It will be ignored.
    in a (created by Styled(a))
    in Styled(a) (created by ResultCard)
    in ResultCard (at App.js:49)
    in div (at App.js:48)
    in div (at App.js:34)
    in div (created by Styled(div))
    in Styled(div) (created by URLParamsProvider)
    in URLParamsProvider
    in Unknown (created by ConnectFunction)
    in ConnectFunction (created by ForwardRef)
    in ForwardRef (created by ReactiveBase)
    in Provider (created by ReactiveBase)
    in ThemeProvider (created by ReactiveBase)
    in ReactiveBase (at App.js:13)
    in App (at src/index.js:7)

**Comment by siddharthlatest** [comment]
@cperlaAFX Looking at the logs, there doesn't seem to be a connection issue. However, you are using the code syntax for v2.x with v3.x of the library. If you want to leave the code unchanged, you can switch to using v2.x. Otherwise, I would recommend reading the docs for the replacement of the `onData` method - https://opensource.appbase.io/reactive-manual/advanced/migrationguide.html.
