### ISSUE TITLE
Custom pagination in ReactiveList

### ISSUE THREAD

**Issue by oshiniG** [appbaseio/reactivesearch#1023]
Can user put custom button to load the data as "show more" and "show less" rather than using pagination in ReactiveList?

**Comment by bietkul** [comment]
You can set `infiniteScroll` and `pagination` prop as `false` in `ReactiveList`, it'll hide the default pagination.
You can use a custom `render` function to define the custom UI.
Check [here](https://opensource.appbase.io/reactive-manual/result-components/reactivelist.html#extending)
