### ISSUE TITLE
SSR fails with sortOptions in ReactiveList

### ISSUE THREAD

**Issue by multidis** [appbaseio/reactivesearch#1024]
**Issue Type:** bug

**Platform:** Web

**Description:**
When `sortOptions` prop is passed to `ReactiveList` it fails with server-side rendering. The error traces to "only used for SSR" - commented code block [here](https://github.com/appbaseio/reactivesearch/blob/next/packages/web/src/components/result/ReactiveList.js#L435).

> Uncaught (in promise) TypeError: Cannot read property 'sortOptionIndex' of undefined

`options.sort = [(_ref10 = {}, _ref10[props.sortOptions[undefined.sortOptionIndex].dataField] =`

**Screenshots:**

**Minimal reproduction of the problem with instructions:**

Working example without `sortOptions` prop (`master`-branch):
https://github.com/multidis/reactivesearch_gatsby

Failing example with `sortOptions` prop: switch to the `sorting` branch where an array or sorting options was [added](https://github.com/multidis/reactivesearch_gatsby/commit/1849ddf03a7da395650436150903426f7214b9ef)

**Reactivesearch version:** 3.0.0-rc.15

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**

This example is based on the following issue originally resolved with reactivesearch v2:
https://github.com/gatsbyjs/gatsby/issues/10556

Relevant stacktrace:

> ReactiveList.js:507 Uncaught (in promise) TypeError: Cannot read property 'sortOptionIndex' of undefined
    at Object../node_modules/@appbaseio/reactivesearch/lib/components/result/ReactiveList.js.ReactiveList.generateQueryOptions (ReactiveList.js:507)
    at index.js:130
    at Array.forEach (<anonymous>)
    at index.js:103
    at new Promise (<anonymous>)
    at initReactivesearch (index.js:80)
    at SearchReactive._callee$ (SearchReactive.js:63)
    at tryCatch (runtime.js:45)
    ...

**Comment by bietkul** [comment]
Thanks for reporting it, it'll be fixed soon.

**Comment by arpithparikh** [comment]
This still persists with the SSR Next.js
