### ISSUE TITLE
onData not working with ReactiveComponent

### ISSUE THREAD

**Issue by DustinKLo** [appbaseio/reactivesearch#1025]
**Issue Type:** Bug

**Platform:** Web

**Description:**
the `onData` function is not working in `ReactiveComponent`

**Reactivesearch version:** 3.0.0-rc.15

```
<ReactiveComponent
  componentId={this.props.mapComponentId}
  URLParams={true}
  onData={(data, rawData, aggregations) => {
    console.log(data);
    console.log(rawData);
    console.log(aggregations);
  }}
  onQueryChange={(prev, next) => { console.log('Queries', prev, next); }}
  render={({ setQuery, value }) => {
    return (
      <MapComponent
        setQuery={setQuery}
        setPolygon={value}
        defaultZoom={this.props.defaultZoom}
        maxZoom={this.props.maxZoom}
        minZoom={this.props.minZoom}
      />
    );
  }}
></ReactiveComponent>
```

i've tried `onData={(data, rawData, aggregations) =>` and `onData={({data, rawData, aggregations})) =>` and neither work
`onQueryChange` is not working either

**Comment by DustinKLo** [comment]
Is there any other way to pass the queried data into `ReactiveComponent`, i see that `onData` is deprecated.

**Comment by bietkul** [comment]
@DustinKLo It seems to work [here](https://opensource.appbase.io/playground/?knob-debounce=300&knob-title=DataSearch%3A%20Books...&knob-weights%5B0%5D=1&knob-weights%5B1%5D=3&knob-filterLabel=Books%20filter&knob-defaultSelected=&knob-queryFormat=or&knob-URLParams%20%28not%20visible%20on%20storybook%29=true&knob-showFilter=true&knob-dataField%5B0%5D=original_title&knob-dataField%5B1%5D=original_title.search&knob-iconPosition=left&knob-showClear=true&knob-fuzziness=1&knob-placeholder=Search%20Books...&knob-autosuggest=true&selectedKind=Base%20components%2FReactiveComponent&selectedStory=with%20onData&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel).
FYI, `onData` will only be triggered when you change the `ReactiveComponent`'s defaultQuery (internal query), it won't be called when you use `setQuery`.
It'll be triggered when you change the `defaultQuery` prop in ReactiveComponent.

**Comment by DustinKLo** [comment]
Can `onData` work with `customQuery`, i need the custom `ReactiveComponent` to also be able to further filter on the main Elasticsearch query DSL
Examples I've found on `defaultQuery` looks like it doesn't touch the main query DSL

Is there a workaround so i can pass the query DSL into my custom component, since `onQueryChange` doesnt work either?
thanks!

**Comment by bietkul** [comment]
> Can `onData` work with `customQuery`, i need the custom `ReactiveComponent` to also be able to further filter on the main Elasticsearch query DSL

No, `setQuery` and `customQuery` does the same thing.
You can use the `react` prop in your custom component, in that way it'll be affected by the `ReactiveComponent`'s query.

For example,

```
<ReactiveComponent
  componentId="Reactive_Component"
  customQuery={() => ({
     query: {
         terms: "XYZ"
     }
  })}
/>
``` 
In your custom component you can use `onData`
```
<ReactiveList
  react={{ and: 'Reactive_Component'}}
  onData={(data) => { console.log(data); }}
/>
```

**Comment by DustinKLo** [comment]
Unfortunately i need to send the data to my `ReactiveComponent`, but thank you for clarifying
is there any plans in the future to trigger `onData` with a `customQuery`?

**Comment by bietkul** [comment]
I can better help you if you can explain the use-case with some code sandbox example.

**Comment by DustinKLo** [comment]
That would be great thank you so much

**Comment by DustinKLo** [comment]
My use case is I'm using a leaflet map (https://react-leaflet.js.org/) and leaflet draw tools (https://github.com/alex3165/react-leaflet-draw) to create bounding boxes that allow to filter in elasticsearch.
the map acts as both a `ReactiveComponent` and also displays map images on the leaflet map itself

<img width="783" alt="Screen Shot 2019-06-24 at 1 37 00 AM" src="https://user-images.githubusercontent.com/13371881/60003982-9a199b00-9620-11e9-9c88-a9174063f912.png">

**Comment by bietkul** [comment]
I think you just need to use the `defaultQuery` prop instead of  `setQuery`  in `ReactiveComponent`.
Update the `defaultQuery` when you want to change the query and `onData` will work as you expect.

**Comment by DustinKLo** [comment]
thank you @bietkul  i'll give it a shot

**Comment by DustinKLo** [comment]
I don't think `defaultQuery` works because it doesn't further filter my results based on the polygon, I can only use `customQuery` for this use case unfortunately,
is there a workaround to maybe pass the entire query into my custom component?

**Comment by DustinKLo** [comment]
I found a workaround, create a function in the parent component which is passed into the `<ReactiveList>` component, retrieve the data and store it as a state and pass it into the custom `<ReactiveComponent>`

**Comment by bietkul** [comment]
It seems like an issue with the uses, so closing it for now.
Feel free to re-open.
