### ISSUE TITLE
[Vue] ReactiveBase setState not defined

### ISSUE THREAD

**Issue by edcoreweb** [appbaseio/reactivesearch#1028]
**Issue Type:**
Bug

**Platform:**
Web: Vue.JS

**Description:**
When making the app prop reactive on the ReactiveBase component, an unknown function is called: **setState** (maybe a remnant from React ?)
https://github.com/appbaseio/reactivesearch/blob/ddef5200a675594beae050a0922ba4bb6219dd50/packages/vue/src/components/ReactiveBase/index.jsx#L68

**Minimal reproduction of the problem with instructions:**
See below:
https://codesandbox.io/s/data-search-4no8n?fontsize=14

**Reactivesearch version:** x.y.z
@appbaseio/reactivesearch-vue": "^1.0.0-beta.15

**Browser:**
all

**Anything else:**
Would create a pull request if only removing the line is the correct fix.

**Comment by bietkul** [comment]
It seems like a bug, we'll fix it soon.
