### ISSUE TITLE
Intermittent spurious requests on ReactiveList select/deselect when combined with RangeSlider/RangeInput

### ISSUE THREAD

**Issue by adadiehl** [appbaseio/reactivesearch#1029]
**Issue Type:**

bug

**Platform:**

Native

**Description:**

I am intermittently seeing an extra query fire when selecting/deselecting an item in a ReactiveList component. This usually (but not always) happens only on the first selection, and the default "match_all" query is launched, followed by the new query. Since the new query returns a smaller result set, it loads briefly before being replaced with the match_all results. Strangely, this only seems to happen when I include either the RangeSlider or RangeInput component in addition to the ReactiveList.

**Comment by siddharthlatest** [comment]
@adadiehl Can you share a code sandbox where this behavior can be replicated?
