### ISSUE TITLE
CategorySearch in Vue?

### ISSUE THREAD

**Issue by bitbit-gmbh** [appbaseio/reactivesearch#1032]
Hey,

are there any plans to implement category search in Vue, or is there a workaround for the DataSearch Component?

My goal is to autosuggest CategoryResults like this:

Input in SearchField: Harry Potter

AutoSuggest:

**Books**
- Title 1
- Title 2

**Movies**
- Title 1
- Title 2

**Comment by bietkul** [comment]
I think for now you can use `renderAllSuggestions` to render custom suggestions.
Check the docs [here](https://opensource.appbase.io/reactive-manual/vue/search-components/datasearch.html#props).
