### ISSUE TITLE
[Question about Datasearch]

### ISSUE THREAD

**Issue by TopHatMan** [appbaseio/reactivesearch#1033]
I have a data search in my header and I want to be there for users to search data. But when I try to customize the render. The dropdown css breaks and just pushes my header down. Is there a better way to customize the highlighted data and list all of the details?

**Comment by bietkul** [comment]
You can use `render` prop in `DataSearch` to display the custom suggestions UI.

**Comment by TopHatMan** [comment]
When I do that thats when the header gets pushed back by the dropdown menu. As well as basic css breaks.
