### ISSUE TITLE
Bug with modal components

### ISSUE THREAD

**Issue by batFormat** [appbaseio/reactivesearch#1051]
**Affected Projects**
React

**Library Version:** 3.0.0-rc.19

**Describe the bug**
My sensor components are in a modal window that opens and closes.

When I open the window I can use filters and they work.

But as soon as I close the modal window, the state that I set in the filters is reset.

Please tell me how can I solve this problem?

**Comment by jyash97** [comment]
Hey @batFormat  
When you close the Modal is the modal might be getting removed from DOM and so ReactiveSearch components are unmounted as the content is removed from DOM. So ideally you will need to use css for hiding the Modal.

**Comment by batFormat** [comment]
@jyash97 
Is there any other way?
I think my logic does not allow me to hide a modal window through css?

**Comment by batFormat** [comment]
But could you tell me how you can load the initial state of the components, for example, from the URL, considering that the sensor(SingleList, DataSearch, etc...) components are not mounted to the DOM (they are mounted only if the modal window is open)
