### ISSUE TITLE
Clearing filters when a DynamicRangeSlider is present doesn't return all results to List

### ISSUE THREAD

**Issue by stefanlesik** [appbaseio/reactivesearch#1054]
Affected Projects
React

Library Version:
3.0.0-rc.20

Describe the bug
Clearing filters when a DynamicRangeSlider is present doesn't return all results to List

To Reproduce
Sandbox:
https://codesandbox.io/embed/eager-leftpad-mhrp4

1. Enter search term "The Illearth War". Hit Enter.
2. Click 'Clear All'

Expected behavior
Should be returned to initial state with all products in view

Macbook
Chrome

**Comment by ebytton** [comment]
is there any workaround for this issue? I am able to reproduce the problem with 3.0.0-rc.23

Thanks

**Comment by ebytton** [comment]
This workaround worked for me. 

` <DynamicRangeSlider
          dataField="ratings_count"
          componentId="BookSensor"
          showFilter={false}
          beforeValueChange={
            function (value) {
              return new Promise((resolve, reject) => {
                if (value.start === value.end) {
                  reject()
                } else {
                  resolve()
                }
              })
            }
          }
          react={{
            and: ["title"]
          }}
        />`
Do not update the range if start == end.
