### ISSUE TITLE
vue: renderAllSuggestions throws an error

### ISSUE THREAD

**Issue by mauxtin** [appbaseio/reactivesearch#1055]
**Affected Projects**
Vue.JS

**Library Version:** x.y.z
v1.0.0-beta.17

**Describe the bug**
In a attempt to solve this https://github.com/appbaseio/reactivesearch/issues/1002#issuecomment-511516296 I tried to use the `renderAllSuggestions` on the `Datasearch` component.
When overriding the `renderAllSuggestions` method, an error is thrown.
`[Vue warn]: Error in render: "TypeError: Cannot read property 'suggestions' of undefined"`

I simply added this in the `Datasearch` demo you have in the docs.
```
  :render-all-suggestions="(data)=>({
    label: `${suggestion._source.original_title} by ${suggestion._source.authors}`,
    value: suggestion._source.original_title,
    source: suggestion._source  // for onValueSelected to work with renderSuggestion
  })"
```
**To Reproduce**
https://codesandbox.io/s/data-search-z8r2w

**Comment by bietkul** [comment]
@mauxtin Fixed in the latest version, you can check the example [here](https://github.com/appbaseio/reactivesearch/tree/next/packages/vue/examples/data-search-custom-suggestions).
