### ISSUE TITLE
How To Create My Own Component in Reactivesearch??

### ISSUE THREAD

**Issue by ashwini987** [appbaseio/reactivesearch#106]
Hello Everyone,
I want to create my own component in Reactivesearch which is same as a "MultiList".
I just want to change the name of component and functionality of it same as a "MultiList" because of I want to apply external CSS on it but it's apply on all.
Can you provide me some help regarding it??
Thanks Regards.

**Comment by siddharthlatest** [comment]
@ashwini987 not sure I understand the use-case. Why can't you use the `style` prop or `className` prop of MultiList?

**Comment by ashwini987** [comment]
Can you please give me example of it, to provide style prop or className prop on component??
Because I can understand what you say, but I don't konw how to apply it.

**Comment by siddharthlatest** [comment]
@ashwini987 Here is an example where I am using the `style` prop with MultiList https://codepen.io/sids-aquarius/pen/OxePea?editors=0010. 

You can also see a code section about the props in the [docs](https://opensource.appbase.io/reactive-manual/v1/components/MultiList.html#multilist-extending). `className` is a similar prop that can be used if you want to inject a CSS class's styles into the component.

**Comment by ashwini987** [comment]
i want to create own custom component ColorList like MultList and in that i want to apply my own html , css whtever i want to lookwise.  
*****How can i create own custom component ColorList ??? *****
i want create component like this below 
![image 2](https://user-images.githubusercontent.com/31088567/31990526-fd5b1dae-b992-11e7-9f14-a140ea33d958.jpg)

right now i use MultiList show it look like this 
![image 3](https://user-images.githubusercontent.com/31088567/31990506-edfae02e-b992-11e7-9d64-01a00359e642.jpg)

**Comment by siddharthlatest** [comment]
@ashwini987 Okay, you can do that with `DataController` https://opensource.appbase.io/reactive-manual/v1/components/DataController.html.

The `dataLabel` prop allows you to define the HTML markup. `style`, `className` props can used to define the styles, and you can use the `customQuery` prop to construct the query.

Does this help?

**Comment by ashwini987** [comment]
No it doesn't help. 
1) how can i create my own custom ColorList component ???

2 ) i want to show color image on checkbox. how can i do that ??
this the image of colour filter in that there is jpg imge for all colours behind the checkboxs.

![image 5](https://user-images.githubusercontent.com/31088567/31996664-f1a2cc46-b9a6-11e7-9493-d570ebff3235.jpg)

3) i want price filter like that right now only rangesilder is there but i want to below like that can we have something like this or create like this ??

![image 6](https://user-images.githubusercontent.com/31088567/31996804-72a68030-b9a7-11e7-9ef2-a15be2077270.jpg)

**Comment by siddharthlatest** [comment]
For 1.) and 2.) you can add your own render() markup in the `dataLabel` prop. The checkbox and jpeg images are how you want the component to look, you can define it there.

For 3.), the RangeSlider component supports the slider (like you mention), but doesn't support an input box filter to select the values right now.

**Comment by ashwini987** [comment]
can you provide example of how to i add my own render() markup in the dataLabel prop ???
                                                         OR
can i apply jpeg imge or color code on multilist colour data. or there is any prop that i pass jpeg img or colur code that is comes from my api ??

**Comment by metagrover** [comment]
You can pass a valid JSX in the dataLabel which may look something like this:

```
<div>
    <a onClick={() => this.setColor("red")}>Red color image or whatever you wish to render</a>
    <a onClick={() => this.setColor("yellow")}>Yellow color image or whatever you wish to render</a>
    .... more colors
</div>
```

The `setColor()` should update the `selectedColor` value in the parent component's state, which is passed as a `defaultSelected` prop to the DataController with a `customQuery` prop to compute the query based on the given color as a parameter.

```
<DataController 
    componentId="ColorPicker"
    defaultSelected={this.state.selectedColor}
    customQuery={this.yourCustomQuery}
    dataLabel={<div>...</div>}
/>
```

So essentially, you need to update the defaultSelected prop on every color selection here.

[Refer docs for more details](https://opensource.appbase.io/reactive-manual/v1/components/DataController.html)
