### ISSUE TITLE
Vue SSR renderData prints html as plain text

### ISSUE THREAD

**Issue by mauxtin** [appbaseio/reactivesearch#1060]
**Affected Projects**
VueJS

**Library Version:** x.y.z
latest

**Describe the bug**
I am trying out the Vue SSR with the ReactiveList component but the renderData outputs html as plain text. (See screenshot, ignore `undefined`)
![image](https://user-images.githubusercontent.com/40521145/61398799-7707a180-a8d5-11e9-9575-5353956aeeb8.png)

**To Reproduce**

1. Clone this and go to this Nuxt.js project https://github.com/appbaseio/reactivesearch/tree/next/packages/vue/examples/with-ssr
2. Install and update to latest versions
3. Change the ResultCard component to ReactiveList and change the renderData method from this:
```
renderData: item => ({
	title: item.name,
	image: item.image,
	url: item.listing_url,
	description: `<div>
		<div className="price">${item.price}</div>
			<p className="info">
				${item.room_type} · ${item.accommodates} guests
			</p>
		</div>`,
}),
```
to this
```
  renderData: item =>  `<div>
      <div className="price">${item.price}</div>
          <p className="info">
              ${item.room_type} · ${item.accommodates} guests
          </p>
      </div>`,
```

I am not sure if that's how the renderData function should be used so please let me know if that's wrong or a bug :)

**Comment by bietkul** [comment]
Yes, you're not using it in the correct way.
You can just use the `renderData` as `slot`, for example in your `template` use it like that
```html
<reactive-list>
  <div slot="renderData" slot-scope="{ item }">
    <div>
      <div className="price">${item.price}</div>
          <p className="info">
              ${item.room_type} · ${item.accommodates} guests
          </p>
      </div>
   </div>
</reactive-list>
```
If you're using `JSX` then you can just define the `renderData` as a function.
