### ISSUE TITLE
sortBy in ReactiveList is not working 

### ISSUE THREAD

**Issue by abhinavgurung** [appbaseio/reactivesearch#1062]
So I am using ReactiveList. it gives the list back all nicely. once I add sortBy, the list disappears from the webpage. Am I missing something here.

My though was sortBy just sorts the results, any other config needed?

thanks

**Comment by bietkul** [comment]
Can you please share an example link (codesandbox) so we can debug it.

**Comment by abhinavgurung** [comment]
The issue has been fixed. it was error on my side. Thank you .
