### ISSUE TITLE
ReactiveList > scrollTarget should/could also accept node

### ISSUE THREAD

**Issue by kud** [appbaseio/reactivesearch#1063]
For the moment scrollTarget only accepts id of the container you wish to apply infinite loading on. 

It could be great to be able to give a node, like a react ref or a document.querySelector().

**Comment by jyash97** [comment]
Hey, @kud  thanks for the idea. It will be great if you can describe a scenario in which this enhancement would fit great.

**Comment by kud** [comment]
```jsx
<ReactiveList
            componentId="AmendmentsResult"
            scrollTarget={this.asideRef.current}
>

<AsideBox ref={this.asideRef}>
          {aside}
</AsideBox>
```

or 

```jsx
<ReactiveList
            componentId="AmendmentsResult"
            scrollTarget={document.querySelector(".org-MyElement")}
>

<AsideBox class="org-MyElement">
          {aside}
</AsideBox>
```

**Comment by jyash97** [comment]
Awesome this is really great 💥 Are you open for creating a PR for this ?

**Comment by jyash97** [comment]
Thanks @felubra for working on this 💯 

@kud This will be released with the next version of Reactivesearch ✨
