### ISSUE TITLE
Custom tag for ReactiveBase

### ISSUE THREAD

**Issue by felubra** [appbaseio/reactivesearch#1064]
**Affected Projects**
React / VueJS

**Is your feature request related to a problem?**
It is related to building proper Semantic HTML.
Sometimes the ReactiveBase component is not only used as a wrapper and also has a style/semantic function in the page, but there is no way to customize the rendered HTML tag, so the semantic is lost in some cases.

**Describe the solution you'd like**
Please provide a way to set a custom tag for the ReactiveBase component that would be inserted in the DOM when the component renders. 

#### Currently
````vue
<ReactiveBase  class-name="PageIndex">
<article>...</article>
</ReactiveBase>
````
renders:
````html
<div  class="PageIndex">
<article>...</article>
</div>
````

#### With the proposed change

````vue
<ReactiveBase  class-name="PageIndex" tag="section">
<article>...</article>
</ReactiveBase>
````
(notice the new *tag* prop)
would render:
````html
<section  class="PageIndex">
<article>...</article>
</section>
````

**Describe alternatives you've considered**
N/A

Thank you!

**Comment by jyash97** [comment]
@felubra  This makes sense 💯 

Instead of `tag` prop we can name the prop `as`. So the API would look like: 

```
<ReactiveBase as="article">
...
</ReactiveBase>
```

@bietkul @siddharthlatest @lakhansamani  Thoughts ?

**Comment by bietkul** [comment]
I think we should implement it.

**Comment by bietkul** [comment]
Added [here](https://github.com/appbaseio/reactivesearch/commit/422d37ad3b10707d65a2a76f1ae3e02307e15399), will be out in next release.
