### ISSUE TITLE
showCount props in multilist behave differently

### ISSUE THREAD

**Issue by abhinavgurung** [appbaseio/reactivesearch#1066]
`  <MultiList
                                    componentId="keywordFilter"
                                    dataField="codeBook.stdyDscr.stdyInfo.subject.keyword.keyword"
                                    
                                    size={1000}
                                    showCheckbox={true}
                                    loader="loading...."
                                    sortBy="asc"
                                    className="keyword-filter"
                                    innerClass={{
                                        label: "list-item",
                                        input: "list-input"
                                    }}
                                    placeholder="Filter by keyword"

                                />`

This is my code for MultiList Component. 
its looks like this in UI

item1                                                         1
item2                                                         3

where as the example in the doc is like this

item1(1)
item2(3)

How can I achieve this. Thanks

**Comment by smcguinness** [comment]
MultiList has a `renderItem` prop which is used to render each individual option in the MultiList. I put a quick example together showing its usage https://codesandbox.io/s/sad-diffie-7ohn4

You can also see more about renderItem and the props of MultiList in the docs - https://opensource.appbase.io/reactive-manual/list-components/multilist.html

**Comment by abhinavgurung** [comment]
Everything works perfectly, except the line 'isSelected is not defined'. is it something i import. thanks

**Comment by jyash97** [comment]
@smcguinness  The demo looks great. @abhinavgurung  I am not seeing any errors in the demo. Can you please elaborate or provide a Codesandbox link for the same ?

**Comment by abhinavgurung** [comment]
https://user-images.githubusercontent.com/12020147/61642290-ab30e880-ac6e-11e9-927a-ba6580db0b2b.png

This is the error. I still need to learn how to put my app in sandbox :)

**Comment by jyash97** [comment]
You can create sandbox from [here](https://codesandbox.io/s/) if you already have this app on GitHub you can import it directly. Do make sure you have `isSelected` as the third function argument in `renderItem`  function.

**Comment by abhinavgurung** [comment]
The issue is fixed. I had it misspelled in the function argument. Thank you.
