### ISSUE TITLE
renderItem is not a function  TypeError: renderItem is not a function

### ISSUE THREAD

**Issue by arpithparikh** [appbaseio/reactivesearch#1067]
**Affected Projects**

REACT SSR  (next.js)
**Library Version:** x.y.z

3.0.0-rc.21
**Describe the bug**

After upgrading to latest I'm started getting this bug
appbaseio/reactivesearch/lib/components/result/ReactiveList.js:394:13
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

 - Browser [e.g. stock browser, safari] -  All browser

**Additional context**

**Comment by bietkul** [comment]
Please check the [docs](https://opensource.appbase.io/reactive-manual/result-components/reactivelist.html#props) for `3.x`, `renderData` has been renamed to `renderItem`.

**Comment by arpithparikh** [comment]
> Please check the [docs](https://opensource.appbase.io/reactive-manual/result-components/reactivelist.html#props) for `3.x`, `renderData` has been renamed to `renderItem`.

But it's coming as TypeError: renderItem is not a function

**Comment by icoxfog417** [comment]
Vue Tutorial uses `renderData`. So fix it helps newcomers.

https://opensource.appbase.io/reactive-manual/vue/getting-started/reactivesearch.html#step-3-adding-filters-and-result-components
