### ISSUE TITLE
showclear not working for componentSearch

### ISSUE THREAD

**Issue by abhinavgurung** [appbaseio/reactivesearch#1068]
I have a componentSearch , but I dont see the "x" beside to clear the typed text. 
am I missing anything. thanks

```
<CategorySearch
    componentId="mainSearch"
    dataField={["codeBook.dataDscr.var.labl",
        "codeBook.docDscr.citation.titlStmt.titl",
        "codeBook.stdyDscr.stdyInfo.subject.keyword",
        "codeBook.stdyDscr.stdyInfo.abstract.__cdata",
        "codeBook.stdyDscr.citation.titlStmt.altTitl"]}
    className="search-bar"
    showClear={true}
    onValueChange={
        function (value) {
            console.log("current value: ", value)//remove this
            //TODO
            //set the state
            //use this value with submit button
            
        }
    }
    
    queryFormat="and"
    placeholder="Search for data files..."
    autosuggest={true}
    filterLabel="search"
    react={{
        and: ["keywordFilter", "dateFilter"]
    }}
/>
```

**Comment by jyash97** [comment]
Hey @abhinavgurung 
Can you please specify the version of Reactivesearch and which library it affects. Along with the steps to reproduce.
Please follow the format for Bug Report Template.

**Comment by abhinavgurung** [comment]
@jyash97 
I am using import { CategorySearch, SelectedFilters } from '@appbaseio/reactivesearch'
how can I check the version? thanks

**Comment by abhinavgurung** [comment]
@jyash97 
found it !
 "@appbaseio/reactivesearch": "^3.0.0-rc.13",

**Comment by jyash97** [comment]
You can check the version from `package.json`. And `showClear` prop works properly I confirmed it. Check this [demo](https://codesandbox.io/s/categorysearch-b1p89).

And here is the screenshot of the clear icon appearing on right side :
![image](https://user-images.githubusercontent.com/22376783/61641315-8b281600-acbc-11e9-9bbf-b972d22bc402.png)

**Comment by abhinavgurung** [comment]
When I try it on sandbox it works, but on my component, it does not. Can you see any issue on my component which I am not able to notice. 
thanks

**Comment by jyash97** [comment]
Can you please share a CodeSandbox link for it?

**Comment by abhinavgurung** [comment]
https://user-images.githubusercontent.com/12020147/61642290-ab30e880-ac6e-11e9-927a-ba6580db0b2b.png

**Comment by abhinavgurung** [comment]
https://user-images.githubusercontent.com/12020147/61644145-28aa2800-ac72-11e9-91fd-78a22b5bb4f9.png

whats weird is , its not showing when I am running the application. But when I try in sand box, its showing the x. 
https://codesandbox.io/s/6gtls

Also , side thing but if you could tell me how to delete the sandbox after, thanks
