### ISSUE TITLE
question: how to update the query url when someone searches for something

### ISSUE THREAD

**Issue by mezuqu** [appbaseio/reactivesearch#107]
Hello,

I cant see if there is a way that when someone searches something 

say i started to type "titanic" and i want to be url to be updated as i type:
say: search.html?=titanic

this is an important thing, as someone could share the specific search results to someone.
but reactivesearch doesnt allow this, because the url is constant and doesnt change

also the filters should be applied to the url.. 

is there a way of doing this?

**Comment by siddharthlatest** [comment]
@mezuqu We do allow this. There is a `URLParams` prop, you can set that to `true`, this is also present in the filter components. https://opensource.appbase.io/reactive-manual/v1/components/DataSearch.html#datasearch-props
