### ISSUE TITLE
Componentsearch on submit button/enter

### ISSUE THREAD

**Issue by abhinavgurung** [appbaseio/reactivesearch#1070]
I would like my component search to do the query only when user press the submit button or press enter. how can I achieve this. I have been spending some time on it now. 

I tried onValueChange

`class SearchBar extends React.Component {
    constructor(props){
        super(props);
        this.state={
            searchText: ""
        }
        //this.handleSubmit = this.handleSubmit.bind(this);  
    }  
    // handleSubmit=(e)=>{
    //     e.preventDefault();
    //     console.log(this.state.value)
    //     //this.setState({value:e.target.value});
    // }
    render() {
        return (
            <div className="search-container">
                <CategorySearch
                    componentId="mainSearch"
                    dataField={["codeBook.dataDscr.var.labl",
                        "codeBook.docDscr.citation.titlStmt.titl",
                        "codeBook.stdyDscr.stdyInfo.subject.keyword",
                        "codeBook.stdyDscr.stdyInfo.abstract.__cdata",
                        "codeBook.stdyDscr.citation.titlStmt.altTitl"]}

                    className="search-bar"
                    showClear={true}
                    onValueChange={(e)=> this.setState({searchText:e.target.value.searchText})}
                    queryFormat="and"
                    placeholder="Search for data files..."
                    autosuggest={true}
                    filterLabel="search"
                    react={{
                        and: ["keywordFilter", "dateFilter"]
                    }}
                />
              <button type="button"  onSubmit={this.onValueChange}  > Search</button>
            </div>
        );
    }
}
`

**Comment by jyash97** [comment]
You can read the docs on controlled behavior in ReactiveSearch over [here](https://opensource.appbase.io/reactive-manual/advanced/componentsusage.html#controlled-components). I have also implemented a small example for the above situation you check the demo [here](https://codesandbox.io/s/datasearch-vf2sz).

Also, it would be great if you follow the PR template this makes easy for us to debug the issue. And there is formatting error in your markdown please do check it.

**Comment by abhinavgurung** [comment]
@jyash97 
Thank you. this is my sandbox. I implemented your code. but its not letting me type anything in the search box.
(ignore no data for now)

**Comment by jyash97** [comment]
Can you please add the code or codesandbox link?

**Comment by abhinavgurung** [comment]
https://codesandbox.io/s/moviesearch-e6qvw

**Comment by jyash97** [comment]
Can you please follow the same approach as given in the above codesandbox. The current code is not going to work as the component is not controlled and does not make use of `triggerQuery`.

**Comment by abhinavgurung** [comment]
@jyash97 
Thank you closing this issue, its fixed. Appreciate the help.
