### ISSUE TITLE
TypeError: Cannot read property 'promoted' of undefined

### ISSUE THREAD

**Issue by arpithparikh** [appbaseio/reactivesearch#1071]
**Affected Projects**

React 

**Library Version:** x.y.z

^3.0.0-rc.21
**Describe the bug**

**To Reproduce**

Getting this error TypeError: Cannot read property 'promoted' of undefined
@appbaseio/reactivecore/lib/actions/query.js:1:5048

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jyash97** [comment]
Hey @arpithparikh  
Can you give me more info on how to reproduce this bug? 
It will be really helpful if you can provide a CodeSandbox or a Codepen link.
