### ISSUE TITLE
Getting "A form control does not have a corresponding label" error on DataSearch component when running WAVE

### ISSUE THREAD

**Issue by allendol** [appbaseio/reactivesearch#1072]
Our interface should be 508 complaint.
I am using DataSearch component and I am running WAVE (Google) access control.
Any idea how I can resolve this?

**Comment by allendol** [comment]
To recreate the error go to your example at:
https://booksearch-appbase.netlify.com/

Activate Wave from Google chrome and see the error. Screenshot is attached:
![ReactiveSearch](https://user-images.githubusercontent.com/40170767/61918264-c88bde00-af1e-11e9-9fde-199e5d2dd079.png)

**Comment by jyash97** [comment]
Hey @allendol  
Thanks for submitting the issue. We have recently added `aria-label` in search components. You can upgrade the version and check once again. Here is the screenshot of `DataSearch` component in latest version: 

![image](https://user-images.githubusercontent.com/22376783/61930276-ded77f80-af9a-11e9-87ce-1771ee2300fb.png)

Code Link: https://codesandbox.io/s/datasearch-8e21k
Demo Link: https://8e21k.csb.app/

**Comment by allendol** [comment]
Hi @jyash97,
Thanks for the quick reply.
- Is this solved for DateRange component also?
- One stupid question as I am not expert in react. How can I upgrade reactivesearch? Can you write the syntax? It can save me time instead of finding it somewhere.
Cheers

**Comment by jyash97** [comment]
> Is this solved for DateRange component also?

Yes

___
> For upgrading version

You can do `yarn add @appbaseio/reactivesearch` or `npm install @appbaseio/reactivesearch`

Let me know if you feel there can be a chance to improve on accessibility even further. Thanks

**Comment by allendol** [comment]
@jyash97,
I already ran this twice:
npm install @appbaseio/reactivesearch 
but still shows:
@appbaseio/reactivesearch@2.18.0
And the problem still exists. 
Any idea?

**Comment by jyash97** [comment]
So this is fixed in `v3`. You can add `@latest` after the dependency name to install the latest dependency. And do check the migration guide from v2 to v3 over [here](https://opensource.appbase.io/reactive-manual/advanced/migrationguide.html).

**Comment by allendol** [comment]
@jyash97,
I made a new version in a new project for v3. 
My existing ResultList and Reactive don't work in Version 3. Don't know how much effort it needs to migrate or change them. I am using react-bootstarp table with some expand collapse, etc on the result.
- Is there any specific location that you added "aria-label: in v3 so I can do it manually for v2 for now? I can look for the upgrade later on. Looks like v2 to v3 upgrade opens a whole new effort.
- Or is there any backward compatibility available?

**Comment by jyash97** [comment]
Hey @allendol 
We have changed ResultList to follow the compound Component pattern. You can check the docs.
___
Do let me know if you face any other difficulties on Migrating from v2 to v3.

**Comment by bietkul** [comment]
Closing since upgrading will resolve it, feel free to re-open.
