### ISSUE TITLE
Componentsearch vs DataSearch autosuggest prop

### ISSUE THREAD

**Issue by abhinavgurung** [appbaseio/reactivesearch#1073]
When I use ComponentSearch the auto suggest does not work for me. but As soon as i Change it in to DataSearch it works. Am I missing anything. I am not making any other changes. Just cahnging the name ComponentSearch to DataSearch. 

Any info would be helpful. thanks

**Comment by bietkul** [comment]
We don't have any component named `ComponentSearch`.
