### ISSUE TITLE
Getting error: TypeError: data.map is not a function in data.map(dat =>  function part of ReactiveList in ReactiveSearch Version 3

### ISSUE THREAD

**Issue by allendol** [appbaseio/reactivesearch#1074]
I am migrating the reactivesearch interface from 2.x to 3.0. Following code was working fine in ReactiveList version 2.x. But now in version 3.0, it is giving the error in line 594:

**TypeError: data.map is not a function**
booksReactiveList
/App.js:
  592 |             var resList = [];
> 594 |             **data.map(dat => {**
  596 |                 var a = {.......

Here is line in ResultList
render={this.booksReactiveList}
....
....
....
Here is the fucntion for booksReactiveList
    booksReactiveList(data) {

        if (data == null) console.log("Null");
        else {
            var resList = [];
            data.map(dat => {
                var a = {

On version v2.x I was using onAllData in ResultList which I changed it to render according to the documentation.
Any idea?

**Comment by allendol** [comment]
I solved the problem by changing:
data.map(dat => {
To:
data.data.map(dat => {

**Comment by jyash97** [comment]
Right, `render` returns an `object` which contains property `loading`, `error` , `data` & other useful properties. You can check all the properties in `render` prop description over  [here](https://opensource.appbase.io/reactive-manual/result-components/reactivelist.html#extending).
