### ISSUE TITLE
question: migrate to preact

### ISSUE THREAD

**Issue by mezuqu** [appbaseio/reactivesearch#108]
is there a special reason to insist on react or is there any roadmap about migration to preact which is well compatible with react and its faster and cheaper (in terms of bandwidth)

**Comment by siddharthlatest** [comment]
@mezuqu I suspect transitioning from React isn't trivial for us, as some of our dependencies (e.g. react-dates for the Date components) use React. We also have a pretty good roadmap for improving the library internals, a core rewrite and a styles rewrite is coming up soon that focusing on perf isn't a top priority.

Would love to support something like this if someone were brave enough to create a fork / PR.
