### ISSUE TITLE
ReactiveBase headers on Authorization

### ISSUE THREAD

**Issue by allendol** [appbaseio/reactivesearch#1083]
I am using token based authentication and the following code is working fine outside of ReactiveSearch:
----
                axios({
                    url: 'https://myurl/_search',
                    method: 'post',
                    headers: { 'content-type': 'application/json', 'authorization': vtoken }
                    , data: query
                    }
                    )
----
I am getting result without any issue. 
However when I am using it in ReactiveSearch I am getting no data.
This is my code:
                <ReactiveBase
                    app={MyIndex}
                    url="https://myurl/_search"
                    headers={{ 'content-type': 'application/json', 'authorization': { vtoken } }}
                >

**Comment by PunKHS** [comment]
Hi @allendol !
Please, see [this issue](https://github.com/appbaseio/reactivesearch/issues/958).
It helped me resolve my problems with authorization.

**Comment by allendol** [comment]
Hi @PunKHS 
Thanks for you feedback. I tried and it didn't work for me.
This is what I am using in above and this is not connected to elasticsearch.

**Comment by allendol** [comment]
My problem was resolved. the code in above was correct. My URL was not. After i changed the URL it is fine now.
