### ISSUE TITLE
send username and password to non appbase.io url

### ISSUE THREAD

**Issue by abhinavgurung** [appbaseio/reactivesearch#1085]
so how do I send my username and password to non appbase.io url. 
i tried credentials and headers both. is there anything else for this purpose. 

tried credentials:"username:password"

and tried
headers={{
            username: 'username',
            password: 'password',
          }}

any suggestion would be appreciated.

**Comment by jyash97** [comment]
Please check this issue: https://github.com/appbaseio/reactivesearch/issues/958

**Comment by abhinavgurung** [comment]
Thanks
