### ISSUE TITLE
Bug: onKeyPress Enter key isn't detected when autosuggest is true

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivesearch#1087]
**Affected Projects**

React

**Library Version:**

3.0.0-rc.23

**Describe the bug**

The `onKeyPress` callback prop doesn't detect an enter key press with the `autosuggest` prop set to `true` (which is the default).

**To Reproduce**

Here's the code sandbox showing the issue: https://codesandbox.io/s/datasearch-5p8w4. You can see the console for key-press logs.

You can try setting `autosuggest={false}` and see that the enter key-press gets detected.

**Expected behavior**

Enter key press should be detected. This is likely some side-effect from the usage of downshift.

**Comment by bietkul** [comment]
@siddharthlatest It is an issue with downshift library, you can check it [here](https://github.com/downshift-js/downshift/issues/662).
By the way, one can use `onKeyDown` in this scenario to track the `ENTER` key event.

**Comment by siddharthlatest** [comment]
- [ ] Sounds good. We can add this as a note in the docs for `DataSearch` and `CategorySearch`.

**Comment by bietkul** [comment]
Updated the docs [here](https://github.com/appbaseio/Docs/commit/da9594c9b8c1941178052dd32dfba738cfee7e37).
