### ISSUE TITLE
initReactiveSearch omits graphQLUrl

### ISSUE THREAD

**Issue by janus-reith** [appbaseio/reactivesearch#1088]
**Affected Projects**
React

**Library Version:**
3.0.0-rc.25

**Describe the bug**
`initReactivesearch` will omit the `graphQLUrl` settings here and not pass it to `Appbase`
https://github.com/appbaseio/reactivesearch/blob/a7ddf5eb2a83c5a4d312b7c4e9c40fe58d375a5a/packages/web/src/server/index.js#L62

**To Reproduce**
Try to implement SSR with `initReactivesearch` and a Graphql-proxied Elasticsearch.

**Expected behavior**
The `graphQLUrl` field is passed the same way like it is when using `ReactiveBase`

**Proposed Solution**
~~Add `graphQLUrl: settings.graphQLUrl,` to `/packages/web/src/server/index.js`.~~
`initReactivesearch` directly performs the msearch-query on Appbase. Perform the same check for the query that is done in `reactivecore` and fetch using graphql instead, or even better, refactor the code so both use the same function.

**Comment by lakhansamani** [comment]
@janus-reith thanks for reporting it. We will be fixing this with the next release.
