### ISSUE TITLE
onChange handler and value behave weird and not consistent

### ISSUE THREAD

**Issue by janus-reith** [appbaseio/reactivesearch#1091]
**Affected Projects**
React

**Library Version:** x.y.z
v3.0.0-rc.25

**Describe the bug**
`onChange` handlers only become active when the component has a `value` set.
While i don't understand why this limitation is in place, the real issue for me is that `onChange` does not return a value that I can use for `value`.
E.g. MultiList returns a single string upon change, expects an array and internally uses an object to keep the current value in `state`.
For the RangeInput I had similar issues.

**To Reproduce**
Take `MultiList` and add `value` from state, and pass a function to `onChange` that sets the value to state. Actually, you wouldn't even need to set it and log it to console instead.

**Expected behavior**
I can easily store the data from an `onChange` in my global store and pass it back to the component using `value`

**Comment by siddharthlatest** [comment]
@janus-reith Is it possible for you to share a codesandbox showing this issue? That would help a lot :-)

**Comment by janus-reith** [comment]
@siddharthlatest I forked the DataSearch example and modified it to demonstrate the issue:
https://codesandbox.io/s/datasearch-is3gu

**Comment by ShahAnuj2610** [comment]
right now you can handle it as shown in the example -> https://codesandbox.io/s/multilist-ew5pk

**Comment by janus-reith** [comment]
@ShahAnuj2610 I don't see how that example solved the issue.
`handleChange` will only add strings to the beginning of the array and won't allow for removing them. It crashes as soon as you uncheck a checkbox.

Sure this could work if I check before if that string exits and remove it if present.

But in my opinion still this shouldn't be the default behaviour. If `value` as a prop sets the whole array, `onChange` should return the whole new array. Getting the currently clicked Checkbox should be a separate handler, like `onCheckboxChange/onCheckboxClick`.

In my perspective you should be able to take any component of the library and use value/onChange on it without knowing its internals.
