### ISSUE TITLE
[Vue] - Add a prop to hide tooltip in rangeslider

### ISSUE THREAD

**Issue by anshumanv** [appbaseio/reactivesearch#1097]
**Affected Projects**

Vue

**Is your feature request related to a problem? Please describe.**
No option to hide tooltip

**Describe the solution you'd like**
add a prop to hide tooltip when set

**Describe alternatives you've considered**

None

**Additional context**
None

**Comment by jyash97** [comment]
Hey @anshumanv 
We are using [vue-slider-component](https://nightcatsama.github.io/vue-slider-component/#/basics/tooltip)  to create the UI and you can directly use the `sliderOptions` prop to pass any prop directly to the component. 
Check this [demo](https://codesandbox.io/s/range-slider-1jhxg)

**Comment by anshumanv** [comment]
Makes sense, thanks @jyash97! 😄
