### ISSUE TITLE
Movies Store homepage(one of the example starter apps) is broken.

### ISSUE THREAD

**Issue by FrozenHearth** [appbaseio/reactivesearch#1106]
**Affected Projects:**   
React 

**Library Version:** 
3.0.0-rc.25

**Describe the bug**
As the title says, when navigating to [https://movies-store-appbase.herokuapp.com/](url), an error message shows up on the homepage, saying, "An unexpected error has occurred"

**To Reproduce**
Navigate to [https://movies-store-appbase.herokuapp.com/](url).

**Screenshots**
https://i.imgur.com/fczPxgV.png

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser: Chrome
 - Version : 76.0

**Comment by siddharthlatest** [comment]
@FrozenHearth Thanks for reporting. I can confirm the issue. We will fixing it shortly.

**Comment by bietkul** [comment]
Fixed it.
