### ISSUE TITLE
ReactiveBase should inform user that search backend cannot be reached. 

### ISSUE THREAD

**Issue by jscheidtmann** [appbaseio/reactivesearch#1109]
**Affected Projects**

React

**Library Version:** x.y.z

3.0.0-rc.26

**Describe the bug**

When specifying the url property in ReactiveBase the component should render an error message to the user, if that url (ElasticSearch cluster) is not available, for whatever reason. Ideally it would give an indication on CORS. 

**To Reproduce**
Run application with `npm start`, with-out running ElasticSearch or misconfiguring ElasticSearch with-out CORS:

`      <ReactiveBase
        app="xxx"
	url="http://localhost:9200/"
      >
        <DataSearch
          componentId="mainSearch"
          dataField={["title", "body", "path"]}
          queryFormat="and"
          iconPosition="left"
        />
  </ReactiveBase>
`

displays a "Search bar":

**Screenshots**

![grafik](https://user-images.githubusercontent.com/19821951/63431290-d437cb00-c41e-11e9-871b-db56e43ada90.png)

**Expected behavior**
An error message is displayed that the respective backend could not be reached.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox 
 - Version: 60.8.0esr

**Additional context**
Display on browsers console:
TypeError: Network request failed
Stack trace:
./node_modules/cross-fetch/dist/browser-ponyfill.js/</self.fetch/</xhr.onerror@http://localhost:3005/static/js/0.chunk.js:28675:18
 index.js:1375

**Comment by PunKHS** [comment]
I have the same problem. Library Version: 3.0.0-rc.26

**Comment by bietkul** [comment]
You can use `renderError` prop to display the error message or use `onError` prop to handle the error.
For more details check the docs [here](https://opensource.appbase.io/reactive-manual/search-components/datasearch.html).
