### ISSUE TITLE
Query for Multilist Filter is altered on load

### ISSUE THREAD

**Issue by hansendx** [appbaseio/reactivesearch#1112]
**Affected Projects**
Vue.JS

**Library Version:** 1.0.0-beta.18

**Describe the bug**

I am using a Multilist filter.
When setting  `:URLParams="true"`, something like `Filter=["thing1","thing2"]` is added to the query part of the url. When reloading the page or taking the url and freshly loading it
`Filter=["thing1","thing2"]` is changed to `Filter=["thing1,thing2"]`.
In addition the results are then also filtered using `"thing1,thing2"` which probably eliminates all results in most cases. 
This happens for all lists longer than one. All occurrences of `","` are replaced by just a `,`.

**To Reproduce**
I have set `:URLParams="true"` in a forked codesandbox
https://codesandbox.io/embed/multi-list-2yure

To reproduce, one has to select multiple filters and reload page in the demo browser.

**Expected behavior**

I would expect `Filter=["thing1","thing2"]` to be kept as `Filter=["thing1","thing2"]`.
The react project seems to handle this correctly:
https://codesandbox.io/embed/multilist-3io0w

I cannot reproduce the bug there.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04, Windows 7
 - Browser: Chrome, Firefox
 - Version: 75.0.3770.142, 68.0.2

**Additional context**

I tried to follow the query through a debugger to identify the problem.
The furthest I got was that the [selectedValues](https://github.com/appbaseio/reactivesearch/blob/8f5ff252d487ed486a68eb619ba026c0b5b922f6/packages/vue/src/components/URLParamsProvider.jsx#L53) function inside the URLParamsProvider component is called with `oldVal` and `newVal` by a vue [watcher function](https://github.com/vuejs/vue/blob/e90cc60c4718a69e2c919275a999b7370141f3bf/dist/vue.runtime.esm.js#L4546).
There `oldVal` still contains the correct `["thing1","thing2"]` string while `newVal` contains `["thing1,thing2"]`.

**Comment by hansendx** [comment]
This problem persist in the 1.0.0 stable release.

**Comment by EnnioSimoes** [comment]
I have the same problem

**Comment by MrCode1997** [comment]
I have the same problem too.

**Comment by hansendx** [comment]
This is still a problem in version 1.7.0
https://codesandbox.io/s/sleepy-cdn-ffruv?file=/src/App.vue
![URLParams](https://user-images.githubusercontent.com/20108516/89760538-e5289300-daec-11ea-8f6d-acf40c13d780.png)

**Comment by bassambarham** [comment]
Any workaround for this issue? I'm facing the same problem as well.

**Comment by bassambarham** [comment]
Hi

The problem is still there. Even with the 1.7.5 version.

/by-date-of-event?regionSensor=["b40f813"%2C"5f6a04e"]

Becomes:

/by-date-of-event?regionSensor=["b40f813%2C5f6a04e"]

**Comment by bassambarham** [comment]
@bietkul Any help would be appreciated.

Thanks

**Comment by hansendx** [comment]
Still an Issue in v1.12.1-vue

**Comment by hansendx** [comment]
Seems to have been fixed between v1.12.1-vue and v1.15.0-vue
