### ISSUE TITLE
Reactive maps `renderPagination` bug

### ISSUE THREAD

**Issue by ShahAnuj2610** [appbaseio/reactivesearch#1117]
**Affected Projects**
React

**Library Version:** x.y.z
v3.0

**Describe the bug**
I have my `renderAllData` method for `ReactiveGoogleMap` as below:
```js
              renderAllData={(
                hits,
                streamHits,
                loadMore,
                renderMap,
                renderPagination
              ) => (
                <div style={{ display: "flex" }}>
                  <div>
                    <div className="card-container">
                      {hits.map(data => (
                        <div key={data._id} className="card">
                          <div
                            className="card__image"
                            style={{ backgroundImage: `url(${data.image})` }}
                            alt={data.name}
                          />
                          <div>
                            <h2>{data.name}</h2>
                            <div className="card__price">${data.price}</div>
                            <p className="card__info">
                              {data.room_type} · {data.accommodates} guests
                            </p>
                          </div>
                        </div>
                      ))}
                    </div>
                    <div>{renderPagination()}</div>
                  </div>
                  <div className="map-container">{renderMap()}</div>
                </div>
              )}
```
When I click on the last page, `renderPagination` renders as below:
<img width="323" alt="Screenshot 2019-08-26 at 3 51 12 PM" src="https://user-images.githubusercontent.com/10362927/63683932-5d814000-c819-11e9-94ce-632048d871b4.png">
In fact, there are four pages.

**Comment by jyash97** [comment]
This is replicable in `ReactiveList`  as well and this is the main reason why `renderPagination` is giving incorrect pages in `ReactiveGoogleMap`. We should fix this issue on ReactiveList. I think this is a side effect from this PR: #1022 

How to Replicate: 

1. Run ReactiveList Example
2. Go to last page ( Check `totalPages` prop on Pagination )

**Comment by anshumanv** [comment]
https://github.com/appbaseio/reactivesearch/blob/f05fc12bd5c4dec4d2d1e1b03292b72ce55b04ea/packages/web/src/components/result/addons/Pagination.js#L23

The issue seems around the currentPage exceeding the total available pages, need to handle some math and edge cases around, that's it. ✨ 🔢 

Can fix this if required. 👍

**Comment by ShahAnuj2610** [comment]
@anshumanv I have fixed this. So lmk if there would be any side effects.
