### ISSUE TITLE
Vue.JS UMD build: 'Cannot use 'in' operator to search for 'default' in undefined'

### ISSUE THREAD

**Issue by michael-wolfenden** [appbaseio/reactivesearch#1121]
**Affected Projects**
Vue.JS

**Library Version:** x.y.z
reactivesearch-vue@1.0.0-beta.18

**Describe the bug**
Adding a script reference to the [minified umb build](https://cdn.jsdelivr.net/npm/@appbaseio/reactivesearch-vue@1.0.0-beta.18/dist/@appbaseio/reactivesearch-vue.umd.min.js) results in the following error:

```
"TypeError: Cannot use 'in' operator to search for 'default' in undefined
    at https://cdn.jsdelivr.net/npm/@appbaseio/reactivesearch-vue@1.0.0-beta.18/dist/@appbaseio/reactivesearch-vue.umd.min.js:1:948
    at https://cdn.jsdelivr.net/npm/@appbaseio/reactivesearch-vue@1.0.0-beta.18/dist/@appbaseio/reactivesearch-vue.umd.min.js:1:710
    at https://cdn.jsdelivr.net/npm/@appbaseio/reactivesearch-vue@1.0.0-beta.18/dist/@appbaseio/reactivesearch-vue.umd.min.js:1:878"
```

**To Reproduce**
https://jsbin.com/sajanuhuya/edit?html,console

**Expected behavior**
I expect to be able to use reactivesearch vue in a static site without bundling support.

**Comment by bietkul** [comment]
Fixed in the latest version, please find the docs [here](https://docs.appbase.io/docs/reactivesearch/vue/overview/QuickStart/#step-2-reactivesearch-as-umd).
