### ISSUE TITLE
Question: How to reload the reactivesearch queries/states?

### ISSUE THREAD

**Issue by mengleihouzz** [appbaseio/reactivesearch#1130]
Hi, 

We are building an admin tool using reactivesearch. One important functionality of our tool is to save the search query or the state. Then people can reload the previous search result and modify on top of it. Does reactivesearch support this? 
Basically, we have two requirements:
1) save the reactivesearch states so that we can reload it.
2) get the Elasticsearch query 

Thanks,
Menglei

**Comment by siddharthlatest** [comment]
@mengleihouzz Yes, this is possible. You can check the [`StateProvider`](https://deploy-preview-38--appbase-docs.netlify.com/docs/reactivesearch/v3/base/stateprovider/) component.
