### ISSUE TITLE
MultiDropDownList not triggering renderNoResults

### ISSUE THREAD

**Issue by mihalo** [appbaseio/reactivesearch#1137]
**Affected Projects**
ReactJS

**Library Version:** x.y.z
3.0.0

**Describe the bug**
MultiDropDownList not triggering renderNoResults when there isn't any results

**To Reproduce**
` <MultiDropdownList
                    componentId="Test"
                    dataField="data.test.keyword"
                    size={100}
                    sortBy="asc"
                    showCount
                    placeholder="Selec"
                    showFilter
                    loader="Loading ..."
                    showSearch
                    innerClass={{
                      select: 'search-select',
                      list: 'search-list',
                    }}
                    renderNoResults={() => <p>No Results Found!</p>}
                  />`

**Expected behavior**
To see No Results Found! text instead of empty div

**Comment by jyash97** [comment]
Hey @mihalo 
I can see it working over [here](https://fe4k3.csb.app/). Try searching `fff` on search you will see the text Nothing Found.

Screenshot: 
![image](https://user-images.githubusercontent.com/22376783/64540788-56d8e980-d33e-11e9-8fbb-5118bdff482d.png)

It would be great if you provide an example link.

**Comment by mihalo** [comment]
Hey @jyash97 
Sorry I was a bit unclear. In your case it is working as expected but when there is initially no options without any search input it doesn't render. I expect it to work even there isn't any values to select. At least show error or no results found text but all I get is empty div.

You can see it here: https://codesandbox.io/embed/multidropdownlist-d059y

What I made is changed original_series.raw to original_series_EMPTY.raw

Not sure if this is a bug or feature request.. :)

**Comment by jyash97** [comment]
Hey @mihalo  
Thanks for pointing the issue this does look like a bug will check into it and let you know.

**Comment by jyash97** [comment]
Hey @mihalo 
Thanks for the issue, it will be released in the upcoming version of ReactiveSearch.
