### ISSUE TITLE
ReactiveSearch components do not support ElasticSearch v7

### ISSUE THREAD

**Issue by neoromantic** [appbaseio/reactivesearch#1139]
**Affected Projects**
React 

**Library Version:** 3.0.0

**Describe the bug**
Since breaking change in Elastic 7.0 which changes the way hits.total displayed from plain value to object, the ReactiveSearch fails on parsing that field, thus breaking whole app.

**To Reproduce**

1. Set up appbase with Elastic 7
2. Try to connect ReactiveSearch in any shape or form
3. Observe an error:

```
 Invariant Violation: Objects are not valid as a React child (found: object with keys {relation, value}). If you meant to render a collection of children, use an array instead.
    in p
    in div
    in Styled(div)
    in div
    in ReactiveList
```

**Comment by bietkul** [comment]
Can you please let us know which version you're using?
It works well with `3.x`.

**Comment by neoromantic** [comment]
> Can you please let us know which version you're using?
> It works well with `3.x`.

It's the latest:

```
➜  alltalents git:(feature/search) ✗ cat package.json| grep appbase
    "@appbaseio/reactivesearch": "^3.0.0",
    "appbase-js": "^4.0.2-beta.7",
```

I've checked the source code, it expects that in hits.total there will be a number returned. And starting from ElasticSeach 7, it returns something like { relation: "eq", value: 5}.

Elastic which I'm testing is on the AppBase. 

It works well with Elastic 5.

**Comment by neoromantic** [comment]
Specifically it is in server/index.js:298

```
	const handleResponse = (res) => {
			const allPromises = orderOfQueries.map(
				(component, index) =>
					new Promise((responseResolve, responseReject) => {
						handleTransformResponse(res.responses[index], component)
							.then((response) => {
								if (response.aggregations) {
									aggregations = {
										...aggregations,
										[component]: response.aggregations,
									};
								}
								hits = {
									...hits,
									[component]: {
										hits: response.hits.hits,
										total: response.hits.total,
										time: response.took,
									},
								};
								responseResolve();
							})
							.catch(err => responseReject(err));
					}),
			);
```

As you can see, it gets total document count from "response.hits.total", which is an object since ES7.

**Comment by bietkul** [comment]
@lakhansamani Can you check on it?
I think it is the side effects of your SSR PR.

**Comment by lakhansamani** [comment]
@bietkul will check this. 
Can you add more details on how this is a side effect of adding new props for `ReactiveBase` component on SSR?

**Comment by bietkul** [comment]
@lakhansamani You can check the code snippet added by @neoromantic.

**Comment by lakhansamani** [comment]
> @lakhansamani You can check the code snippet added by @neoromantic.

Thanks 👍
