### ISSUE TITLE
change searchWeight/weights to fieldWeights for DataSearch and CategorySearch

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivesearch#115]
For the **CategorySearch** and **DataSearch** components, the prop used for applying weights on field should be named as `fieldWeights` instead of `weights` (currently used in CategorySearch) or `searchWeight` (currently used in DataSearch).

**Comment by metagrover** [comment]
Added here: a94b467af9547d43275f7073d4e316149bbc4390
