### ISSUE TITLE
[Feature Request] componentId shouldn't be used as selected filter name

### ISSUE THREAD

**Issue by kud** [appbaseio/reactivesearch#1150]
**Affected Projects**
React

**Is your feature request related to a problem? Please describe.**
As I code in english, I also named my components in english in their `componentId` prop.

However, I had to change it in french because it's what it's used to display the name of the filter in `<SelectedFilters />` buttons.

There's a problem here between code naming and interface.

**Describe the solution you'd like**
components should habe a `componentName` prop which will be used for `<SelectedFilters />` and `componentId` for all about code like in `react` prop to make the relationship between components.

**Comment by kud** [comment]
```
            <MultiDropdownList
              placeholder="Sort du vote"
              componentId="Sorts"
              dataField="fate.label"
              react={{
                and: ["Cibles", "Groupes politiques", "Sorts", ],
              }}
```

It makes me quite sad to use those names in `react` prop as it's all about code here, not about interface.

**Comment by siddharthlatest** [comment]
@kud `componentId` is just a default key used in the SelectedFilters component. If you use the `filterLabel` key, that label will be used in the SelectedFilters component instead. HTH!

**Comment by kud** [comment]
Thank you!
