### ISSUE TITLE
How to re-run render function

### ISSUE THREAD

**Issue by z4m0** [appbaseio/reactivesearch#1158]
Given the following setup:
```jsx
const MyComponent = props => (
  <ReactiveList {...props}>
    {({ data }) => props.children({data, ...props})}
  </ReactiveList>
)
```
Is there a way to re-run the render function `props.children({data, ...props})` when some value of the variable props changes without repeating the ES query?

**Comment by bietkul** [comment]
It was an issue with `v3.0.0` fixed it in `v3.0.1`, please upgrade to the latest.
