### ISSUE TITLE
SearchFilters with SingleDropdownRange for date

### ISSUE THREAD

**Issue by lucmski** [appbaseio/reactivesearch#1160]
**Affected Projects**
 React

**Library Version:** 3.0.1

**Describe the bug**
https://github.com/twintproject/twint-search/blob/master/searchapp/src/SearchFilters.js#L68-L143

**To Reproduce**
http://x0rzkov.hd.free.fr:5000/
http://x0rzkov.hd.free.fr:9200/limo/_search?pretty=true&q=*:*

**Expected behavior**
How to filter by range of date in format "2009-01-01 00:00:00 " instead of "2009-01-01T00:00:00Z" ?

Cheers,
L.

**Comment by kvin97** [comment]
Shall I work on this bug...I have to contribute to an open source project as an assignment in university. Can you assign this to me?

**Comment by siddharthlatest** [comment]
@lucmski This isn't a ReactiveSearch issue. You have to first set the date format in your ElasticSearch index - see [ref here](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-date-format.html). Then, you should be able to query it via RS.

@kvin97 You can pick up any issue with a label `good first issue`.

**Comment by lucmski** [comment]
We could change the date format, but it would break a lot of stuff for Twint users.
And a lot of people are using elastic as backend, for work...

If with kibana we can set a specific datetime window, I'm sure we can do the same via requests since the endpoint is still the same.

Maybe you can add a date formatter on your side.
