### ISSUE TITLE
Error on Analytics with Toggle

### ISSUE THREAD

**Issue by gpassarelli** [appbaseio/reactivesearch#1164]
**Affected Projects**
Not sure if this is an issue with the reactivesearch or with the core. I'm currently using the Vue.JS version.

**Library Version:** x.y.z
1.0.0.beta-19

**Describe the bug**
When you set the Analytics options and try to toggle off a filter, it will fire the following error:
`TypeError: Cannot read property 'start' of null`
And breaks the code

**To Reproduce**
Set the analytics option to true on ReactiveBase and try to use the Toggle filter. When it fires on, it works, but when it fires off, it throws the error:

https://codesandbox.io/s/toggle-button-48mkz

**Expected behavior**
Reactivesearch should keep working 
**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome

**Comment by derantigo** [comment]
Same mistake with reactivesearch@3.0.3.  
I think need to add check componentValues.value on null in analytics.js (line 88).

**Comment by bietkul** [comment]
@gpassarelli I couldn't replicate it.

**Comment by gpassarelli** [comment]
@bietkul open the codesandbox I added, then click on "Social" to add the toggle filter, then click on "Social" again to remove the toggle filter, and you'll see the console error.

The expected behavior would be whenever "disabled" the toggle filter, to show all results, right?

**Comment by bietkul** [comment]
Thanks for the explanation, we'll fix it soon.

**Comment by bietkul** [comment]
@gpassarelli Fixed it in `1.0.0-beta.21`.
