### ISSUE TITLE
passing i18n instance within the ReactiveList props

### ISSUE THREAD

**Issue by abhinavgurung** [appbaseio/reactivesearch#1172]
I am trying to use i18n instance which is declared as
 const {t, i18n} = withTranslation();
I can use it inside the ReactiveList component but not one step below inside sortoptions prop.

How can i use the i18n instance in here:
sortOptions={[
            {
              label: 'Recently Updated',
              dataField: {**i18n**.language === 'en' ? 'dateStudyVersion.en' : 'dateStudyVersion.fr'},
              sortBy: 'desc',
            **},**
          ]}

**Comment by jyash97** [comment]
@abhinavgurung  Please follow the issue template. An example would really help us understand the issue.
