### ISSUE TITLE
[Question] v3 ReactiveGoogleMap How to add layers, polygons etc

### ISSUE THREAD

**Issue by delkant** [appbaseio/reactivesearch#1180]
I couldn't find any example on how to add polygons to a ReactiveGoogleMap 

There is an old example on how to do this 
https://github.com/appbaseio/reactivesearch/blob/next/site/demos/datalayer/src/index.js#L56

but I don't know how to adapt this to a ReactiveGoogleMap component.

Any examples or pointers to documentation on how to do this?

**Comment by jyash97** [comment]
Hey @delkant thanks for the issue. We should definitely have some documentation on this.

@lakhansamani Any idea on how to do this?

**Comment by delkant** [comment]
hi @lakhansamani any pointers about where should I be looking? Can a _ReactiveMap_ component be used directly instead of a _ReactiveGoogleMap_?? so I can do something like what you have for datalayer's example for V2

**Comment by delkant** [comment]
Hi @jyash97 @lakhansamani I know you must be very busy, but I am really needing a way to draw polygons and until now I haven't found a way to accomplish this. I would be very graceful if you can point me to a place where I can read more or find examples

**Comment by lakhansamani** [comment]
Hi @delkant sorry for the late reply. Will be sharing a quick sandbox by end of this day.

**Comment by lakhansamani** [comment]
@delkant here is a quick example of how you can add polygons to a ReactiveGoogleMap
https://codesandbox.io/s/reactivemaps-6loll

Closing this issue for now. Feel free to reopen if you face any other issues
