### ISSUE TITLE
How can I have a filter similar to DateRange but not with start date and end date and calender view ( as in few cases its not needed) . But the options in the filter should be predefined like - "Last Month", Last 3 Months" and "Last Year". So I checked at the Daterange filter by reactivesearch but I dont want two date field( start date and end date and also dont want calender view in the filter) . ONLY 3 fields last x days and automatically filter records based on my date from datafield. Do you guys know how can I do that?

### ISSUE THREAD

**Issue by Gouravagrawal** [appbaseio/reactivesearch#1182]
**Affected Projects**

**Library Version:** x.y.z

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Gouravagrawal** [comment]
Something like this...which is ultimately filtering results based on dates but does not need start date, end date or calender view

![image](https://user-images.githubusercontent.com/11697927/66070471-61db0000-e51f-11e9-83b1-099dfd964360.png)

**Comment by jyash97** [comment]
Hey @Gouravagrawal Please follow the issue template.  This is not a bug this is more of a question. 

You can do this using `MultiDataList` with `customQuery` for Date Range. You can read more about query [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-range-query.html#range-query-time-zone).
