### ISSUE TITLE
Do we have sketch/illustrator files of the UI components?

### ISSUE THREAD

**Issue by esafwan** [appbaseio/reactivesearch#119]
In the homepage and GitHub readme you have given examples of well designed UI components. Is there any particular UI kit that we have used. Or do we have a sketch/illustrator file of these components? It would help the UI designers of the project that have chosen reactivesearch for their project.

**Comment by siddharthlatest** [comment]
@esafwan The UI components on the Readme and webpage are inspired by the library,  we do have an internal design but there isn't a one-to-one match with the implementation.

Can you tell me more about the design use-case you are seeing here?

**Comment by esafwan** [comment]
When someone decides to use **reactivesearch** for their project, there will be at least some who are happy with the default look and feel that the library provides.  In most case, the UI of the project will be done by an independent designer. In such a case, if a design template exists around this framework, we would just need to share it with the designer. This is absolutely possible when we use Angular/Material and Bootstrap and all as design templates exist. We just need to ask the designer to use them as the base. Hope, I made myself clear.

**Comment by metagrover** [comment]
[Sketch file added for v2](https://opensource.appbase.io/reactivesearch/resources/ReactiveSearch_Playground.sketch)
