### ISSUE TITLE
when I land on my search page i want to hard code the value to be searched first.

### ISSUE THREAD

**Issue by abhinavgurung** [appbaseio/reactivesearch#1190]
so I am coming to the search page from different component A. now I am bringing a search text from component A to my search page. I want the search to be queried as soon as I land on my search page.  
currently I have it set up as when user types the value in search page and either press enter or a search button. it then sends query.

I see there is defaultValue  prop, but how to trigger the query on mount. 
How can this be achieved.

**Comment by abhinavgurung** [comment]
May be the other way of saying is: I have triggerQuery function controlled like it only fires when enter key is pressed. but I want to hard code an initial search value that fires automatically once.

**Comment by grinono** [comment]
Did you find a soltuion for this? looking for the same
