### ISSUE TITLE
RangeInput triggers query on render

### ISSUE THREAD

**Issue by scotthooker** [appbaseio/reactivesearch#1192]
**Affected Projects**
React 
**Library Version:** x.y.z
3.0.2

**Describe the bug**
RangeInput triggers query on render

**To Reproduce**
Add a range input filter

**Expected behavior**
The customQuery should not fire until an input is made. 

**Desktop (please complete the following information):**
Mac OSx (Irrevelant)

**Comment by scotthooker** [comment]
Any update on this?

**Comment by scotthooker** [comment]
Still a bug I think,

**Comment by joaodos3v** [comment]
+1

**Comment by scotthooker** [comment]
Not stale
