### ISSUE TITLE
NestedList: Component Update

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivesearch#12]
- [x] Update the **NestedList** component to be in sync with ReactiveBase
- [x] Delete the **NestedList** component from ReactiveBase.
- [x] Delete the **NestedList** story from ReactiveBase.
- [x] Delete the **NestedList** story from ReactiveMaps.

**Comment by metagrover** [comment]
Fixed here: 03c64b8b7afc4be72532162a335fac48d569412d
