### ISSUE TITLE
Unable to resolve data for blob: (null)

### ISSUE THREAD

**Issue by FuriioS** [appbaseio/reactivesearch#1201]
**Affected Projects**
React Native

**Library Version:** x.y.z
"@appbaseio/reactivesearch-native": "^0.12.0"

**Describe the bug**
An error message showing the following:
Unable to resolve data for blob: (null)

**To Reproduce**
Create an empty screen and add to the render <ReactiveBase />, <DataSearch /> and <ReactiveList />.

When the UI render the <ReactiveList />, app crashes showing the following error.
Unable to resolve data for blob: (null)

If I remove <ReactiveList />, when I write something on the <DataSearch /> searchbox, the same error ocurred.

**Expected behavior**
Render elements matching with the searched query

**Smartphone (please complete the following information):**
 - Device: iPhone XR / Pixel 2
 - OS: iOS 13.2 / Android 9

**Additional context**
    "native-base": "^2.13.8",
    "react": "16.8.6",
    "react-native": "0.60.5",

**Comment by davidmrp** [comment]
Same issue here!

**Comment by siddharthlatest** [comment]
@davidmrp We don't recommend using ReactiveSearch native, instead use Searchbox for React Native: https://docs.appbase.io/docs/reactivesearch/react-native-searchbox/quickstart/

**Comment by manuelabarca** [comment]
> @davidmrp We don't recommend using ReactiveSearch native, instead use Searchbox for React Native: https://docs.appbase.io/docs/reactivesearch/react-native-searchbox/quickstart/

But this library only work with appbase.io elastics, we need to use elastic cloud clusters :/

**Comment by siddharthlatest** [comment]
@manuelabarca You can use Searchbox React Native with any upstream Elasticsearch cluster. It requires installing appbase.io (or our open-source https://github.com/appbaseio/reactivesearch-api service) to interface with the upstream Elasticsearch.
