### ISSUE TITLE
DynamicRangeSlider not rendering when minimum value is 0

### ISSUE THREAD

**Issue by JakeShelley1** [appbaseio/reactivesearch#1205]
**Affected Projects**
React

**Library Version:** x.y.z
v3.0.3

**Describe the bug**
I have a field of datatype long called `rating_count`. When I use that as the `dataField` for my `DynamicRangeSlider` component the component does not render. 

The network request goes out and returns the proper response with the min and max of the field. When I update my index to make all `rating_count` values greater than zero, the `DynamicRangeSlider` renders properly.

**To Reproduce**
1. Create an index with a `long` field
2. Add a doc to that index where your chosen field is `0`
3. Setup `DynamicRangeSlider` as it says in the docs
4. Your slider will not render

**Expected behavior**
`DynamicRangeSlider` should render with the minimum value of 0

**Desktop (please complete the following information):**
Chrome v77.0.3865.120

**Additional context**
I'm not sure if this is expected behavior. Looking at the example (with the books) the minimum there is 1, so maybe this should be classified as an enhancement?

**Comment by JakeShelley1** [comment]
I've continued to dig on this with no luck. For more context, here's the query that my DynamicRangeSlider makes initially:
```
{
  "query": {
    "match_all":{}
  },
  "aggs": {
    "min": {
      "min": {
        "field": "review_count" 
      }
    },
    "max": {
      "max": {
        "field": "review_count"
      }
    }
  }
}
```

The `aggregations` field this returns looks like this
```
{
  "aggregations" : {
    "min" : {
      "value" : 0.0
    },
    "max" : {
      "value" : 12071.0
    }
  }
```
After removing all 0 values from the `review_count` field I'm searching, I tried again and the format of the result looks identical (except the values being 1.0 and 27.0 respectively), but the component still doesn't render.

**Comment by rp4rk** [comment]
Also experiencing this, exact same recreation steps as Jake.

**Comment by rp4rk** [comment]
https://github.com/appbaseio/reactivesearch/blob/next/packages/web/src/components/range/DynamicRangeSlider.js#L69

I believe this line is the problem, `this.props.range.start` will be coerced to false and cause the block to never be entered, meaning `this.state.range` is never set resulting in the component not rendering.
