### ISSUE TITLE
Customizing SelectedFilters component's markup

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivesearch#121]
```
<SelectedFilters onData={this.onData}>
...
onData(data) {
  // data has a shape of {label: "some_label", value: "selected_value(s)"}
  // value can be a String, Array (example: MultiList), or an Object (example: NestedList)
  return {
    label: "updated_label",
    value: "updated_value"
  }
}
```

**onData** - callback function called for each component's filter to be rendered in the SelectedFilters component which provides the {label, value} object and expects an updated object with the same {label, value} shape.

### Notes:

1. If the return value is null, the component's filter does not get rendered.
2. The label passed in onData is the componentId of the component (or the filterLabel if one is applied). The return value of the label can either be a String or a JSX markup (to render a custom CTA).
3. Complete styles won't be customizable with onData, a similar `onAllData` prop can allow the user to render the whole SelectedFilters component without any restrictions.

**Comment by siddharthlatest** [comment]
Needs to be discussed further along with how changes in #174 affects this.

**Comment by aktywnitu** [comment]
Hi,

How can I use SelectedFilters to clear my CustomComponent?
I have tested:
```
clearValue(label, value) {
    console.log('clearValues:)
    this.setValue('')
  }
  clearValue = () => {
    this.setValue('', true);
  }
```
But it does'n work.
So now I pushed extra button to Clear my filter
`results.push(<div key='' onClick={() => this.clearValue()}>Clear</div>)`
But I prefer user SelectedFilters component.
Please tell me how it works.

**Comment by metagrover** [comment]
Support added. [Refer docs here](https://opensource.appbase.io/reactive-manual/base-components/selectedfilters.html#extending).
