### ISSUE TITLE
ReactiveList: renderNoResults not triggering

### ISSUE THREAD

**Issue by anusha-dey** [appbaseio/reactivesearch#1214]
**Affected Projects**
Web

**Library Version:** x.y.z
3.0.3

**Describe the bug**
In ReactiveList, renderNoResults does not get triggered if onError has been previously triggered by the component.

**To Reproduce**
Cause an error to occur in an ElasticSearch msearch that triggers onError, then search for something that should result in no results. The renderNoResults function does not get triggered.

**Expected behavior**
Expected to see renderNoResults function triggered, or "No Results Found." displayed as is the default, instead nothing is being triggered or displayed.

**Desktop (please complete the following information):**
 - OS:Ubuntu
 - Browser: chrome

**Related**
https://github.com/appbaseio/reactivesearch/pull/1145
https://github.com/appbaseio/reactivesearch/pull/1137

**Comment by bietkul** [comment]
@qrst07 No results found is the case when there are empty results present in your db for the query, in case of an error you can use `renderError` and display whatever you want.

**Comment by danielsnider** [comment]
Hi @qrst07 can you please double check. Does the sequence of events that we mention still cause a bug? To test perform a search that triggers `renderError` (for example "::") followed by a valid search that returns no results, does `renderNoResults` get triggered? Thanks!

**Comment by danielsnider** [comment]
Yeah, I tested that it is still a bug. 
Hi @bietkul,
For us when `renderError` is triggered then we never see `renderNoResults` in the future until reloading the page. If we don't have an error occur then `renderNoResults` works fine. Does this happen to you?

**Library Version:** web 3.0.3
