### ISSUE TITLE
ReactiveList pagination button bug

### ISSUE THREAD

**Issue by WGriffing** [appbaseio/reactivesearch#1218]
**Affected Projects**
React

**Library Version:** x.y.z
3.0.3

**Describe the bug**
The pagination buttons do not work as expected for the `ReactiveList` (or `ResultList`) component.

I think there are 2 problems:
1. When `showEndPage={false}`, the last 2 pages do not display the pagination buttons properly.
2. When `showEndPage={true}` and `pages={5}`, the last 2 pages receive dedicated buttons, such as `1 ... 3 4 ... (N-1) N`. If the number of pages is increased, the last number of pages with dedicated buttons also increases.

**To Reproduce**
https://codesandbox.io/s/reactivelist-pagination-problem-rpeij

**Problem 1:**
1. Visit sandbox link above and navigate to https://rpeij.csb.app/?SearchResult=1894 in the embedded browser pane.
1. Scroll down to pagination buttons.
1. Observe that buttons are not as expected. Instead of seeing buttons for `Prev 1890 1891 1892 1893 1894`, we see buttons `Prev 1 Next`.
1. Click `Prev` button once.
1. Observe that buttons still are not as expected.
1. Click `Prev` button once.
1. Observe that the buttons finally look normally except that page `1892` appears to be the last page visually. We already know this is not the case.
1. Click `Next` once.
1. Observe problem has re-occurred.
1. Click `Next` button once.
1. Observe you have been redirected (unexpectedly) to results page 1 rather than ending up back at page 1894.

**Problem 2:**
1. Visit sandbox link above.
1. Edit `index.js` and change to `showEndPage={true}` in the `ReactiveList`.
1. Edit `index.js` and change to `pages={10}` in the `ReactiveList`.
1. Navigate to https://rpeij.csb.app/?SearchResult=1886 in the embedded browser pane.
1. Observe that the buttons are `Prev 1 ... 1883 1884 1885 1886 1887 ... 1891 1892 1893 1894 Next`.
1. Wouldn't it be more appropriate for the buttons to be `Prev 1 ... 1882 1883 1884 1885 1886 1887 1888 1889 ... 1894 Next`?
   * Perhaps instead of 1882, it should display 1890. An even number of pages is a slightly harder case than an odd number of pages.

**Expected behavior**
* Problem 1:
  * I expect the page numbers to match the actual last page. In the sandbox, this means that page 1894 should truly be the last page.
  * The page numbers should not fail to be created on the last 2 pages.
* Problem 2:
  * I would have expected the page numbers in my example to be `1 ... 3 4 5 ... N`. 
    - In other words, I expect to use one page for page 1, one page for the last page, and the the remaining X pages (in this example 3) to be used in the middle, around where I am navigating.
    - As I approach the first or last page, I expect the `...` gaps to go away and the buttons to become continuously numbered, for example something like `1 2 3 4 ... N`. I believe this already occurs but I'm mentioning it to ensure it doesn't regress.

**Screenshots**
Problem 1:
![image](https://user-images.githubusercontent.com/18578940/68035589-57d12c00-fc9a-11e9-949a-c3b8af40dfd1.png)
![image](https://user-images.githubusercontent.com/18578940/68035642-6b7c9280-fc9a-11e9-9685-7ee7e17a1826.png)

Problem 2:
![image](https://user-images.githubusercontent.com/18578940/68035696-84854380-fc9a-11e9-8d8d-9bcf52a6809e.png)

**Desktop (please complete the following information):**
 - OS: any
 - Browser: any
 - Version: any

**Additional context**
I believe this problem is caused by code in `packages/web/src/components/result/addons/Pagination.js`.

Specifically, I would like to draw your attention to line 153:
```js
{(currentPage <= (totalPages - pages) + 2 || totalPages <= pages) && buildPaginationDOM(this.props, 'start')}
```

Even more specifically, I believe the first conditional, `currentPage <= (totalPages - pages) + 2`, is responsible for problem 1. However, in my limited testing the fix is not as simple as `currentPage < totalPages` because that actually leads to unexpected `...` and other weird behavior when `showEndPage={true}`. I was going to submit a PR, but I've obviously not yet had time to zero in on a complete solution and thought a discussion might yield a better path forward.

To use our sandbox page numbers as an example, for the last page it is evaluating as `1893 <= (1894 - 5) + 2` which is `1893 <= 1891` (it is 1893 here because, as you know, the currentPage is indexed from 0 but I'm spelling it out for anyone else). It's obvious that it won't start rendering the buttons again until we go backwards 2 pages to 1891 (displayed to user as 1892) and that is exactly what you can see in the sandbox.

**Related Issues**
#1117

**Comment by WGriffing** [comment]
I just want to add that I'm very happy with how useful the entire tool is and I'm not at all opposed to doing some work and contributing back. I just haven't quite figured out the solution yet.

**Comment by ShahAnuj2610** [comment]
> Prev 1 ... 1882 1883 1884 1885 1886 1887 1888 1889 ... 1894

I was thinking we could introduce a prop called `pageNeighbours`, which indicates the number of additional pages to show on each side of the current page, this could address the rendering of pagination as quoted above in a much more generic way. This would collide with `pageSize` prop. Thoughts?

![](https://i.imgur.com/ACldHNb.png)

**Comment by WGriffing** [comment]
I'm not opposed to something like `pageNeighbors`, but as you mentioned, it is very similar to the `pageSize` property. You may also consider altering the behavior of `pageSize` such that when `showEndPage` is enabled, `pageSize` functions like your proposed `pageNeighbors` but otherwise functions as it does today. Then again, that may be an upgrade headache for users who are accustomed to the current behavior.

Other than the complication that `pageSize` is not always guaranteed to be odd (which is ideal when `showEndPage` is enabled), your idea is essentially the same issue/improvement I was trying to report. 

Your 3 pictures could correspond to `pageSize = 3`, `pageSize = 5`, and `pageSize = 7` and it would match my desired/expected behavior. 

However, if I tried those same settings today, I believe I would end up with the first picture the same, the 2nd picture becoming `1 ... 4 5 ...  13 14` and the 3rd picture becoming `1 ... 4 5 6 ... 12 13 14`. 

If you did a 4th picture with `pageNeighbors = 4` (equivalent to `pageSize = 9`), then I believe you would see `1 ... 5 6 7 8 ... 15 16 17 18`. 

The pattern I have observed is that for every `+2` on `pageSize` you see `+1` page in the middle group of buttons and `+1` page on the end group of buttons. I thought this was a possible bug with how the `pageSize` is divided between the 3 button groupings.
