### ISSUE TITLE
ReactiveBase Connect to AWS ElasticSearch via Lambda as proxy

### ISSUE THREAD

**Issue by rshahhutch** [appbaseio/reactivesearch#1225]
Hi!

We are trying to connect ReactiveBase to AWS ElasticSearch with Lambda as proxy. The POST request payload we are seeing is as below that is being sent.

{"preference":"SearchResult"}
{"query":{"match_all":{}},"size":5,"_source":{"includes":["*"],"excludes":[]},"from":0}

The response we get back is 

"errorType": "SyntaxError",
    "errorMessage": "Unexpected token \\ in JSON at position 30",
    "trace": [
        "SyntaxError: Unexpected token \\ in JSON at position 30",
        "    at JSON.parse (<anonymous>)",
        "    at Runtime.handleOnce (/var/runtime/Runtime.js:67:14)"
    ]

The Lambda function throws above error as it doesn't accept invalid JSON. We are unable to connect and get any result back. Is there any workaround? How do you suggest we handle this?

**Comment by josephbburke** [comment]
So i think that your lambda proxy function on AWS is incorrectly parsing the JSON body from ReactiveBase. After debugging my lambda, I found the payload to be:

```
{
    "preference": "mainSearch"
}

{
    "query": {
        "bool": {
            "must": [
                {
                    "bool": {
                        "must": {
                            "bool": {
                                "should": [
                                    {
                                        "multi_match": {
                                            "query": "a",
                                            "fields": [
                                                "name",
                                                "description"
                                            ],
                                            "type": "best_fields",
                                            "operator": "or",
                                            "fuzziness": 0
                                        }
                                    },
                                    {
                                        "multi_match": {
                                            "query": "a",
                                            "fields": [
                                                "name",
                                                "description"
                                            ],
                                            "type": "phrase_prefix",
                                            "operator": "or"
                                        }
                                    }
                                ],
                                "minimum_should_match": "1"
                            }
                        }
                    }
                }
            ]
        }
    },
    "size": 20
}
```

Which is two JSON objects. This means that JSON.parse() will fail:
```
> var test = "{\"preference\":\"mainSearch\"}\n{\"query\":{\"bool\":{\"must\":[{\"bool\":{\"must\":{\"bool\":{\"should\":[{\"multi_match\":{\"query\":\"asd\",\"fields\":[\"name\"],\"type\":\"best_fields\",\"operator\":\"or\",\"fuzziness\":0}},{\"multi_match\":{\"query\":\"asd\",\"fields\":[\"name\"],\"type\":\"phrase_prefix\",\"operator\":\"or\"}}],\"minimum_should_match\":\"1\"}}}}]}},\"size\":20}\n"
undefined
> JSON.parse(test)
Thrown:
SyntaxError: Unexpected token { in JSON at position `28`
```

To solve this either don't parse the JSON, or catch and do nothing:
```
 try {
        var testJSON = JSON.parse(opts.body);
        console.log("Valid JSON")
    } catch(e) {
        console.log("Failed to parse JSON")
    }
```

**Comment by prashant-rajoriya** [comment]
> So i think that your lambda proxy function on AWS is incorrectly parsing the JSON body from ReactiveBase. After debugging my lambda, I found the payload to be:
> 
> ```
> {
>     "preference": "mainSearch"
> }
> 
> {
>     "query": {
>         "bool": {
>             "must": [
>                 {
>                     "bool": {
>                         "must": {
>                             "bool": {
>                                 "should": [
>                                     {
>                                         "multi_match": {
>                                             "query": "a",
>                                             "fields": [
>                                                 "name",
>                                                 "description"
>                                             ],
>                                             "type": "best_fields",
>                                             "operator": "or",
>                                             "fuzziness": 0
>                                         }
>                                     },
>                                     {
>                                         "multi_match": {
>                                             "query": "a",
>                                             "fields": [
>                                                 "name",
>                                                 "description"
>                                             ],
>                                             "type": "phrase_prefix",
>                                             "operator": "or"
>                                         }
>                                     }
>                                 ],
>                                 "minimum_should_match": "1"
>                             }
>                         }
>                     }
>                 }
>             ]
>         }
>     },
>     "size": 20
> }
> ```
> 
> Which is two JSON objects. This means that JSON.parse() will fail:
> 
> ```
> > var test = "{\"preference\":\"mainSearch\"}\n{\"query\":{\"bool\":{\"must\":[{\"bool\":{\"must\":{\"bool\":{\"should\":[{\"multi_match\":{\"query\":\"asd\",\"fields\":[\"name\"],\"type\":\"best_fields\",\"operator\":\"or\",\"fuzziness\":0}},{\"multi_match\":{\"query\":\"asd\",\"fields\":[\"name\"],\"type\":\"phrase_prefix\",\"operator\":\"or\"}}],\"minimum_should_match\":\"1\"}}}}]}},\"size\":20}\n"
> undefined
> > JSON.parse(test)
> Thrown:
> SyntaxError: Unexpected token { in JSON at position `28`
> ```
> 
> To solve this either don't parse the JSON, or catch and do nothing:
> 
> ```
>  try {
>         var testJSON = JSON.parse(opts.body);
>         console.log("Valid JSON")
>     } catch(e) {
>         console.log("Failed to parse JSON")
>     }
> ```

Then how do we send only one JSON, the query JSON
