### ISSUE TITLE
SelectedFilters: onAllData prop

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivesearch#123]
An alternative to #121 which allows customizing the complete markup as well as the styles of the `SelectedFilters` component.

```javascript
<SelectedFilters onAllData={this.onAllData} .. />
...
onAllData = (data) => (
  // data here is an Array of objects, where object has the shape of
  data.map(({ label, value, clearFilterCallBack }) => (
    <div className="my_tag">
        <div className="my_label_class">label</div>: 
        <div className="my_value_class">value</div>
        <div className="my_clearFilter_class" onClick={clearFilterCallBack}>X</div>
    </div>
  ))
)
```

**Note**: How to allow selective clearing of a value or values when the value is a vector?

**Comment by divyanshu013** [comment]
This is now possible with the `render` prop of `SelectedFilters`. [Docs](https://opensource.appbase.io/reactive-manual/base-components/selectedfilters.html#extending)
