### ISSUE TITLE
Pagination: browser back button issue

### ISSUE THREAD

**Issue by rjschmitt** [appbaseio/reactivesearch#1233]
**Affected Projects**
React

**Library Version:** 3.0.3

**Describe the bug**
When selecting some value in `MultiDropdownList` and clicking pagination some pages, let's say starting from 1 to 2, 3, 4, 5 and `URLParams` is active the parameter in the url changes accordingly. But when I click the back button of the browser, it instantly goes all the way back to page 1 and resets MultiDropdownList.

**To Reproduce**
go to https://codesandbox.io/s/reactivelist-pagination-problem-rpeij
Select some value in MultiDropdownList and just click the pagination and then at some point the browser back button.

**Expected behavior**
Being on page n it should step back to page n-1 (in history stack). e.g. coming from page 4 to 3 the browser back button should target back to page 3.
Furthermore, MultiDropdownList should remain the value it had.

**Screenshots**
![image](https://user-images.githubusercontent.com/2667575/68850347-26ae1e00-06d4-11ea-84ed-ecdc1d7471f1.png)
![image](https://user-images.githubusercontent.com/2667575/68850366-3168b300-06d4-11ea-8baf-8ce8e61e2601.png)
![image](https://user-images.githubusercontent.com/2667575/68850393-40e7fc00-06d4-11ea-9ed3-217e33d5b9cf.png)
![image](https://user-images.githubusercontent.com/2667575/68850432-4fceae80-06d4-11ea-8662-28347b5b2b22.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chromium
 - Version Version 78.0.3904.70 (Official Build) Arch Linux (64-bit)

**Comment by Pawani-DeSilva** [comment]
Any update on this?

**Comment by f2xx-blip** [comment]
I am getting the same error. Can we fix this?
