### ISSUE TITLE
Pagination with URLParams ignores ReactiveList defaultQuery

### ISSUE THREAD

**Issue by grantas33** [appbaseio/reactivesearch#1234]
**Affected Projects**

React

**Library Version:** x.y.z

3.0.3

**Describe the bug**

An user visits the webpage with the ReactiveList component, and with the ReactiveList page number set in URLParams. User changes the page by clicking on a pagination button, and then returns to the initial page by clicking on a pagination button. Upon clicking on the initial page pagination button, the defaultQuery of the ReactiveList stops to execute in further requests and the page does not update

**To Reproduce**

https://codesandbox.io/s/reactivelist-hhvml
Add `?SearchResult=3` to the query params in the sandbox browser and refresh (reload) the sandbox browser once.
Go to the first page by clicking on the first pagination button.
Go to the third page by clicking on the third pagination button.

**Expected behavior**

The products remain sorted as described by the ReactiveList defaultQuery and the third page appears

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Chrome
 - Version 78

**Comment by ShahAnuj2610** [comment]
@grantas33 seems to work for me.

![](https://i.imgur.com/otziLBg.png).

**Comment by siddharthlatest** [comment]
@grantas33 Can confirm that the issue doesn't occur. I am marking this as closed, but feel free to add an example if you're still seeing this elsewhere.
