### ISSUE TITLE
Downshift Version Conflict

### ISSUE THREAD

**Issue by rccoe** [appbaseio/reactivesearch#1236]
**Affected Projects**
React

**Library Version:** x.y.z
3.0.3

**Describe the bug**
The latest version of Downshift breaks MultiDropdownLost
 
**To Reproduce**

Installed the latest version of [downshift](https://www.npmjs.com/package/downshift) (3.4.1) and used it on the same page as several MultiDropdownList components. The selects don't render, just the titles.

**Expected behavior**
The package should probably be locked at a specific version, not with "^1.31.2", or fixed to work with newer versions

**Screenshots**

**Desktop (please complete the following information):**
Mac, Chrome

**Smartphone (please complete the following information):**

**Additional context**

Thanks!

**Comment by ShahAnuj2610** [comment]
@rccoe I'm using `downshift` latest version, but that does not affect the `MultipDropdownList` style: https://codesandbox.io/s/confident-dawn-1yknf. Can you share a reproducible code sandbox demo?
