### ISSUE TITLE
MultiDropDownList SearchBox no Auto-Refresh/Render

### ISSUE THREAD

**Issue by jogam** [appbaseio/reactivesearch#1237]
**Affected Projects**
Vue.JS

**Library Version:** 1.0.0-beta.21

**Describe the bug**
Enabling searchbox via :showSearch="true" shows input field properly, but available options in dropdown list are only filtered if dropdown is re-opened or 'ENTER' is pressed in input field. In web version filtering is as typed / reactive?!

**To Reproduce**

1. open Demo sandbox from docu: https://opensource.appbase.io/reactive-manual/vue/list-components/multidropdownlist.html
2. add `:showSearch="true"` to MultiDropdownList definition in App.vue
3. start typing in searchbox <-- no change in options
4. close dropdown + re-open OR hit ENTER

**Expected behavior**
Options should be filtered as typed in searchbox as per WEB version.

**Desktop:**
 - Ubuntu 16.04
 - Chromium / Electron
 - 78.0.3904.70 / 5.0.11

**Comment by infinitodk** [comment]
Reopen! Issue persists.
