### ISSUE TITLE
Missing props for v2

### ISSUE THREAD

**Issue by divyanshu013** [appbaseio/reactivesearch#124]
## SingleList

- [x] selectAllLabel
- [x] showSearch and placeholder
- [x] <strike>initialLoader</strike> (Not supported anymore)

## MultiList

- [x] selectAllLabel
- [x] showSearch and placeholder
- [x] <strike>initialLoader</strike> (Not supported anymore)

## ReactiveList

- [x] sortOptions
- [x] <strike>initialLoader</strike> loader

## SingleDropdownList

- [x] showCount

## MultiDropdownList

- [x] showCount

## ToggleButton

- [x] URLParams standardize
- [x] onValueChange standardize

**Comment by metagrover** [comment]
Added here: c21f7da3bc81f5647bdd5bae4cfd1104de922fb1 1f7b7332e7c1c2b85a3574dcba7b7cd3706f6717 8ebacea08d71e764589adaf40fc04508f157118e a6a7f1151a5d722c5206546a63886a8820ec4c41 c723005f80a0b1164436b47ea4e50e381585f91c 358b87601442236ae041299f2dcc6b7b1364b351
