### ISSUE TITLE
Props getting passed as value in MultiDataList customQuery

### ISSUE THREAD

**Issue by rccoe** [appbaseio/reactivesearch#1252]
**Affected Projects**
React

**Library Version:** x.y.z
3.1.0

**Describe the bug**
When using customQuery in MultiDataList, for which the props are documented as (value, props), 50% of the time, the "Value" prop gets passed the props for the MultiDataList itself.

**To Reproduce**

For some reason, codesandbox isn't working for the code I put in there, but here it is. If you check the console, sometimes the "Value" log will be an array, sometimes it'll be an object of props e.g. "URLParams", "innerClass"...
https://codesandbox.io/s/vigorous-antonelli-2xg71

**Expected behavior**
Value prop should be "Value" 100% of the time. Passing it props breaks the query if you start passing it random react props as JSON.

**Screenshots**
<img width="279" alt="Screen Shot 2019-11-22 at 10 25 39 AM" src="https://user-images.githubusercontent.com/1855247/69438091-7747fb80-0d12-11ea-92ce-d28e057e6339.png">

Correct output:
<img width="499" alt="Screen Shot 2019-11-22 at 10 26 16 AM" src="https://user-images.githubusercontent.com/1855247/69438156-8dee5280-0d12-11ea-977f-1a1c61fd5dcd.png">

Second, incorrect props that break the query:
<img width="521" alt="Screen Shot 2019-11-22 at 10 26 57 AM" src="https://user-images.githubusercontent.com/1855247/69438222-a5c5d680-0d12-11ea-85bc-626e73c4c4c8.png">

**Desktop (please complete the following information):**

Mac Mojave, Chrome latest

**Smartphone (please complete the following information):**

**Additional context**

**Comment by crab86** [comment]
Does this only happen in MultiDataList? Having troubles with MultiList and customQuery at the moment. I will try to reproduce it here as well.
