### ISSUE TITLE
React Typescript - customQuery not a valid prop on ReactiveList

### ISSUE THREAD

**Issue by rccoe** [appbaseio/reactivesearch#1271]
**Affected Projects**
React

**Library Version:** x.y.z
3.1.1

**Describe the bug**
Trying to add customQuery as a prop to ReactiveList, I get an error. The documentation states that this prop should be possible: [Docs](https://docs.appbase.io/docs/reactivesearch/v3/result/reactivelist/)

> It is possible to override this query by providing defaultQuery or customQuery.

**To Reproduce**

```
<ReactiveList
{...props}
            customQuery={() => ({ query: { match_all: {} } })}
/>
```

**Expected behavior**
Typescript shouldn't complain

**Comment by ShahAnuj2610** [comment]
seems to be a typo, fixed [docs](https://github.com/appbaseio/Docs/pull/91)
