### ISSUE TITLE
CategorySearch render prop is not working

### ISSUE THREAD

**Issue by skagrawal10** [appbaseio/reactivesearch#1272]
Hi, 

I am using render prop in CategorySearch to change the layout of suggestion shown to user. But, it seems, it is not overriding default render function. Even, when I am providing custom render function, it is taking default layout. 

Please help here.

**Comment by jyash97** [comment]
Hey @skagrawal10  
Can you share a codesandbox link? 

Check this example: https://codesandbox.io/s/beautiful-kirch-z958p
