### ISSUE TITLE
Autosuggest does not work for non-ascii characters in DataSearch

### ISSUE THREAD

**Issue by lakhansamani** [appbaseio/reactivesearch#1273]
**Affected Projects**
ReactJS

**Library Version:** x.y.z
3.1.1

**Describe the bug**
When we have `asciifolding` analyzer on for text fields, ElasticSearch tokenizes ascii characters into English characters which makes the search easier.
For example if I have `crémer` in my data, then it tokenizes this into `cremer` so that we can search with normal English.

Sample DataSet: https://dejavu.appbase.io/?appname=ascii_example&url=https://search-arc-tester-f6qku5j7i5lnqogzbibj336mgy.us-east-1.es.amazonaws.com/&mode=edit

In DataSearch component when we search through `cre`, `_msearch` query returns the correct result. But these results are not shown in suggestions. This is because `getSuggestion` is not able to parse based on `currentValue`, i.e. `cre`

getSuggestion: https://github.com/appbaseio/reactivecore/blob/master/src/utils/suggestions.js#L23

**To Reproduce**
https://codesandbox.io/s/infallible-tdd-3fg68

**Expected behavior**
it should show all results in autosuggestion / at least allow this configured with custom render method.

**Comment by lakhansamani** [comment]
Works with custom render method and `rawData`

updated example: https://codesandbox.io/s/infallible-tdd-3fg68

**Comment by davidkong0987** [comment]
Something happened overnight... now the sandbox no longer works. When clicking the result, the entire screen goes blank and the following errors are raised
```

Warning: A component is changing a controlled input of type undefined to be uncontrolled. Input elements should not switch from controlled to uncontrolled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components
    in input (created by Styled(input))
    in Styled(input) (created by Downshift)
    in div (created by Downshift)
    in Downshift (created by DataSearch)
    in div (created by Styled(div))
    in Styled(div) (created by DataSearch)
    in DataSearch
    in Unknown (created by WithTheme(Component))
    in WithTheme(Component) (created by Context.Consumer)
    in Connect(WithTheme(Component)) (created by ForwardRef)
    in ForwardRef (at src/index.js:14)
    in div
    in Unknown (created by Styled(Component))
    in Styled(Component) (created by URLParamsProvider)
    in URLParamsProvider
    in Unknown (created by Context.Consumer)
    in Connect(Component) (created by ForwardRef)
    in ForwardRef (created by ReactiveBase)
    in Provider (created by ReactiveBase)
    in ThemeProvider (created by ReactiveBase)
    in ReactiveBase (at src/index.js:10)
    in div (at src/index.js:9)
    in App (at src/index.js:66)
The above error occurred in the <DataSearch> component:
    in DataSearch

    in Unknown (created by WithTheme(Component))

    in WithTheme(Component) (created by Context.Consumer)

    in Connect(WithTheme(Component)) (created by ForwardRef)

    in ForwardRef (at src/index.js:14)

    in div

    in Unknown (created by Styled(Component))

    in Styled(Component) (created by URLParamsProvider)

    in URLParamsProvider

    in Unknown (created by Context.Consumer)

    in Connect(Component) (created by ForwardRef)

    in ForwardRef (created by ReactiveBase)

    in Provider (created by ReactiveBase)

    in ThemeProvider (created by ReactiveBase)

    in ReactiveBase (at src/index.js:10)

    in div (at src/index.js:9)

    in App (at src/index.js:66)


React will try to recreate this component tree from scratch using the error boundary you provided, ReactiveBase.
```
