### ISSUE TITLE
ReactiveComponent SelectedValue Existence Check Fails on Number with Value 0

### ISSUE THREAD

**Issue by AaronPlave** [appbaseio/reactivesearch#1277]
**Affected Projects**
React

**Library Version:** 3.0.2

**Describe the bug**
The `selectedValue` prop in ReactiveComponent can be of type `number` but in the `mapStateToProps` of ReactiveComponent the value existence check `state.selectedValues[props.componentId].value` fails when the value is 0. The result is that `selectedValue` will be `null` when it should be `0`. This issue is exposed through the use of the `setQuery` prop in the render method of ReactiveComponent. 

Ex:
```JS
setQuery({
   query: { match: { 'someKey': 0 } }, 
   value: 0
});
```
results in a `null` value for the ReactiveComponent.

See https://github.com/appbaseio/reactivesearch/blob/next/packages/web/src/components/basic/ReactiveComponent.js#L284 for the line of code in question.

**Expected behavior**
SelectedValue should be able to handle 0 as a valid number.

**Additional context**
Ran into this issue when trying to implement a custom number input using ReactiveComponent. My workaround so far has been to use a string version of the number as the `value` property of the object I pass to `setQuery`. This isn't too much of a headache but requires some back and forth type conversions which could be avoided.

**Comment by mitchgillin** [comment]
We are trying to create a custom toggle filter and are running into this problem as well. Initializing a filter with a value of false will cause an error of "improper selectedValue"
