### ISSUE TITLE
Add input controls to RangeSlider

### ISSUE THREAD

**Issue by divyanshu013** [appbaseio/reactivesearch#128]
Ref

![image](https://user-images.githubusercontent.com/6682655/33565519-59453ecc-d943-11e7-9155-ca8bc0ec6f2f.png)

**Comment by siddharthlatest** [comment]
@divyanshu013 So this would be like selecting from a range of values, is the range user defined? Mostly, I have seen input boxes in e-commerce sites, not sure if a dropdown makes sense.

**Comment by metagrover** [comment]
Imo input boxes would be better. We can create it as a new component - `RangeInput`, and in order to achieve the functionality in the above screenshot, we can make use of `onValueChange` and `defaultSelected` props.

**Comment by siddharthlatest** [comment]
`RangeInput` is a good name, slider can be an optional prop for this component.

**Comment by divyanshu013** [comment]
Added in https://github.com/appbaseio/reactivesearch/commit/ce01d9a25fc7c615a44a55c0bdd12470225b913c
