### ISSUE TITLE
Incorrect Vue Documentation on ReactiveList renderResultStats 

### ISSUE THREAD

**Issue by bitbit-gmbh** [appbaseio/reactivesearch#1280]
I recently updated to ReactiveSearch Vue 1.0, and noticed that renderResultStats for ReactiveList changed slightly (despite the documentation!):

https://opensource.appbase.io/reactive-manual/vue/result-components/reactivelist.html

renderResultStats -> totalResults is not available anymore, it is now numberOfResults.
totalPages  is now numberOfPages.

Is this a bug or a feature? :-)

**Comment by jyash97** [comment]
Hey @Dreamfish19 

We have switched to new docs. Check the vue reactivesearch docs here: https://docs.appbase.io/docs/reactivesearch/vue/overview/QuickStart/
