### ISSUE TITLE
Can you apply global filtering in reactivesearch

### ISSUE THREAD

**Issue by allendol** [appbaseio/reactivesearch#1288]
This is my use case.
I have created index which has a column: city. (Actually column city is within the child index. So the index is a parent child index.)
I would like to use ReactiveSearch to display data for this index using SingleDropDown list, DataSearch, and ReactiveList. But I like to apply a filtering for city='something" no matter what the user selects or types in the search criteria.
I cannot use SingleDropDown for city and set default value for it, because the city column is not in the main index. It is in the child index and I don't know if it is possible to put datafield and refer to child index.
How can I do it?

**Comment by grinono** [comment]
Interested in this as well, adding custom queries(filters) per component may be the only solution.

**Comment by jide** [comment]
There is an example of using ReactiveComponent to set a default value and refer to it in other components' "react" prop. Not sure if it fits with child index though, but here is the example: 
https://codesandbox.io/s/3ylrrr0r5q?from-embed
And the doc:
https://docs.appbase.io/docs/reactivesearch/v3/advanced/reactivecomponent/
