### ISSUE TITLE
React + Reactivesearch with ES index + wrong default argument _msearch

### ISSUE THREAD

**Issue by cb29** [appbaseio/reactivesearch#1304]
Hello,

I'm using "@appbaseio/reactivesearch": "^3.2.0", and an index in a ES cluster version 7.0.
I tried to use a basic SearchBox, but I get always an error 401 from ES.
After having debug, I see that the request use this URL pattern : 
`https://my-cluster/my-index/_msearch`
With ES the first argument must be "_search' and not 'msearch', isn't ir?

How can I modify this argument for my differents requests? Add an element in the 'ReactiveBase' component?

Thanks for your help.

**Comment by cb29** [comment]
I found a solution to modify this first argument, add this line in the Reactsearch Base : transformRequest={props => ({    ...props,    url: props.url.replace('_msearch', '_search')  })}

But now I get an 406 error....

DId you have a fully example to connect Reactivesearch with an index from an ES Cluster ?

Thanks.

**Comment by lakhansamani** [comment]
@cb29 `_msearch` is a valid request for ElasticSearch. It helps in combining requests for multiple components.
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-multi-search.html

`401` Error refers to Unauthorized error. That means you are missing credentials for your URL
you can either use `credentials` prop or add basic auth in URL itself
example: `http://admin:admin@mycluster.com`

For more information, you can check docs here: https://docs.appbase.io/docs/reactivesearch/v3/overview/reactivebase/

**Comment by cb29** [comment]
@lakhansamani

it's ok if I add the basic auth in the url. Thanks !!!
