### ISSUE TITLE
Default Suggestions doesn’t work with render prop in DataSearch widget

### ISSUE THREAD

**Issue by abhinavraj23** [appbaseio/reactivesearch#1310]
**Describe the bug**
Default Suggestions doesn’t work with render prop in DataSearch widget. [Codesandbox link](https://codesandbox.io/s/awesome-swartz-7iuk2?fontsize=14&hidenavigation=1&theme=dark
)

**To Reproduce**
Use this codesandbox [link](https://codesandbox.io/s/awesome-swartz-7iuk2?fontsize=14&hidenavigation=1&theme=dark)

**Expected behavior**
Default suggestions should work in any case

**Comment by bietkul** [comment]
@abhinavraj23 I checked the code sandbox example, you can directly(no need to define `defaultSuggestions` prop) use the default suggestions in your custom`render` method. It doesn't seem to be a library bug, if you're using the `render` method then it's your responsibility to render the UI.
For example, check [here](https://codesandbox.io/s/pedantic-wozniak-ksnr1).
