### ISSUE TITLE
Run reactivesearch for development purposes

### ISSUE THREAD

**Issue by michalica** [appbaseio/reactivesearch#1313]
**Affected Projects**
React, web

**Library Version:** x.y.z
next

**Describe the bug**
I really spent a lot of time on this so I need to ask. 
I forked, cloned (ssh), installed dep., and run project with _yarn dev:web_ .

Dev server is running it detects changes but I really cannot figure out what port is used by the server.

**Screenshots**
My terminal:
<img width="565" alt="Snímka obrazovky 2020-01-04 o 21 10 14" src="https://user-images.githubusercontent.com/16046334/71771136-c5b60000-2f36-11ea-9180-c91d5627f01d.png">

**Desktop (please complete the following information):**
 - Mojave

**Additional context**
thanks for helping me

**Comment by jyash97** [comment]
Hey @michalica 

You will need to run an example present in `/packages/web/examples/` in order to debug and test the latest changes.
