### ISSUE TITLE
Datasearch autocomplete suggestions size

### ISSUE THREAD

**Issue by priyanksha-monotype** [appbaseio/reactivesearch#1319]
We are using DataSearch component of ReactiveSearch-vue in our application.

 

I am facing one issue because dataSearch(autocomplete) displays only 10 results, but my query is returning 20.

 

Is there any property where we can set this size or render every suggestions?

**Comment by priyanksha-monotype** [comment]
@bietkul Any idea about this?

**Comment by jyash97** [comment]
Hey @priyanksha 

This enhancement makes sense.

Currently we are slicing down the suggestions to a hardcoded value which is `10`. It should be easy to add a prop called `suggestionSize` or `size` which can be used in place of this hardcoded value. 

Code Line: https://github.com/appbaseio/reactivesearch/blob/next/packages/web/src/components/search/DataSearch.js#L843

Thoughts @siddharthlatest @bietkul @lakhansamani @ShahAnuj2610  ?

**Comment by bietkul** [comment]
Right, it should be configurable.

**Comment by lakhansamani** [comment]
@jyash97 @priyanksha yes this should be configurable 👍

**Comment by priyanksha-monotype** [comment]
I tried adding "size" property in DataSearch, it didn't work. What reactive base version should I use?

**Comment by priyanksha-monotype** [comment]
My current version is : "@appbaseio/reactivesearch-vue": "1.0.0-beta.21",

**Comment by siddharthlatest** [comment]
Re-opening as the Vue.JS enhancement is still remaining.
