### ISSUE TITLE
RangeSlider beforeValueChange selectedValue issue

### ISSUE THREAD

**Issue by divyanshu013** [appbaseio/reactivesearch#132]
Using a `setState` in `beforeValueChange` is causing the component to receive `selectedValue` in an infinite loop. Need to find the root cause and fix.

**UPDATE**: root cause found to be `selectedValue` change while the component is updating. Also noticeable if a `beforeValueChange` promise takes long time to resolve and the component's state changes during that time. This was causing a chain reaction 💥  of setting and resetting the `selectedValue`

**Comment by metagrover** [comment]
Possible fix: Use lock based system

**Comment by metagrover** [comment]
Fixed here: 0c531212ae02bc452c1d9ea61d4ca2ead1ea2f4b

--

TODO:
- [ ] Add locking mechanism to all components

**Comment by siddharthlatest** [comment]
@dhruvdutt Do you want to pick this one up?

**Comment by dhruvdutt** [comment]
@siddharthlatest Yeah, I already saw the changes yesterday and talked with @metagrover about it. The issue is a bit complicated than it seems. We will update the assignees today once it's finalized.
