### ISSUE TITLE
DataSearch component doesn't update hits in StateProvider correctly If I use autoSuggest=false

### ISSUE THREAD

**Issue by michalica** [appbaseio/reactivesearch#1320]
**Affected Projects**
Web

**Library Version:** x.y.z

3.2.1

**Describe the bug**
If I use autoSuggest=false, State provider provides just currentValue of DataSearch. It doesn't provide hits nor aggregations.

**To Reproduce**
use autoSuggest=false and consoleLog searchState[comoponentIdOfDataSearch]

**Screenshots**

I did some inspections of action in redux that are dispatched on ValueChange:

disableAutosuggest:

![disableAUtosuggest](https://user-images.githubusercontent.com/16046334/72085409-8c4e0d80-3305-11ea-9a84-5af5c8de6c49.png)

enableSuggest:

![withEnabledAutosuggested](https://user-images.githubusercontent.com/16046334/72085456-9ff97400-3305-11ea-8b75-3539af50a205.png)

**Desktop (please complete the following information):**
 - Ubuntu

**Comment by ShahAnuj2610** [comment]
hey, @michalica can you share `code sandbox` link?

**Comment by michalica** [comment]
Hey @ShahAnuj2610 , Here is example in codesandbox:

https://codesandbox.io/s/distracted-grothendieck-3mxgs

You can see (in console) that StateProvider provide just value of BookSensor if autosuggest=false

**Comment by ShahAnuj2610** [comment]
it's the correct behaviour. When `autoSuggest={false}`, suggestions query doesn't get fired, so hits for `BookSensor` don't get updated. As a result, `StateProvider` doesn't get updated with `hits` and you only get `currentValue`
