### ISSUE TITLE
Please remove the typo error in MultiDataList js code for customQuery to work

### ISSUE THREAD

**Issue by e-gaulue** [appbaseio/reactivesearch#1328]
https://github.com/appbaseio/reactivesearch/blob/640f970330509d7a85bf40b1125ddbe75e88f2b8/packages/web/src/components/list/MultiDataList.js#L289

The call just need single parentheses. Maybe somme other places in the code are concerned.

Regards,

**Comment by e-gaulue** [comment]
It's on the way: #1359

**Comment by alexfgo** [comment]
The same problem appears to be happening on defaultQuery property.
At this moment it seems impossible to provide any custom function on both properties.

Regards
