### ISSUE TITLE
CustomQuery datasearch doen't fire on double space and backspace

### ISSUE THREAD

**Issue by priyanksha-monotype** [appbaseio/reactivesearch#1331]
@siddharthlatest @jyash97 @bietkul 
Hi Guys,

My customQuery is called but _msearch call is not going on more than one space or backspace in DataSearch. Stuck in this. Any idea?

<DataSearch
          componentId="SearchSensorAc"
          iconPosition="right"
          categoryField="type"
          placeholder="Search by fonts, designers, foundry, psname"
          queryFormat="or"
          class="data-search"
          filterLabel="Search"
          renderNoSuggestion="No suggestions found"
          :URLParams="false"
          :dataField="['all_search_names','name']"
          :fieldWeights="[1, 2]"
          :autosuggest="true"
          :fuzziness="0"
          :debounce="350"
          :showClear="true"
          :customQuery="customQuery"
          @valueChange="handleValueChange"
          @keyUp.enter="handleKeyPress"
          @valueSelected="handleValueSelected"
          :defaultSelected="searchTerm"
        />

**Comment by ShahAnuj2610** [comment]
@priyanksha can you share code sandbox example?
