### ISSUE TITLE
Checking of checkbox in Multilist is slow when there is a lot of data

### ISSUE THREAD

**Issue by michalica** [appbaseio/reactivesearch#1335]
**Affected Projects**

Web
**Library Version:** 3.2.4

**Describe the bug**

Checking checkbox MultiList and MultiDataList in combination with showing a lot of data (1000 reacords)  in ReactiveList has significant delay.

**To Reproduce**

https://codesandbox.io/s/silent-sunset-f33kk
 - https://f33kk.csb.app/

**Expected behavior**

Checkbox should be checked immidiately

**Desktop (please complete the following information):**
- Ubuntu

**Additional context**

I know that 1000 records is a lot but I noticed the issue already with 300 records

**Comment by davidkong0987** [comment]
writing our own render function made a huge diff

```
render={({
          data,
          handleChange,
          }) => console.log(data) || data.map(item => (
              <div onClick={() => handleChange(item.value)} key={item.value}>
                  <span>{item.value}</span>
                  {state[stateName].includes(item.value)&&"✓"}
              </div>
            )
          )}
```
