### ISSUE TITLE
appbase.io image on search page

### ISSUE THREAD

**Issue by mrtinkz** [appbaseio/reactivesearch#1336]
**Affected Projects**

**Library Version:** x.y.z

**Describe the bug**

powered by appbase.io image is showing up on search page, next to paging to be precise. Included the screenshot.

<img width="967" alt="Screen Shot 2020-01-22 at 3 25 58 PM" src="https://user-images.githubusercontent.com/377147/72931830-91ab4f00-3d2c-11ea-897f-c01de39b84f4.png">

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jyash97** [comment]
Hey @mrtinkz 
If you are using a free plan of appbase.io than it is required to place the logo. Otherwise, you can hide it using CSS.
