### ISSUE TITLE
Using DataSearch with showVoiceSearch on SSR failing window is not defined

### ISSUE THREAD

**Issue by aleplusplus** [appbaseio/reactivesearch#1338]
**Affected Projects**
React

**Library Version:** 3.2.4

**Describe the bug**
Using DataSearch with showVoiceSearch on SSR failing window is not defined

**To Reproduce**

Using NextJS with DataSearch and the prop `showVoiceSearch=true`

**Expected behavior**

**Screenshots**

<img width="1305" alt="Screen Shot 2020-01-24 at 11 09 00 AM" src="https://user-images.githubusercontent.com/6319838/73083896-fc2dcd80-3e99-11ea-9f47-3d3e894f5ae3.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version Version 79.0.3945.117 (Official Build) (64-bit)

**Additional context**

**Comment by ShahAnuj2610** [comment]
@aleplusplus you need to tweak code a little bit. Here's a working example for you: https://codesandbox.io/s/elated-flower-rm2wo

You can do this using `Wrapper` component:
```
const Wrapper = props => {
  return <DataSearch {...props} />;
};

// class
state = { mount: false };
componentDidMount() {
  this.setState({ mount: true });
}

//render
{this.state.mount && <Wrapper {...components.datasearch} />}
```
