### ISSUE TITLE
Components don't get updated after setValue from selectedFilters

### ISSUE THREAD

**Issue by schmidtflo** [appbaseio/reactivesearch#1372]
**Affected Projects**
React

**Library Version:** 3.4.1

**Describe the bug**
When using setValue within the SelectedFilters-Component with `setValue(component, ['value1','value2'])`, the respective component receives the new state, but doesn't get updated. Strangly, clearing all Values of a component with `setValue(component, null)` (like in the Docs) works. I can see the new selected values in the component when using react dev tools, but the component doesn't trigger an update. I also get no error in the console.

**To Reproduce**
This is the render-function from the SelectedFilters, which is setting the new Value:

```
render={(props) => {
 const {selectedValues, setValue} = props;

 const removeSpecificFilter = (component, value) => {
   let componentFilters = selectedValues[component].value;
   componentFilters.splice(componentFilters.indexOf(value), 1);
   setValue(component, componentFilters);
 };

 let filters = [];

 for (let [component, values] of Object.entries(selectedValues)) {
   if(Array.isArray(values.value)) {
     values.value.forEach((entry) => {
       filters.push(
         <button
           key={component + entry}
           onClick={() => removeSpecificFilter(component, entry)}
         >
           {entry}
         </button>
       )
     })
   }
 }

 return filters;
}}
```

The component which doesn't get updated is a MultiList.

**Expected behavior**
When setting a new array of values, the filter component should trigger the regular update similar to when the user would uncheck an entry. 

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 80

**Comment by ShahAnuj2610** [comment]
@schmidtflo Can you share a reproducible code sandbox demo?
