### ISSUE TITLE
ReactiveList's `renderItem` called twice

### ISSUE THREAD

**Issue by tankchintan** [appbaseio/reactivesearch#1375]
I have noticed that the `renderItem` is being called twice for each actual result item being passed to the reactiveList, this seems a bug. 

Reproducing it pretty easy, I just put `console.log` in the renderItem & print out the id of the item being rendered, you will notice it right away, the duplicates. 

This happens regardless of any other sensors are attached to the reactivelist or not.

I used the demo from ReactiveList and just used `renderItem` instead of `render` and I put in the log. See codesandbox [here](https://codesandbox.io/s/gallant-sea-b3zmp).

I just noticed that the same happens when I put console.log in `render` as well.

**Comment by jyash97** [comment]
Hey @tankchintan, thanks for reporting the issue

This is a known issue. For now you can use `React.memo` or `shouldComponentUpdate`. 
Here is the sandbox link: https://codesandbox.io/s/inspiring-greider-8kb65

Ref Issue : https://github.com/appbaseio/reactivesearch/issues/1086

**Comment by ShahAnuj2610** [comment]
routing this issue to https://github.com/appbaseio/reactivesearch/issues/1086
