### ISSUE TITLE
Generated nested AND query on lists doesn't work for certain cases

### ISSUE THREAD

**Issue by carlopascual** [appbaseio/reactivesearch#1376]
**Affected Projects**
React (But probably all versions)

**Library Version:** x.y.z
9.2.6

**Describe the bug**
Given a structure like this:
```
{
  "brands": {
    "type": "nested",
    "properties": {
      "name": {
        "fields": {
          "raw": {
            "type": "keyword",
          },
          ...
        },
      },
      ...
    }
  }
}
```
with sample data:
```
{
  ...,
  "brands": [
    {"name": "X"},
    {"name": "Y"}
  ]
}
```

and a `MultiList` like this:
```
 <MultiList
  ...
  dataField="brands.name.raw"
  nestedField="brands"
  queryFormat="and"
/>
```
The filters return nothing if both X and Y are selected.

The query generated looks something like:
```
{
  "query": {
   "nested": {
     "path": "brands",
     "query": {
       "bool": {
         "must": [
           {
             "term": {
               "brands.name.raw": "X"
             }
           },
           {
             "term": {
               "brands.name.raw": "Y"
             }
           }
         ]
       }
     }
   }
  }
}
```
but this query doesn't work. 

My guess is that ElasticSearch is first fetching the items with brand "X" first and ignoring everything else in the `name` array so it can no longer find brand "Y". One solution is to invert the order of the queries such that:
```
{
  "query": {
    "bool": {
      "must": [
        {
          "nested": {
            "path": .brands",
            "query": {
              "term": {
                 "brands.name.raw": "X"
              }
            }
          }
        },
        {
          "nested": {
            "path": "brands",
            "query": {
              "term": {
                 "brands.name.raw": "Y"
              }
            }
          }
        }
      ]
    }
  }
}
```

**Comment by ShahAnuj2610** [comment]
@carlopascual Thanks for reporting. It would be great if you can share reproducible code sandbox example.

**Comment by carlopascual** [comment]
https://codesandbox.io/s/objective-currying-wt4w9?file=/src/App.js try this one. :) Clicking crime OR drama shows `El rey de la carretera`, but selecting both of them shows nothing
