### ISSUE TITLE
[Question] SearchProvider only returns results in the first page?

### ISSUE THREAD

**Issue by wenjzhu** [appbaseio/reactivesearch#1378]
First I want to express a lot of thanks to reactivesearch developers for making this:) 

My question is about `SearchProvider`. It seems it is working fine for only the first page results by default. How can I make it serialize all of the page results? 

I looked at the documentation and there is a place said `pagination` is one of the valid keys but I tried to use it as a prop but failed. Is there any examples or instructions about how to use it (or should I use it) properly? 

Any comments would be helpful. Thanks.

**Comment by bietkul** [comment]
@wenjzhu I'm guessing that you're talking about `StateProvider` component which can be used to access the current state of `reactivesearch` components. If `pagination` prop is set to `true` in `ReactiveList` then in `StateProvider` you'll only get the `hits` for the selected page.

**Comment by wenjzhu** [comment]
> @wenjzhu I'm guessing that you're talking about `StateProvider` component which can be used to access the current state of `reactivesearch` components. If `pagination` prop is set to `true` in `ReactiveList` then in `StateProvider` you'll only get the `hits` for the selected page.

Thanks for your reply, yes I used `pagination` for `ReactiveList` component. I tried to set it to false after seeing your comment, but it only let me see the "rendered" results(so had to scroll down many times to see the whole results)...I guess my question is, is it possible for us to get all the results by rendering for one time?

**Comment by ShahAnuj2610** [comment]
@wenjzhu it's possible. Set `pagination={false}` and `infiniteScroll={false}` and pass **size** prop as per your need (i.e. the number of results you want to see at one go). Here's a demo: https://codesandbox.io/s/elastic-williams-4i1hx?file=/src/index.js.
