### ISSUE TITLE
SSR not working for nested queries

### ISSUE THREAD

**Issue by carlopascual** [appbaseio/reactivesearch#1388]
**Affected Projects**
React

**Library Version:** 3.5.0

**Describe the bug**
Going to a URL that rehydrates a nested query with SSR doesn't work

**To Reproduce**
The easiest way to reproduce this is to run something based off of `/packages/web/examples/ssr/pages/reactivelist`:
```
import React, { Component } from "react";
import {
  ReactiveBase,
  SingleList,
  SelectedFilters,
  ReactiveList
} from "@appbaseio/reactivesearch";
import initReactivesearch from "@appbaseio/reactivesearch/lib/server";

const settings = {
  app: "algolia-movies",
  credentials: "HpM7YCrz4:17b7d153-c649-4088-a7aa-8679c72d770f"
};

const singleListProps = {
  componentId: "Genres",
  dataField: "genre_nested.genre.keyword",
  nestedField: "genre_nested",
  URLParams: true,
  size: 100
};

const reactiveListProps = {
  componentId: "SearchResult",
  dataField: "_score",
  react: { and: ["Genres"] },
  URLParams: true,
  className: "result-list-container",
  render: ({ data }) => (
    <div>
      {data.map(item => (
        <div key={item.objectID} style={{ border: "1px solid black" }}>
          <h3>{item.title}</h3>
          <h4>{item.genre}</h4>
        </div>
      ))}
    </div>
  )
};

export default class Main extends Component {
  static async getInitialProps({ query }) {
    return {
      store: await initReactivesearch(
        [
          {
            ...singleListProps,
            source: SingleList
          },
          {
            ...reactiveListProps,
            source: ReactiveList
          }
        ],
        query,
        settings
      )
    };
  }

  render() {
    return (
      <ReactiveBase {...settings} initialState={this.props.store}>
        <div className="row">
          <div className="col">
            <SingleList {...singleListProps} />
          </div>

          <div className="col">
            <ReactiveList {...reactiveListProps} />
          </div>
        </div>
      </ReactiveBase>
    );
  }
}
```

Select one of the filters and refresh. The page URL should have changed. Nothing loads and this error is thrown in the server:
```
Response {
  size: 0,
  timeout: 0,
  [Symbol(Body internals)]: {
    body: PassThrough {
      _readableState: [ReadableState],
      readable: false,
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: true,
      _transformState: [Object]
    },
    disturbed: true,
    error: null
  },
  [Symbol(Response internals)]: {
    url: 'https://scalr.api.appbase.io/algolia-movies/_msearch?',
    status: 400,
    statusText: 'Bad Request',
    headers: Headers { [Symbol(map)]: [Object: null prototype] }
  }
}
```

**Comment by ShahAnuj2610** [comment]
Right. The component crashes. Here's a reproducible source: https://codesandbox.io/s/async-haze-gtpnc?file=/pages/index.js

**Comment by carlopascual** [comment]
Awesome fix @ShahAnuj2610 for the nested queries! But I'm still having issues with the SSR, when it comes to more custom queries.
 
Here's a codesandbox of the SSR with a customQuery breaking:
https://codesandbox.io/s/broken-ssr-nested-example-r0ozf?file=/pages/index.js You can comment `getInitialProps` to get the sandbox working.

**Comment by ShahAnuj2610** [comment]
@carlopascual your `customQuery` and `defaultQuery` should not have `query` key included. Check this working csb example: https://codesandbox.io/s/broken-ssr-nested-example-9k64j?file=/pages/index.js

**Comment by carlopascual** [comment]
@ShahAnuj2610 You are right, it is working now. In my application though, there were some queries that wouldn't work without the `query` key, but I'll report that in a separate issue when I isolate what exactly it was. Thanks again!

**Comment by carlopascual** [comment]
@ShahAnuj2610 actually, I was mistaken. Even in your example: https://codesandbox.io/s/broken-ssr-nested-example-9k64j?file=/pages/index.js , `customQuery` without the `query` key is breaking the query.

Try running the example then refresh the sandbox browser. You'll see a failed `_msearch` query in the network tab with the reason: `Unknown key for a START_OBJECT in [nested].`

Here is the generated query:

```
{
  "query": {
    "bool": {
      "must": [
        {
          "bool": {
            "must": [
              {
                "nested": {
                  "path": "genre_nested",
                  "query": {
                    "term": {
                      "genre_nested.genre": "drama"
                    }
                  }
                }
              }
            ]
          }
        }
      ]
    }
  },
  "size": 10,
  "_source": {
    "includes": [
      "*"
    ],
    "excludes": []
  },
  "from": 0,
  "nested": {
    "path": "genre_nested",
    "query": {
      "term": {
        "genre_nested.genre": "drama"
      }
    }
  }
}
```
It looks like `nested` isn't being included in the main query.. Can you confirm for me if this is the behavior you are experiencing as well?
