### ISSUE TITLE
Warning(ReactiveSearch): The `analytics` prop has been marked as deprecated, please set the `recordAnalytics` property as `true` in `appbaseConfig` prop instead.

### ISSUE THREAD

**Issue by kud** [appbaseio/reactivesearch#1396]
**Affected Projects**
React

**Library Version:** "@appbaseio/reactivesearch": "3.7.0"

**Describe the bug**
I didn't specify any `analytics` attribute and I've got this message.

I wonder if `analytics` is not set by default.

**Comment by bietkul** [comment]
Fixed it here https://github.com/appbaseio/reactivesearch/commit/3b067065815e67b3201931e6ae830231677c265f

**Comment by kud** [comment]
Thank you!
