### ISSUE TITLE
Sort Not Working Properly After Navigation

### ISSUE THREAD

**Issue by devinsm** [appbaseio/reactivesearch#1397]
**Affected Projects**
React

**Library Version:** x.y.z
3.0.3

**Describe the bug**
The select box sometimes displays an option inconsistent with the current sort order of the results.

**To Reproduce**
1. Go to https://github.com/appbaseio/reactivesearch#web
1. Click on "demos/booksearch"
1. Select "Title A->Z" as the sort option
1. Use the browser's back button to go back to the contribution guide
1. Use the browser's forwards button to go back to the book search
1. "Title A->Z" will be shown as the selected sort option, but the books will be sorted by rating

**Expected behavior**

The selected sort option should always match the sort order of the results.

**Screenshots**

![reactive_sort_bug](https://user-images.githubusercontent.com/22419909/77810430-9c969e80-7051-11ea-8129-1d2890e937be.gif)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome, safari
 - Version: Chrome 80, Safari 13

**Comment by ShahAnuj2610** [comment]
Currently we do not store `sortOptions` in the URL. We only store page number in the URL. Otherwise, this would have been possible by passing `URLParams=true` in `ReactiveList` component. This would be a good enhancement to do.

For your ref: ![](https://i.imgur.com/4hL9PUp.png)

Read more about it over [here](https://docs.appbase.io/docs/reactivesearch/v3/result/reactivelist/#props).

**Comment by devinsm** [comment]
@ShahAnuj2610 Thanks for your response! I think however there's been a slight miscommunication. The issue is not that the sort option resets after navigation (that is the expected behavior). The issue is that although the order of results goes back to the default, the select box still displays the option the user last selected. So in the .gif above, the select box says that the items are sorted by title, when they are actually sorted by rating.

**Comment by ShahAnuj2610** [comment]
@devinsm Thanks! I got it.
