### ISSUE TITLE
Get error 504 timeout + Query too slow

### ISSUE THREAD

**Issue by cb29** [appbaseio/reactivesearch#1398]
Hello,

sometimes I get an error 504 (error in logs of Chrome/FF...) with my reactivesearch app. Some filters aren't displayed and/or an error is rendered for the results.
After reading several posts, we can see that the query to ES seems to be too slow (.../_msearch). 
With ReactiveSearch, can I resolve this problem with a specific parameter or anything ? (truncate query, query by parts (filters part + results part)...)

Thanks for your help.

I'm using ES 7 on a Google Cloud Plateform.

**Comment by siddharthlatest** [comment]
@cb29 The 504 error is related to your hosting service. This is not a ReactiveSearch issue. I recommend following the best practices for ES hosting. You can also choose to host with [appbase.io clusters](https://appbase.io/clusters) - where we can provide support on this.
