### ISSUE TITLE
MultiList frequently calls customQuery with undefined value and props.

### ISSUE THREAD

**Issue by gauthierm** [appbaseio/reactivesearch#1403]
**Affected Projects**
React

**Library Version:** x.y.z
```
  "@appbaseio/reactivecore": "^9.0.3",
  "@appbaseio/reactivesearch": "^3.2.4",
```

**Describe the bug**
`MultiList` frequently calls customQuery with undefined value and props.

**To Reproduce**
```jsx
<MultiList
  dataField="type"
  customQuery={(value, props) => {
    console.log(value, props);
    return { query: { terms: { [props.dataField]: value } } };
  }}
/>
```

**Expected behavior**
`customQuery` is called with `value` and `props` as defined in documentation.

**Additional context**
This is caused by the MultiList `componentDidUpdate` using isIdentical to compare the `customQuery` and `defaultQuery` props. The `isIdentical` helper function checks if the props are functions and if they are, it runs the functions with no arguments.

**Comment by gauthierm** [comment]
See https://github.com/appbaseio/reactivesearch/blob/next/packages/web/src/components/list/MultiList.js#L165

and https://github.com/appbaseio/reactivesearch/blob/next/packages/web/src/utils/index.js#L64-L65

**Comment by ShahAnuj2610** [comment]
Thanks for reporting. I noticed one more issue while looking into this, which we need to resolve. The props are coming as **undefined** in the `customQuery` (ideally this shouldn't be the case) due to which accessing `props.dataField` crashes the component. This may or may not apply to other components which applies `aggs` query.

CSB: https://codesandbox.io/s/stupefied-herschel-lcyge?file=/src/index.js

**Comment by gauthierm** [comment]
Yes, the reason they are coming as undefined is explained in the issue description. It should be easy to fix.

**Comment by gauthierm** [comment]
Proposed fix looks like it will work. This will cause customQuery and defaultQuery functions to be called frequently. Should the documentation be updated to let people know the functions should written to not be expensive?

**Comment by ShahAnuj2610** [comment]
> This will cause customQuery and defaultQuery functions to be called frequently

@gauthierm  I have also fixed this in the linked PR. Now it won't get called when we compare internally (e.g in componentDidUpdate).
