### ISSUE TITLE
Default sort option doesn't work in SSR.

### ISSUE THREAD

**Issue by divyadeep-MT** [appbaseio/reactivesearch#1411]
**Affected Projects**
React

**Library Version:** x.y.z
3.7.1

**Describe the bug**
`defaultSortOption` prop isn't taken into account when rendering result list on server side. Instead, the first option present in the sort-options list is taken to generate the ElasticSearch query. 

**To Reproduce**
1. Add sort options to the SSR example's `ReactiveList` props.
2. Set `defaultSortOption` as something other than the first sort option.

**Expected behavior**
The result list received as a response from server should be sorted according to the `defaultSortOption` provided. However, the selected option in the dropdown list of sort options is correct.

**Desktop (please complete the following information):**
 - OS: All
 - Browser All
 - Version All

**Additional context**

**Fix**
I'm attaching the fix I'm using for this issue.
```
// in node_modules/@appbaseio/reactivesearch/lib/components/result/ReactiveList.js

ReactiveList.generateQueryOptions = function (props) {
	// simulate default (includeFields and excludeFields) props to generate consistent query
	var options = (0, _helper.getQueryOptions)(_extends({ includeFields: ['*'], excludeFields: [] }, props));
	options.from = props.currentPage ? (props.currentPage - 1) * (props.size || 10) : 0;
	options.size = props.size || 10;

	// begin custom code
	if (props.sortOptions) {
		const sortOptionIndex = props.defaultSortOption ? props.sortOptions.findIndex(function (s) {
			return s.label === props.defaultSortOption;
		}) : 0;
	// end custom code

		var _ref10;
		console.log("props.defaultSortOptions", props.defaultSortOption);
		options.sort = [(_ref10 = {}, _ref10[props.sortOptions[sortOptionIndex].dataField] = { // originally 0 was present in place of sortOptionIndex
			order: props.sortOptions[sortOptionIndex].sortBy // originally 0 was present in place of sortOptionIndex
		}, _ref10)];
	} else if (props.sortBy) {
		var _ref11;

		options.sort = [(_ref11 = {}, _ref11[props.dataField] = {
			order: props.sortBy
		}, _ref11)];
	}

	return options;
};
```

**Comment by ShahAnuj2610** [comment]
@divyadeep-MT I'm not able to reproduce it. This is my `ReactiveList` config for `sortOptions`:

```
		sortOptions: [
			{
				label: 'Bed Type',
				dataField: 'bed_type',
				sortBy: 'asc',
			},
			{
				label: 'Bedrooms',
				dataField: 'bedrooms',
				sortBy: 'asc',
			},
		],
		defaultSortOption: 'Bedrooms',
```
and it's applying `Bedrooms` sort by default.

Check this working SSR csb example for more info: https://codesandbox.io/s/bold-sara-mjhb3?file=/pages/index.js

**Comment by divyadeep-MT** [comment]
Hi @ShahAnuj2610, you closed the issue without even letting me reply :/.
The issue is visible even in the codesandbox URL you shared
![Screenshot from 2020-04-17 12-15-16](https://user-images.githubusercontent.com/52448286/79540138-3ed00200-80a5-11ea-92af-3ce978dd80d7.png)
Reload the page and take a look at the response for the request for the network call corresponding to the page. You'll be able to see that results are corresponding to sort option "Bed Type", and not "Bed Room". 

Another way to identify the issue is apply network throttling. On the initial load, results corresponding to "Bed type" sort options are shown that change to results corresponding to "Bedrooms" on client side, which beats the point of SSR. 

Please take another look.

Thanks.

**Comment by ShahAnuj2610** [comment]
OK, I got your point. The **defaultSortOption** should get applied right on mount regardless of query applied or not.

**Comment by divyadeep-MT** [comment]
Exactly. You got it :smiley:
