### ISSUE TITLE
Add ViewSwitcher component for v2

### ISSUE THREAD

**Issue by divyanshu013** [appbaseio/reactivesearch#142]
**I'm submitting a ...**

- [ ] bug report
- [x] feature request
- [ ] other

**Current behavior:**

We need a view switcher implementation (as we had in v1) or some similar solution that allows easy switching of result views.

**Expected / new behavior:**

Providees easy view switching capabilities for components

**Reactivesearch version:** x.y.z

v2 alpha release

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

NA

**Anything else:**

NA

**Comment by metagrover** [comment]
ViewSwitcher won't be supported. A generic react toggle component can be implemented to achieve this functionality.
