### ISSUE TITLE
Demo apps for 2.0

### ISSUE THREAD

**Issue by metagrover** [appbaseio/reactivesearch#143]
### To review:

- [x] HackerNews
- [x] GitXplore
- [x] Ecommerce
- [x] Product Hunt
- [x] GoodBooks
- [x] Airbnb

**Comment by divyanshu013** [comment]
UI/UX changes

- [ ] Ecommerce app positioning of search box
- [ ] GitXplore app change icon position, remove `autosuggest`, improve search box styles
- [ ] ProductHunt app positioning of header items

**Comment by siddharthlatest** [comment]
**Concept Apps:**

- [ ] Secure app: Use an Elasticsearch index via a middleware proxy which has dummy authorization rules to showcase how to secure an app.
- [ ] An app that uses react-router and OAuth to show to integrate with the rest of the frontend ecosystem.

**Comment by siddharthlatest** [comment]
@dhruvdutt We can also upgrade the old TodoMVC app now that we have streaming support. This would also show an example that uses react-router, and we may be able to clear all the TodoMVC tests given the new `innerClass` prop support.
