### ISSUE TITLE
Reactivesearch 2.0 website

### ISSUE THREAD

**Issue by metagrover** [appbaseio/reactivesearch#144]

**Comment by siddharthlatest** [comment]
Current improvements:

- [ ] Optimizing content for mobile responsive mode. For instance, here: the buttons can be in the same row. We can show the Github link in the navbar. Spacing between sections can be normalized and reduced.  
![](https://i.imgur.com/gvWbouM.png)
- [ ] Cards should highlight the link on hover (In the Up to 10x Savings section)
- [ ] Testimonials: We can accommodate two of them
- [ ] Adding labels in the "comparing codes" section.
