### ISSUE TITLE
DataSearch one char keywords search second time don't show any suggestion

### ISSUE THREAD

**Issue by nomedia** [appbaseio/reactivesearch#1456]
**Affected Projects**
 React 

**Library Version: 3.0.0-rc.26

**Describe the bug**

For example  when I enter   2  it will show suggestion, then I delete 2 and type 2  again  it don't show any suggestion 

the document demo also have this problem

https://codesandbox.io/s/github/appbaseio/reactivesearch/tree/next/packages/web/examples/DataSearch?from-embed=&file=/src/index.js

**Comment by bietkul** [comment]
This issue has already been fixed in the latest version.
