### ISSUE TITLE
Unable to install the dependencies in WSL2 - Ubuntu

### ISSUE THREAD

**Issue by jrishabh55** [appbaseio/reactivesearch#1458]
**Affected Projects**
Reactive Search

**Library Version:** master branch

**Describe the bug**
I'm unable to install the project on my system

**To Reproduce**
1. clone the repo
2.
 ```
git submodule init
git submodule sync
git submodule update --remote
```
3. yarn

**Expected behavior**
yarn install should work fine

**Screenshots**

![image](https://user-images.githubusercontent.com/18290665/81675617-b9096180-946c-11ea-91a5-f676ba8d5821.png)

**Desktop (please complete the following information):**
![image](https://user-images.githubusercontent.com/18290665/81675327-47c9ae80-946c-11ea-8417-c91bd765c392.png)

**Comment by jyash97** [comment]
Hey, @jrishabh55  Thanks for filing the issue.
Can you try this with node v10 or node v13?

**Comment by jrishabh55** [comment]
I was using node v12.16.1 earlier 

i noticed that there was a problem with dependencies, g++ was not installed on my system (good to have something in docs), i installed it and few new errors popped up. They look like something related to some version mismatch 
![image](https://user-images.githubusercontent.com/18290665/81676969-25389500-946e-11ea-95c6-8bcf64909dbe.png)

It worked for node v10 bus same problem with node v13

**Comment by acosta-edgar** [comment]
I am seeing the same errors on https://github.com/appbaseio/reactivesearch/issues/1458#issuecomment-627273434 on MacOS with node 14.30

Is there a node version requirement?
Thanks!

**Comment by jrishabh55** [comment]
@acosta-edgar use node 10 for now till we have a fix here.
