### ISSUE TITLE
ReactiveComponent not clearing the url param when removing Selected Filter

### ISSUE THREAD

**Issue by DustinKLo** [appbaseio/reactivesearch#1460]
**Affected Projects**
React

**Library Version:** x.y.z
3.8.5

**Describe the bug**
When the facet is cleared, the url param of the component isnt removed,
however clicking `clear all` removes it 

**To Reproduce**
https://codesandbox.io/s/reactivecomponent-7mpr5?file=/src/index.js

**Expected behavior**
the url param should be removed when clearing

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome

working code sandbox: https://codesandbox.io/s/reactivecomponent-7mpr5?file=/src/index.js

**Comment by bietkul** [comment]
@jyash97 Can you check on this?

**Comment by jyash97** [comment]
Hey @DustinKLo 

Thanks for reporting the issue. I can see the value is reset but the URLParams are not removed. I will check on this today and will create a fix for this.

**Comment by bietkul** [comment]
@jyash97 Any update on this?

**Comment by sa-aj** [comment]
I am also facing this issue can you please help @bietkul did you find any solution ?

**Comment by DustinKLo** [comment]
@sa-aj i resorted to using the latest version of the library which didn't have this bug
```
"@appbaseio/reactivesearch": "3.2.4",
```

its not a true fix but hopefully this helps

**Comment by DustinKLo** [comment]
@bietkul @jyash97 is there any update on this?
If not i can give it a shot if you can point me to where to look regarding the logic that handles the `URLParams` value

**Comment by DustinKLo** [comment]
i was able to "somewhat" fix the issue, the url query param now clears when clearing the (`ReactiveComponent`) filter
https://github.com/appbaseio/reactivesearch/compare/next...DustinKLo:fix_reactivecomponent_url

but when the page loads with the query param already set, the filter is not used
`ReactiveComponent` also doesn't work when using page forward and backwards on the browser

can someone point me where to look to make a proper fix to this issue? thanks 👍

**Comment by sbeus** [comment]
This appears to still be an issue with no real work-around.  Can it be re-opened for investigation?

**Comment by paulo-h-cunha** [comment]
Facing the same issue. 
Please re-open!
