### ISSUE TITLE
Bug parsing URLParams in ReactiveBase

### ISSUE THREAD

**Issue by pcvonz** [appbaseio/reactivesearch#1475]
**Affected Projects**

React
**Library Version:** x.y.z

Working off this commit: e2eacff2275c201a5becea71a58996313c2653df
**Describe the bug**

In `ReactiveBase` in this loop: https://github.com/appbaseio/reactivesearch/blob/e2eacff2275c201a5becea71a58996313c2653df/packages/web/src/components/basic/ReactiveBase.js#L120

If `parsedParams.value` is undefined when parsing URLParams, the `selectedValue.value` is set to the parsed params.
https://github.com/appbaseio/reactivesearch/blob/e2eacff2275c201a5becea71a58996313c2653df/packages/web/src/components/basic/ReactiveBase.js#L127
 If parsed params is an Object (which is the case for the CategorySearch component) then this line: https://github.com/appbaseio/reactivesearch/blob/e2eacff2275c201a5becea71a58996313c2653df/packages/web/src/components/search/CategorySearch.js#L158

Will cause ReactiveSearch to throw an error.
**To Reproduce**

1. Instantiate a CategorySearch component with URLParams set to true
2. Perform a search on a category 
3. Remove `value` from the `Search` object in the URL bar.
4. Reload

**Expected behavior**

Only set `selectedValue` in reactive base if `value` is a string. 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

I've run into this bug a few times in my app. Sometimes when using the `back` and `forward` buttons. 

Navigating with back button:

1. `somesearchapp.whatever/?`
2. `somesearchapp.whatever/?Search=%7B%22category%22%3A%22%2FRoot%20Catalog%2FDefault%20Category%2FTabletop%22%2C%22value%22%3A%22cup%22%7D`

![bug](https://user-images.githubusercontent.com/6378569/82688739-37ed5f80-9c0e-11ea-8276-0fd7abff321d.gif)

Error being thrown:
`TypeError: "this.state.currentValue.trim is not a function"`

**Comment by pcvonz** [comment]
I think the issue is actually related to: #1339

**Comment by sachh185** [comment]
@pcvonz I faced a similar issue. Was this fixed? Or did you find any workaround?
