### ISSUE TITLE
Use props render in MultilList, SelectedFilter cannot clear item

### ISSUE THREAD

**Issue by longnk1301-vmodev** [appbaseio/reactivesearch#1490]
**
I have issue when use render for MultiList, so then I cannot clear item selected on SelectedFilter, please give me any solution, thanks!!
**

**Comment by jyash97** [comment]
Hey @longnk1301-vmodev can you please follow the issue template and create a sample CodeSandbox Link which shows the issue?

**Comment by acosta-edgar** [comment]
Hey @longnk1301-vmodev , could your report be a duplicate of #1512 ?

**Comment by bietkul** [comment]
@longnk1301-vmodev Track it here #1512
