### ISSUE TITLE
Limit suggestions height in DataSearch and CategorySearch

### ISSUE THREAD

**Issue by divyanshu013** [appbaseio/reactivesearch#150]
**I'm submitting a ...**

- [ ] bug report
- [x] feature request
- [ ] other

**Expected / new behavior:**

Suggestions should have a max line limit

**Reactivesearch version:** x.y.z

latest

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

All

**Anything else:**

Possible implementation https://codepen.io/martinwolf/pen/qlFdp

**Comment by siddharthlatest** [comment]
Currently, suggestions UI isn't bearable on full-text datasets - try technews demo.
