### ISSUE TITLE
Initial filter query inefficiency with `_msearch`

### ISSUE THREAD

**Issue by mitchgillin** [appbaseio/reactivesearch#1502]
**Affected Projects**
React

**Library Version:** x.y.z
3.11.4

**Describe the bug**
Initial load of app is causing a `_msearch` to fire for each filter. Having large doc sizes in ES and having multiple filters in place is causing crashes to my infra. 

**To Reproduce**
Have ~15 filters in place and hit an ES node with large files.

**Expected behavior**
ReactiveSearch should batch all queries on first render to perform an efficient `_msearch`

**Desktop (please complete the following information):**
 - OS: MacOS Catalana 10.15.5
 - Browser: Brave/Chrome
 - Version: 1.11.69 Chromium: 83.0.4103.106 (Official Build) beta (64-bit)

**Comment by bietkul** [comment]
@mitchgillin We already have that issue in our top priority. For now you can try the following things:
- Use collapsible UI for filters, only render when required or interacted by user.
- Use small sizes for filter queries

**Comment by janhoy** [comment]
Would it not be more efficient if ReactiveSearch sent *one* search request to ES, compiled from the needs of all components, and then each component subscribes to the result and pulls out "their" data? Or do you have a use case where you'll update a filter widget without updating the main search result or the opposite?

**Comment by siddharthlatest** [comment]
@janhoy This is how ReactiveSearch works, it generates a combined query (via `msearch`, multi search) for all the components that would be affected by a given interaction. Except during the initialization phase, where ReactiveSearch fires independent queries for each component instead of combining them together. The above issue is specific to this scenario - there is room for improvement here.

**Comment by bietkul** [comment]
The `initialQueriesSyncTime` prop introduced in `v3.24.0` can be used to merge the filters' queries at initial load.

> Note: This prop only works with `enableAppbase` prop.
