### ISSUE TITLE
ReactiveList loading does not update with custom query defined.

### ISSUE THREAD

**Issue by Sarthak049** [appbaseio/reactivesearch#1506]
**Affected Projects**
ReactiveSearch-VueJS

**Library Version:** 1.5.2

**Describe the bug**
When checking the 'loading' flag in reactive list's render slot the 'loading' **true only when default query is running on the page load**. It is always false when the customQuery is defined for subsequent queries.

**To Reproduce**
- In a sample project define a customQuery that takes long time to execute.
- Print the value of 'loading' in the template.

**Expected behavior**
It is expected that the value of loading is true while the custom query result is returned. And is only false once the query has returned the result even if no result or error.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18
 - Browser: chrome, firefox
 - Version: latest

**Comment by bietkul** [comment]
@Sarthak049 Can you share the code sandbox link replicating the issue?
I'm still not clear on your use-case. Loading property in `ReactiveList` will change when it fetches the new results.

**Comment by Sarthak049** [comment]
@bietkul sure I will add a code sandbox shortly. 
The usecase here is to display a loader till the ReactiveList updates the results. But what happens is as soon as I type my query in the DataSearch bar, the loading prop is set true and in the next second (before results are rendered in ReactiveList) it is set as False again and the results are not yet rendered in the ReactiveList. I will share the code sandbox to demonstrate the same. Not sure if this is happening due to wrong event being fired. Another thing I noticed is that the custom query function is called twice for every query (Tried printing to console when function is triggered).
