### ISSUE TITLE
Date Range component

### ISSUE THREAD

**Issue by metagrover** [appbaseio/reactivesearch#151]
## Bug Report

**Current behavior:**
- **Incorrect range selection**

If you have an end-date selected (screenshot - `2018-02-14`), and clear the start-date, you will be able to select any date in the calendar as the start-date, even the dates after `2018-02-14`.

![screen shot 2017-12-27 at 8 51 31 pm](https://user-images.githubusercontent.com/9116042/34385314-c32bdf10-eb47-11e7-8e32-9b552833bb54.png)

Also, if I have an end date selected, and I'm selecting the start date, the calendar should grey-out irrelevant dates (i.e. the dates after the end date)

- **UX issues**

    * Currently, the component does not tell you in any way which date are you selecting at any given point. (i.e. you won't know if you're selecting an end-date or a start-date)
    * The range selection isn't continuous. Calendar closes after selecting the start-date and you will have to click the end-date input field to open the calendar again to select the end date.

- **Support more Customization**

Allow users to change the middle `-`'s markup which connects two input fields together. Possible usecase: You may want to change the `-` to an arrow (`->`) or `to`.

**Expected / new behavior:**

- To improve the UX, we can highlight the range while selecting and keep the calendar open until the user is done selecting both the dates. 

**Reactivesearch version:**  latest

**Comment by siddharthlatest** [comment]
In the possible customizations support, it should be possible to change the entire top portion including the input fields.

An example from Airbnb.

![screen shot 2017-12-28 at 12 13 45 am](https://user-images.githubusercontent.com/630042/34390162-f80021a8-eb63-11e7-887b-e37bac5be26e.png)

**Comment by metagrover** [comment]
**UX Issues:**

When the date range is already selected, and now you modify the start date such that (end date - start date > 1 month duration), the calendar auto-focuses on the end date. 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/9116042/41906621-f554bc94-795b-11e8-8399-60d6a1856248.gif)

**Correct behavior:** It should focus on the start date if you are changing the start date. It should focus on the end date if you are changing the end date.
