### ISSUE TITLE
RangeSlider URLParams=true modifies the window.location.href even if the user has not interacted with it

### ISSUE THREAD

**Issue by PeterCiuffetti** [appbaseio/reactivesearch#1511]
**Affected Projects**
React

**Library Version:**
3.11.8

**Describe the bug**
When I set URLParam=true to either a RangeSlider or a DynamicRangeSlider, the URL in the browser location is modified even if the user has not adjusted the range.
For example, I have a date field in my index called release-date (its an integer year).  It has values of 1999 through 2020.  I have a RangeSlider to allow the user to select a subset of this range.

```
      <RangeSlider
        componentId="date"
        filterLabel="Date"
        dataField="release-date"
        className="date-filter"
        range={{
          start: 1999,
          end: 2020,
        }}
        rangeLabels={{
          start: '1999',
          end: '2020',
        }}
        showHistogram={true}
        stepValue={1}
        interval={1}
        showFilter={true}
        URLParams={true}
      />
```
With URLParam set to true, my browser location will have a param ?date=[1999%2C2020] even though the user has not reacted with this filter.

**To Reproduce**
https://codesandbox.io/s/reactivecomponent-0v14d
You only need to set URLParam={true} to any RangeSlider or DynamicRangeSlider and the issue will occur.

**Expected behavior**
Other filter components, such as SingleList and MultiList do not exhibit this behavior.  The user has to modify the value of the filter before the URLParam is added to the URL in the browser location.  Note that the 'SelectedFilters' component does not render anything for the RangeSlider until the range slider has been modified.  My expectation would be that the URLParam would also only appear when the 'SelectedFilters' rendered a clear box for the modified filter.

**Screenshots**
![image](https://user-images.githubusercontent.com/1168204/88101158-992ca300-cb6b-11ea-8e32-72d6b0ae5a63.png)

**Desktop (please complete the following information):**
 - OS: MacOS X High Sierra
 - Browser chrome, and others
 - Version 83

**Comment by sebastienlabine** [comment]
This is also breaking the back button, you can't go back. When you go back, the params are removed from the pages and then added back

**Comment by scotthooker** [comment]
+1

**Comment by scotthooker** [comment]
I think this is still an issue and can't work out where to look in the code to solve it.
