### ISSUE TITLE
Multilist - No results found when react router changes

### ISSUE THREAD

**Issue by jrishabh55** [appbaseio/reactivesearch#1513]
**Affected Projects**
React

**Library Version:**
Latest stable version 3.11.8

**Describe the bug**
The Multilist (Probably others, haven't tried), resets the data 

**To Reproduce**
https://codesandbox.io/s/red-glade-0xehd?file=/src/index.js

**Expected behavior**
The data should either stay in the list or reload again, Instead of being stuck at no results.

**Comment by bietkul** [comment]
<b>The solution is to use unique component IDs.</b>

I can explain that why is it happening.
- RouteA renders `<ListComponent>` with same `componentID`
- RouteB renders `<ListComponent>` with same `componentID`

When you change to routeB from routeA then it'll unmount the `RouteA`.
Sequence of events =>
Constructor gets called for `routeB` => Where do we register a component with `componentID`
ComponentWillUnmount gets called for `routeB` => It'll un-register the component with same `componentID`

Now we don't have the `componentID` in redux store so you won't see the results.
I don't have a proper solution for it but open to suggestions.
