### ISSUE TITLE
Bug: cannot resolve '../../../../reactivecore/src/utils/helper' in search components

### ISSUE THREAD

**Issue by ghost** [appbaseio/reactivesearch#1523]
**Affected Projects**
React

**Library Version:** x.y.z
3.12.0

**Describe the bug**
Missing modules

**To Reproduce**
https://codesandbox.io/s/github/appbaseio/reactivesearch/tree/next/packages/web/examples/DataSearch?from-embed=&file=/package.json

**Comment by bietkul** [comment]
@george-dotdev Thanks for reporting it, fixed it here https://github.com/appbaseio/reactivesearch/commit/1f2838ce3cf414352627b3d051f8eaff5862290d
