### ISSUE TITLE
URLParams not applied consistently

### ISSUE THREAD

**Issue by vijaygenius123** [appbaseio/reactivesearch#1537]
**Affected Projects**

React 
**Library Version:** x.y.z

3.11.6

**Describe the bug**

URLParams When set to true are not being applied consistently. 
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jyash97** [comment]
Hey @vijaygenius123  thanks for reporting the issue.

Can you provide a Codesandbox link with all the steps on reproducing the bug?

**Comment by vijaygenius123** [comment]
Sure, Am Working On Creating An Example On Codesandbox. Will Update The Details Once Done

**Comment by vijaygenius123** [comment]
Unable To Recreate On Appbase Environment.
