### ISSUE TITLE
Unable to use reactive-list using cdn

### ISSUE THREAD

**Issue by CryptoZorro** [appbaseio/reactivesearch#1542]
I followed the quickstart from your docs (https://docs.appbase.io/docs/reactivesearch/vue/overview/QuickStart/) to the word, but used the cdn instead of npm (and changed props to kebab-casing in my dom template)... and reactive-list doesn't seem to work. When I commented-out reactive-list, the other components multi-list & single-range seem to work! 

Sample here - https://jsfiddle.net/akayy/m3xapf58/

I'm on a non-node env and would appreciate some clarity if I can use reactivesearch when using the cdn without any limitations? 

Thanks!

**Comment by CryptoZorro** [comment]
Any luck with looking into this issue? Wondering if this is still an active components library?

**Comment by bietkul** [comment]
Hey @CryptoZorro, there were some issues with `html` content in `renderItem` slot that is why it wasn't working.
Here is an example, with latest version https://jsfiddle.net/ucaypej6/6/

**Comment by CryptoZorro** [comment]
Thanks for reverting on this - You may want to apply the same fix in your docs as well - https://docs.appbase.io/docs/reactivesearch/vue/overview/QuickStart/#step-4-adding-filters-and-result-components
