### ISSUE TITLE
List components don't react to map search

### ISSUE THREAD

**Issue by rbeers** [appbaseio/reactivesearch#1548]
**Affected Projects**
React

**Library Version:** 
"@appbaseio/reactivemaps": "^3.0.0-beta.11"
"@appbaseio/reactivesearch": "^3.12.5"

**Describe the bug**
When you use the search as move feature in a reactive openstreet map, other components don't react to that component id.  The map reacts to other list components fine but not the other way around.

**To Reproduce**
1. Run the basic map example
2. Set `searchAsMove` and `showSearchAsMove` to true.
3. Set the react prop on the places list to react to the map component
4. Drag the map around and the list doesn't change.  The markers change but the list doesn't.

**Expected behavior**
The list should update based on the bounding box of the map search.

**Comment by kmalay** [comment]
I'm also trying to get `List` components to react to bounding box queries in the map component.  Is this possible?

**Comment by bietkul** [comment]
@rbeers Can you please share a codesandbox link?

**Comment by rbeers** [comment]
@bietkul Here is a codesandbox example: https://codesandbox.io/s/priceless-germain-p0q2e
