### ISSUE TITLE
Only display the result selected from Data-Search

### ISSUE THREAD

**Issue by elise-lcdb** [appbaseio/reactivesearch#1549]
Hi! This really isn't an issue, more a question on how I could properly implement something.
I'm trying to create this vue app, where when the user first shows up to the page, they see absolutely nothing. However it is when they search and click on the item that they see the information only relating to that one item. Just the first result, no pagination.

So far what I have tried doing is having the results list size set to 1, and hid the pagination with css. Is there a better way to do this? To only show results in the result-list when the value of the data-search is not empty?

Thanks very much in advance!

By any chance, is there a discord?

**Comment by bietkul** [comment]
You can use the `customQuey`  prop to override the `DataSearch` query.
For example,
```jsx
<DataSearch
  customQuery={(value) => ({ query: { term: { YOUR_FIELD: value }}})}
/>
```
