### ISSUE TITLE
componentId prop shouldn't be required for result components

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivesearch#155]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other

**Current behavior:**

`componentId` is a required prop for Result components, i.e. in ResultCard, ResultList and ReactiveList.

**Screenshots:**
![screen shot 2017-12-29 at 4 10 22 am](https://user-images.githubusercontent.com/630042/34424997-193cc6e2-ec4e-11e7-98ed-903cee6635f6.png)

**Expected / new behavior:**

`componentId` shouldn't be a required prop in result components by default. If you are using `selectedFilters` or `URLParams`, perhaps a warning should show up that a `filterLabel` prop is required.

**Comment by metagrover** [comment]
Can you elaborate on the benefits it will provide if we make it an optional prop?

It is possible to make it an optional prop, but that comes with the baggage of auto-generating unique ids for the result components. Also, having this as an optional prop in the result components and a required prop in the other component just make things inconsistent, and it will make the url params and request-preference-logs a bit ugly IMO.
