### ISSUE TITLE
Remove all styling?

### ISSUE THREAD

**Issue by royduin** [appbaseio/reactivesearch#1553]
Is it possible to remove all styling and style all elements with my own classes? So remove the injected styles from emotion completely.

**Comment by bietkul** [comment]
@royduin Removal is not possible however you can customize ReactiveSearch components in the following ways
- You can define your class at the component level to override the default style.
- Most of the components support `render` and `renderItem` methods that allow you to use your own UI elements.
- `ReactiveComponent` can be used to integrate any UI component to Elasticsearch.
