### ISSUE TITLE
vue: Selected Filters component not visible

### ISSUE THREAD

**Issue by royduin** [appbaseio/reactivesearch#1578]
**Affected Projects**
Vue

**Library Version:** 
v1.7.11-vue

**Describe the bug**
The component doesn't show up at all. I though it maybe had something to do with #1501 as that component didn't show up either, but it doesn't seem te be related. Maybe also an easy fix @bietkul?

**Comment by bietkul** [comment]
@royduin Filters are working fine in latest version https://codesandbox.io/s/staging-dawn-ckyge?file=/src/App.vue

**Comment by royduin** [comment]
Whoeps, it was a problem at my side. Sorry!
