### ISSUE TITLE
Bug: Only exact matches will be found.

### ISSUE THREAD

**Issue by simkea** [appbaseio/reactivesearch#1591]
Hello,

My setup: ReactApp
React: 17.0.1
reactivesearch: 3.14.0
elasticsearch: 6.8.4

https://github.com/appbaseio/reactivesearch/blob/121cc1595d735f066f028a54660eece61256bde4/packages/web/src/components/search/DataSearch.js#L329

I compared the problem with version 2.16.1 and here the search works.
I noticed that in version 2.16.1 the type "phrase_prefix" is used.

Why was this type changed from "phrase_prefix" to "phrase"?

br
Henry

**Comment by simkea** [comment]
I have now rolled back to version 3.4.1, because here the type "phrase_prefix" is set and thus the search also works correctly.

I think something is wrong here.
Or do I need to migrate the ElasticSearch server to 7.x?

**Comment by siddharthlatest** [comment]
@simkea Can you explain the use-case where phrase_prefix results in an incorrect match? Can you also define correct / incorrect? A Codesandbox demo would be super useful for us to tell more here.

The reasoning for using phrase_prefix v/s phrase is that the former should cover more cases (should be a superset in most cases) for matching v/s the latter. A phrase_prefix query should still return the exact match result that a phrase query would return.

**Comment by simkea** [comment]
I can't tell what it is, but the search result is wrong with "phrase".

**reactivesearch: 3.4.1**
Request:
`{"preference":"result"}
{"query":{"bool":{"must":[{"bool":{"must":[{"bool":{"should":[{"multi_match":{"query":"schorr","fields":["givenname^2","surname^1","department","directDial","name","extensionattribute1","title","facsimiletelephonenumber"],"type":"cross_fields","operator":"and"}},{"multi_match":{"query":"schorr","fields":["givenname^2","surname^1","department","directDial","name","extensionattribute1","title","facsimiletelephonenumber"],"type":"phrase_prefix","operator":"and"}}],"minimum_should_match":"1"}},{"match_all":{}}]}}]}},"size":9,"_source":{"includes":["*"],"excludes":[]},"from":0,"sort":[{"surname.keyword":{"order":"asc"}}]}`

Response:
`{"responses":[{"took":1,"timed_out":false,"_shards":{"total":5,"successful":5,"skipped":0,"failed":0},"hits":{"total":1,"max_score":null,"hits":[{"_index":"dev","_type":"doc","_id":"","_score":null,"_source":{"telephonenumber":"","mail":"","title":null,"givenname":"Henry","surname":"Schorradt","postalcode":" ","physicaldeliveryofficename":" ","company":"","streetaddress":"","sn":"Schorradt","department":"11","facsimiletelephonenumber":null,"mobile":null,"extensionattribute3":null,"extensionattribute2":null,"objtype":"user","extensionattribute1":"","l":"","samaccountname":"","userprincipalname":"","directDial":"","displayname":"Schorradt, Henry","name":"","distinguishedname":"","fullFD":"","personalTitle":null},"sort":["Schorradt"]}]},"status":200}]}`

**reactivesearch 3.14.0**
Request:
`{"preference":"result"}
{"query":{"bool":{"must":[{"bool":{"must":[{"bool":{"should":[{"multi_match":{"query":"schorr","fields":["givenname^2","surname^1","department","directDial","name","extensionattribute1","title","facsimiletelephonenumber"],"type":"cross_fields","operator":"and"}},{"multi_match":{"query":"schorr","fields":["givenname^2","surname^1","department","directDial","name","extensionattribute1","title","facsimiletelephonenumber"],"type":"phrase","operator":"and"}}],"minimum_should_match":"1"}},{"match_all":{}}]}}]}},"size":9,"_source":{"includes":["*"],"excludes":[]},"from":0,"sort":[{"surname.keyword":{"order":"asc"}}]}`

Response:
{"responses":[{"took":2,"timed_out":false,"_shards":{"total":5,"successful":5,"skipped":0,"failed":0},"hits":{"total":0,"max_score":null,"hits":[]},"status":200}]}

![image](https://user-images.githubusercontent.com/612913/105319624-6e2c1600-5bc5-11eb-8aa7-cd17dac3739e.png)

Here is my code of the component:
`                        <DataSearch
                            componentId="Suche"
                            title="Suche"
                            dataField={[
                                "givenname",
                                "surname",
                                "department",
                                "directDial",
                                "name",
                                "extensionattribute1",
                                "title",
                                "facsimiletelephonenumber"
                            ]}
                            placeholder="Name, Telefonnummer..."
                            URLParams={true}
                            fieldWeights={[2, 1]}
                            queryFormat="and"
                            showIcon={false}
                            showClear={true}
                            showFilter={false}
                            onValueChange={value => this.setState({searchValue: value})}
                        />`

And the listing:
`                        <ReactiveList
                            componentId="result"
                            dataField="surname.keyword"
                            from={0}
                            size={9}
                            showResultStats={false}
                            sortBy="asc"
                            loader="Whoopsi, da ist wohl etwas schief gelaufen ... 🥔"
                            pagination={true}
                            style={{
                                padding: "10px"
                            }}
                            react={{
                                and: ["Suche", "orgs"],
                                or: ["dept"]
                            }}
                            renderItem={this.renderer}
                            defaultQuery={()=> {
                                if(this.state.searchValue.length > 0){
                                    return {
                                        query: {
                                            match_all: {}
                                        }
                                    }
                                } else {
                                    return {
                                        query: {
                                            match_none: {}
                                        }
                                    }
                                }
                            }}
                        />`

**Comment by siddharthlatest** [comment]
@simkea Oh, I see that we changed from phrase_prefix to a phrase. v3.4.1 creates a `phrase_prefix` but the latest release creates a `phrase` query. This looks like a bug from our end, we will look at this and fix. Thanks for bringing this to attention.

**Comment by simkea** [comment]
Thx! 
If it's not a bug on your end, I just want to understand why the search result changed. And if maybe a different configuration of ElasticSearch is needed for that.
