### ISSUE TITLE
MultiList, showLoadMore={true} causes setState error

### ISSUE THREAD

**Issue by rachaeldawn** [appbaseio/reactivesearch#1608]
**Affected Projects**
React

**Library Version:** x.y.z
3.14.0

**Describe the bug**
When using `MultiList`, setting the `showLoadMore` to true causes the `can't call setState on a component that is not yet mounted` error. See screenshots.

**To Reproduce**

On a working repo with a MultiList, add showLoadMore={true}

**Expected behavior**
I just works without throwing errors because `setState` is not called from the constructor

**Screenshots**
![Screenshot](https://i.imgur.com/JSEXlWa.png)

**Desktop (please complete the following information):**
 - OS: Linux (Kubuntu)
 - Browser: Chrome
 - Version: 88.0.4324.150 (Official Build) (64-bit)

**Additional context**
I went poking around, and the flow I can see that is causing the problem is this:

The constructor calls [updateQueryProps](https://github.com/appbaseio/reactivesearch/blob/next/packages/web/src/components/list/MultiList.js?ts=2#L76), which then calls [updateQueryOptions](https://github.com/appbaseio/reactivesearch/blob/next/packages/web/src/components/list/MultiList.js?ts=2#L392). Inside, [checks the props for showLoadMore](https://github.com/appbaseio/reactivesearch/blob/next/packages/web/src/components/list/MultiList.js?ts=2#L394), then [calls setState](https://github.com/appbaseio/reactivesearch/blob/next/packages/web/src/components/list/MultiList.js?ts=2#L395) indirectly from the constructor and only happens when `showLoadMore=true`.

Should be a pretty straightforward fix. I have [created a PR](https://github.com/appbaseio/reactivesearch/pull/1607) already.

**Comment by bietkul** [comment]
PR is merged and a new version is out.
