### ISSUE TITLE
All filters render title even if not take any value data

### ISSUE THREAD

**Issue by erenkucuker** [appbaseio/reactivesearch#1613]
![ssss](https://user-images.githubusercontent.com/66262604/108048078-a8b79000-7057-11eb-8a22-e30673367b29.png)

This is happening when you use filters coordinated. After you pick a value from a filter this is still rendering no result filters title

Dynamic filter components need not render if there is no value returned.

**Comment by bietkul** [comment]
The issue is not clear from the description. Can you share a code sandbox link that replicates the issue?

**Comment by erenkucuker** [comment]
I solved problem i will send pull request directly soon.
