### ISSUE TITLE
[Preact] Wrong usage of 'name' attribute for function components.

### ISSUE THREAD

**Issue by junqueror** [appbaseio/reactivesearch#1614]
**Affected Projects**
React

**Library Version:** x.y.z
^3.12.4

**Describe the bug**
When the reactive components are created, their component name is updated at the end. Ej:
```js
ForwardRefComponent.name = 'ReactiveComponent';
```
This line is throwing the following error:
```
Uncaught TypeError: Cannot assign to read only property 'name' of function.
```
Example in some components: [ReactiveComponent](https://github.com/appbaseio/reactivesearch/blob/9d084c5049152ee1b3b0dbd735683e3dfccabe86/packages/web/src/components/basic/ReactiveComponent.js#L344),  [ReactiveList](https://github.com/appbaseio/reactivesearch/blob/9d084c5049152ee1b3b0dbd735683e3dfccabe86/packages/web/src/components/result/ReactiveList.js#L967)

This name update doesn't work with [Preact](https://github.com/preactjs/preact). The [`name`](https://developer.mozilla.org/es/docs/Web/JavaScript/Referencia/Objetos_globales/Function/name) property for functions is read-only. According to [this issue](https://github.com/preactjs/preact/issues/2197) in Preact repo, `name` property should be replaced with `displayName`, which can be edited, and I think it is designed for this purpose.

**To Reproduce**
Use any React project with ReactiveSearch with Preact instead of React

**Expected behavior**
The ReactiveSearch code doesn't break.
The display names of the reactive components are changed correctly.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome, any
 - Version: Chrome 88.0.4324.146

**Additional context**

Trace:
![Captura de pantalla 2021-02-16 a las 20 37 31](https://user-images.githubusercontent.com/35776007/108112832-ef78aa80-7096-11eb-894e-4941859be58e.png)

**Comment**

This is the only bug found so far when using **ReactiveSearch** with **Preact**. I think that by making this small change in all the components we would have the library working perfectly with **Preact**.

**Comment by bietkul** [comment]
@junqueror The fix is out(v3.18.1).
