### ISSUE TITLE
Infinitescroll bug when elasticfield use text type fielddata true

### ISSUE THREAD

**Issue by erenkucuker** [appbaseio/reactivesearch#1618]
**Affected Projects**
 React Web 

**Library Version:** x.y.z
 3.15 

**Describe the bug**

**Expected behavior**
 When you use a filter that used on elastic data "type:text fielddata:true" end of the page its scroll top. This should be fixed because peoples may need to use a filter or search from input directly for the same field.  

**Screenshots**

https://prnt.sc/104qf4h

**Comment by bietkul** [comment]
@erenkucukersoftware Can you try setting `scrollOnChange` to `false`?

![alt text](https://i.imgur.com/3Dkl7m5.png)
