### ISSUE TITLE
Handle errors and improve stacktrace

### ISSUE THREAD

**Issue by divyanshu013** [appbaseio/reactivesearch#163]
**I'm submitting a ...**

- [x] feature request

**Expected / new behavior:**

We should handle errors, for example by using `componentDidCatch` and improve the stacktrace for errors if we can, adding browser, OS and reactivesearch version info.

**Comment by metagrover** [comment]
Currently errors are emitted on the streams response, and https://github.com/appbaseio/reactivecore/blob/master/src/actions/index.js#L150-L153 `handleError()` is never getting called. Check appbase-js related methods for this.
