### ISSUE TITLE
defaultValue prop not working on DynamicRangeSlider component

### ISSUE THREAD

**Issue by jothikannan89** [appbaseio/reactivesearch#1651]
**Affected Projects**
React

**Library Version:** 
Recent stable version

**Describe the bug**
defaultValue prop not working on DynamicRangeSlider component
Same issue on RangeInput also

**To Reproduce**
https://codesandbox.io/s/wispy-darkness-z3edi?file=/src/index.js

**Desktop (please complete the following information):**
 - OS: Widnows
 - Browser : All

**Comment by ubaranzorlu** [comment]
The issue persists. I cannot get it working in any way. My code:

```
<DynamicRangeSlider
        componentId={filter.key}
        dataField={filter.parameter}
        filterLabel={filter.name}
        onValueChange={props.onChange}
        defaultValue={(min, max) => ({
          start: 100,
          end: max,
        })}
        />
```
