### ISSUE TITLE
Extending ToggleButton should include anchor element

### ISSUE THREAD

**Issue by larsdouweschuitema** [appbaseio/reactivesearch#1656]
**Affected Projects**
VueJS

**Is your feature request related to a problem? Please describe.**
Extending the toggle button to implement a custom design is not including the anchor element resulting in difficulties to overwrite. You can overwrite by putting a class on the parent, but in our case the project is using tailwind classes and does not include custom classes.

The anchor elements have styling that I want to be able to resolve within the extending of the component using tailwind classes instead of adding a custom class.

**Describe the solution you'd like**
renderItem should include the anchor element allowing you to overwrite any of the elements part of the ToggleButton for behavioural/styling purposes according to the desired user experience

**Describe alternatives you've considered**
No alternatives

**Additional context**
No additional context.

**Comment by bietkul** [comment]
@larsdouweschuitema I agree with you. The `renderItem` should allow overriding the default `button` element.
Currently, the `renderItem` slot provides the following properties:
- item => item object
- isSelected => To know if the item is selected or not

We can make the following changes:
- add an additional method to handle the click event.
   - handleClick
- When `renderItem` is defined then avoid using the default element as `button`. Just render the content of `renderItem` slot.

**Comment by bietkul** [comment]
@larsdouweschuitema The fix is out(`v1.15.0`).
