### ISSUE TITLE
vue: ToggleButton not setting the default value with URLParams

### ISSUE THREAD

**Issue by lakhansamani** [appbaseio/reactivesearch#1657]
**Affected Projects**
Vue.JS

**Library Version:** x.y.z
1.13.1

**Describe the bug**
ToggleButton component is not setting the default value when URLParams is set to true

**To Reproduce**
https://codesandbox.io/s/peaceful-stallman-d07kj

**Expected behavior**
If the value is present in URLParam and if you referesh the page, ToggleButton should have that value selected by default

**Screenshots**
https://www.loom.com/share/218668fdaf8946088d731d5e117f20e1

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bietkul** [comment]
@lakhansamani The fix is out now(`v1.14.1`).
