### ISSUE TITLE
vue: pagination issues

### ISSUE THREAD

**Issue by lakhansamani** [appbaseio/reactivesearch#1661]
**Affected Projects**
Vue.JS

**Library Version:** x.y.z
1.13.1

**Describe the bug**
* Pagination doesn't reset with filter change
* Pagination doesn't respect the browser back button and results are staled
* Incorrect information when results are not found

**To Reproduce**
https://codesandbox.io/s/cranky-galileo-473mf?file=/src/App.vue

**Expected behavior**

**Screenshots**
https://www.loom.com/share/722a60409e68481cb256f39d5f4f9629

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bietkul** [comment]
@lakhansamani Fixed it in `v1.16.0`
