### ISSUE TITLE
ReactiveMap for Vue.js

### ISSUE THREAD

**Issue by jpsc** [appbaseio/reactivesearch#1664]
**Affected Projects**
Vue.JS

**Is your feature request related to a problem? Please describe.**
Currently appbase provides for the React version a component to use with maping. It would be great if we could leverage the same for the vue version.

**Describe the solution you'd like**
Create a Vue.js version of the [ReactiveMap ](https://docs.appbase.io/docs/reactivesearch/v3/overview/reactivemaps/)

**Describe alternatives you've considered**
Wrapping a custom ReactiveBase component on a Google Maps implementation but it would be nicer if were to be officially supported.

**Comment by larsdouweschuitema** [comment]
@bietkul @lakhansamani Could you look at this

**Comment by bietkul** [comment]
@jpsc @larsdouweschuitema Sure, we can build the `ReactiveMap` component for Vue but it would take some time. The workaround is to use `ReactiveComponent` to build custom search interfaces. https://docs.appbase.io/docs/reactivesearch/vue/advanced/ReactiveComponent/

**Comment by bietkul** [comment]
The `ReactiveGoogleMap` component is available now.
https://docs.appbase.io/docs/reactivesearch/vue/map/reactivegooglemap/
