### ISSUE TITLE
RangeInput for Vue.js

### ISSUE THREAD

**Issue by jpsc** [appbaseio/reactivesearch#1665]
**Affected Projects**
Vue.JS

**Is your feature request related to a problem? Please describe.**
Currently appbase provides for the React version for range input. It would be great if we could leverage the same for the vue version.

**Describe the solution you'd like**
Create a Vue.js version of the [RangeInput](https://docs.appbase.io/docs/reactivesearch/v3/range/rangeinput/)

**Describe alternatives you've considered**
None

**Comment by larsdouweschuitema** [comment]
@bietkul @lakhansamani Could you look at this

**Comment by bietkul** [comment]
@jpsc @larsdouweschuitema Sure, we can build the `RangeInput` component for Vue but it would take some time. The workaround is to use `ReactiveComponent` to build custom search interfaces. https://docs.appbase.io/docs/reactivesearch/vue/advanced/ReactiveComponent/

**Comment by bietkul** [comment]
@larsdouweschuitema The release is out now(v1.15.0). [RangeInput]( https://docs.appbase.io/docs/reactivesearch/vue/range/RangeInput/) docs.
