### ISSUE TITLE
ReactiveComponent - resultStats on slotScope props is empty

### ISSUE THREAD

**Issue by renancarvalho** [appbaseio/reactivesearch#1671]
**Affected Projects**
Vue.JS

**Library Version:** 
1.13.1

**Describe the bug**
resultStats slote-scope prop. for reactiveComponents are empty on every update

**To Reproduce**
![image](https://user-images.githubusercontent.com/2653810/117412198-c983d900-af14-11eb-98c1-e5df8d650060.png)

**Expected behavior**
I would expect to receive values on the resultStats object

**Screenshots**
![image](https://user-images.githubusercontent.com/2653810/117412409-0ea80b00-af15-11eb-8b62-27e272d12d90.png)

**Comment by renancarvalho** [comment]
@bietkul 

I am trying to get the search result number to display it inside this <FiltersFooter />

**Comment by bietkul** [comment]
@renancarvalho I don't find any issue with `resultStats`. The `resultStats` property is specific to the component's query i.e you'll only get it when you have the `defaultQuery` prop defined.
https://codesandbox.io/s/stoic-glitter-ii9nq?file=/src/App.vue
If you want to access `resultStats` for any other component then you can access it using `StateProvider` component. https://docs.appbase.io/docs/reactivesearch/vue/advanced/StateProvider/
