### ISSUE TITLE
Add counts single-range component

### ISSUE THREAD

**Issue by renancarvalho** [appbaseio/reactivesearch#1691]
**Affected Projects**
 Vue.JS 

**Is your feature request related to a problem? Please describe.**
SingleRange do not have counts ( aggregation data )

**Describe the solution you'd like**
Add counts for SingleRange component

**Comment by renancarvalho** [comment]
@bietkul

**Comment by bietkul** [comment]
@renancarvalho The [single range](https://docs.appbase.io/docs/reactivesearch/vue/range/SingleRange/) component deals with the static data.
![alt singlerange](https://i.imgur.com/Q2vwXII.png)

If you want to display the counts(aggregation data) then please use the MultiList/SingleList component.
