### ISSUE TITLE
Publish sketch design components and symbols.

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivesearch#170]
**Issue Type:**

Enhancement

**Description:**

Publish sketch design components and symbols for v2 components. The idea is to help designers create accurate UIs based on Reactivesearch. Based on feedback from #119.

This will be iteration 1, future enhancements can include some pre-configured UI screens and theme presets available within Sketch.

**Comment by metagrover** [comment]
Added to reactivesearch website

**Comment by metagrover** [comment]
[Download sketch file](https://opensource.appbase.io/reactivesearch/resources/ReactiveSearch_Playground.sketch)
