### ISSUE TITLE
ReactiveList URLParam pagination bug

### ISSUE THREAD

**Issue by katrinewi** [appbaseio/reactivesearch#1701]
**Affected Projects**
React 

**Library Version:** x.y.z
3.12.1

**Describe the bug**
When using ReactiveList with URLParams enabled the behavior is not correct. 
The bug occurs when refreshing the page with the page number in the url param with another value than 1, let's say 4. Then, if you navigate to another page and then go back to page 4, you will be taken to page 1.

**To Reproduce**
[https://codesandbox.io/s/textfield-forked-x45l6?file=/src/index.js](https://codesandbox.io/s/textfield-forked-x45l6?file=/src/index.js)
In the codesandbox, refresh with url https://x45l6.csb.app/?SearchResult=4, then navigate to page 3, then back to page 4.

**Expected behavior**
Should not be redirected back to first page

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bietkul** [comment]
@katrinewi We have fixed this issue in `v3.19.0`.
