### ISSUE TITLE
Single List allows the user to deselect an option

### ISSUE THREAD

**Issue by renancarvalho** [appbaseio/reactivesearch#1703]
**Affected Projects**
 Vue.JS 

**Library Version:** x.y.z
1.13.1

**Describe the bug**
Single list (radio button group ) allows you to have nothing selected.. which makes not sense for radio buttons.

**To Reproduce**
Render a single list and check

**Expected behavior**
Have always something from the list selected once they are radio buttons

**Screenshots**
![image](https://user-images.githubusercontent.com/2653810/120202947-7b1ddd80-c227-11eb-852d-74fa6a5c24a0.png)

https://codesandbox.io/s/github/appbaseio/reactivesearch/tree/next/packages/vue/examples/single-list?from-embed

**Comment by renancarvalho** [comment]
@bietkul, could you please take a look into this one ? 

Thank you!

**Comment by bietkul** [comment]
@renancarvalho You can set the default selected value using the `defaultValue` prop.
![alt img](https://i.imgur.com/IVAD0uS.png)

**Comment by renancarvalho** [comment]
It is there.

**Comment by bietkul** [comment]
The solution here is to define a new prop named `enableStrictSelection`, when it is set to`true` then disable the ability to disable an option in the following components.
 React
 - `SingleList`
 - `SingleDataList`
 - `SingleDropdownList`
 - `SingleRange`
 - `SingleDropdownRange`
 
 Vue
 - `SingleList`
 - `SingleDropdownList`
 - `SingleRange`

**Comment by renancarvalho** [comment]
Thanks! will try =)

**Comment by renancarvalho** [comment]
Hi @bietkul,

I have installed the new version 1.15.0 and added enableStrictSelection= true  for the single-list in our vue project.
We still having the issue.

**Comment by siddharthlatest** [comment]
@renancarvalho We've currently finalized on how to support it and assigned it internally. This is yet to be addressed, it should be out with the next release most likely.

**Comment by bietkul** [comment]
@renancarvalho We have fixed it in v1.15.1.
