### ISSUE TITLE
results automatically show up on starting the react web application

### ISSUE THREAD

**Issue by HesterG** [appbaseio/reactivesearch#1709]
**Affected Projects**

React JS

**Is your feature request related to a problem? Please describe.**

I am trying to add a search feature to my web application, and on starting the web application, all results automatically shows even i haven't click on search.

**Describe the solution you'd like**

When the web application is started, i don't want the search results to appear automatically. I want the results to appear only after i do search for something.

**Comment by siddharthlatest** [comment]
@HesterG You can configure this behavior. I will move this to Discussions.

You can use the `defaultQuery` on the <ReactiveList/> component to configure the default query to use. Or if you can share your code snippet, happy to guide on how to.
