### ISSUE TITLE
Handle Cluster click event.

### ISSUE THREAD

**Issue by renancarvalho** [appbaseio/reactivesearch#1716]
**Affected Projects**

**Is your feature request related to a problem? Please describe.**
We need to show a component that is similar to a carousel

**Describe the solution you'd like**
 Basically we pass an array of data and navigate on it. We would like to handle the cluster click and then render this carousel of data. right now we can only handle click for a simple marker, not clusters.
Similar to this, where the user can navigate on a clustered data.

![image](https://user-images.githubusercontent.com/2653810/122246590-f689bb00-cec6-11eb-88e2-84cf884014f8.png)

**Describe alternatives you've considered**
none

**Additional context**
N/A

**Comment by bietkul** [comment]
It has been fixed in the latest version of Reactivesearch.
