### ISSUE TITLE
Add a resetDefault prop to SelectedFilters components to reset filters back to their default values

### ISSUE THREAD

**Issue by larsdouweschuitema** [appbaseio/reactivesearch#1722]
**Affected Projects**
VueJS

**Is your feature request related to a problem? Please describe.**
Using "clearValues" prop on SelectedFilters components does not take into account the "defaultValue" set on each individual component.

**Describe the solution you'd like**
A "resetDefault" prop so that you can decide whether to completely reset using "clearValues" or resetting back to defaults.

**Describe alternatives you've considered**
Writing custom functionality to set the state. But this was quickly stated bad practice because of bad syncing with appbase components in special the StateProvider.

**Additional context**
Default values set on component
![image](https://user-images.githubusercontent.com/8817968/122536743-27800200-d025-11eb-95cd-603bb02c0dcc.png)

Default values before clear
![image](https://user-images.githubusercontent.com/8817968/122536766-2e0e7980-d025-11eb-90df-3a532c57859f.png)

After clear > All values are empty/nothing/0
![image](https://user-images.githubusercontent.com/8817968/122536785-32d32d80-d025-11eb-9081-663396273c31.png)

**Comment by bietkul** [comment]
@mohdashraf010897 We can define a new prop named `resetToDefault` in `SelectedFilters` component. 
When `resetToDefault` is set to true, then it would set the filter value to the `defaultValue`.
The default value for `resetToDefault` would be `false`.
