### ISSUE TITLE
Vue 3

### ISSUE THREAD

**Issue by jpsc** [appbaseio/reactivesearch#1732]
**Affected Projects**
Vue.js

**Describe the solution you'd like**
Vue 3 is every day reaching a level of stability and support from the community that will be hard to ignore in the near future. My suggestion is to start discussing how we are going to tackle this. Migration steps are documented here (https://v3.vuejs.org/guide/migration/introduction.html#overview).

There is a lot of paths we can take, so I will leave this as broad as possible to foster the discussion.

**Comment by jpsc** [comment]
I would suggest start by creating a list of dependencies that would be blocking if we wanted to start with this update. eg: vue-gmaps, vue-slider

**Comment by siddharthlatest** [comment]
@jpsc We have been discussing this internally. With this issue now open, we can start with listing the dependencies that are blocking Vue 3.0 support.

**Comment by jpsc** [comment]
Great to hear. A few things that come to mind about this:
- We probably need some infra changes to allow for fixes/patches releases to the current version (as it's going to be a breaking/major change).
- Vue 3 does not have IE11 support. This not only needs to be communicated but also taken advantage of (eg. removing unnecessary polyfills).
-  Shall we rethink how reactive search can be consumed? (Probably out of scope). There is a multitude of opportunities to reveal by using the composition api. That's maybe something that could be valid for react and hooks.

**Comment by siddharthlatest** [comment]
@jpsc These are great points.

> We probably need some infra changes to allow for fixes/patches releases to the current version (as it's going to be a breaking/major change).

We will continue supporting Vue 2.x (ReactiveSearch 1.x) for some time, as the majority of the users will be here. We can come up with a timeline of till when will this support last.

> Vue 3 does not have IE11 support. This not only needs to be communicated but also taken advantage of (eg. removing unnecessary polyfills).

This is a really good point, and we should be optimizing for bundle size and performance here.

> Shall we rethink how reactive search can be consumed? (Probably out of scope). There is a multitude of opportunities to reveal by using the composition api. That's maybe something that could be valid for react and hooks.

Yes, would love to. Can you share any pointers on how you're thinking about this?

**Comment by jpsc** [comment]
> Yes, would love to. Can you share any pointers on how you're thinking about this?
I'm sorry, I don't have enough experience with composition API or hooks to give a proper suggestion 🙈.

**Comment by vince83110** [comment]
+1

With Nuxt3 in beta, and soon in RC / stable, it will be useful to support Vue3.

We are starting the migration in my company, Nuxt 2 => Nuxt 3 / Vue3, we will fork reactivesearch and see what we can do.

**Comment by alancwoo** [comment]
@siddharthlatest @jpsc I was curious if there was any movement on this issue or if it's recommended to start new projects in Vue2 instead?

**Comment by PeterPilley** [comment]
Hi +1 on this, we are moving to vue3 now, be awesome if it supported it
