### ISSUE TITLE
ToggleButton When Used as Child Component is Removed from SelectedValues  

### ISSUE THREAD

**Issue by rollinsb1010** [appbaseio/reactivesearch#1738]
**Affected Projects**
React

**Library Version:** 3.20.0

**Describe the bug**

Trying to use ToggleButton as a child component of ReactiveList. The initial query is fired and properly executed in most cases but then unable to reset the filter. Therefore, it only appears in SelectedFilters for a second before being removed. 

**To Reproduce**
https://codesandbox.io/s/charming-thompson-nzxet?file=/src/index.js:1941-2526

**Steps to reproduce the behavior:**
1) Create ReactiveList with render method
2) Render ToggleButton component within ReactiveList render method

**Expected behavior**
Goal is to keep ToggleButton state in selectedValues and be able to unset the state via SelectedFilters once enabled

**Screenshots**

**Desktop (please complete the following information):**

OS: OSX Catalina
Browser: Firefox Developer Ed
Version: Latest

**Comment by bietkul** [comment]
@rollinsb1010 Can you please use the issue template?
