### ISSUE TITLE
Expose event "Search as I move the map" adding custom behavior

### ISSUE THREAD

**Issue by larsdouweschuitema** [appbaseio/reactivesearch#1742]
**Affected Projects**
VueJS

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
- If the user clicks on the checkbox "search as I move the map" we would like to be able to use a callback function to clear all the filters or something else (any custom behavior), so basically expose this event

Additional
- Translations "search as I move the map"
- Customize title "search as I move the map"

**Describe alternatives you've considered**
Add our own button that handles all of this programmatically.

**Additional context**
![image](https://user-images.githubusercontent.com/8817968/126961794-abeadd74-f557-4473-baf1-7786ac85d3ce.png)

**Comment by bietkul** [comment]
@larsdouweschuitema Closing it because `debounce` is working fine as per our chat.

**Comment by bietkul** [comment]
We have added the support for the above functionalities in `v1.16.0-alpha.15`.
- Use `search-as-move` event to handle the search as move checkbox click
- Use `searchAsMoveLabel` prop to customize the default title for checkbox. The same can be used for translations.
