### ISSUE TITLE
Debounce in searchbox config not being applied

### ISSUE THREAD

**Issue by larsdouweschuitema** [appbaseio/reactivesearch#1743]
**Affected Projects**
VueJS

**Library Version:** x.y.z
1.16.0-alpha.12

**Describe the bug**
Changing value of debounce in searchbox config has no effect no matter what value you set.
Every character that you type is fired an event immediately.

**To Reproduce**
1. Set a debounce of 1 or more seconds in the config
2. Type a full search in the searchbox e.g. "Amsterdam"
2. Every letter fires an event / Multiple events are fired

**Expected behavior**
1. Set a debounce of 1 or more seconds in the config
2. Type a full search in the searchbox e.g. "Amsterdam"
2. New requests are delayed waiting on user to be done typing
3. Only 1 event is fired

**Screenshots**
![image](https://user-images.githubusercontent.com/8817968/126963248-d9610712-b232-4ff2-a973-8ef4c1e25bda.png)

**Desktop (please complete the following information):**
Any

**Smartphone (please complete the following information):**
Any

**Comment by bietkul** [comment]
@larsdouweschuitema Closing it because debounce is working fine as per our chat.
