### ISSUE TITLE
Implement Pagination as its own component to improve generalizability

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivesearch#175]
**Issue Type:**

Enhancement / Idea

**Description:**

Current pagination component's implementation is tightly coupled within each Result component. The idea is to use Pagination as a HOC around any result component, thus making the implementation DRY friendly. This may also help add pagination to other components beside result component (e.g. infinite scrolling support on list components).

Requires careful thought on separation of concerns, and also needs some other enhancements like:

1. URLParams for pagination (to navigate to a specific result view),
2. A more customizable navigation of the pages.

**Comment by Guazi** [comment]
+1, I would find this very helpful to show URLParams for pagination.

**Comment by metagrover** [comment]
Added here: 51360fed4bf042542460ed2a83a99ce6594e5058 086bb18c8a6627db85f0a504ce1ae33762f839ae
