### ISSUE TITLE
sortOptions: Allow choice b/w tab and dropdown displays

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivesearch#176]
**Issue Type:**

Enhancement

**Description:**

Allow user a choice between showing sortOptions as a dropdown display (default) or a tab display.

Example spec:

```js
<ResultCard
  showSortOptions="tab" (defaults to "dropdown")
/>
```

**Comment by metagrover** [comment]
We will be creating a separate component for sorting results and this sort of customisation can be achieved via ReactiveComponent.
