### ISSUE TITLE
[Bug] Dropdown component vulnerable to XSS attacks

### ISSUE THREAD

**Issue by tvt-devteam** [appbaseio/reactivesearch#1771]
**Affected Projects**
React

**Library Version:** 3.22.0

**Describe the bug**

User inputted HTML tags are not sanitized by ReactiveSearch. They are rendered using dangerouslySetInnerHTML, and will get inserted into the DOM as such.

**To Reproduce**

1. Insert an HTML tag into ElasticSearch. We used ```<img src onerror("alert('Testing');">```
2. Have a component that uses the shared Dropdown component search and load this data into UI
3. Javascript inside the onerror function gets executed

**Expected behavior**
User inserted HTML tag should be either sanitized to not contain HTML tag characters, or just be rendered as a string.

**Screenshots**

**BUG**

1. User inserts a tag they want to be associated with their image. This get inserted into ElasticSearch.

<img width="374" alt="Screenshot 2021-08-17 at 9 40 01" src="https://user-images.githubusercontent.com/76695316/129678117-cb4749ce-f2d8-42f7-8a70-667f99197454.png">

2. We use [MultiDropdownList component](https://docs.appbase.io/docs/reactivesearch/v3/list/multidropdownlist/) to render all tags found within ES. 

<img width="303" alt="Screenshot 2021-08-17 at 9 40 46" src="https://user-images.githubusercontent.com/76695316/129678335-02d29d95-2f34-4652-94c0-2cf00e858e68.png">

3. The component fails to show the given tag label as a string, as it is rendered into DOM instead.

<img width="565" alt="Screenshot 2021-08-17 at 9 41 31" src="https://user-images.githubusercontent.com/76695316/129678676-4dc5079e-513c-432f-9eaf-fa2808bfffc4.png">

**INTENTED**

4. The tag label is rendered as a string
<img width="295" alt="Screenshot 2021-08-17 at 9 43 36" src="https://user-images.githubusercontent.com/76695316/129682752-672db791-7c82-4b1f-973a-bc443fb96710.png">

<img width="565" alt="Screenshot 2021-08-17 at 9 43 56" src="https://user-images.githubusercontent.com/76695316/129682819-cd0813e8-a57f-4f9d-b381-fea8e285bb02.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Google Chrome
 - Version 92.0.4515.131

**Smartphone (please complete the following information):**

Has not been tested on mobile

**Additional context**

Link to component that is (most likely) causing the issue

https://github.com/appbaseio/reactivesearch/blob/13a29bab1db06f9ccf5964c625f693bc106baba0/packages/web/src/components/shared/Dropdown.js#L228

NOTE: This has been only slightly tested by us and might not be the best or even correct solution, but it got us some positive results.

Proposed solution:

Change:

```javascript
typeof item[labelField] === 'string' ? (0, _core.jsx)(
'span',
{
	dangerouslySetInnerHTML: {
		__html: item[labelField]
	},
})
: item[labelField],
```

into:

```javascript
typeof item[labelField] === 'string' ? (0, _core.jsx)(
 'span',
{
  className: (0, _helper.getClassName)(_this2.props.innerClass, 'label') || null
},
item[labelField]) : item[labelField],
```

**Comment by tvt-devteam** [comment]
Bump - is there any info on this, or has this been looked at? How should we proceed with this problem?

**Comment by siddharthlatest** [comment]
@tvt-devteam We're supporting HTML rendering to allow a user control over how the UI gets rendered. Since the user is both in control of rendering / their Elasticsearch, I don't see how this is vulnerable to misuse.

Sanitizing the input here would have the side-effect of users not being able to use rich HTML, so this isn't an ideal solution imo.

**Comment by tvt-devteam** [comment]
Thanks for the answer @siddharthlatest 

We looked into the component some more and indeed did find the `renderItem` prop and was able to fix this problem on our end!

We are still thinking that use of this component is a bit risky because of it defaulting to use `DangerouslySetInnerHTML`. 

Maybe there could be a prop to enable/disable the use of this way of rendering, which would be disabled by default?
