### ISSUE TITLE
Error: Unable to resolve data for blob: (null) - React native

### ISSUE THREAD

**Issue by manuelabarca** [appbaseio/reactivesearch#1785]
**Affected Projects**
React native ("@appbaseio/reactivesearch-native")

**Library Version:** x.y.z
^0.12.0

**Describe the bug**
I have this error "Error: Unable to resolve data for blob: (null)" in production, when i development i have this

```
if (typeof GLOBAL !== 'undefined' && __DEV__) {
	// Route network requests through Chrome's native XMLHttpRequest
	GLOBAL.XMLHttpRequest = GLOBAL.originalXMLHttpRequest || GLOBAL.XMLHttpRequest;

	// Use native Blob for native XMLHttpRequest set above
	GLOBAL.Blob = GLOBAL.originalBlob || GLOBAL.Blob;

	// Use native FileReader to read native Blob set above
	GLOBAL.FileReader = GLOBAL.originalFileReader || GLOBAL.FileReader;
}
```
But when i try in release mode i see blob error and not search in elastic :S Any help with this ?

**To Reproduce**
Build app in release mode.

**Snapshots**

<img width="532" alt="Captura de Pantalla 2021-09-15 a la(s) 10 35 54" src="https://user-images.githubusercontent.com/20046746/133443389-4d29789d-5cf7-49e0-a858-f44b9cfc2f76.png">

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS14

**Additional context**
When I am in debug mode it works without any problem, but when we launched the version to test flight we realized that the results were not coming from the elastic search, after debugging in release mode from xcode we realized that it throws this blob error (null) and we don't know why that should only happen in debug mode

**Comment by siddharthlatest** [comment]
@manuelabarca Can you use the issue template to add the details, which library / version / environment / replicable snippet would be good for us to check more on.

**Comment by manuelabarca** [comment]
> @manuelabarca Can you use the issue template to add the details, which library / version / environment / replicable snippet would be good for us to check more on.

I just updated with the template, If you know any possible solution, I would appreciate it
