### ISSUE TITLE
Provide a way to use user or session identifiers in routing preferences

### ISSUE THREAD

**Issue by lorenzocestaro** [appbaseio/reactivesearch#1811]
**Affected Projects**
This should affect all packages as it is a performance improvement in the core

**Is your feature request related to a problem? Please describe.**
How `componentId` is currently used under the hood can lead to performance issues in client applications. `componentId` is used to keep internal component state, but it is also used as a value for the `preference` options in queries. [Quoting ES documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-search.html#search-preference), by setting a `preference` we are **forcing the query to be routed to the same shards in the same order, every single time**. 

If an application uses simple static strings as values for `componentId`, the queries from **all the users** of the application will be routed to the same shards. Which means that the load will not be distributed across the whole cluster and some shards will have considerably more load than others. This could degrade query performance due to shards being overloaded and require premature scaling of the elasticsearch cluster.

**Describe the solution you'd like**
First of all, I think this should be stated in the documentation more explicitly, so users are informed of the meaning that the `componentId` carries. Right now it is described only as a way for the library to define the reactive dependencies, but in reality it has impact on performance.

I am using the react library, so I don't know if this solution would work for all the distribution. But I think it would be optimal to have the possibility to supply and extra value as a prop to `ReactiveBase`. This will ideally be a value that changes among users, like a user id or a session id. This extra value would be used internally by reactivesearch to compute the internal ids and used for `preference` in queries.

**Additional context**
Just an interesting [elasticsearch PR](https://github.com/elastic/elasticsearch/pull/24671) that highlight how also Kibana uses session ids in routing preferences.
Also this issue springs from a discussion started in [this other issue](https://github.com/appbaseio/reactivesearch/issues/1216).

**Comment by siddharthlatest** [comment]
Thank you for this great description @lorenzocestaro  💯

**Comment by bietkul** [comment]
@lorenzocestaro We have fixed it in the latest release.
