### ISSUE TITLE
Way to Clear the MultiDropdownList Search Text box

### ISSUE THREAD

**Issue by rohit9m** [appbaseio/reactivesearch#1814]
**Affected Projects**

**Library Version:** 3.12.3

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/22859300/142575017-ee42926a-f001-4ece-b046-50e71528ab73.png)

**Desktop (please complete the following information):*WIndows 10*

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mohdashraf010897** [comment]
Hey 👋  @rohit9m 
Please provide more context, it would help to better understand the issue.

**Comment by rohit9m** [comment]
Hi @mohdashraf010897 ,

  For a multidropdownlist component, if we make show search property as true like below or using any props

  <MultiDropdownList
                  showSearch={true}

It will generate a text box in any dropdown list to make a search in dropdown list items, but there is no option to clear that search text box.

**Comment by TMKrishna1211** [comment]
Hello @mohdashraf010897 , Can you please help us on this issue. Awaiting your response.

**Comment by TMKrishna1211** [comment]
We are facing issue with clearing the searched text after filtering the results of Multi select dropdownlist as mentioned in the details above.

**Comment by bietkul** [comment]
@TMKrishna1211 We can notice the issue.
@mohdashraf010897 Check the issue at [here](https://codesandbox.io/s/frosty-worker-3zegv?file=/src/index.js)
We can add a clear button in the input box to clear the searched text.

**Comment by rohit9m** [comment]
Hi @mohdashraf010897 ,
When you guys are planning to release this ?

**Comment by rohit9m** [comment]
Hi @mohdashraf010897 , @bietkul ,

Can you please suggest if this fix is available in Version 3.29. We are upgrading our project with latest version.

**Comment by bietkul** [comment]
@rohit9m Yes, it is included. You would have to set the `showClear` prop to `true` in dropdown list components.
