### ISSUE TITLE
Update vue-slider-component

### ISSUE THREAD

**Issue by royduin** [appbaseio/reactivesearch#1815]
Currently vue-slider-component V2 is used: https://github.com/appbaseio/reactivesearch/blob/b017c358d9fb5b0a05062d2b70895519e5c3d7e3/packages/vue/package.json#L49 which has a known bug: https://github.com/NightCatSama/vue-slider-component/issues/409 also covered in the readme: https://github.com/NightCatSama/vue-slider-component/tree/v2#exceptions. V3 doesn't have that issue so it would be nice if the lib is getting updated within Reactive Search.

**Comment by mohdashraf010897** [comment]
Hey 👋  @royduin 
You can upgrade to [v 1.24.3-alpha.1](https://www.npmjs.com/package/@appbaseio/reactivesearch-vue/v/1.24.3-alpha.1) while we make a stable release.

Working Demo(s)
- [RangeSlider](https://codesandbox.io/embed/heuristic-browser-6lhnr?fontsize=14&hidenavigation=1&theme=dark)
- [DynamicRangeSlider](https://codesandbox.io/embed/zealous-einstein-kgfuq?fontsize=14&hidenavigation=1&theme=dark)

Thanks.

**Comment by royduin** [comment]
Awesome, thanks 💯

**Comment by royduin** [comment]
Merged and released, thanks 🥳 just one issue apart from the changed styling: https://github.com/appbaseio/reactivesearch/pull/1886
