### ISSUE TITLE
renderItem MultiDataList 3rd parameter wrong

### ISSUE THREAD

**Issue by freddyftw** [appbaseio/reactivesearch#1821]
https://github.com/appbaseio/reactivesearch/blob/1c2f5fb313c32613501756c870accac3e54a9afe/packages/web/src/components/list/MultiDataList.js#L508

Shouldn't the 3rd argument be `isChecked` from https://github.com/appbaseio/reactivesearch/blob/1c2f5fb313c32613501756c870accac3e54a9afe/packages/web/src/components/list/MultiDataList.js#L479 ? I'm always getting false in `isSelected`

**Comment by mohdashraf010897** [comment]
@freddyftw Hey 👋 , thanks for reaching out. will shortly respond with something.
Meanwhile, I would recommend using the Issue Template 👉 https://github.com/appbaseio/reactivesearch/blob/next/.github/ISSUE_TEMPLATE/bug_report.md for reporting any issue.

**Comment by mohdashraf010897** [comment]
@freddyftw 
You can upgrade to [Version 3.26.1-alpha.2](https://www.npmjs.com/package/@appbaseio/reactivesearch/v/3.26.1-alpha.2) that specifically fixes the above issue. 

Working Demo 👉  https://codesandbox.io/embed/elastic-beaver-4jvem?fontsize=14&hidenavigation=1&theme=dark

Thanks
