### ISSUE TITLE
Unnecessary states are pushed to browser history

### ISSUE THREAD

**Issue by divyanshu013** [appbaseio/reactivesearch#186]
# Bug

## Description

An app built with reactivesearch is pushing a lot of unnecessary states to history. This makes it tedious to use back and forward navigations from the browser. We should identify the root cause and fix such that only one state is pushed to the history for a change.

**Minimal reproduction of the problem with instructions:**

Check any app built with reactivesearch eg - https://appbaseio-apps.github.io/gitxplore-app/
Look at the history stack in the browser and try to use back/forward navigations

**Reactivesearch version:** x.y.z

v2 beta latest

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome 63 macOS 10.13, however I suspect it would happen on all

**Comment by siddharthlatest** [comment]
Saw this a couple of times as well.

**Comment by metagrover** [comment]
Ref: e240ecde02ce3d37f0ea31e2fd2cba5e661182a7
