### ISSUE TITLE
Connnection unsuccessful to elasticsearch on localhost .

### ISSUE THREAD

**Issue by coolb0y** [appbaseio/reactivesearch#1934]
### Discussed in https://github.com/appbaseio/reactivesearch/discussions/1933

<div type='discussions-op-text'>

<sup>Originally posted by **coolb0y** April 25, 2022</sup>
I used the sandbox code https://codesandbox.io/s/0yn05 . I put my index name as app name and credentials I put which I created during elasticsearch installation "elastic:somepassword" format and also link I gave was https://localhost:9200 . After setting all the cors setting in elasticsearch.yml . I found this error  console
` {"type":"default","status":400,"ok":false,"statusText":"Bad Request","headers":{"map":{"content-length":"88","content-type":"application/json"}},"url":"https://localhost:9200/dataserver/_reactivesearch.v3","_bodyInit":{},"_bodyBlob":{},"bodyUsed":true}`
Please help me .</div>

**Comment by coolb0y** [comment]
same issue with me on Opensearch

**Comment by coolb0y** [comment]
After One year I know the answer. This issue occurs either the index name you are providing is wrong i.e app name should be index name also this index should already exists in elasticsearch or opensearch if not create that index first. Second issue occurs which is mostly the case  url="http://127.0.0.1:9200"
      app="datapp"
      credentials="user:pass"
      enableAppbase={false}
enableAppbase should be false else it send request to /yourindex/_reactivesearch route which does not exists in elasticsearch instead of /yourindex/_msearch which exists in elasticsearch.

**Comment by capricornusx** [comment]
At now, for me, this vue example config:

```vue
<script>
const selfHostedCluster = {
  url: "http://localhost:9200/yourindex/_search",
  headers: { "Content-Type": "application/json" },
  method: "POST"
};
</script>

<template>
  <reactive-base :endpoint=cluster >
     <div id="app"> some data </div>
  </reactive-base>
</template>
```


Also, your need configure CORS for [elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/current/behavioral-analytics-cors.html), like:

```
http.cors.allow-origin: "*" # Only use unrestricted value for local development
http.cors.enabled: true
http.cors.allow-credentials: true
http.cors.allow-methods: OPTIONS, POST
http.cors.allow-headers: "*"
```
