### ISSUE TITLE
RangeInput not clearing correctly

### ISSUE THREAD

**Issue by Emilvooo** [appbaseio/reactivesearch#1937]
**Affected Projects**
React

**Library Version:** x.y.z
3.30.0

**Describe the bug**
When filtering using the RangeInput filter the <SelectedFilters reset buttons don't work.

**To Reproduce**
Use the lastest version of ReactiveSearch and use the RangeInput filter.

**Expected behavior**
The reset buttons should reset the RangeInput filters.

**Screenshots**
![Peek 2022-04-26 10-54](https://user-images.githubusercontent.com/1354252/165262607-a1e19bbd-ea2e-49ee-9e59-fcbed326dc8f.gif)

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.04
 - Browser: Firefox, Chrome & Safari
 - Version: Lastest versions

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: iOS 15.4.1
 - Browser Safari
 - Version: Lastest

**Additional context**
Tried using normal Slider and here it's working right. See example:
![Peek 2022-04-26 11-06](https://user-images.githubusercontent.com/1354252/165265104-2f14cdd6-3cc2-4ea4-98c8-e04d57fd8e0f.gif)

**Comment by RukshanJS** [comment]
I'm having the same issue. Did you find any fix or workaround?

**Comment by mohdashraf010897** [comment]
@Emilvooo https://github.com/appbaseio/reactivesearch/pull/1972 fixes the issue. Please confirm if you are good with the fix.

cc @RukshanJS
