### ISSUE TITLE
Duplicate pagination

### ISSUE THREAD

**Issue by bachvu-michael** [appbaseio/reactivesearch#1966]
**Affected Projects**
React

**Library Version:** x.y.z
"@appbaseio/reactivesearch": "3.30.3",

**Describe the bug**
duplicate pagination

**To Reproduce**

https://codesandbox.io/s/withered-cdn-pun7db?file=/src/index.js

at 'ReactiveList' component change size={2000} and add showEndPage={true}

**Expected behavior**
remove duplicate or debug about this bug to know the reason, so get the solution

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MACOS
 - Browser Chorme
 - Version 101.0.4951.54 (Official Build) (arm64)

**Comment by bachvu-michael** [comment]
![Uploading Screen Shot 2022-05-09 at 14.11.42.png…]()

**Comment by bachvu-michael** [comment]
![Screen Shot 2022-05-09 at 14 11 42](https://user-images.githubusercontent.com/26225921/167359543-74b7a932-ed1a-4fb5-9803-b57ce42d1e4f.png)

**Comment by siddharthlatest** [comment]
This is fixed and released in the latest releases.
