### ISSUE TITLE
MultiList re-renders several times instead of once

### ISSUE THREAD

**Issue by mirjan-hoffmann** [appbaseio/reactivesearch#1974]
**Affected Projects**
React

**Library Version:** x.y.z
from 3.25.1 (also in current version 3.31.0)

**Describe the bug**
When a `MultiList` component is updated via `react`-property (e.g. to update the document-counter), the component is re-rendered very often. This affects performance significantly.

**To Reproduce**
https://codesandbox.io/s/crazy-sinoussi-3j9mbd?file=/src/index.js
* select a value in the _BookSensor_ (first sensor)
* have a look at the console-output for "render MultiList" -> e.g. "render MultiList: TitleSensor" is logged 10 times

**Expected behavior**
Re-render the MultiList component only once, like in version 3.25.0

Same codesandbox like above, just with decreased reactivesearch version to 3.25.0: https://codesandbox.io/s/blissful-goldberg-6x1wvz?file=/src/index.js

* Select a value in this codesandbox like above and the "render MultiList: TitleSensor" is just logged once

**Screenshots**
![reactivesearch_multiple_rerender](https://user-images.githubusercontent.com/19548499/169779649-8966ad17-5394-46eb-95db-71b1efc16dfe.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.4 LTS
 - Browser firefox
 - Version 100.0.2

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by ubaranzorlu** [comment]
Any updates on that one? It seems like the PR doesn't actually solve the problem for me. MultiList renders so much that it always maxes the bars in React Profiler and crashes my app. 3.25.0 seems a more reliable version for MultiList.

**Comment by ubaranzorlu** [comment]
Using those versions as dependencies solved all my problems.

`
{
  "dependencies": {
    "@appbaseio/reactivecore": "9.14.10",
    "@appbaseio/reactivesearch": "3.25.0"
  }
}
`

**Comment by bietkul** [comment]
Hello @ubaranzorlu, can you try upgrading to latest version?

**Comment by mirjan-hoffmann** [comment]
Upgraded to `"@appbaseio/reactivesearch": "3.34.1"` - performance looks good with this one. Also, my sandbox-example just logs a single re-rendering:  https://codesandbox.io/s/xenodochial-bhaskara-wvjhfm

-> fixed from my point of view

**Comment by ubaranzorlu** [comment]
> Hello @ubaranzorlu, can you try upgrading to latest version?

Issue is resolved, thanks 👍
