### ISSUE TITLE
New Component: DynamicRangeSlider

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivesearch#2]
Like RangeSlider but decides its range based on the underlying data, i.e. dynamically.

### Component Props

- **componentId** `String`  
    component ID.
- **appbaseField** `String`  
    DB field to be mapped with UI for querying. Should be numeric.
- **title** `String`  
    title of the component, optional.
- **rangeLabels** `Function` [optional]  
    takes a `function(start_val, end_val)` and returns an object in the format:
```
{
  "start": "start label",
  "end": "end label"
}
```
- **defaultSelected** `Function` [optional]  
    takes a `function(start_val, end_val)` and returns an object in the format:
```
{
  "start": 0,
  "end": 10
}
```
- **showHistogram** `Boolean`  
    whether to show the histogram. Defaults to `true`.
- **stepValue** `Number`  
    step value specifies the slider stepper. Value should be an integer between 1 and floor(#total-range/2). Defaults to 1.

### CSS Styles API

`rbc-histogram-active`
`rbc-rangelabels-active`
`rbc-title-active`

### Stories

1. Basic story
2. Story with passing labels via a function
3. With default selected 
4. With a different step value than 1
5. In a dark theme
6. Playground.

**Comment by metagrover** [comment]
Added here: cb01a8b7b3f9c0bff9ba49e99be626b3d9e999f8 0a85a4a777c873b358e6a2530a9f68ccde66c9cb bf1c5431e2b23414d202b406dd60aee8ecf02b47
