### ISSUE TITLE
Search Examples: Component Usage

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivesearch#20]
- [x] Product Hunt search should work on both title and description.
- [x] Airbnb components should implement `react` prop between themselves.
- [x] E-commerce sensor components should implement the `react` prop between themselves.
- [x] E-commerce example's category search filter does not show any results on picking a category.
- [x] Yelp's suggestions seem to be broken. ![](https://i.imgur.com/ZY9y7s2.png)
While it shows "BARDS TOWN", clicking on it doesn't bring up any results.
- [x] Meetup's search topics box doesn't show any suggestions. I tried "Big Data", "Single", "Social" ![](https://i.imgur.com/YpynUo9.png)

We should implement a noResults view in all examples.

Importantly, we are selling the search functionality and that is broken in some key examples. We need to fix that first.

**Comment by siddharthlatest** [comment]
- [ ] HN app: Change mapping to use "English" analyzer and use the new app.
- [ ] PH app: Check if English analyzer is needed.

**Comment by metagrover** [comment]
Fixed examples here: 9f27557d636b7f572ff1fe8758b5f46a6d0e51d1 2bcd8afcf1e7f79729c9c341510e3b875ded6211 a73e0efb9757198066ca7cb516d1d6616fea9ea1 9e26be31ffe091da1f0e611f932739f04ef54af9 895a47df79a19b7d75ce278c93ac15a9bf850612  dbdd2cdd9f3a1cb10c53d9e036a5aec646f4a81a 85ab28d320a5b6ffb5dc0eba1380d2c9c5a6e065

**Comment by metagrover** [comment]
Updated HN app in onboarding: 227768875f441da437b621879d0257b0c73e11e3

**Comment by siddharthlatest** [comment]
- [ ] Upper casing in tags in Product Hunt app
- [ ] Infinite scroll issue, scrollTarget prop should fix that
- [ ] Meetup search content similar to actual meetup app.
