### ISSUE TITLE
Typescript definition files (.d.ts) not present on >3.34.3

### ISSUE THREAD

**Issue by nwidynski** [appbaseio/reactivesearch#2043]
**Issue Type:**
Bug + Enhancement

**Platform:**
Web

**Description:**
I'm trying to use the latest version of reactivesearch in a typescript project.
Despite the documentation, and example provided in the docs, typescript definitions are not available.

**Minimal reproduction of the problem with instructions:**

1. Step: npm install @appbaseio/reactivesearch@latest
2. Step: Check the contents of node_modules/@appbaseio/
3. Step: See that there are no .d.ts files available.

**Reactivesearch version:** >3.34.4

**Comment by SavvyShah** [comment]
Thanks for reporting the issue. It has been fixed. Could you upgrade to latest version(`v3.38.1`)?
