### ISSUE TITLE
Export to CSV not working for infinite scrolling

### ISSUE THREAD

**Issue by neelshahxooa** [appbaseio/reactivesearch#2057]
**Library Version:** 3.38.3

**Describe the bug**
On Infinite scrolling I have enabled export option, on clicking export to csv button it is throwing error.

**To Reproduce**
enable pagination, export and click export csv, check this sandbox for reference
https://codesandbox.io/s/reactivesearch-quickstart-final-app-forked-ji3bz6?file=/src/App.js

Also if you don't use enableAppbase and click export, it throws error

**Comment by mohdashraf010897** [comment]
@neelshahxooa Thanks for raising the issue. 🙌 

We will get back to you with a fix asap. 🔧

**Comment by siddharthlatest** [comment]
@neelshahxooa `enableAppbase={true}` is necessary for exporting to work, as exporting is based on the [ReactiveSearch API](https://docs.reactivesearch.io/docs/search/reactivesearch-api/).
