### ISSUE TITLE
TreeList dataField array causing elasticsearch to return error on field

### ISSUE THREAD

**Issue by Kyokatarz** [appbaseio/reactivesearch#2059]
**Affected Projects**
React

**Library Version:** x.y.z
v3.38.3

**Describe the bug**
TreeList causes Elasticsearch field term to return 400 because it doesn't allow an array.
Elasticsearch version: v7.16.1 

^ Could elasticsearch version be the problem?

**To Reproduce**
Passing `dataField` props to `TreeList` using elasticsearch v7.16.1

**Expected behavior**
It should work like other components

**Screenshots**
![Screen Shot 2022-08-30 at 12 38 20](https://user-images.githubusercontent.com/51933605/187431160-8e011cfc-9bbb-43fd-a465-e94795498ba3.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by siddharthlatest** [comment]
@Kyokatarz can you share the field mapping being used for dataField, and the network request payload?

**Comment by Kyokatarz** [comment]
I'm not sure how to extract field mapping, but here is network request payload :D

```
{"preference":"treeListSensor"}
{"query":{"match_all":{}},"size":0,"aggs":{"class.keyword":{"terms":{"field":["class.keyword"],"order":{"_count":"desc"}}}}}
```

**Comment by markusguenther** [comment]
I have the same issue. It works when I use the field as a string (with an error in the console that I should use an array for the data Field). We use open search instead of elastic search.

```
<TreeList
            title="Spielphasen"
            componentId="gamePhases-filter"
            dataField="gamePhasesDetails"
            showCount={true}
            showSwitcherIcon={true}
            renderItem={(label, count, isSelected) => {
                const gamePhaseObject = getGamePhaseObject(label, searchFilterEntities.gamePhases);
                return (
                    <span>
                        {gamePhaseObject.label}
                    </span>
                )
            }}
        />
```

And `gamePhasesDetails` is just a UUID that is matched to the search entry.
With `dataField={['gamePhasesDetails']}` it is not working.

**Resulting in:**
```
{"error":{"root_cause":[{"type":"x_content_parse_exception","reason":"[1:82] [terms] field doesn't support values of type: START_ARRAY"}],"type":"x_content_parse_exception","reason":"[1:82] [terms] field doesn't support values of type: START_ARRAY"},"status":400}
```

**Payload:**
```
{"preference":"gamePhases-filter"}
{"query":{"match_all":{}},"size":0,"aggs":{"gamePhasesDetails":{"terms":{"field":["gamePhasesDetails"],"order":{"_count":"desc"}}}}}
```

**Comment by siddharthlatest** [comment]
@markusguenther 

Since `TreeList` is best used for levels (hierarchy) > 1, and there has to be a clear attribution of parent/child relationships, I think the current restriction on not allowing Array type of fields makes sense.

---

A follow-up question here: When you only have one level as here, would using MultiList or SingleList component instead work?

**Comment by markusguenther** [comment]
Hi we plan to use two levels but already had the issue with one ;)

**Comment by samkio** [comment]
We are facing the same issue. I'm not sure how this works as the "terms" field cannot be an array for aggregations based on the docs?  https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html

The payload would need to be something like (for `dataField:["class.keyword","room.keyword"]`):
```
{"preference":"treeListSensor"}
{"query":{"match_all":{}},"size":0,"aggs":{"class.keyword,room.keyword":{"terms":{"field":"class.keyword","order":{"_count":"desc"}},"aggs":{"room.keyword":{"terms":{"field":"room.keyword"}}}}}}
```

i.e. having a nested aggregation within the aggregator?

**Comment by samkio** [comment]
I can confirm that by intercepting the request and changing it to the above query I was able to get it to render. (Not sure if the doc count is correct).
