### ISSUE TITLE
<ReactiveBase /> url prop cuts the value

### ISSUE THREAD

**Issue by kud** [appbaseio/reactivesearch#206]
**Issue Type:**
BUG

**Description:**

I use my component/url prop like this:

```javascript
      <ReactiveBase
        app="bills,amendments"
        url="https://mydomain.com/api/search/"
      >
```

However, ReactiveSearch cuts the value of my url by `https://mydomain.com` which makes a request like `https://mydomain.com/bills,amendments` which is wrong.

It should do `https://mydomain.com/api/search/bills,amendments`

To fix it, I have done this:

```javascript
      <ReactiveBase
        app="/api/search/bills,amendments"
        url="https://mydomain.com"
      >
```

but it's not obvious in my point of view.

**Reactivesearch version:** `"@appbaseio/reactivesearch": "2.0.0"`

**Anything else:**

URL shouldn't be cut or should accept not only domain name but also path in the url.

**Comment by metagrover** [comment]
Fixed in 2.2.0 🎉
