### ISSUE TITLE
Typescript definition files (.d.ts) not present on >3.39.4

### ISSUE THREAD

**Issue by samkio** [appbaseio/reactivesearch#2069]
Same as https://github.com/appbaseio/reactivesearch/issues/2043 but for the latest version. Is there an error on how this is being published that causes this to happen frequently?

**Issue Type:**
Bug + Enhancement

**Platform:**
Web

**Description:**
I'm trying to use the latest version of reactivesearch in a typescript project.
Despite the documentation, and example provided in the docs, typescript definitions are not available.

**Minimal reproduction of the problem with instructions:**

1. Step: npm install @appbaseio/reactivesearch@latest
2. Step: Check the contents of node_modules/@appbaseio/
3. Step: See that there are no .d.ts files available.

Reactivesearch version: >3.39.4

**Comment by bietkul** [comment]
@samkio You can upgrade to https://github.com/appbaseio/reactivesearch/releases/tag/v3.40.1
