### ISSUE TITLE
Autosuggest include search history

### ISSUE THREAD

**Issue by rgb-panda** [appbaseio/reactivesearch#2072]
**Affected Projects**

React / Vue.JS / React Native

**Is your feature request related to a problem? Please describe.**

Have you considered adding search history to the autosuggest feature of DataSearch/CategorySearch similar to how google does it? It would be really handy

![image](https://user-images.githubusercontent.com/1173031/191831532-3e8adb17-8c31-4693-82be-b9450cebba7b.png)

**Comment by SavvyShah** [comment]
This is possible with [enableRecentSuggestions](https://docs.reactivesearch.io/docs/reactivesearch/v3/search/searchbox/#enablerecentsuggestions) and passing a [config](https://docs.reactivesearch.io/docs/reactivesearch/v3/search/searchbox/#recentsuggestionsconfig). You can checkout the [working example](https://codesandbox.io/s/github/appbaseio/reactivesearch/tree/next/packages/web/examples/SearchBox?from-embed).
