### ISSUE TITLE
CSS classes not correct?

### ISSUE THREAD

**Issue by hilary-L** [appbaseio/reactivesearch#212]
I'm trying to use the latest version of reactivesearch in my react app but I'm having a bit of trouble with the styles. The docs claim that the components should have namespaced css classes - "rbc-datasearch" and so forth. However, when I check out the rendered components in my inspector, all of the CSS classes look more like the type of classes that are generated by something like Styled Components... which makes it really difficult to target if writing styles in something like sass. What's going on?

If I need to do my css in my js to use these components I will, but some extra info on how to hook into the components' use of styled components (or whatever equivalent it's using) would be appreciated.

**Comment by divyanshu013** [comment]
Hi @hilary-L, it seems like you came across an old section in the docs which should have been updated. I've updated it and you should be able to see the latest version now. Thanks for bringing this to out notice 🙂 

Let me know if this helps
Ref https://opensource.appbase.io/reactive-manual/search-components/datasearch.html#styles

**Comment by hilary-L** [comment]
Yes, that helped. Thank you!
