### ISSUE TITLE
TypeError: this.updater.enqueueCallback is not a function

### ISSUE THREAD

**Issue by grinono** [appbaseio/reactivesearch#213]
i'm trying to test the code from. https://opensource.appbase.io/reactive-manual/search-components/datasearch.html
in a instance without react-router-redux (
import { ConnectedRouter } from 'react-router-redux
') it looks to work just fine. But with the router clicking on the search bar breaks the package.

<img width="1437" alt="schermafbeelding 2018-01-17 om 11 51 00" src="https://user-images.githubusercontent.com/4255206/35038986-c62674ec-fb7c-11e7-93bb-b8d1cf1ac0b9.png">

**Comment by divyanshu013** [comment]
Hi @grinono, can you share your code snippet? A github repo or codesandbox would be even better.

You can also use [this codesandbox](https://codesandbox.io/s/github/appbaseio/reactivesearch/tree/dev/packages/web/examples/DataSearch?from-embed) as a starting point

**Comment by grinono** [comment]
issue disappeared after a day working on other aspects. No idea what it was..

**Comment by divyanshu013** [comment]
Awesome, let me know if it happens again 😁
