### ISSUE TITLE
React 17+ support?

### ISSUE THREAD

**Issue by joshua-scott** [appbaseio/reactivesearch#2132]
**Affected Projects**
React

**Library Version:**
3.43.1 (latest)

**Describe the bug**
This package has a dependency `"react-redux": "^6.0.1",`, which in turn has peer dependency `react@"^16.4.0-0"`. This means React 17+ cannot be used, even though React 17 was released over two years ago.

**To Reproduce**
`npm init -y && npm install @appbaseio/reactivesearch react@^17 react-dom@^17 && npm install` will show this warning:

```
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-redux@6.0.1
npm WARN Found: react@17.0.2
npm WARN node_modules/react
npm WARN   react@"^17.0.2" from the root project
npm WARN   10 more (@appbaseio/reactivesearch, @appbaseio/rheostat, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.4.0-0" from react-redux@6.0.1
npm WARN node_modules/@appbaseio/reactivesearch/node_modules/react-redux
npm WARN   react-redux@"^6.0.1" from @appbaseio/reactivesearch@3.43.1
npm WARN   node_modules/@appbaseio/reactivesearch
npm WARN
npm WARN Conflicting peer dependency: react@16.14.0
npm WARN node_modules/react
npm WARN   peer react@"^16.4.0-0" from react-redux@6.0.1
npm WARN   node_modules/@appbaseio/reactivesearch/node_modules/react-redux
npm WARN     react-redux@"^6.0.1" from @appbaseio/reactivesearch@3.43.1
npm WARN     node_modules/@appbaseio/reactivesearch
```

**Expected behavior**
It would be compatible with React updates within a reasonable timeframe.

**Comment by mohdashraf010897** [comment]
Hey 👋  @joshua-scott 

Thanks for raising the issue. We recently incorporated support for React versions > 16, here's a codesandbox that uses **React v18** -> [RS example](https://codesandbox.io/s/github/appbaseio/reactivesearch/tree/next/packages/web/examples/SearchBox?from-embed)

Let know if it helps.
