### ISSUE TITLE
Vue - getCamelCase function breaks u-r-l-params

### ISSUE THREAD

**Issue by indykoning** [appbaseio/reactivesearch#2159]
**Affected Projects**

Vue
**Library Version:** x.y.z

1.33.0-1.33.6
**Describe the bug**

From 1.33.0 onward any filters with URLParams via u-r-l-params set in html templates no longer update the url
**To Reproduce**

Create a filter with urlparams using u-r-l-params and check a filter
**Expected behavior**

The url should be updated with the selected filter
**Screenshots**

**Desktop (please complete the following information):**
 - OS: OSX,Windows,Linux
 - Browser chrome, safari, firefox
 - Version *

**Smartphone (please complete the following information):**
 - Device: *
 - OS: *
 - Browser stock browser, safari, chrome, firefox
 - Version *

**Additional context**

This is caused by the getCamelCase function and the way these variables are named.
https://github.com/appbaseio/reactivesearch/blob/ab321867a47d833514c66464208cba69f29598fc/packages/vue/src/utils/index.js#L128
This getCamelCase function always leaves the first character be, so the result of u-r-l-params would be uRLParams which it cannot find.

This bug was introduced by the PreferencesConsumer it seems
https://github.com/appbaseio/reactivesearch/compare/v1.32.4-vue...v1.33.1-vue#diff-c6feaa767d7c3ebdec295b3057cc949ece9cf3479ea95eac3bf6ec82367b06d9R18

A possible solution would be to lowercase the variables. or rename the variable to be urlParams so url-params would work.

**Comment by SavvyShah** [comment]
Hello. I am not able to reproduce the issue. I found that the URLParams do work as expected. I have made an [example here with multiple values selected](https://0ymz6p.csb.app/?Authors=%5B%22J.D.+Robb%22%2C%22Terry+Pratchett%22%5D). 

Can you answer some questions below regarding your usage:
What filter you are using?
Are you passing prop `:URLParams="true"`?
Where are you passing the lowercase (underscore separated) values?

**Comment by indykoning** [comment]
Hi, I'm sorry i meant to add that this is done via slots from html
e.g. 
![image](https://user-images.githubusercontent.com/15870933/221806743-029d3415-05e0-4673-9734-8bdb2f67827c.png)

Vue is loaded on the `#app` div and our components are loaded from the generated .html file.
So essentially we have NO templates within our Vue files, but solely depend on the vue components for their logic, and use slots handle the templates.

Since the html of our `<multi-list>` component is not hidden away from the html interpreter, the html interpreter will handle it first.
The html interpreter does not support capital letters (is case insensitive), thus transforming it all to lower case
https://www.w3.org/TR/2008/WD-html5-20080610/syntax.html#:~:text=In%20the%20HTML%20syntax%2C%20attribute,attribute%20names%20are%20case%2Dinsensitive.

This is why Vue already does some magic with component names; We can use `<MultiList>` `<multilist>` and `<multi-list>` and it will have the same effect
