### ISSUE TITLE
native: Enhancements / Bugs

### ISSUE THREAD

**Issue by dhruvdutt** [appbaseio/reactivesearch#216]
**Issue Type:**
Enhancements / Bugs

**Description:**
- ~[ ] Rename components~
	- ~SingleDropdownList / MultiDropdownList => SingleList / MultiList~
	- ~SingleDropdownRange / MultiDropdownRange => SingleRange / MultiRange~
- [x] Ignore the bucket key with an empty or whitespace value.
- [ ] Change the dir structure/move sensor components to relevant folders.
    - [ ] Add MultiDropdown<Range,Slider>
- [x] RangeSlider not working.

**Reactivesearch version:** latest

**Comment by metagrover** [comment]
Added RangeSlider component - f2ae670b90e2e18f90cb941eec525a25f11b31b3
