### ISSUE TITLE
No results after upgrading to 3.43.7

### ISSUE THREAD

**Issue by scottroot** [appbaseio/reactivesearch#2173]
**Affected Projects**

React/ Nextjs 13
"react": "^18.2.0",
"next": "^13.1.6",

**Library Version:** x.y.z

"@appbaseio/reactivesearch": "^3.43.7",

**Describe the bug**

Project was working and displaying results for search, but now no results are shown.  In network tab of inspector I can see that results were returned.

**To Reproduce**

Install React with NextJS and ReactiveSearch;
Create Datasearch component and Reactivelist.  Try to render the results with either render, renderItem props or with children. The page is unchanged after searching.
If the loader prop is used, it just remains loading with no change.

**Expected behavior**

Results should populate as they did in previous version, or there should be some change I should read to make to work with any changes in this version.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: IOS and also on Ubuntu
 - Browser Safari, Chrome, and Chrome + Firefox on Ubuntu

**Smartphone (please complete the following information):**

**Additional context**
No errors.  Attempting to console.log the result within render or renderItem props does nothing.  It seems to never reach the point of receiving the response, although I can see it in my browser's inspector.

**Comment by SavvyShah** [comment]
Hey there. I understood your problem as the Searchbox not filtering results when typed in. I'm unable to replicate the issue using a [NextJS example](https://github.com/appbaseio/reactivesearch/tree/v3/packages/web/examples/ssr) we have in our library. 

To run the example you would need to clone the repo and perform below steps:
```
git submodule init
git submodule update
yarn
yarn dev:web
yarn --cwd packages/web/examples/ssr dev
```
Can you compare the usage of the example with your app?
OR
Can you provide an issue example which describes your issue?

**Comment by kasvith** [comment]
Im having the same issue. no results, no errors

**Comment by siddharthlatest** [comment]
@kasvith Can you share a CSB?

**Comment by kasvith** [comment]
@siddharthlatest i ve opened another issue

**Comment by kasvith** [comment]
@siddharthlatest #2183

**Comment by siddharthlatest** [comment]
Closing this issue as it's not reproducible, feel free to add a comment with a CSB here if this is still an issue.

**Comment by kasvith** [comment]
@siddharthlatest this is very much reproducible. check the SB i created on #2183
