### ISSUE TITLE
DynamicRangeSlider not rendering

### ISSUE THREAD

**Issue by WHITE-developer** [appbaseio/reactivesearch#2176]
**Affected Projects**

React

**Library Version:** x.y.z

^3.38.3

**Describe the bug**

The dynamic range slider is not rendering, and no console error is shown.
When loading the same data in the RangeSlider and setting the range manual a slider is getting rendered.

**To Reproduce**

```JS
<DynamicRangeSlider
  componentId="leasePrice"
  dataField="leasePrice"
  includeNullValues
  title="Lease price"
/>
 ```

**Expected behavior**

Dynamic range slider should show up

**Comment by siddharthlatest** [comment]
@WHITE-developer Here's a reference from the docs where DynamicRangeSlider works well: https://codesandbox.io/s/github/appbaseio/reactivesearch/tree/next/packages/web/examples/DynamicRangeSlider?from-embed

> Note: This uses `4.0.0-alpha.2` release, however, it should work for the latest 3.x version as well.

Can you share a CodeSandbox for the same where you see the issue?

**Comment by WHITE-developer** [comment]
Hi @siddharthlatest looks like wrapping everything in `<React.StrictMode>` is what causing the component not to rending
