### ISSUE TITLE
React 18 Support

### ISSUE THREAD

**Issue by kasvith** [appbaseio/reactivesearch#2180]
**Affected Projects**

React

**Is your feature request related to a problem? Please describe.**

This package uses React 16 as a peer dep

**Describe the solution you'd like**

Upgrade to React 18

**Describe alternatives you've considered**

**Additional context**

**Comment by bietkul** [comment]
@kasvith You can use reactivesearch `4.x` which supports React 18.
https://www.npmjs.com/package/@appbaseio/reactivesearch/v/4.0.0-alpha.2

**Comment by kasvith** [comment]
Oh, i got this error with redux

I think you may need to update redux dep

```
.
└─┬ @appbaseio/reactivesearch 4.0.0-alpha.2
  ├─┬ react-redux 6.0.1
  │ ├── ✕ missing peer redux@"^2.0.0 || ^3.0.0 || ^4.0.0-0"
  │ └── ✕ unmet peer react@^16.4.0-0: found 18.2.0
  └─┬ react-day-picker 7.4.10
    └── ✕ unmet peer react@"~0.13.x || ~0.14.x || ^15.0.0 || ^16.0.0 || ^17.0.0"
: found 18.2.0
Peer dependencies that should be installed:
  redux@"^2.0.0 || ^3.0.0 || ^4.0.0-0"
```

**Comment by kasvith** [comment]
@bietkul will it be possible to ditch Redux and use something like Zustand/Jotai/Valtio/Context API ?

Since Redux is no longer recommended i think it would be a good thing to move on

**Comment by ghost** [comment]
> @kasvith You can use reactivesearch `4.x` which supports React 18. https://www.npmjs.com/package/@appbaseio/reactivesearch/v/4.0.0-alpha.2

How can you say that reactivesearch supports React 18, if it depends on outdated react-day-picker v7 which lists React 17 as its highest peer dependency?

reactivesearch literally tells npm that it is intended for React up to version 17 upon installation. Yes, peer dependencies can be ignored, and it **_probably_** will still work, but there are absolutely no guarantees.

**Comment by ghost** [comment]
> @bietkul will it be possible to ditch Redux and use something like Zustand/Jotai/Valtio/Context API ?
> 
> Since Redux is no longer recommended i think it would be a good thing to move on

I am sorry, may I wonder, please, by whom Redux is no longer recommended? I didn't find any information about that neither on Redux docs nor by Dan Abramov.
