### ISSUE TITLE
Not working with Vite Dev Mode

### ISSUE THREAD

**Issue by kasvith** [appbaseio/reactivesearch#2183]
**Affected Projects**

React

**Library Version:** x.y.z

3.43.7

**Describe the bug**

RS connects to ElasticSearch/Appbase without any problem. But there are no results displayed even server sending them correctly.
This only happens in `dev` mode. In production mode it works fine

No errors in console

**To Reproduce**

Stackblitz: https://stackblitz.com/edit/vitejs-vite-s4v3zz?file=src/App.jsx
- Install RS with Vite and React
- Copy example code

**Expected behavior**

- Should display book results in dev mode

**Screenshots**

![image](https://user-images.githubusercontent.com/13379595/219656716-39981df6-77e4-4fdc-a417-d110d65ab050.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

This worked even with Astro well, i don't know why its not working on dev mode

**Comment by kasvith** [comment]
Also treeshaking is not working in vite

I tried direct imports and my js bundle got around 2MB with just this. (only used ReactiveBase, MultiList, DataList etc)
I see EsCharts in the bundle

**Comment by kasvith** [comment]
I opened an issue on Vite
https://github.com/vitejs/vite/issues/12094

It seems this is a problem with 3.43.7 release

@siddharthlatest its the same issue in #2121

**Comment by SavvyShah** [comment]
Hey @kasvith , You can remove `React.StrictMode`. We use certain lifecycle methods that are disabled in StrictMode. Then it would work in `dev`.

**Comment by kasvith** [comment]
Oh, thank you.

@SavvyShah btw is it possible to use v4 with a regular ES server? i tried v4 with React18 but it isn't working with regular ES Servers

**Comment by SavvyShah** [comment]
No. From v4 we don't support regular elasticsearch servers. You have to use elastic server hosted using [reactivesearch](https://www.reactivesearch.io/).
