### ISSUE TITLE
web, native: DatePicker parity

### ISSUE THREAD

**Issue by dhruvdutt** [appbaseio/reactivesearch#225]
**Issue Type:**
Bug

**Description:**
Currently, we're supporting `initialMonth` prop in web version of DatePicker and the same prop is named `startDate` in native. We need to finalize one prop name and replicate it across both platforms. 

[Update] `initialMonth` would be used across both platforms.

- [x] Update native DatePicker
- [x] Update web docs, add `initialMonth`
- [x] Update native docs, add `initialMonth`

**Reactivesearch version:** latest

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by divyanshu013** [comment]
Added in both native and web docs
