### ISSUE TITLE
Add loader support

### ISSUE THREAD

**Issue by divyanshu013** [appbaseio/reactivesearch#227]
**Issue Type:**

Enhancement (Both web and native)

**Description:**

We should add support for `loader` prop in components which fetch data asynchronously. This sometimes causes the components to appear a bit after the entire page has loaded and push the content which looks bad IMO.

**Minimal reproduction of the problem with instructions:**

Try any app built with reactivesearch (say [gitxplore-app](https://appbaseio-apps.github.io/gitxplore-app/)) and notice that the filters pop in after the UI has loaded. Throttling the network should also help in replicating the issue.

**Reactivesearch version:** x.y.z

2.2.0

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

All

**Comment by siddharthlatest** [comment]
- [ ] Add loader support for ReactiveComponent. (Request reference: https://gitter.im/appbaseio/reactivesearch?at=5b5b8c8f17c942036b79dfc8)
