### ISSUE TITLE
native: Inner styles

### ISSUE THREAD

**Issue by dhruvdutt** [appbaseio/reactivesearch#233]
**Issue Type:**
Enhancement

**Description:**
Support inner styles in native similar to `innerClass` prop in web.
```
{
    "inputElement": {styleObject},
     ... other inner elements
}
```

**Reactivesearch version:** latest

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by metagrover** [comment]
`innerStyle` and `innerProps` are now supported for targeted customisations of inner-components 🎉
