### ISSUE TITLE
Multi MulltiList selecting problem

### ISSUE THREAD

**Issue by fones** [appbaseio/reactivesearch#235]
**Issue Type:**
BUG

**Description:**
When got the same value in two or more MultiLists, selecting one in any MutliList, always selects the value in the first MultiList.

**Screenshots:**
![image](https://user-images.githubusercontent.com/2134294/35486741-ba06ece2-0472-11e8-9037-dbf167bc3799.png)

**Minimal reproduction of the problem with instructions:**
Two MultiLists with at least one the same value inside both of them.

**Reactivesearch version:** 2.2.0

**Browser:** all

**Anything else:** nope

**Comment by metagrover** [comment]
Released in `v2.2.1` 🎉
