### ISSUE TITLE
MultiList and MultiDataList components have issues with filtering the search results

### ISSUE THREAD

**Issue by mrtinkz** [appbaseio/reactivesearch#243]
**Issue Type:**

bug
**Description:**

MultiList and MultiDataList components have issues with filtering the search results. Or at least I think they do.

The MultiList does not show up on the screen and does not throw any errors, I am guessing it's not being rendering properly or has issues connecting to es to get the data but does not report any issues.

The MultiDataList on the other hand is rendered on the screen with the user provided data but does not bind well with the DataSearch component and the ResultList components, though i can see the filters being applied in the SelectedFilters looks like the result list does not apply the filters as needed, which results in showing 0 records.

The combination of the MultiList/MultiDataList with DataSearch and ResultList does not fetch any records, so far I got filtering working only with the DataSearch.

I had my doubts that I was not using the correct configuration but I doubt that, any help would be great, thank you.

```
 <ReactiveBase app="company" 
            url="http://localhost:9200" 
            type="data">
```

```
<MultiList
                    componentId="categories"
                    dataField="type.raw"
                    title="Sectors"
                    queryFormat="and"
                    react={{
                      and: 'search',
                    }}
                    URLParams
                    showSearch={false}
                    filterLabel="Sectors"
                  />
```

```
<MultiDataList
                    componentId="sector"
                    dataField="type.raw"
                    data={[
                      {
                        label: "Finance",
                        value: "finance"
                      },
                      {
                        label: "Technology",
                        value: "technology"
                      }
                    ]}
                    title="Sector"
                    queryFormat="and"
                    react={{
                      and: 'search',
                    }}
                    URLParams
                    showSearch={false}
                  />
```

```
<DataSearch
                    title="Data Search"
                    dataField={[
                      "name",
                      "name.search",
                      "type",
                      "type.raw"
                    ]}
                    categoryField="name.raw"
                    componentId="search"
                  />
```

```
<ResultList
                    componentId="SearchResult"
                    dataField="name"
                    size={10}
                    onData={this.onData}
                    className="result-list-container"
                    pagination
                    react={{
                      and: ["categories", "sector", "search"]
                    }}
                  />
```
**Screenshots:**

**Minimal reproduction of the problem with instructions:**

**Reactivesearch version:** 2.2.1

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**

**Comment by mrtinkz** [comment]
I guess, I am doing something wrong, I picked up an example for MultiDataSearch [here](https://codesandbox.io/s/github/appbaseio/reactivesearch/tree/dev/packages/web/examples/MultiDataList?from-embed) this works as is, but when i try to change the field in MultiDataSearch from 							dataField="group.group_topics.topic_name_raw.raw" to dataField="reason" which has Yes/No and tried to filter the results which did not give me any results. Since the examples are working I guess this is not a bug but more of a question.

**Comment by mrtinkz** [comment]
Odd, the MultiList exampls work but the moment I plug it into my local es it doesn't even show up, any ideas what am I doing wrong?

**Comment by metagrover** [comment]
There could be an issue with the mappings of your MulitList's field. Check console, you should see errors related to failed aggregations query. If not, probably there is no data in that field, so kindly check that as well.

The MultiList won't show up when there is no data. On the other hand, it will show an error in browser console if the aggregation query fails.

**Comment by siddharthlatest** [comment]
@mrtinkz Can you share your mapping object?

**Comment by mrtinkz** [comment]
@metagrover  you are right, It came down to that, I wasn't seeing any errors in the browser console but the es was reporting the errors. @siddharthlatest  thanks, i will close this one. Appreciate your time.
