### ISSUE TITLE
How can I add element in initial Loader props??

### ISSUE THREAD

**Issue by ashwini987** [appbaseio/reactivesearch#250]
**Issue Type:**
[Enhancement]

**Description:**
In Version 1, I can use initial-Loader props which value I provide as a string.
Now I want to add spinner or Loader instead of string value.
How can I add extra element in initial-Loader.
And in Version 2 no such a props that work as a initial-loader.

**Screenshots:**
![download](https://user-images.githubusercontent.com/31088567/35899988-88c8cc6a-0bf5-11e8-8031-da8746144315.png)

**Reactivesearch version:v1/v2

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by divyanshu013** [comment]
Hi @ashwini987, in v2 right now the `loader` support is only available in the result components. We'll be adding the support in other components soon. Related issue https://github.com/appbaseio/reactivesearch/issues/227
