### ISSUE TITLE
Feature Request: Optional prop for a clear button on text/search components.

### ISSUE THREAD

**Issue by davidklebanoff** [appbaseio/reactivesearch#255]
**Issue Type:**
Enhancement

**Description:**

![image](https://user-images.githubusercontent.com/7867074/36059902-d0328dd0-0df2-11e8-98ba-b50107ac415b.png)

Add a prop on the  TextField, DataSearch, and CategorySearch components which adds a clear button that clears all the text in the text input when clicked (and re-runs a search when appropriate). Similar to the [HTML 5 clear button](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/search) that would show for some browsers if type="search".

**Example Documentation:**

- **showClear** Boolean [optional] whether to display a clear or custom icon in the input box. Defaults to false.
- **clearIcon** HTML [optional] displays a custom clear icon instead of the default **X**

**Comment by divyanshu013** [comment]
Thanks for contributing @davidklebanoff @davkap92. We'll roll this out in the coming release 💛
