### ISSUE TITLE
FeatureRequest: The ability to have multiple sorts per sortOption

### ISSUE THREAD

**Issue by davidklebanoff** [appbaseio/reactivesearch#256]
**Issue Type:**
Enhancement

**Description:**
My apologies if this already exists in some way; if it does I could not find it.

I'm looking for a way to have more advanced sort options. Specifically, the ability for a _sortOption_ to support multiple sorts, executed in the order declared.

For example, suppose we wanted two search options, **Best Match** which sorts by the relevance score, and **Rating** which sorts by the rating field and secondarily sorts by the relevance score.

Here's a crude mockup:
```jsx
<ResultCard
    react={{
        "and": ["PriceFilter", "SearchFilter"]
    }}
    onData={this.onData}
    sortOptions={[
        {
            label: "Best Match",
            dataField: "_score",
            sortBy: "desc"
        },
        {
            label: "Rating",
            and: {[
                {
                    dataField: "rating",
                    sortBy: "desc"
                },
                {
                    dataField: "_score",
                    sortBy: "desc"
                }
            ]}
    }]
/>
```

This feature request applies to all the result components: **ResultList**, **ResultCard**, and **ReactiveList**.

[ElasticSearch sort docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-sort.html)

**Comment by metagrover** [comment]
This is pretty interesting. Thoughts @siddharthlatest?

**Comment by davidklebanoff** [comment]
Bump. @siddharthlatest. :)

**Comment by metagrover** [comment]
How about a consistent structure like this:

```
sortOptions={[
        {
            label: "Best Match",
            sort: { order: "desc", dataField: "_score" },
        },
        {
            label: "Rating",
            sort: [
                { order: "desc", dataField: "_score" },
                { order: "desc", dataField: "rating" },
            ],
        },
}}
```

**Comment by davidklebanoff** [comment]
@metagrover That looks great to me!

**Comment by siddharthlatest** [comment]
@davidklebanoff Imo, doing something like this breaks the current apps that use `sortOptions` prop. Also, this still misses out certain things: mode, geo_distance sorting, etc. options that ES's sort DSL offers.

One solution (that already works) here is to use the `defaultQuery` and pass the appropriate `sort` query to it when the dropdown UI selection changes. This offers a no compromise sorting DSL with some trade-off in having to write a dropdown UI.

**Comment by axeff** [comment]
@siddharthlatest When I try to put my geo_distance sorting into the setQuery (I'm using ReactiveComponent), the sort part is magically cut out.
Query looks like this in my code but if I 
`query = {
  from: 0,
  size: 10,
  query: {
    bool: {
      filter: {
        geo_distance: {
          distance: '300km',
          location: [
            lon,
            lat,
          ],
        },
      },
    },
  },
  sort: {
    _geo_distance: {
      location: {
        lat,
        lon,
      },
    },
  },
};`

But if I look into the _msearch headers it is missing:
`{
  "query": {
    "bool": {
      "must": [
        {
          "bool": {
            "must": [
              {
                "bool": {
                  "filter": {
                    "geo_distance": {
                      "distance": "300km",
                      "location": [
                        8.8311195373535,
                        47.936405749046
                      ]
                    }
                  }
                }
              }
            ]
          }
        }
      ]
    }
  },
  "size": 10
}`

I really need _geo_distance to work. Is there any other way to get this done?

**Comment by axeff** [comment]
I ended up writing my query using axios and not use ReactiveSearch. But my use case will become more complex soon and I would really like to get back to Reactivesearch on Native.

**Comment by metagrover** [comment]
You can always use `ReactiveComponent` for your custom needs until we figure out an implementation for this as a part of the library. 

[Find relevant docs here](https://opensource.appbase.io/reactive-manual/advanced/reactivecomponent.html).

**Comment by axeff** [comment]
Tried this as well. See the comment above. When using ReactiveComponent with setQuery() the part where I insert `sort` will not be in my Request Payload.

**Comment by metagrover** [comment]
Oh then it seems like a bug, I will check on this. Thanks for bringing this up.

**Comment by axeff** [comment]
@metagrover I updated a [codesandbox](https://codesandbox.io/s/8o3v422) I once created. As far as I can see there are two POST's in network panel of which the first does have my query **including sort**, then there is a second one with query:all which will be rendered in ResultCard.

**Comment by metagrover** [comment]
Not sure if I understand that but if you can update the `ResultCard`s defaultQuery dynamically, then the component will fire the updated queries as you change the `defaultQuery` prop.

**Comment by bigscratcher** [comment]
Can you add example here, how to sort by `_geo_distance`. I am struggling with it some time.
I can't add it in `customQuery` in `DataSearch` or anywhere else, it needs to come after `query: {}` part as separate section and to get the following in _msearch header:
`{
    "from": 0,
    "size": 10,
    "query": {
        "match_all": {}
    },
    "sort": {
        "_geo_distance": {
            "pin": "48.1362, 11.5729",
            "order": "asc",
            "unit": "km"
        }
    }
}`

**Comment by davidkong0987** [comment]
Would love to revive this!

**Comment by danielnolde** [comment]
This would be a very worthwhile addition, i agree, and the issue is still current.

**Comment by arpithparikh** [comment]
I agree This would be a very worthwhile addition, i agree, and the issue is still current.

 I like this propose structure 👍 


sortOptions={[
        {
            label: "Best Match",
            sort: { order: "desc", dataField: "_score" },
        },
        {
            label: "Rating",
            sort: [
                { order: "desc", dataField: "_score" },
                { order: "desc", dataField: "rating" },
            ],
        },
]}
