### ISSUE TITLE
Clarify use of map components

### ISSUE THREAD

**Issue by davidklebanoff** [appbaseio/reactivesearch#260]
**Issue Type:**
bug?

**Description:**
The relationship between ReactiveSearch and ReactiveMaps is a bit unclear to me and perhaps to others as well. The map components appear to be documented in the [ReactiveSearch manual](https://opensource.appbase.io/reactive-manual/map-components/geodistanceslider.html), however they don't seem to be part of the [ReactiveSearch](https://github.com/appbaseio/reactivesearch/tree/dev/packages/web/src/components) code base. This was unexpected. I initially attempted to import `PlacesSearch` alongside `CategorySearch`, attempting to follow along with guidance in the ReactiveSearch manual, when things blew up and I noticed something was amiss. Perhaps documentation should be updated to clarify things, or maybe the projects need to be re-orged a bit?

**Update**: Ah, I just discovered **ReactiveMaps Quickstart**, which helps a bit... but I only discovered it because I had done a search in the manual search box. I'm not sure it's linked to from anywhere. Also directly linking to the page returns a 404? https://opensource.appbase.io/getting-started/reactivemaps.html

**Comment by metagrover** [comment]
Currently, Reactivemaps and Reactivesearch are on two different architectures. We have done a major re-write with ReactiveSearch and will soon get to Reactivemaps as well. We will reflect this properly in our docs and fix the broken documentation links as well 😅 . Thanks for reporting!

@divyanshu013 can you take this up and fix the docs?

**Comment by davidklebanoff** [comment]
Got it! That makes sense. I'm sure you've already considered it, but if not - consistent styling across both projects would be awesome. ReactiveMaps components use of Materialize make them clash visually with ReactiveSearch.

**Comment by metagrover** [comment]
Yes, we will be getting rid of all the inconsistencies with the styling and core transaction management logic. `v2` of reactivemaps will have identical styling and should work seamlessly with reactivesearch.

**Comment by divyanshu013** [comment]
Reactive maps quickstart is updated at https://opensource.appbase.io/reactive-manual/getting-started/reactivemaps.html

Map components at https://opensource.appbase.io/reactive-manual/map-components/geodistanceslider.html
