### ISSUE TITLE
Add sortOptions to URLParams

### ISSUE THREAD

**Issue by Guazi** [appbaseio/reactivesearch#261]
Issue Type:
enhancement

Description:
We should add sort options to the URL Params so a user can land on the results page sorted in a specific manner.

**Comment by ThunderDev1** [comment]
This would be a very helpful feature, any chance of seeing this in a future release @metagrover ?

**Comment by metagrover** [comment]
@bietkul can you take a look at this?

**Comment by stevewillard** [comment]
Anyone know if there is a workaround to get this behavior? Or, if there was any progress to add it?

**Comment by atindersingh67** [comment]
Any news on this , Or someone created any custom component to handle this.

**Comment by BobWez98** [comment]
I need this too, any updates?

**Comment by bietkul** [comment]
The workaround is to use the [ReactiveComponent](https://docs.appbase.io/docs/reactivesearch/v3/advanced/reactivecomponent/). Set the `URLParams` to true, and define the `customQuery` to apply the default sort. Use the `setQuery` method to change the query when sort option gets changed. You should set the `value` property as the sort value in the `setQuery` method.
Now, depend on the `ReactiveComponent` using the `react` prop in `ReactiveList`.

**Comment by BobWez98** [comment]
Thanks for the workaround. Could you show an example of a customQuery with a sorting prop?
