### ISSUE TITLE
RatingsFilter URLParams is not working

### ISSUE THREAD

**Issue by davidklebanoff** [appbaseio/reactivesearch#265]
**Issue Type:**
bug

**Description:**
When setting the `RatingsFilter` component's `URLParams` property to `true`, the parameters are placed in the URL. Perfect! But if go to the page with the params in the URL, the rating filter is not applied. 

**Minimal reproduction of the problem with instructions:**

```jsx
<RatingsFilter
  componentId="ratingsSensor"
  dataField="ratings"
  data={[
    {"start": 4, "end": 5, "label": "4 & up"},
    {"start": 3, "end": 5, "label": "3 & up"},
    {"start": 1, "end": 5, "label": "All"}
  ]}
  URLParams={true}
/>
```

**Reactivesearch version:**
2.2.1

**Comment by divyanshu013** [comment]
This should be out in the next release (v2.3.0)
