### ISSUE TITLE
Add support for unrated results in RatingsFilter

### ISSUE THREAD

**Issue by davidklebanoff** [appbaseio/reactivesearch#267]
**Issue Type:**
enhancement

**Description:**
Sometimes search results may have no ratings. On the `RatingsFilter` component, it would be nice to have a boolean option that indicates whether unrated results should be included in a filter. The property could be set at the component level, but setting it at the `data` property level would allow more granularity.

The option could indicate whether to include a result when the dataField is `undefined` or 0.

Something like:

```jsx
<RatingsFilter
  componentId="ratingsSensor"
  dataField="ratings"
  data={[
    {"start": 4, "end": 5, "label": "4 & up"},
    {"start": 3, "end": 5, "label": "3 & up"},
    {"start": 1, "end": 5, includeUnrated: true, "label": "All"}
  ]}
/>
```

**Comment by jyash97** [comment]
This would be included in the next release ✨ . Fixed here #1003
