### ISSUE TITLE
Add a <span> and innerClass to counts within List Components

### ISSUE THREAD

**Issue by davidklebanoff** [appbaseio/reactivesearch#268]
**Issue Type:**
enhancement

**Description:**
Currently the counts shown on list components, such as `MultiList`, `SingleList`, and others are part of the same HTML element as the label, and thus cannot be styled separately. I think the counts should be in a `<span>` element that can optionally be given a class via `innerClass`.

**Comment by divyanshu013** [comment]
The next release v2.3.0 will introduce the support for an additional `innerClass` with key `count` which will be applicable for `Single/MultiDropdownList` and `Single/MultiList` components. Thanks for your feedback @davidklebanoff 🍻
