### ISSUE TITLE
E-commerce app: styling

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivesearch#27]
- [ ] Flex layout when the Result Card Items have only two elements in a row.

![](https://i.imgur.com/8XZ2CgO.png)

**Comment by corysimmons** [comment]
If you're using `justify-content: space-between` then fixing this is nearly impossible.

Reduced case: https://codepen.io/corysimmons/pen/JWgevb?editors=1100

I fought with this for weeks trying to turn flexbox into a grid system.
