### ISSUE TITLE
Add showCount property to SingleDataList and MultiDataList

### ISSUE THREAD

**Issue by davidklebanoff** [appbaseio/reactivesearch#270]
**Issue Type:**
enhancement

**Description:**
Just like SingleList and MultiList, SingleDataList and MultiDataList could make use of a showCount property. They can update asynchronously so the counts will only appear when loaded without disrupting the "static" nature of of the DataList labels. There can be a separate option on whether labels that return a 0 count should be hidden or not.

This can be especially useful as an alternative to SingleList and MultiList because sometimes the aggregation counts are quite slow, when compared to the actual search query. By using a hybrid approach of static label filters with dynamic counts, users don't have to wait for the counts to load before receiving search results or filter options.

**Comment by davidklebanoff** [comment]
This seems highly related to #270 and they probably should be addressed at the same time, or combined into one issue.

**Comment by siddharthlatest** [comment]
Here, we can use the `include` key to fetch the count for the terms set in SingleDataList / MultiDataList components.

Reference: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#_filtering_values_with_exact_values
