### ISSUE TITLE
ToggleButton - setting multiselect=false causes onValueChange to fire twice on button clicks. May also cause infinite loops when changing state.

### ISSUE THREAD

**Issue by davidklebanoff** [appbaseio/reactivesearch#273]
**Issue Type:**
bug

**Description:**
When using the ToggleButton component, setting the property `multiSelect={false}` causes the onValueChange event to fire twice when a button is toggled. Didn't investigate other events or components.

**Minimal reproduction of the problem with instructions:**
https://codesandbox.io/s/n0rkvyw89j

**Reactivesearch version:** x.y.z
2.2.1

**Browser:**
Tested in Chrome, probably effects all browsers.

**Comment by davidklebanoff** [comment]
Not sure if this is caused by the same issue or not, but adjusting the state based on onValueChange events causes an infinite loop.

Example:
https://codesandbox.io/s/wy396r19zl

**Comment by divyanshu013** [comment]
Thanks for reporting the issue @davidklebanoff, this should be out in the next release 😸
