### ISSUE TITLE
Add a scroll target option to pagination

### ISSUE THREAD

**Issue by Guazi** [appbaseio/reactivesearch#274]
Issue Type:
enhancement

Description:
Currently, upon changing pages in ReactiveList, the page scrolls to the top of the page. We should add an option to the pagination setting to have it either not scroll or set a scroll target manually.

**Comment by metagrover** [comment]
I think the best approach here would be to support an event handler `onPageChange`, which when set, will not scroll the page and let the user customise its behavior.

**Comment by metagrover** [comment]
Added related documentation [here](https://opensource.appbase.io/reactive-manual/result-components/resultlist.html#props) and this enhancement should be out in `v2.3.0` 🎉
