### ISSUE TITLE
Ability to set highlight context size (fragment_size)

### ISSUE THREAD

**Issue by ngsalmon** [appbaseio/reactivesearch#277]
**Issue Type:** Enhancement

**Description:** An option to set the highlight fragment_size on search components where highlighting is supported

**Screenshots:**

**Minimal reproduction of the problem with instructions:**

**Reactivesearch version:** x.y.z

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**

**Comment by divyanshu013** [comment]
The search components now support a `customHighlight` prop where you can return your custom highlight settings object. Resolved in #285.

This will be out in the upcoming release v2.3.2. More info available in the [docs](https://opensource.appbase.io/reactive-manual/search-components/datasearch.html#props).
