### ISSUE TITLE
Access problem to my Elastic cluster

### ISSUE THREAD

**Issue by ymzoughi** [appbaseio/reactivesearch#279]
**Issue Type:**
Bug

**Description:**
I tried to connect Reactive Search to my Elastic cluster with ReactiveBase components, but the problem is that I have an extra "/" in the url

**Screenshots:**
<img width="137" alt="capture d ecran 2018-02-22 a 10 49 37 am" src="https://user-images.githubusercontent.com/5389466/36531443-2922ad24-17be-11e8-9d6b-023873a90891.png">

**Reactivesearch version:** 
V2

**Browser:** 
all

**Comment by metagrover** [comment]
It seems like you're missing `app` prop here maybe. What have you set `ReactiveBase` component props here?

`app` should be the index of your Elasticsearch cluster.

**Comment by ymzoughi** [comment]
Hello @metagrover, thank you for the replay
There is my config in the ReactiveBase componenents

```
<ReactiveBase
        url="http://localhost:11000/ads"
        app="autos">
        <CategorySearch
            componentId="searchbox"
            dataField="name"
            categoryField="brand.raw"
            placeholder="Search for cars"
        />
      </ReactiveBase>
```

**Comment by siddharthlatest** [comment]
@ymzoughi I can see the extra slash, but does that affect a query in any way? I am able to run /_search against an ES cluster with an extra slash just fine.

**Comment by ymzoughi** [comment]
@siddharthlatest it works on servers but not others

**Comment by siddharthlatest** [comment]
@ymzoughi Can you elaborate? Not sure I understand.

**Comment by ymzoughi** [comment]
@siddharthlatest it works with my production cluster, but not with the local one

**Comment by siddharthlatest** [comment]
@ymzoughi What version of Elasticsearch does your local cluster run?

**Comment by ymzoughi** [comment]
@siddharthlatest ES6

**Comment by siddharthlatest** [comment]
@ymzoughi I am not able to replicate the issue, tried with v6.2.2. If you can share the response or logs from ES, I can tell better. But my hunch is that the extra slash isn't causing the issue.

**Comment by siddharthlatest** [comment]
**Update:** I am able to replicate the issue when there is an extra slash after the type name.

@metagrover This happens when a type is present in the request and the request URI looks like `/app/type//_search...` when you access a raw Elasticsearch URI. Most middlewares should be able to correct the URI which explains why it's not happening on appbase.io service and @ymzoughi's production server.

**Comment by metagrover** [comment]
Got it! Thanks for the details. Will fix this shortly 👍

**Comment by metagrover** [comment]
Fixed in the latest appbase-js release and should be out in `v2.3.0` :tada:
