### ISSUE TITLE
ResultList and ResultCard components: Pagination Prop Changes

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivesearch#28]
- [x] Change `showPagination` prop to `pagination`.

We will also include a CSS style class for the same, `rbc-pagination-active` and `rbc-pagination-inactive`.

Reference: https://github.com/appbaseio/reactivebase/issues/76.

**Comment by metagrover** [comment]
Fixed here: ad224200f04a8f84c296a121db8920f338767787

Also synced `ResultCard` and `ResultList` with`ReactiveList`
