### ISSUE TITLE
Update Count Dynamically w/ MultiSearch

### ISSUE THREAD

**Issue by rzsm93** [appbaseio/reactivesearch#281]
**Issue Type:**
enhancement

If using > 1 multisearch component, update the document count dynamically as you select filters
**Platform:**
ReactiveSearch 

**Description:**
Document/Result count should update dynamically based on selected filters

**Comment by divyanshu013** [comment]
Hi @rzsm93, can you post an example using CodeSandbox or share a link to the repository? Which components are you using here? It's possible to update the results dynamically using [react](https://opensource.appbase.io/reactive-manual/advanced/react.html) prop

You may use [this](https://codesandbox.io/s/github/appbaseio/reactivesearch/tree/dev/packages/web/examples/TextField?from-embed) codesandbox link as a starter

**Comment by rzsm93** [comment]
Ok - this makes sense. Did not realize react prop could be used in search/range/list components the same was as it's used in results component.

**Comment by divyanshu013** [comment]
No problem, will clarify this in docs :)
