### ISSUE TITLE
In DynamicRange Silder Tooltip is not present in V2.0.0 

### ISSUE THREAD

**Issue by ashwini987** [appbaseio/reactivesearch#284]
**Issue Type:**
 enhancement' issue. 

**Platform:**
Web

**Description:**
In DynamicRange Silder Tooltip is not there, So how can user know that which range is selected ??? 
In V1 version tooltip is present. but not in v2.0.0

**Screenshots:**
![dynamic-tooltip](https://user-images.githubusercontent.com/31088567/37074003-5b2d51fc-21f0-11e8-9254-c1e50c3a97a6.png)

**Reactivesearch version:** 
https://github.com/appbaseio/reactivesearch/releases/tag/v2.0.0  ------> I m using this version right now 

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by divyanshu013** [comment]
We use `rheostat` from `airbnb` for the slider component. Currently there is no functionality to show tooltips in rheostat. One way to add this functionality would be to send a PR to `rheostat`. [Here](https://github.com/airbnb/rheostat/issues/134) is the related issue.

Another alternative if someone wishes to show the current slider positions would be to expose a prop which returns the current values of the slider (before running the query) and use them in the UI just like airbnb does. Ref-

![](https://screenshots.firefox.com/RGhkI0Ivainy4v7C/www.airbnb.co.in)

**Comment by metagrover** [comment]
I think the solution mentioned in [this comment](https://github.com/airbnb/rheostat/issues/134#issuecomment-358129687) seems relevant. We will try it out internally, and if it works, we will roll out an updated for this.

Will keep the progress posted here!

**Comment by ashwini987** [comment]
for this issue, i am using  **"title" : y[n]**  in Build File(index.js), so atleast user know price not on current slider positions but at steady position.
