### ISSUE TITLE
Feature Request: support making nextPage, prevPage, and setPage functions public on reactiveList.

### ISSUE THREAD

**Issue by lopper** [appbaseio/reactivesearch#287]
**Issue Type:**
enhancement

**Description:**
It would be nice to be able to programmatically move to a particular page of the search result. Right now, the  paging options can only be evoked by user input. Is there a way to expose the nextPage, prevPage, and setPage functions of the reactiveList?

**Comment by lopper** [comment]
@divyanshu013 are there any thoughts on this enhancement?

**Comment by metagrover** [comment]
For this use-case, we will support the following API:

- `currentPage` prop - which can be used to set and update on the current page of the result component.
- `onPageChange` prop - will be enhanced to expose the current page number on page change.

**Comment by lopper** [comment]
@metagrover nice. I will try to make a pull request for this change. One question, what do you think should hold precedent, the currentPage prop or the page query parameter when the component is first loaded?

**Comment by siddharthlatest** [comment]
@lopper iirc, we give precedence to the URLParam value if set on initial load (a user may be opening a saved URL from before), and thereafter the value set via the prop (as it may be programmatically changing)

**Comment by lopper** [comment]
@siddharthlatest how do you keep track of the state of whether the component has finished initial load in the mapStateToProps? 

The currentPage property current reads it's value from the store. Here is the current code.
```
currentPage: (
		state.selectedValues[`${props.componentId}-page`]
		&& state.selectedValues[`${props.componentId}-page`].value - 1
	) || 0,
```
I'm assuming we need to do something like.

```
currentPage: (
		!initLoad && state.selectedValues[`${props.componentId}-page`]
		&& state.selectedValues[`${props.componentId}-page`].value - 1
	) || this.props.currentPage || 0,
```
I'm thinking the only way to track an initLoad value would be to create another reduced in reactiveCore. However, I don't think adding another reducer to accomplish this would be very good. It would add a lot more code.

However, if we make the requirement so that the URLParam does not hold precedence, then the change will be much simpler. 

I can make the following change.
```
currentPage: (
	props.currentPage || state.selectedValues[`${props.componentId}-page`]
	&& state.selectedValues[`${props.componentId}-page`].value - 1
) || 0,
```
As long as the currentPage is not set as a prop on the component on initial load, the URLParam will be used to set the currentPage. Then, after initial load, the user can start setting the currentPage prop on the results component, which will allow changing the current page. 

Any thoughts on this?

**Comment by metagrover** [comment]
I can answer that for you. If you look at the structure of any component, you'd find that we check for the selected/default value (giving more preference to the selected value i.e. value coming from the URL at that point of time) [before the component mounts](https://github.com/appbaseio/reactivesearch/blob/dev/packages/web/src/components/list/SingleList.js#L49-L53), and we do something similar in the `componentWillReceiveProps` to check for the dynamic [changes on the desired prop](https://github.com/appbaseio/reactivesearch/blob/dev/packages/web/src/components/list/SingleList.js#L89-L93).

You can use the similar architecture to implement the enhancement for `currentPage` in this case.
