### ISSUE TITLE
Module parse failed node_modules/rheostat/src/Slider.jsx

### ISSUE THREAD

**Issue by alankar-anand** [appbaseio/reactivesearch#289]
**Issue Type:**
bug
**Platform:**
Web
**Description:**
When trying to use reactivebase in my project I get this error.

You may need an appropriate loader to handle this file type.
```
| class Button extends React.Component {
|   render() {
|     return <button {...this.props} type="button" />;
|   }
| }
    at eval (Slider.jsx:1)
    at Object../node_modules/rheostat/src/Slider.jsx (reactBoilerplateDeps.dll.js:23162)
    at __webpack_require__ (reactBoilerplateDeps.dll.js:21)
    at eval (RangeSlider.js:17)
    at Object../node_modules/@appbaseio/reactivesearch/lib/components/range/RangeSlider.js (reactBoilerplateDeps.dll.js:535)
    at __webpack_require__ (reactBoilerplateDeps.dll.js:21)
    at eval (index.js:86)
    at Object../node_modules/@appbaseio/reactivesearch/lib/index.js (reactBoilerplateDeps.dll.js:679)
    at __webpack_require__ (reactBoilerplateDeps.dll.js:21)
    at eval (index.js from dll-reference reactBoilerplateDeps?5e4a:1)
```

I'm using React Boilerplate.
The issue and possible solution can be found under rheostat github issues: 
https://github.com/airbnb/rheostat/issues/98

**Minimal reproduction of the problem with instructions:**
I installed the project using the following docs: 
https://opensource.appbase.io/reactive-manual/getting-started/reactivesearch.html#step-0-install-reactivesearch

**Reactivesearch version:** 2.3.2

**Browser:** Version 64.0.3282.186 (Official Build) (64-bit)

**Comment by divyanshu013** [comment]
Hi @alankar-anand, it seems like an issue with webpack config of `react-boilerplate` with handling `.jsx` file. You may try this [example](https://github.com/appbaseio/reactivesearch/tree/dev/packages/web/examples/RangeSlider) from the repo where we already have a sample webpack config.

**Comment by alankar-anand** [comment]
Hi @divyanshu013, Is it possible to use reactivesearch with react-boilerplate ?

**Comment by divyanshu013** [comment]
I think it should be possible. You might need to play around with the webpack settings `react-boilerplate` comes by default. In the [example repo](https://github.com/appbaseio/reactivesearch/tree/dev/packages/web/examples/RangeSlider) we are using [this](https://github.com/appbaseio/reactivesearch/blob/dev/packages/web/examples/RangeSlider/webpack.config.js) webpack config. Can you check if it works?

**Comment by divyanshu013** [comment]
Hey @alankar-anand we're now using the commonjs module for `rheostat` from `/lib/Slider`. This will be out in the next patch release v2.3.3 shortly.
