### ISSUE TITLE
Feature: Add onAllData prop support for ReactiveComponent

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivesearch#290]
**Issue Type:**

Enhancement

**Platform:**

Both

**Description:**

The current way a ReactiveComponent passes data back is via context props to it's inner component. This is great if you are adding a UI component, but slightly cumbersome if you are using `ReactiveComponent` to run a custom query where no UI is needed.

Also, we should deprecate **DataController** component as all the use-cases it supports can be better supported via ReactiveComponent.

**Comment by metagrover** [comment]
`onAllData` callback here now provides `hits` and `aggregations` as params.

**Comment by siddharthlatest** [comment]
@metagrover Can you also update the docs?

**Comment by metagrover** [comment]
yes, I'm working on it!

**Comment by metagrover** [comment]
Added here: https://github.com/appbaseio/reactive-manual/commit/8e9a00507a32c952c7ce303fe959bf3606ee51de
