### ISSUE TITLE
Feature: Support aggregating on missing value for the list components

### ISSUE THREAD

**Issue by lopper** [appbaseio/reactivesearch#291]
**Issue Type:**
enhancement

**Description:**
It would be nice to have a way to specify that the `SingleList`, `MultiList`, `SingleDropdownList`, and `MultiDropdownList` should return an entry for items that do not have a value.  Specifically, I want to be able to add the "missing" property to the terms aggregation query.  

We could add the following two properties to each of the components listed above.
`showMissing:<boolean>`
`missingLabel:<string>`

**Comment by davidklebanoff** [comment]
This is somewhat related to discussions in #269.

**Comment by davidklebanoff** [comment]
@lopper et al. - perhaps a means to disable the the missing items? So they are shown but not interactive, seeing as clicking one would be a no-op.

**Comment by lopper** [comment]
@davidklebanoff I think you have misinterpreted what I would like to do. Let me give an example. 

If I have the following 5 items in elasticsearch. 
```
{_id: 1, tag : 'apple'}
{_id: 2, tag : 'orange'}
{_id: 3, tag : 'orange'}
{_id: 4, tag : 'grape'}
{_id: 5 }
```
Right now, the `SingleList` with the count option enable would show in the list
- apple (1)
- grape (1)
- orange (2)

I want to have a way to add an additional entry so that I can filter the search results with items that have no tag entry. I would like the list to show

- apple (1)
- grape (1)
- orange (2)
- N/A (1)

My thinking is that setting `showMissing` to true could indicate to change the aggregate query for filter options to return a count for the items that are missing the dataField. The `missingLabel` would determine the label that is used to represented the items with the missing dataField.

**Comment by davidklebanoff** [comment]
Ah yes, that makes more sense. I thought you may have meant _missing_ as in returning a 0 for the current filters.

**Comment by metagrover** [comment]
TODO:

- [ ] Add docs
- [ ] Support MultiDropdownList and MultiList

**Comment by divyanshu013** [comment]
Hi @lopper, do you want to send PR for MultiDropdownList and MultiList too?

**Comment by lopper** [comment]
@divyanshu013 Yes, I'll send a PR for MultiDropdownList and MultiList.
