### ISSUE TITLE
Multiple requests generated from using `react` attributes for a single search

### ISSUE THREAD

**Issue by a-magdy** [appbaseio/reactivesearch#294]
Hi there,

Issue Type: enhancement
Platform: Web
Reactivesearch version: ^2.0.0-beta

Description:

`react` field causes components to update based on other components, but I noticed that if we have more than 1 component reacting to another component, we get more than network request for just one search.
For ex: In the demo app [book search](https://opensource.appbase.io/reactivesearch/demos/goodbooks/), we have to 2 components with react to the `mainSearch` in lines:
https://github.com/appbaseio-apps/booksearch/blob/master/src/App.js#L91
https://github.com/appbaseio-apps/booksearch/blob/master/src/App.js#L52

Reproduction:

When I type something in the search field, I get 2 network requests:
<img width="376" alt="screen shot 2018-03-15 at 19 28 46" src="https://user-images.githubusercontent.com/14139855/37483846-264b4bfe-2887-11e8-9e2b-a178fcb0ee5a.png">
(well actually 4, but 2 of them are OPTIONS for the other 2)

And this is going to grow if we have more fields with `react` properties defined in them, don't you think that we should combine these searches into one with every request in all components in the same ReactiveBase?

Thank you for your efforts :)

**Comment by siddharthlatest** [comment]
@a-magdy Great point, we plan to use `_msearch` feature to send bulk search requests in an upcoming release. Currently, the number of requests per interaction are proportional to the number of connected components to that component.

**Comment by a-magdy** [comment]
@siddharthlatest Thanks for the quick reply :)

Good to hear it'll be implemented in a future release :) 💪

**Comment by siddharthlatest** [comment]
I have created a separate issue for this. Thanks for bringing it up :-)
