### ISSUE TITLE
Feature: Use _msearch to send bulk requests

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivesearch#295]
**Issue Type:**

Enhancement

**Platform:**

Both

**Description:**

Use [`_msearch`](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-multi-search.html) to optimize the number of search requests sent to the ES backend. See #294 for what happens currently. We send requests proportional to the number of components connected to the one which sees an interaction.

**Reactivesearch version:** x.y.z

latest

**Comment by metagrover** [comment]
Released in `v2.5.0` 🎉

**Comment by a-magdy** [comment]
Hi @metagrover,

Thanks for working on this feature :) 

I tested it locally with v2.6.0 and I am facing 2 issues:

1. I am using a proxy app to customize the query (for security), and I threw an error that the last line has to be new line
  - So I updated the encoding of the request from `application/json` to `application/x-ndjson` and added a newline after stringifying the request, but it didn't work as well
  - __Q:__ what is your guidelines or recommendations to update the query using a proxy app with reactivesearch and multi-request queries

2. For the sake of testing the new feature, I updated my app to point to elasticsearch directly, not the broken proxy app, and it worked, but I noticed that I am getting multiple `msearch` queries
  - I thought there is something wrong with my code, so I checked the hosted `Booksearch` demo, but it was using v2.0.0-beta, so I cloned it locally, updated the library to `v2.6.0` and tested it and still got multiple `msearch queries
  - __Q:__ are there any requirements or configurations to use the new `msearch`
    - And can I control it, meaning can I toggle it on and off -one use case would be testing the query of each component independently-

Again thanks for the amazing work you guys do in @appbaseio :) love using your tools <3

**Comment by metagrover** [comment]
I'd highly recommend you to try **S**erver **S**ide **R**endering wherein, we only make one `_msearch` query to feed data to all the reactive components. 

👉 [Read all about it here in the introductory blog post](https://medium.appbase.io/blazing-fast-apps-%EF%B8%8F-with-reactivesearch-9586ed24ccbc).

**Comment by a-magdy** [comment]
@metagrover Thanks for your reply

I am manipulating the request body, after parsing it as json using `bodyParser`: it was like:

```javascript
const app = express();

app.use(cors());

app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));

app.use((req, res, next) => {

  // Here I check my custom autherization header and manipulate the `req.body` json object

  next();
})

// Define proxy options
const options = {
  target: _elastic_host_url_,
  changeOrigin: true,               // needed for virtual hosted sites
  // ws: true,                         // proxy websockets
  onProxyReq: (proxyReq, req, res, options) => {
    if(req.body) {
      let bodyData = JSON.stringify(req.body);
      console.log({ bodyData });
      // In case if content-type is application/x-www-form-urlencoded -> we need to change to application/json
      proxyReq.setHeader('Content-Type','application/json');
      proxyReq.setHeader('Content-Length', Buffer.byteLength(bodyData));
      // Stream the content
      proxyReq.write(bodyData);
    }
  }
};

app.use("*", proxy(options));
```

And it was working fine with json format

I've been testing with the new format, hoping that [`bodyParser libs`](https://github.com/expressjs/body-parser/tree/master/lib/types) but I couldn't find any references to `ndjson` instead of `json`
I even tried writing my own `ndjson` middleware, copying the content of the [`json`](https://github.com/expressjs/body-parser/blob/master/lib/types/json.js) one and updating this [line](https://github.com/expressjs/body-parser/blob/master/lib/types/json.js#L89) to use [`ndjson`](https://github.com/maxogden/ndjson) parser, but not success

I tried a lot of other tools: [can-ndjson-stream](https://github.com/canjs/can-ndjson-stream), [parse-ndjson](https://github.com/mjannino/parse-ndjson), but I couldn't them to run in the proper order

The last trial I did, which I think I'll go with for now, is updating the code above to:

```javascript
const app = express();

app.use(cors());

// app.use(bodyParser.json());
app.use(bodyParser.text( { type: 'application/x-ndjson' } ));
app.use(bodyParser.urlencoded({ extended: false }));

app.use((req, res, next) => {

  // Here I check my custom autherization header

  // And now I'll get req.body as a multi-line string with ndjson format -json object in each line-
  // So I am thinking of just using string split by `\n` and manipulate every 2nd line with the same logic as a single request body

  next();
})

// Define proxy options
const options = {
  target: _elastic_host_url_,
  changeOrigin: true,               // needed for virtual hosted sites
  // ws: true,                         // proxy websockets
  onProxyReq: (proxyReq, req, res, options) => {
    if(req.body) {
      // TODO test this to properly stringify the req.body as `ndjson` (don't forget the trailing `/n`)
      let bodyData = JSON.stringify(req.body);
      console.log({ bodyData });
      // In case if content-type is application/x-www-form-urlencoded -> we need to change to application/json
      // proxyReq.setHeader('Content-Type','application/json');
      proxyReq.setHeader('Content-Type','application/x-ndjson');
      proxyReq.setHeader('Content-Length', Buffer.byteLength(bodyData));
      // Stream the content
      proxyReq.write(bodyData);
    }
  }
};

app.use("*", proxy(options));
```

But by default, removing any manipulations works by just updating the middlewares and encoding in the proxy config

For the multi `_msearch` requests, I understand it now, it is combining searches after the initial loading :+1: really nice :) 

And for the __SSR__, I think it is a fantastic idea, will definitely try it, I think it'll be really beneficial in different use cases :) 🎉

**Comment by divyanshu013** [comment]
[Here's](https://github.com/appbaseio-apps/reactivesearch-proxy-server/blob/master/index.js) how I'm doing it now, let me know if you think it can be improved.

**Comment by a-magdy** [comment]
@divyanshu013 Thanks for sharing it

I tried is locally and it works for in my app, I think it is good as is :+1:

**Comment by divyanshu013** [comment]
Looks great 😁

**Comment by a-magdy** [comment]
I am glad it made you laugh :D !!

**Comment by mhurne** [comment]
@a-magdy Somewhat off-topic, but I'm curious - in practice, how easy/difficult have you found implementing and maintaining a proxy to secure your search data to be? I'm interested in using Reactivesearch but am concerned about that aspect.

**Comment by a-magdy** [comment]
@mhurne It wasn't that hard to get started, if you know the basics of node.js, it shouldn't be a problem.

they already provide a starting proxy-server here: https://github.com/appbaseio-apps/reactivesearch-proxy-server/

and it is just ready for you to implement your logic: https://github.com/appbaseio-apps/reactivesearch-proxy-server/blob/master/index.js#L38

I didn't find it difficult at all to start, and the approach of creating a proxy server is a great idea, not just for security, but also for rate limiting (if you want to implement it)

If you face any challenges, the guys here are very helpful, I've had great experience whenever I had a question

**Comment by mhurne** [comment]
Thanks for the info, @a-magdy
