### ISSUE TITLE
Pagination doesn't correctly update when the size property in the Results is changed

### ISSUE THREAD

**Issue by lopper** [appbaseio/reactivesearch#298]
**Issue Type:**
bug

**Platform:**
Web

**Description:**
When I change the size property of the ReactiveList, the pagination component does not update to reflect the correct last possible page. 

 For example, if I start with a ReactiveList with a pagination size of 10 and there are 300 results, the last page is page 30. However, if I then change the size to 50, the pagination component does not update to reflect that the last page should now be 6. The pagination still shows 30 as the last page.

**Comment by siddharthlatest** [comment]
Thanks for filing this issue @lopper! We will try to incorporate this for the next release. If you have already identified the root cause - feel free to send a PR.
