### ISSUE TITLE
New component: TagCloud

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivesearch#3]
### Component Props

- **componentId** `String`  
    component ID.
- **appbaseField** `String`  
    DB field to be mapped for the query.
- **title** `String` [optional]  
    title of the component, optional.
- **multiSelect** `Boolean` [optional]    
    whether to allow multiple tag selections. Defaults to `false`.
- **defaultSelected** `String` or `Array`  
    pre-selected values, specified as one of String or Array type. Same validation logic as with ToggleList.
- **showCount** `Boolean` [optional]  
    whether to show the count next to the data label. Defaults to `false`.

Component would be sorted in alphabetical order, and for the time being, will not support any other sort options. The size of the labels will depend on the frequency of their occurrence. Selected label will show a background-color effect.

### CSS Styles API

`rbc-count-active`
`rbc-multiselect-active`
`rbc-title-active`

### Stories

1. Basic story
2. With default Selected values
3. With multi-select set and default Selected values
3. with dark theme
4. Playground.

**Comment by metagrover** [comment]
Added here: 270030eac9e375885e5404e9b35aedad47b05b53 480eb8f61b0712b789712e84be67f0aa8214d52c
