### ISSUE TITLE
Result* Components: Scroll and Height issues

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivesearch#30]
- [x] Show Powered by logo only when container height > 300px.
- [x] Better way to detect infinite scroll page.

**Comment by metagrover** [comment]
[] Add `scrollTarget` prop

**Comment by metagrover** [comment]
Fixed here: 443403aba73cd047898e2704b4c998222fa729d7

**Comment by farhan687** [comment]
- [ ] Add `scrollOnTarget` prop to ResultCard and ResultList expect reference of element as prop value. Apply scroll on that referenced element.

**Comment by farhan687** [comment]
Fixed here: 006f1269910637db453afc39960ebfb3a454cd82
