### ISSUE TITLE
Feature Request: Add property to make UrlParams a directory instead of a GET param

### ISSUE THREAD

**Issue by davidklebanoff** [appbaseio/reactivesearch#301]
**Issue Type:**
enhancement

**Platform:**
Web

**Description:**
Sometimes it makes more sense for a parameter to be represented as a directory as opposed to a GET parameter. For example, consider the Meetup search with a non-multiselect `ToggleButton`.

```
<ToggleButton
  componentId="MeetupTops"
  dataField="group_topics.topic_name.raw"
  data={
    [{"label": "Social",   "value": "social"},
     {"label": "Travel",   "value": "travel"},
     {"label": "Outdoors", "value": "outdoors"}]
  }
  defaultSelected=["Social"]
  multiSelect={false}
  filterLabel="category"
  URLParams={true}
/>
```

Currently the url would be:
`http://www.example.com?category=%22social%22`

But it would be nice if a property was added that made the parameter a directory, like:
`http://www.example.com/social`

Thoughts?

**Comment by metagrover** [comment]
Hi @davidklebanoff, IMO this should not be the library concern as there is no way our root component can figure out which component does the value `social` map to (in `http://www.example.com/social` url). Also, there is no trivial way to support multiple values in such pattern of urls.

You can easily implement it for your use-case via `react-router` though: Handle the route param in your root component and assign it as `defaultSelected` in the desired reactivesearch component.

Hope this helps!

**Comment by davidklebanoff** [comment]
@metagrover Thanks!

**Comment by axeff** [comment]
Does anyone have an idea on how to do that with `next-routes`? My pattern for, let's say some country filter, should look like this: `pattern: '/country/:countryname/ instead of ?country="{countryname}"

**Comment by divyanshu013** [comment]
Hi @axeff you can access the url in your root component and pass the `countryname` as the `defaultSelected` value in the country filter.
