### ISSUE TITLE
ResultList: sortOptions prop %@#! with query

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivesearch#31]
When applying **sortOptions** prop, the resulting query gets sorted on an "undefined" field.

![](https://i.imgur.com/Cx32OQY.png)

and generates a 400 search parse exception.

![](https://i.imgur.com/dohev16.png)

The result is a sad list with nothing to show.

![](https://i.imgur.com/YnB4myE.png)

**Comment by siddharthlatest** [comment]
There was a documentation mismatch with the implementation, updated the docs. It would be nice to add a PropType validation for the fields to be expected at some point.

**Comment by GraemeFulton** [comment]
Ah I think I found what's going one, I've not mapped the field correctly - anyone that stumbles across my problem, [read here](https://stackoverflow.com/questions/34493947/elasticsearch-is-not-sorting-the-results).

**Comment by baj84** [comment]
Did you ever get this working? I am also getting 'undefined' on sort property even though I have done the mapping properly. Even when I try to sort by '_score' I get the sort undefined issue.
