### ISSUE TITLE
DynamicRangeSlider work According to customQuery , onchange Slider render the results(products)   

### ISSUE THREAD

**Issue by ashwini987** [appbaseio/reactivesearch#315]
**Issue Type:**
Bug Report. 
**Platform:**
 Web 

**Description:**
In DynamicRangeSlider I am using _customQuery_ according to my requirement that Showing all products according to customQuery. But issue is that if I slide the silder, others Components like Resultcard , Multulist etc. value is not change.

I have data which contain one field "**min_price**" . but issue is that in some products "**min_price**" Field is **_not exists_** OR in some products "**min_price**" Field is **_exists but value is NULL_**, so for that i use _customQuery_ in DyanamicRangeSilder accoding to this above conditions.   

This is the code that show all products according to some products "min_price" Field is not exists OR in some products "min_price" Field is exists but value is NULL.
  
```
<DynamicRangeSlider
	componentId="DynamicRangeSensor"
	dataField="min_price"
	title="Price Range"
	customQuery={
	   function(value, props) {
	       return {	
			"query" : {
				 "bool" : {
					 "filter" : {
						"bool" : {
						   "should" : [
							 { "bool" : {
								"must" : [
									 { "exists" : {"field" : "min_price"}
								  ]
							   }},
							   { "bool" : {
								  "must_not" : [
									{ "exists" : {"field" : "min_price"}}
								   ]
							   }}
						     ]
						}
					  }
				    }
				}
			}				
		 }		
	 }
	showHistogram = {false}
	defaultSelected={(min, max) => (
	     {
		"start": min,
		 "end": max
	      }
	)}
	rangeLabels={(min, max) => (
		{
			"start": "$ "+ min ,
			"end": "$ "+ max
		}
	)}
/> 
```
**Reactivesearch version:** 
v2.0.0

**How to reslove this issue and render products according to user silde the slider ???**
 
**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by dweep119** [comment]
The same issue I am facing.
Is there any way to fix this type of issue.
