### ISSUE TITLE
ShowFilter RangeInput

### ISSUE THREAD

**Issue by ymzoughi** [appbaseio/reactivesearch#320]
**Issue Type:**
Help wanted

**Platform:**
ReactiveSearch for Web

**Description:**
Hello is it possible to add the showFilter prop for RangeInput ?

**Reactivesearch version:** 2.2.3

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by jyash97** [comment]
We support `showFilter` prop in both v2 and v3. 🚀
