### ISSUE TITLE
Upgraded to 2.5.0 from 2.3.3 - TypeError: nextProps.defaultQuery is not a function

### ISSUE THREAD

**Issue by joelrojo** [appbaseio/reactivesearch#330]
**Issue Type:**
Bug

**Platform:**
ReactiveSearch Web

**Description:**
I updated to `2.5.0` from `2.3.3` in order to us the `onNoResults` prop on `ReactiveList`, but not my search isn't working. I'm getting the error below:

```
TypeError: nextProps.defaultQuery is not a function
ReactiveComponent.componentWillReceiveProps
node_modules/@appbaseio/reactivesearch/lib/components/basic/ReactiveComponent.js:93
  90 | }
  91 | console.log("PROPS")
  92 | console.log(nextProps);
> 93 | if (!(0, _helper.isEqual)(nextProps.defaultQuery(), this.defaultQuery)) {
  94 | 	this.defaultQuery = nextProps.defaultQuery();
  95 | 
  96 | 	var _ref2 = this.defaultQuery || {},
```

I tried defining a defaultQuery prop to see if maybe that was the issue, but still received this on any search and any page on the app.

**Comment by metagrover** [comment]
Fixed in `v2.5.1` 🎉
