### ISSUE TITLE
Export query result to a file? 

### ISSUE THREAD

**Issue by knguyen0105** [appbaseio/reactivesearch#334]
Is it possible to export a query result to a file? 

I'm working on a search feature for our customer database. One requirement is that users can export a search result to a csv file so that it can be forwarded to another team (i.e marketing). 

How do I implement this with reactivesearch? Thanks

**Comment by davidklebanoff** [comment]
It seems to be you would want to hook into the `onAllData` property of your result component to retrieve the search result data and from there you can perform your custom logic to generate a csv file.

**Comment by siddharthlatest** [comment]
@knguyen0105 What @davidklebanoff is suggesting should work. There is one caveat (that I can think of) - your max export size (due to the result size cap in Elasticsearch) will be up to `1000` results.

**Comment by knguyen0105** [comment]
Thanks much @davidklebanoff and @siddharthlatest. 

What if we need to export upto 1M records? What are the risks if we modify the Elastic settings? One workaround I can think of is to save the query (not the query result) to run it later on the terminal where I have more flexibility, Would it work?

**Comment by davidklebanoff** [comment]
@knguyen0105 That sounds like a question best suited for ElasticSearch. Have you tried looking at the ElasticSearch documentation, Google, or Elasticsearch forums?

Remember, ReactiveSearch is just a React-based UI for Elasticsearch. Outside of the user interface and the query building logic, the core of the work is being done by Elasticsearch.

**Comment by knguyen0105** [comment]
@davidklebanoff : My apology if the question seems irrelevant. I just tried reactivesearch and elasticsearch a few days ago. 

Maybe I wasn't clear. My question is can I retrieve the query being sent to elasticsearch from ResultList component. My end-users (non-tech) will have a button 'Save Query' when there are more than 10k records. The user will "Save Query" and forward it to tech support later.

**Comment by metagrover** [comment]
Hi @knguyen0105 

If you are dealing with large sets of data, you'll have to determine the active query on the results component via `onQueryChange` and then perform paginated requests to the elasticsearch cluster and keep feeding the results from the query (paginated) hits.

(I will attach a code snippet to achieve this sometime later today).

**Comment by knguyen0105** [comment]
Thank you @metagrover . A code sample defintely will help a lot.

**Comment by metagrover** [comment]
Snippet for exporting query hits data as csv can be [found here](https://gist.github.com/jrishabh55/bf1d7d1259f1a49f4b2c00dd4a13c890). 🎉 

@knguyen0105 Please try it out and let me know if that works for you!
