### ISSUE TITLE
web: infinite loading is not working in result components

### ISSUE THREAD

**Issue by divyanshu013** [appbaseio/reactivesearch#336]
**Issue Type:**

Bug

**Platform:**

Web

**Description:**

After the result component has finished loading the results, the `loading` state still remains `true` which makes the infinite scrolling logic not work.

**Minimal reproduction of the problem with instructions:**

[Check story](https://opensource.appbase.io/playground/?selectedKind=Result%20components%2FReactiveList&selectedStory=With%20infinite%20loading&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)

**Reactivesearch version:** x.y.z

2.5.1

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

All

**Comment by metagrover** [comment]
@dhruvdutt Do you want to take this up? I think it happened after we added `onNoResults` support.
