### ISSUE TITLE
DataSearch.JS capability to override/replace words in text autocomplete results 

### ISSUE THREAD

**Issue by preritmohan** [appbaseio/reactivesearch#339]
**Issue Type:**
Bug

**Platform:**
Reactivesearch Web

**Description:**
In DataSearch.js I need to make certain words in autocomplete for results to be in uppercase. I did some manipulation to replace words but the build fails and cannot minify DataSearch.js and the app does not work in IE.

**Screenshots:**
For ex. if I type leed in search box all the autocomplete results come back with leed in small. Need to capitalize LEED in all occurrences in autosuggest.

**Minimal reproduction of the problem with instructions:**

**Reactivesearch version:** 5.7+

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**

**Comment by vaibhav-groupten** [comment]
+1

**Comment by siddharthlatest** [comment]
@preritmohan How are you doing this: via the [`onSuggestion` prop](https://opensource.appbase.io/reactive-manual/search-components/datasearch.html#extending) or some other way?

Do you see any error logs in the browser when you use `onSuggestion`?

**Comment by preritmohan** [comment]
Hi @siddharthlatest. I had done via some custom logic. Totally missed the onSuggestion prop. I was able to achieve it by onSuggestion prop. Thanks!
