### ISSUE TITLE
Reset Filters

### ISSUE THREAD

**Issue by ymzoughi** [appbaseio/reactivesearch#342]
**Issue Type:**
enhancement

**Platform:**
ReactiveSearch for Web

**Description:**
is there a way to reset all Filters?

**Reactivesearch version:** 2.5.1

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by metagrover** [comment]
You can use `SelectedFilters` component in which we show the selected filters' value as clearable tags and also a `Clear All` button. Read more about it [here](https://opensource.appbase.io/reactive-manual/base-components/selectedfilters.html).

**Comment by ymzoughi** [comment]
Thank you
