### ISSUE TITLE
Datetime range filter sugestion - chart with zoom ability

### ISSUE THREAD

**Issue by aktywnitu** [appbaseio/reactivesearch#344]
**Issue Type:**
Hi,
I need feature like Kibana has on Discover page - chart with results count with zoom ability.
Do reactivesearch have such component or I need write it myself?

Can you tell me also where can I ask such questions.
https://slack.appbase.io/ don't work.

**Platform:**

**Description:**

**Screenshots:**

**Minimal reproduction of the problem with instructions:**

**Reactivesearch version:** x.y.z

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**

**Comment by siddharthlatest** [comment]
@aktywnitu You can ask on our gitter - https://gitter.im/appbaseio/reactivesearch. I don't know what component Kibana is showing, but you can invariably achieve anything either using ReactiveList or ReactiveComponent along with your own custom UI component to render the results from these.
