### ISSUE TITLE
Allow SelectedFilters to limit which components are cleared

### ISSUE THREAD

**Issue by dubcanada** [appbaseio/reactivesearch#345]
**Issue Type:**
enhancement

**Platform:**
Web

**Description:**
Allow SelectedFilters to specific which components get cleared

**Minimal reproduction of the problem with instructions:**
Right now if you have selectedfilters and click Clear filters it clears all filters, but if you have a filter that you don't want ever cleared it clears that as well.

**Reactivesearch version:latest

**Browser:** All

**Anything else:**
Nope!

**Comment by metagrover** [comment]
Currently, I don't think there is any to get around this with `Clear All`, you can although hide `Clear All` button with `showClearAll` set as `false` and only show the desired clearable filters as tags.

**Comment by siddharthlatest** [comment]
Based on a recent issue discussion, we should allow custom rendering of SelectedFilters so the user has a choice on how the filters can be cleared.

**Comment by siddharthlatest** [comment]
There is already an open issue with a spec on how to do this #121, closing this in favor of that.
