### ISSUE TITLE
[Question] Is it possible to remove Double-Quotes from URL when selecting any Filter?

### ISSUE THREAD

**Issue by faizansaiyed** [appbaseio/reactivesearch#346]
**Issue Type: Question**

**Platform: Web**

**Description:**
Is there any way to remove Double Quotes from URL when selecting any filter and also Reactive Search to work properly?

**Reactivesearch version: 2.0.0** 

**Browser: All**

**Comment by metagrover** [comment]
I guess so, we do it to cover all use-cases in one go - by Stringify-ing everything. We can however, check if the value's type is already a string then skip it - [here](https://github.com/appbaseio/reactivesearch/blob/dev/packages/web/src/components/basic/URLParamsProvider.js#L53).

Open to PRs if you want to take this up!

**Comment by ashwini987** [comment]
Hello @metagrover , 
I try this solution remove  JSON.stringify in URLParamsProvider.js but still i face the problem like,
 1st time query is work http://localhost:8001/?SearchSensor=pen but, when i refresh the page query not working but URL is same. 

so how can i slove this problem with refresh the page query also work properly according to URL ?

**Comment by metagrover** [comment]
Seems like a parsing issue to me. Can you check what value is getting set for the `SearchSensor` in the `selectedValues` of the redux-store?

**Comment by ashwini987** [comment]
sorry i m not getting

**Comment by ashwini987** [comment]
This the screensort 
![redux-store2](https://user-images.githubusercontent.com/31088567/42259965-32360562-7f80-11e8-9b2e-30a17413bfd8.png)

**Comment by ashwini987** [comment]
1st time query is work http://localhost:8001/?SearchSensor=pen but, when i refresh the page query not working but URL is same. this issue i m facing.

**Comment by metagrover** [comment]
What value do you get in the `selectedValue` prop of `CategorySearch` after you refresh?

**Comment by ashwini987** [comment]
null

**Comment by metagrover** [comment]
That's because it's not getting parsed correctly from the URL now.

You may have to [get rid of `JSON.parse` from here now](https://github.com/appbaseio/reactivesearch/blob/dev/packages/web/src/components/basic/ReactiveBase.js#L85).

**Comment by ashwini987** [comment]
resolve this issue. thank you
