### ISSUE TITLE
Add support for defaultQuery prop in all data-driven components

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivesearch#353]
**Issue Type:**

Enhancement

**Platform:**

Both

**Description:**

We support `defaultQuery` prop to let the user pass an external query for Result components. We should add a similar to other components where a React prop can be applied.

This is useful when you have another query (think global config) that needs to execute along with other ReactiveSearch components.

- [ ] Add support on Web
- [ ] Add support on Native
- [ ] Update the docs.

**Comment by siddharthlatest** [comment]
Once we add this support, we can deprecate the `DataController` component and remove it with the 3.0.0 release. All the use-cases it serves can be better served by the defaultQuery prop (adding additional query(ies) or the ReactiveComponent (creating custom UI components).

**Comment by metagrover** [comment]
TODO: Clean up `defaultQuery` from search components.

**Comment by metagrover** [comment]
Support for necessary components was added.

Related: https://github.com/appbaseio/reactivesearch/issues/855
