### ISSUE TITLE
Support for 'show all' on search?

### ISSUE THREAD

**Issue by carlopascual** [appbaseio/reactivesearch#354]
**Issue Type:**
Enhancement

**Platform:**
Web

**Description:**
It would be nice to have a 'see all results for ${search}'

**Screenshots:**

![image](https://user-images.githubusercontent.com/13900345/39474286-8a2b88be-4d53-11e8-8280-13e990a04a3c.png)

**Comment by siddharthlatest** [comment]
One way to handle something like this is giving full control of suggestions rendering. Similar to the `onSuggestion` prop we added in the past https://github.com/appbaseio/reactivesearch/issues/117, we can support an `onAllSuggestions` prop.

Giving full JSX control to the user would allow this use-case as well as more specific ones where a custom suggestions display is required.

**Comment by davidklebanoff** [comment]
@siddharthlatest - That sounds like a good idea. Perhaps using the above feature request as an example of the `onSuggestion` flexibility. Win win.

**Comment by carlopascual** [comment]
I'm not sure if I missed it from the documentations, but is there a way to also limit the maximum amount of suggestions that are displayed on search? It would be useful to limit it to be able to make sure that the 'See all results' are seen as well. :)
