### ISSUE TITLE
Unionise highlighting of results for fields with (native) subfields

### ISSUE THREAD

**Issue by metagrover** [appbaseio/reactivesearch#357]
## Issue
Enhancement

## Description
Currently, we only highlight results of `dataFields` which are being rendered in the view **ignoring their sub-fields**. For certain search use-cases where there won't be a full-word match, we only receive such highlights in the sub-fields (`.search` field w.r.t. appbaseio standard mappings). For example:

<br />

![](https://i.imgur.com/vrVdVWn.png)

<br />

For results, where we don't have anything highlighted, we are receiving the marked highlights in `.search` subfield. So, it's best to unionise the highlight-results of `dataFields` with their respective sub-fields before rendering.

**Reactivesearch version:** 2.6.2

**Comment by siddharthlatest** [comment]
One option here is to transparently pass the `highlight` key returned from the response in the `onAllData` and `onData` callbacks (will be `renderAllData` and `renderData` in v3.0.0).
