### ISSUE TITLE
Support for parent/child query

### ISSUE THREAD

**Issue by szaranek** [appbaseio/reactivesearch#358]
**Issue Type:**
enhancement
**Platform:**
Web 
**Description:**
ES allows connecting documents in parent/child relations. It will be nice to have native support in reactive search components for that kind of query instead of using custom query (which actually doesn't work for aggregations in multiDropDownList ).  Adding additional prop with children type and wrapping original query may be enough to solve this issue.
**example query:**
```
GET trail/_search
{
	"query": {
		"bool": {
			"must": [{
				"bool": {
					"must": [{
						"bool": {
							"must": {
								"has_child": {
									"type": "Revisions",
									"query": {
										"bool": {
											"must": [{
												"terms": {
													"type": ["OMS"]
												}
											}]
										}
									}
								}
							}
						}
					}]
				}
			}]
		}
	},
	"size": 100,
	  "aggs": {
    "Revisions": {
      "children": {
        "type" : "Revisions" 
      },
    	"aggs": {
    		"direction": {
    			"terms": {
    				"field": "direction",
    				"size": 100,
    				"order": {
    					"_count": "desc"
    				}
    			}
    		}
    	}
    }
  }
}
```

**Comment by allendol** [comment]
Did you find the solution for this?
