### ISSUE TITLE
Enhancement: Show defaultSuggestions in DataSearch even when autoSuggest is false

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivesearch#359]
**Issue Type:**

Enhancement

**Platform:**

Web and Native

**Description:**

`defaultSuggestions` is a good way to guide an end-user on how the search works or for showing popular search queries. We should show defaultSuggestions in the UI if the user sets the prop even when autoSuggest (which controls whether suggestions should appear as user types a query) may be set to `false`.

**Screenshots:**

**Minimal reproduction of the problem with instructions:**

**Reactivesearch version:** x.y.z

Latest

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**

**Comment by divyanshu013** [comment]
Fixed via #463
