### ISSUE TITLE
web: Result components don't get updated when page is changed from browser controls

### ISSUE THREAD

**Issue by divyanshu013** [appbaseio/reactivesearch#360]
**Issue Type:** Bug

**Platform:** Web

**Description:** When using a result component with `pagination` and `URLParams`, the url gets updated when clicking on a new page number but using the browser controls to go back only updates the url and not the result component.

**Minimal reproduction of the problem with instructions:**  For example if we are on page 2 and click the browser back button, only the url gets updated. The result component still stays at page 2.

**Reactivesearch version:** latest (dev)

**Comment by dubcanada** [comment]
None of the components get updated when history state updates, if you have a ToggleButton select an option and then go back it does not unselect that option.

**Comment by dubcanada** [comment]
I played around with it a bit and there is no `window.onpopstate` to monitor the query and set the props depending on the value.

It also becomes super hard to deal with as each value is kind of all over the place.

I played around and got a semi working version for ToggleButtons/TextField that looks something like

https://gist.github.com/dubcanada/68b136c670c4970752da2b2ba13a9a9b

But I have no idea how we want to handle everything else, as pagination is completely different and it becomes very difficult to get the URL parameters and parse them and set them properly according to the different components.

Example TextField is set to `?componentId="value"` and ToggleButton is set to `?componentId=["Label"]` so you need to get the value (parsing it is super weird), turn it into the actual value (from the label) and then set that value using `this.props.setValue`

But then you start getting into a mess when you start looking at components under wrappers and stuff. And pagination which isn't a prop but a state on the result component.

So besides hacking away at it I am not sure how best to do this.

Any thoughts/suggestions?

**Comment by metagrover** [comment]
Fixed here: 47297e8 

We will roll this out later today in `v2.7.0` 🎉
