### ISSUE TITLE
OnChangeQuery not firing when 2 reactive list on the same page

### ISSUE THREAD

**Issue by talelcool** [appbaseio/reactivesearch#362]
**Issue Type:**
BUG

**Platform:**
WEB

**Description:**
When I use try to put two different reactive list on the same page, onChangeQuery doesn't fire any more or fire for only one time in certain cases.

One of the ResultList is watched by many filters components via react props.

**Minimal reproduction of the problem with instructions:**

**Reactivesearch version:** Last Dev
**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**

**Comment by metagrover** [comment]
Can you attach a codesandbox link replicating this issue?

**Comment by talelcool** [comment]
here is an example

https://codesandbox.io/s/r7y49k2wl4

**Comment by metagrover** [comment]
Fixed with `v2.6.5` 🎉
