### ISSUE TITLE
"Missing" checkbox does not work in MultiList with "and" queryFormat

### ISSUE THREAD

**Issue by dedaimia** [appbaseio/reactivesearch#370]
**Issue Type:**
Bug
**Platform:**
Web

**Description:**
If you add a MultiList with queryFormat='and' and showMissing=true, a checkbox for items missing the data field is shown (and counts are correct if showCount on), but clicking the checkbox does not return the correct results - result list is always empty.     It works properly with queryFormat='or' but not 'and'.  I've written a custom query to fix this, but it would have been nice if it worked out of the box.

**Screenshots:**

**Minimal reproduction of the problem with instructions:**

1. Add a MulitList component for a data field that is missing on some entries. 
2. Set queryFormat='and'
3. Set showMissing=true
4. Add ResultList component set up to react to the MultiList component.  It's helpful if you set this to show a message onNoResults
5. Click on any of the "regular" entries in the MultiList - ResultList should update appropriately
6. Click on the checkbox for missing (N/A) values.   Result list will show no results, even though there are entries in the index with the data field missing/empty.

**Reactivesearch version:** 
2.6.1

**Browser:** 
Chrome 66.x 

**Anything else:**
The problem appears to be that in "and" mode it builds this query for when the missing (N/A) checkbox is checked....which is of course an impossible condition:
{"must":
[{"term":{"panelTargetReports.question.label":"N/A"}},
{"bool":{"must_not":{"exists":{"field":"panelTargetReports.question.label"}}}}]}

Could the default query logic for 'and' be modified to leave out the "term" entry for the missing (N/A) checkbox?  The query would then work.    It is worth noting that checking both N/A and any of the other checkboxes makes no sense when in 'and' mode, so making checking N/A should also deselect other options?

In 'or' mode it builds a valid query:
{"should":
[{"terms":{"panelTargetReports.question.label":[]}},
{"bool":{"must_not":{"exists":{"field":"panelTargetReports.question.label"}}}}]}

**Comment by dedaimia** [comment]
BTW, I'm not suggesting someone else has to fix this, I can contribute with the fix I'm already using, just wanted to see if anyone had comments/feedback first.

**Comment by metagrover** [comment]
Thanks for filing this. Makes sense! We will never have an intersection on the empty and non-empty values.

@siddharthlatest thoughts here?

**Comment by siddharthlatest** [comment]
Sorry I missed out on this for long. The behavior of the library makes sense. If you really need to enable this behavior, it's possible by programmatically setting the `queryFormat` prop when the missing label is selected.
