### ISSUE TITLE
Reset Filter

### ISSUE THREAD

**Issue by ymzoughi** [appbaseio/reactivesearch#374]
**Issue Type:**
Question
**Platform:**
ReactiveSearch for Web

**Description:**
is it possible to create a button that allows you to reset all filters

**Comment by metagrover** [comment]
We currently support it via `SelectedFilters` whose customisation related issue is filed here - #121 

You can refer SelectedFilters [docs here](https://opensource.appbase.io/reactive-manual/base-components/selectedfilters.html).

Hope that helps!
