### ISSUE TITLE
[Enhancement] onMouseOver event for ResultCard

### ISSUE THREAD

**Issue by baj84** [appbaseio/reactivesearch#376]
Using reactive search for web.

I need to be able to show a preview of the item in the result list when the user placed their mouse over it.

There is currently no way to pass callbacks for mouse events. I think this could be really useful

**Comment by metagrover** [comment]
Thanks for bringing this up. I agree, this will be a valuable addition. We can add a key called `containerProps` to collect all the props for the card/list elements via `onData()`.

Open to PRs if you or anyone else wants to take this up 😄 

For now, you can use [ReactiveList](https://opensource.appbase.io/reactive-manual/result-components/reactivelist.html) to achieve this.

**Comment by baj84** [comment]
I can have a look at creating a PR. Can I ask how you would use reactivelist to accomplish this?

**Comment by metagrover** [comment]
ReactiveList lets you render your own custom markup, so you can attach `onMouseOver` event on the card elements. The only caveat is - you will have to write card styles on your own.

For reference:

```js
onData={(res) => <div onMouseOver={() => {...}}>{res.title}</div>}
```

**Comment by divyanshu013** [comment]
Added in `v2.6.7` 🏁
