### ISSUE TITLE
Paginate aggreation results

### ISSUE THREAD

**Issue by aktywnitu** [appbaseio/reactivesearch#377]
I have reactivesearch app which display sold products stats.
Instead displaying every transaction I would like display aggregated results (Name of products and numer od transactions). I have done it using CustomComponent, but is still more like filter component, no results comonent.  There is no pagination feature.
Is it some better way to do it?
Can I transform ResultList / ReactiveList to show my aggregated results with included _source?

**Comment by metagrover** [comment]
Related: https://github.com/appbaseio/reactivesearch/issues/340

**Comment by siddharthlatest** [comment]
@aktywnitu does that describe your use-case well or have we missed something?

**Comment by divyanshu013** [comment]
Closing this, will keep things posted at #340
