### ISSUE TITLE
web: Upgrade to the new lifecycle

### ISSUE THREAD

**Issue by divyanshu013** [appbaseio/reactivesearch#383]
# Enhancement

**Platform:**

Web

**Description:**

With react 16.4, the legacy lifecycle hooks will start throwing warnings. We would have to think through how to solve this if we still want to keep supporting the older versions of react.

**Reactivesearch version:** x.y.z

2.6.5

**Comment by jyash97** [comment]
Fixed in version 3 rc versions Release 💥
