### ISSUE TITLE
Issue with Elastic cluster for  native 

### ISSUE THREAD

**Issue by rouaha** [appbaseio/reactivesearch#384]
**Issue Type:**
Try to search using DataSearch component but after put text I got unhandle promise rejection error.

**Platform:**
 Navite
**Description:**
here is my code
    ``<ReactiveBase
             url ="http://-es-cluster-ip:9200"
            app="crop_type"     // index name though i have multiple indexs
         >
       <DataSearch
             componentId="searchbox"
             dataField ={['id']}
            placeholder="Search"
             autosuggest={true} 
          /></ReactiveBase>

**Screenshots:**
![issue](https://user-images.githubusercontent.com/27863237/40639999-cec31fe4-6335-11e8-8847-837f58592ca7.PNG)

**Reactivesearch version:** x.y.z
"@appbaseio/reactivesearch-native": "^0.7.0",
   "native-base": "^2.2.0",
    "react": "16.0.0-alpha.6",
    "react-native": "0.44.3",

Please provide example with real es cluster.Thanks in advance

**Comment by metagrover** [comment]
Sorry about the delay on this. I tested an app with a local and an aws-hosted cluster and I was able to get things to work smoothly in both the cases. If you can provide more details or setup your project on expo-snack and share with me, I can help debugging this issue.

Make sure that you have the project setup properly. We recently released `v0.8.0`, so you should try upgrading and see if things work for you. You may wanna try:

```bash
watchman watch-del-all && rm -rf node_modules/ && yarn cache clean && yarn install && yarn start --reset-cache
```

Also, if you have multiples indices on your cluster, you can use them via:

```js
app="index1,index2,index3"
```
