### ISSUE TITLE
Multiple field for DateRange (Writing custom elastic queries)

### ISSUE THREAD

**Issue by emrealper** [appbaseio/reactivesearch#386]
Is it possible to use two date field for DateRange component?

The current DateRange component is checking whether the dataField is between date inputs or not.

What if we also want to check for a second elastic field like "CheckOutDate" to add an extra DateRange query works for "First date input" LessThanEqualTo **CheckOutDate** and "Second date input" GreaterThanOrEqualTo **CheckInDate**.

It can be general custom query question please do not only focus the scenario in the above paragraph.

```
   <DateRange
                    dataField="CheckInDate"
                    componentId="DateRangeSensor"
                    title="When"
                    numberOfMonths={2}
                    queryFormat="basic_date"
                    placeholder={{
      start: 'Check-in',
      end: 'Check-out'
  }}
                    initialMonth={new Date('04-01-2017')}
                />
```

**Comment by metagrover** [comment]
We don't support multiple fields with DateRange component at the moment, but you can always write a `customQuery` utilising your desired fields based on the input params.

Learn about [defining custom queries here](https://opensource.appbase.io/reactive-manual/advanced/customquery.html#defining-a-custom-query).
