### ISSUE TITLE
ResultList docs

### ISSUE THREAD

**Issue by rwb196884** [appbaseio/reactivesearch#389]
https://opensource.appbase.io/reactive-manual/result-components/resultlist.html#props

For property `onResultStats` the function parameter names are given but not their order.

Experimentation suggests that the order or the parameters is the reverse order to that in which they appear in the sentence 
> show custom result stats using a function that takes two parameters for `time_taken` and `total_results` and returns a string.

I believe that the function signature is `function (total_results, time_taken)`. It would be helpful to state this in the help rather than leaving us to guess.

**Comment by divyanshu013** [comment]
Thanks for bringing this up, I've updated the docs to make it clearer.
