### ISSUE TITLE
Custom sorting of MultiList items

### ISSUE THREAD

**Issue by baj84** [appbaseio/reactivesearch#390]
**Issue Type:** Enhancement

**Platform:** Web

**Description:**
I'm trying to make it so the MultiList list items are sorted by a specific 'sort' field, the sortBy prop only allows for 'asc', 'desc' and 'count'. It would be awesome you could specify a custom sortBy field.

**Comment by davidklebanoff** [comment]
I'm trying to understand what the desired goal is here. Do you have an example use case?

**Comment by baj84** [comment]
Sure. So I have a 'Level/Floor' filter and these levels have to be in a specific order, so they have an integer order value. I need to be able to sort the list items by this order value. E.g.

```
Mezzanine
Level 10
Level 9
...
Ground Floor
Basement
etc.
```

**Comment by baj84** [comment]
Anyone know a way that this might currently be achieved?

**Comment by sahilchopra** [comment]
+1

**Comment by siddharthlatest** [comment]
This can be achieved now with the `transformData` prop - https://opensource.appbase.io/reactive-manual/list-components/multilist.html.
