### ISSUE TITLE
Better API specs for onResultStats

### ISSUE THREAD

**Issue by divyanshu013** [appbaseio/reactivesearch#392]
**Issue Type:**

Enhancement

**Platform:**

Web

**Description:**

`onResultStats` provides result and time stats and is used as a render function. It's good for rendering data however, we should design the spec in a way which also allows the user to update the state of their app for conditional rendering. Related discussion at #356.

**Reactivesearch version:** x.y.z

2.6.6

**Comment by metagrover** [comment]
Ideally, we should have `onResultStats` for reading purposes and `renderResultStats` for rendering purposes.

**Comment by metagrover** [comment]
Now available in 3.0 (alpha and above)
