### ISSUE TITLE
Cursor jumps to end of input when inputValue is changed when using DataSearch

### ISSUE THREAD

**Issue by Arvind6353** [appbaseio/reactivesearch#394]
Hi , 
I am using Datasearch Component . 
Whenever I try to modify the search value (lets say change the middle character) , the cursor position is going to the end of the input . I guess its rerendering every time . 

Pls suggest a fix . 

I tried the demo sandbox example for datasearch and I face the same issue there .

` <DataSearch
            componentId="searchbox"
            dataField={["title"]}
            fieldWeights={[3]}
            placeholder="Search"
            autosuggest={false}
            highlight={true} />`

**Comment by Arvind6353** [comment]
@divyanshu013  Pls do let me know if you find any soln or workaround to solve this issue

**Comment by Arvind6353** [comment]
@metagrover @siddharthlatest : Do you have any soln or workaround for this issue ?

**Comment by metagrover** [comment]
Sorry, didn't get any time to dive into this 😅

Open to PRs if you can propose a solution to this 🐱

**Comment by Arvind6353** [comment]
@metagrover : I used ReactiveComponent and created a custom input and it solved this issue . 
But the Reactive component provides only an option to add the query . I am not able to find an option to highlight the fields. Can you pls let me know if there is an option for highlighting the results , similar to using setQuery in reactive component.

**Comment by Arvind6353** [comment]
I solved this cursor issue by making some changes in Datasearch component file . I removed some state changes on the field (isOpen) and as I was not using suggestions here , I commented some of the state changes pertaining to it and it worked.

**Comment by Arvind6353** [comment]
@aeronesto : Just comment out the state changes on isOpen field . And if you are not using suggestions , remove the state change on suggestions field as well .

**Comment by aeronesto** [comment]
@Arvind6353  : I tried to do what you said, with combinations of autosuggest & this.state.isOpen set to true/false, but it didn't solve the cursor issue.

I am using @appbaseio/reactivesearch@2.6.2

**Comment by divyanshu013** [comment]
@aeronesto, would you like to send a PR for this?

**Comment by aeronesto** [comment]
@divyanshu013, sure thing.

**Comment by rohit-sourcefuse** [comment]
@aeronesto, I am still facing this issue is it resolved?
Packages versions :
 "@appbaseio/reactivesearch": "^2.8.1"
"react": "16.4.1"

**Comment by divyanshu013** [comment]
Hi @rohit-sourcefuse, it isn't resolved yet.

**Comment by rohit-sourcefuse** [comment]
@divyanshu013, Thanks for your reply any suggestion on this? 
How to fix this issue at our end without messing with reactive search code?

**Comment by divyanshu013** [comment]
At the moment you can use [`ReactiveComponent`](https://opensource.appbase.io/reactive-manual/advanced/reactivecomponent.html) to create a custom component. Haven't gotten the time to dive into the issue yet in the `DataSearch` component but PRs are welcome. There has been some discussion about the issue in the comments above if you want to take a shot :)

**Comment by aeronesto** [comment]
@rohit-sourcefuse I just submitted the [PR](https://github.com/appbaseio/reactivesearch/pull/493/commits/61e08014fdf9d7657affd9bdd1b12e0d19e33608) to fix this.

**Comment by divyanshu013** [comment]
Available now in v2.8.2
