### ISSUE TITLE
Best way to get the values selected via MultiList(refinement list)

### ISSUE THREAD

**Issue by Arvind6353** [appbaseio/reactivesearch#398]
Hi , 
I have many multi list components for filtering . 

What is the best way to get the values being selected on each of these filters . Lets say there is a single method to get the current filters state . 

I see that there is a method on ResultList - onQueryChange . I see that it gives the updated query each time a filter is selected . But is there a method that can quickly get the filters selected instead of onquerychange

**Comment by Arvind6353** [comment]
@metagrover : Thank you . I have more than 5 multilist components and so I have to hookup this onvaluechange on each of the component right ?.

**Comment by metagrover** [comment]
Yes, you will have to add it to every component.

I will keep this issue updated regarding the specs and implementation for `SelectedFilters` getter/event for the same.

**Comment by karetfe** [comment]
Hi @Arvind6353  How you resolve this point? using onValueChange()? @metagrover  the issu still Open, is there a new enhancement for it?

**Comment by metagrover** [comment]
@karetfe Yes, `onValueChange` should work. Refer [docs here](https://opensource.appbase.io/reactive-manual/list-components/multilist.html#extending).

**Comment by bietkul** [comment]
Check the new [StateProvider](https://opensource.appbase.io/reactive-manual/base-components/stateprovider.html) component, which solves these problems efficiently.
