### ISSUE TITLE
New component: RatingsFilter

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivesearch#4]
### Component Props

- **componentId** `String`  
    component ID.
- **appbaseField** `String`  
    DB field to be mapped for the query.
- **title** `String` [optional]  
    title of the component, optional.
- **data** `Object Array`  
    an array of objects with `start`, `end` numeric values and `label` as either string or HTML.
```
{[
  {"start": 4, "end": 5, "label": "4 stars and up"}, 
  {"start": 3, "end": 5, "label": "3 stars and up"}, 
  {"start": 1, "end": 5, "label": "> 1 stars"}
]}
```
- **defaultSelected** `Object`  
    pre-selected ratings value, specified with `start` and `end` keys, values should match one of the elements in the **data** array prop.

### CSS Styles API

`rbc-title-active`

For a selected item, there should be a `rbc-active` class.

### Stories

1. Basic story
2. With default selected values
3. with dark theme
4. Playground.

**Comment by metagrover** [comment]
Added here: 7efded28f13eeb34fbdd7052882bcdfc1a88b0a6 6546ff28a6e7adf5356c1ad20b5b2124e9802b0a b635b86635d7b205dcf5f00c4473c78bf4ac6277
