### ISSUE TITLE
Add onFilterCleared prop to SelectedFilters

### ISSUE THREAD

**Issue by calebdel** [appbaseio/reactivesearch#401]
**Issue Type:**
Enhancement

**Platform:**
Web

**Description:**
Add a new prop `onFilterCleared` to `SelectedFilters` that will be invoked with the value of the selected filter being cleared or it will indicate that all filters have been cleared.

**Reactivesearch version:**
2.6.2

**Comment by vivek12345** [comment]
@metagrover Any example with the code which renders filters?I have figured out how to do this, but I can't seem to figure out from the documentation as to how do I create a list with filters in it.

**Comment by vivek12345** [comment]
Actually I figured out how to add filters.

**Comment by metagrover** [comment]
Sure, we have the [components playground](https://opensource.appbase.io/playground/?selectedKind=Base%20components%2FDataController&selectedStory=Basic&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs) as a submodule in this project that you can start with - which runs on the storybook, or alternatively, [web examples](https://github.com/appbaseio/reactivesearch/tree/dev/packages/web/examples) should come handy.

[SelectedFilters docs](https://opensource.appbase.io/reactive-manual/base-components/selectedfilters.html) is a good starting point. Here, we need to add support for `onFilterCleared` prop as mentioned above.

Thanks for taking out time to look into this 👍

**Comment by vivek12345** [comment]
@metagrover should this be called also when someone unchecks the filter or only when I click on the cross icon of the filter to clear it?

**Comment by metagrover** [comment]
I think the best thing to do here is to only call this function when there is an interaction with the `SelectedFilters` component, i.e. a filter is cleared. We can call this prop as `onClear`.

Also, in order to watch for the changes on the `SelectedFilters`, it'd be best to do that via `onChange` method, which will be executed anytime there is a change (addition or removal) in selected-values from the redux store.

**Comment by vivek12345** [comment]
Alright that's a fair point.I am thinking how will I determine the interaction.Filters can be anything right.A dropdown, a checkbox or something else?

**Comment by vivek12345** [comment]
Okay I think may be setValue can help here because that is called if something set or removed.What do you think?

**Comment by metagrover** [comment]
Ideally, you should watch for the changes on the `selectedValues` from the redux store via `componentWillReceiveProps` method. But don't worry about that, we don't need to implement that right now - until a valid use-case pops up.

We should only focus on the `onClear` here for now 🐱

**Comment by vivek12345** [comment]
well in that case, this should do the job
```
remove = (component, value = null) => {
  this.props.setValue(component, null);
  this.props.onFilterCleared && this.props.onFilterCleared(value);
};
```

**Comment by metagrover** [comment]
Yes, we should keep things consistent with the values. Also, the function should be called `onClear` and should also return the `componentId` as well.

So the signature should look like: `onClear(componentId, value)` where value van be an array or a string.

Still not sure about the clearAll event though. Open to suggestions. @divyanshu013

**Comment by vivek12345** [comment]
Alright understood.For the value here should I send the value as 
```
[
  {
    "start": 0,
    "end": 3,
    "label": "Rating < 3"
  },
  {
    "start": 3,
    "end": 4,
    "label": "Rating 3 to 4"
  }
]
```
Like this or with just the label?

**Comment by metagrover** [comment]
Yes, the entire `value` object should do the trick since we do some parsing at our end to render the labels.

**Comment by calebdel** [comment]
@vivek12345 Thanks, this looks great! @metagrover will this be released soon?

**Comment by metagrover** [comment]
Thanks for the patience on this guys. We will roll it out in this week.
