### ISSUE TITLE
Infinite scrolling not working in IE 11

### ISSUE THREAD

**Issue by baj84** [appbaseio/reactivesearch#402]
**Issue Type:**
Bug

**Platform:**
Web

**Description:**
Infinite loading doens't work in IE 11. This is true on the examples (in storybook) too. There are no errors. Is this a known issue? If so, is anyone able to point me in the right direction to fix it?

Thanks!

**Screenshots:**

**Minimal reproduction of the problem with instructions:**

**Reactivesearch version:** Stable

**Browser:** IE 11

**Comment by baj84** [comment]
Beautiful!

**Comment by divyanshu013** [comment]
Available now 👌
