### ISSUE TITLE
Pass the query string parameter from html page to reactivesearch

### ISSUE THREAD

**Issue by allendol** [appbaseio/reactivesearch#404]
**Issue Type:**

**Platform:**

**Description:**

I need to pass the query string parameter from html page to reactivesearch. The parameter should be passed to defaultSelected prop of DataSearch component. I thought this could be done via javascript. Apparanetly that is not the right way. Any detail will be helpful.

**Screenshots:**

**Minimal reproduction of the problem with instructions:**

**Reactivesearch version:** x.y.z

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**

**Comment by metagrover** [comment]
Not sure if I understand this correctly, but if you pass the data as URL param with the id as that of the component you want to pass it to, the component should be able to set that as the selected value. For example:

If I want to pass 'hello' to the 'search' component, I can just do `http://myapp.com/?search='hello'`. Notice how I'm stringify-ing the 'hello' here when I pass it to the URL.

Hope that helps.
