### ISSUE TITLE
Datasearch do a strict match query using "" (exact phrase match)

### ISSUE THREAD

**Issue by Arvind6353** [appbaseio/reactivesearch#406]
Hi ,

I am using datasearch with queryFormat as "or".

Is there a way by which when the user types "react js" (note the " " between the string) , the results matches the whole of 'react js' (similar to the queryFormat=and) and in other cases does a queryFormat = 'or'

**Comment by Arvind6353** [comment]
@siddharthlatest : Ok thank you . But does datasearch support wildcard search ?

**Comment by siddharthlatest** [comment]
@Arvind6353 Are you referring to https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-wildcard-query.html? You can always use a `customQuery` prop to override the default search query being used by DataSearch component.

**Comment by Arvind6353** [comment]
@siddharthlatest : Thank you :). And regarding your previous suggestion about using state variable , 
I would have to update the queryFormat whenever an onvalueChange event happens and based on the value being entered by the user , I will update the state to either 'or' or 'and' . AM I right ?.

**Comment by Arvind6353** [comment]
@siddharthlatest @divyanshu013  : Query format = 'and' is not equal to the exact phrase match using "". Is there a way exact phrase match can be done via datasearch

**Comment by siddharthlatest** [comment]
You can do that by using the keyword datatype field (which doesn't apply analysis) in the DataSearch's `dataField` prop.
