### ISSUE TITLE
Result of defaultSelected function not evaluated by isEqual

### ISSUE THREAD

**Issue by pparke** [appbaseio/reactivesearch#407]
It looks like the change from `types.range` to `types.func` in https://github.com/appbaseio/reactivesearch/commit/c04b5e0f391f56b37a4e749d77bdad00158f1223 didn't account for `isEqual` not evaluating functions.  `isEqual` only checks the constructor of the object passed to it which does not work for comparing two functions.  Passing the result of the compared functions in to `isEqual` may be a solution.

https://github.com/appbaseio/reactivesearch/blob/d1c81b3da5b0f19f6b9423d45b67e80fe0fe0fb0/packages/web/src/components/range/DynamicRangeSlider.js#L80

**Comment by metagrover** [comment]
Will be out in `v2.9.0`
