### ISSUE TITLE
Allow index to be specified as part of a customQuery

### ISSUE THREAD

**Issue by krsnaa** [appbaseio/reactivesearch#408]
**Issue Type:**
enhancement

**Platform:**
web

**Description:**
Having to specify an app name in RectiveBase is very restrictive for scenarios where a categorical search needs to be applied on the same field across indices - especially now where ElasticSearch has restricted 1 type per index. Additionally, there are legitimate use-cases where the result expected is an amalgamation of fields from across indices. 

Restricting all operations and results to a single index is overly simplistic. At the very least, customQueries should enable one to access any index across a single server connection in ReactiveBase.

If however there is an existing way to do this, please let me know as I have been unable to find it despite an exhaustive look through the documentation and source code.

**Comment by siddharthlatest** [comment]
@krsnaa `appname` can take multiple indexes: you have to separate them by comma. Does that help?

**Comment by krsnaa** [comment]
@siddharthlatest - Wow! that definitely helps. Thank you so much!!
Perhaps this could be reflected on the ReactiveBase [doc](https://opensource.appbase.io/reactive-manual/getting-started/reactivebase.html)?

Thanks again; this is awesome.

**Comment by siddharthlatest** [comment]
This was a recent addition. I have updated the doc as well, thanks for the pointer!
