### ISSUE TITLE
Using Lucene Syntax in custom query 

### ISSUE THREAD

**Issue by Arvind6353** [appbaseio/reactivesearch#409]
Hi , 
I am trying to provide a way for the user to search using lucene syntax (eg: title : test).

I am using data search component and whenever the user starts typing , its doing the search . 

Is there a way where we can disable this option and have a search button which on being clicked executes the search ?.

**Comment by Arvind6353** [comment]
@divyanshu013 @siddharthlatest @metagrover : Any suggestions on the above ?

**Comment by divyanshu013** [comment]
Hi, I think it would be best to create your own component for this, since it would give you full control. Please check out `ReactiveComponent` https://opensource.appbase.io/reactive-manual/advanced/reactivecomponent.html

**Comment by Arvind6353** [comment]
@divyanshu013 : Ok thank you
