### ISSUE TITLE
Is it possible to hide DataSearch component?

### ISSUE THREAD

**Issue by allendol** [appbaseio/reactivesearch#410]
**Issue Type:**

**Platform:**

**Description:**

Is it possible to hide DataSearch component? User has its own search control on the page with its own header, footer, etc. They can pass the search phrase to DataSearch component and it is working fine. But they don't want to see two search controls visible on the page and they don't want to give up their search control. 

**Screenshots:**

**Minimal reproduction of the problem with instructions:**

**Reactivesearch version:** x.y.z

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**

**Comment by divyanshu013** [comment]
If you wish to visually hide the component, one way is to use CSS and make it `display: none`. Example,

```js
<DataSearch
  style={{ display: 'none' }}
  ...
/>
```
