### ISSUE TITLE
Hightlight support in Reactive component

### ISSUE THREAD

**Issue by Arvind6353** [appbaseio/reactivesearch#412]
Hi , 

Is there a way I can provide highlight option when using a Reactive component.

There is a setQuery method but it only handles the query portion . 

This higlight feature is available with Dataasearch though , but am using ReactiveComponent to create a custom search box to fix the cursor position issue . 

Let me know if there are any options

**Comment by Arvind6353** [comment]
@metagrover @divyanshu013 : Do u guys have any suggestion for handling highlight with ReactiveComponent ?

**Comment by mindis** [comment]
same issue

**Comment by metagrover** [comment]
As of the cursor position issue mentioned here in this issue, it has been fixed for a while now.

---

If you still want to add a highlight query in ReactiveComponent, you can use <strike>`customQuery` (if using v3) (or)</strike> `defaultQuery` prop <strike>(or) `setQuery` method in children components</strike> based on your needs.

**Comment by mindis** [comment]
Would you be able to spot why I can't get highlights in product matches in the following setup. 
I'm using two separate indices "products" and "brands".
User is shown list of brands from "brands" index. If user clicks one of displayed brands a query with selected brand is executed on "products" index.
For some reason matching snippets are not highlighted.

Version: v3 

### App.js

```
import React, { Component } from 'react';
import { ReactiveBase, ResultList,ReactiveComponent } from '@appbaseio/reactivesearch';
import CustomComponent from './CustomComponent';


class App extends Component {
	
  render() {
	  
    return (
      <section className="container">
	  
        <ReactiveBase
           app="brands,products"
           url="http://xx.xx.xx.xx:9200">
		  
			<div style={{ display: "flex", flexDirection: "row" }}>
			<div style={{ display: "flex", flexDirection: "column", width: "40%" }}>

			<ReactiveComponent
				componentId="CarSensor"
				highlight={true}
				
				defaultQuery={() => ({
					aggs: {
						'brand': {
							terms: {
								field: 'brand',
									order: {_count: 'desc',},
									size: 50,
										},
									},
								},
							})}
							
			>
				<CustomComponent />
			</ReactiveComponent>
			
				</div>
			
			<ResultList
				componentId="ResultList"
				dataField="name_unigram_no_stemm"
				stream={true}  
				size={15}
				pagination={true}
				showResultStats={true}
				loader="Loading Results.."
				react={{and: ["CarSensor"]}}
				renderData={this.carsList}
			/>

			</div>
			
		 </ReactiveBase>
      </section>
    );
  }
  
  carsList(data) {
		return {
			title: (
			<div dangerouslySetInnerHTML={{ __html: data['name_unigram_no_stemm'] }}/>
			)
		};
	}
 
}
export default App;

```

### CustomComponent.js

```
import React, { Component } from 'react'; 


class CustomComponent extends Component {

	render() {
		if (this.props.aggregations) {
			return this.props.aggregations['brand'].buckets.map(item => (
			<div key={item.key} 
			onClick={() => {     
				const query ={
					"bool": {
						"must": [
							{"query_string": {"query": item.key}},
							{"terms": {"_index": ["products"]}}
								]
							}
							};
                    this.props.setQuery({query})
                }}

				>
					{item.key}
					
				</div> 
			));
		}
		
		return null;
	}
}  
export default CustomComponent;  

```

**Comment by metagrover** [comment]
You need to set the highlight query in elasticsearch. Please refer docs here: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-highlighting.html

**Comment by mindis** [comment]
Still can't get it working.
Added highlight to query.  Query works from python.

```
				const query ={
						"query": {
						    "bool": {
						      "must": [
								{"term" : {"name_unigram_no_stemm" : item.key}},
								{"terms": {"_index": ["products"] }}
									]
									}
								},
						"highlight" : {"fields" : {"name_unigram_no_stemm" : {}}}
					};
```

I've looked at the request payload generated by reactivesearch and it seems that highlight is not passed to elasticsearch. 

Request Payload if I select brand "formula" 

{"preference":"ResultList"} 
{"query":{"bool":{"must":[{"bool":{"must":[{"bool":{"must":[{"term":{"name_unigram_no_stemm":"formula"}},{"terms":{"_index":["products"]}}]}}]}}]}},"size":15,"_source":{"includes":["*"],"excludes":[]},"from":0}

**Comment by metagrover** [comment]
Check this codesandbox example - https://codesandbox.io/s/o7lvno2kq9 (using a dummy query here, but it should help)

**Comment by mindis** [comment]
thanks, but in your example if I replace line 73 with  {data.brand} I should expect the brand in results to be highlighted, but it isn't?

**Comment by metagrover** [comment]
I just added that as a dummy for highlight query usage with `defaultQuery`. Check this functional example here: https://codesandbox.io/s/y39x51lx0x

**Comment by mindis** [comment]
thanks, but I expected that after clicking any brand, the results of brand to be highlighted. Example only highlights hard coded "Ford". Sorry I miss something obvious here.

**Comment by metagrover** [comment]
No worries. Here you go - https://codesandbox.io/s/xlyvl0o07p

I'm now updating the relevant query from `setQuery` of the custom component - instead of the fixed query like before.

**Comment by mindis** [comment]
Thanks, now it works :)
