### ISSUE TITLE
Feature: Allow including / excluding fields from the hits in Result Components

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivesearch#417]
**Issue Type:**

Enhancement

**Platform:**

Web, should apply to native as well

**Description:**

Elasticsearch allows [source filtering](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-source-filtering.html) of results by using the `_source` key on the /_search endpoint.

Possible prop names for doing this can be `includeData` and `excludeData`.

We should support this behavior in ReactiveSearch's result components. Reference question: https://stackoverflow.com/questions/50880533/how-to-filter-source-in-reactivesearch.

**Comment by bietkul** [comment]
Instead of defining props like `includeData` & `excludeData`, Can we have a prop like `queryOptions`, in which user can define a set of extra query options, which is more scalable.
And the main advantage of this prop, user don't need to wait from our side ( to include the option ), if a particular option is not present in the prop list.

For eg
```ts
queryOptions = {{
   _source: {
      includeFields: ['*'],
      excludeFields: ['text'],
  }
}}
```
Note: We can provide the frequently used options as props, & can also provide an extra `queryOptions` prop to extend the options further.

**Comment by siddharthlatest** [comment]
I like the idea of segmenting less used props into a sidecar prop. In this case though, `includeFields` and `excludeFields` (more appropriate imo than `includeData` and `excludeData`) props are important in the Result components as they affect the network latency perf.

The props should look like:

```
includeFields: {['*']}
excludeFields: {['revenue']}
```

**Comment by bietkul** [comment]
Cool, so apart from `includeData` & `excludeData` we can expose one more prop like `queryOptions` which can be used if an option is not supported by us (as a prop).

**Comment by mtxr** [comment]
#464 wonderful!

**Comment by siddharthlatest** [comment]
- [ ] Can we add this to docs, and then close the issue?

**Comment by siddharthlatest** [comment]
@bietkul I am testing this feature and the current implementation is a flawed one. There is no source filtering happening at the query level, so all the results are returned back as is. Can you reference the commit where this support was added? cc @metagrover

**Comment by bietkul** [comment]
@siddharthlatest I'm just appending the `_source` property in the query options which can have `include` & `exclude` properties.
https://github.com/appbaseio/reactivecore/pull/13/files
