### ISSUE TITLE
DateRange dataField prop should accept both string and array

### ISSUE THREAD

**Issue by metagrover** [appbaseio/reactivesearch#421]
**Issue Type:**
Bug

**Platform:**
Web

**Description:**
We should accept both string and array in the [dataField's propTypes here](https://github.com/appbaseio/reactivesearch/blob/dev/packages/web/src/components/date/DateRange.js#L401).

Related: https://github.com/appbaseio/reactive-manual/issues/87

**Comment by vivek12345** [comment]
@metagrover This https://github.com/appbaseio/reactivesearch/pull/426
Takes care of this change too

**Comment by metagrover** [comment]
Thanks for contributing @vivek12345 💯 

We will roll this out in the upcoming release.
