### ISSUE TITLE
What is the best way to show loading or side effect

### ISSUE THREAD

**Issue by lan-nguyen91** [appbaseio/reactivesearch#422]
**Issue Type:** Suggestion

**Platform:** Native

**Description:** How to show Loading when processing search

**Reactivesearch version:** 0.8.0

Hi team, and thanks for this awesome module

I am running into scenario, where if my search comeback with empty data, I would like to display a not found Component. Something like :arrow_double_down: 

![no_result](https://user-images.githubusercontent.com/14827876/41812555-06ad40d0-76da-11e8-8707-fd044612c329.png)

I can use the hook `onAllData`, and check the result length, not sure if that is the best solution.

Also if I use onAllData, there is a second or two delay after searching, so ideally I want to display a spinner, what would be the best way to accomplish this.
I know there is a loading for infinite scroll for web version, but im not sure if I can do something similar for native.

**Comment by siddharthlatest** [comment]
Hi @lan-nguyen91, you can do both of those using the following props:
`loader` to load the data and `onNoResults` to render JSX of your choice when no results are found. You can find more info on the props here - https://opensource.appbase.io/reactive-manual/result-components/reactivelist.html#props.

**Comment by siddharthlatest** [comment]
I just saw that you filed this issue for `Native`. I am not sure if we support these props over there yet. cc @metagrover

**Comment by lan-nguyen91** [comment]
@siddharthlatest  yes it is in the native codebase now that I checked the code. It is just not release and documented yet. Thanks :)

**Comment by metagrover** [comment]
Thanks for pointing this out. We will do a native release shortly.
