### ISSUE TITLE
Result Card does not accept a custom component

### ISSUE THREAD

**Issue by soflass1293** [appbaseio/reactivesearch#427]
**Issue Type:**
'enhancement'

**Platform:**
Web

**Description:**
**Enhance Result Card to accept a custom component**
I am using React Material-UI library so I wanted to make a Result List using Card items, but the issue is that it renders itself as a list (only vertical). So I checked the Result Card but it cannot accept a component, it only accept a specific object.  
Thanks.

**Comment by metagrover** [comment]
You can use [ReactiveList](https://opensource.appbase.io/reactive-manual/result-components/reactivelist.html) instead, and easily render custom markup as you please 😸

**Comment by soflass1293** [comment]
Hello
I tried it but it has the same issue, it renders items each one in the whole row. For example I want to have 4 items in one row, that an be done in Result Card.
The problem in Result Card is not customizable, the only way I found is to inject the component in the description field 
` onData={(res) => {return {
     description: <GridItem />
}}}`
but the problem is that it is in a field and it shows the border of the original card.

I have attached 3 images of examples:
Reactive List, Result Card and Result List.
I want the result to be similar to Result Card but using a custom component
` onData={(res) => 
          <GridItem />
}`
Reactive List 
![reactivelist](https://user-images.githubusercontent.com/15141013/41848027-00b1b0d0-7874-11e8-8104-6efd4b40c621.png)

Result Card
![resultcard](https://user-images.githubusercontent.com/15141013/41848028-00d65d22-7874-11e8-97fa-30166f2bdf03.png)

Result List
![resultlist](https://user-images.githubusercontent.com/15141013/41848029-00f6cd64-7874-11e8-9561-eaae124aeb05.png)

**Comment by metagrover** [comment]
It's a simple css issue. You can use `flex` or `css-grid` to arrange the components on your screen.

If you want to access the container styling along with this- you can use `onAllData` prop on `ReactiveList`.

**Comment by metagrover** [comment]
This should help:

```js
onAllData(allData, streamData) {
    return (
        <div className="grid">
            {allData.map(item => <h3>{item.propertyName}</h3>)}
        </div>
    );
}
```

`onAllData` expects you to return one element (container) which contains everything you want to render in the results component. Hence, we wrap all the results in one `div.grid`.

**Comment by amirasyraf** [comment]
@metagrover 
Thanks, but it seems allData is returning an object instead of the expected array? So allData.map does not work since Objects do not have a .map method.
