### ISSUE TITLE
MultiIndex search 

### ISSUE THREAD

**Issue by Arvind6353** [appbaseio/reactivesearch#430]
Hi , 

I have a query regarding using multiple indices for search .

I am currently having a single Root reactivebase component to which I am setting an index name and elastic search url. 

Am looking for a way where in I can specify the list of indices and I would get the results combined from all the given indices . Is this possible ?

**Comment by divyanshu013** [comment]
Yeah, try using comma separated indices in your `app` prop. Check [this](https://stackoverflow.com/a/50971593/4952669)

**Comment by siddharthlatest** [comment]
@Arvind6353 Can you close the issue if the above suggestion worked?
