### ISSUE TITLE
Unable to connect with Elasticsearch due to CORS

### ISSUE THREAD

**Issue by waiknott** [appbaseio/reactivesearch#431]
**Issue Type:**
bug

**Platform:**
web

**Description:**
I'm unable to connect to elasticsearch due to CORS. The browser is not triggering a preflight check. I have the appropriate elasticsearch server settings set. One of those settings is access-control-allow-credentials:true.

**Screenshots:**

**Minimal reproduction of the problem with instructions:**
1. Create an elastic search cluster with access-control-allow-credentials= true in the cors settings. Cluster should be on a different domain than the server
2. Connect using the url in ReactiveBase (no need for credentials)
3. Browser doesn't trigger CORS (I get a 405 unauthorized back)

**Reactivesearch version:** x.y.z
2.6.8

**Browser:** Chrome, Firefox, Safari

**Anything else:**

I've solved this with axios in other libraries by setting withCredentials=true. I was able to get this working with reactivesearch by adding credentials:true to the request options fetch_request.js in appbase-js. This works form my use case but probably not for everyone.

**Comment by siddharthlatest** [comment]
@metagrover We can implement this in appbase_js. I believe I have seen this error in a couple of cases as well.

**Comment by siddharthlatest** [comment]
@waiknott What are your elasticsearch.yml settings, can you share all (so we can replicate what you are seeing)?

**Comment by waiknott** [comment]
Unfortunately I have an NDA in place that prevents me from sharing all of them. 

The relevant ones (about CORS):
http.cors.enabled:true
http.cors.allow-origin: /https:?:\/\/.*/redacted\.com(:[0-9]+)?/
http.cors.allow-headers: x-requested-with, content-type, content-length, authorization, accept
http.cors.allow-credentials:true

**Comment by metagrover** [comment]
@bietkul can you check on this?

**Comment by bietkul** [comment]
Yes, we have the support for `credentials` in appbase.js > 4.0.
