### ISSUE TITLE
Searching nested objects <question> <enhancement>

### ISSUE THREAD

**Issue by aeronesto** [appbaseio/reactivesearch#432]
**Issue Type:** enhancement, question

**Platform:** Web

**Description:**
I have a nested object in one of my fields; I am indexing pdf content and my 'authors' field has an object for each author:

```js
authors: {
    { 'author' : 'John Doe' },
    { 'author' : 'Jane Doe' }
}
```
I would like to use `<DataSearch/>` to search for a specific author in the 'authors' field. I've tried setting the `dataField` prop to both `'authors'` and `'authors.author'`, but neither of these will return any results.

I read in this [question](https://stackoverflow.com/questions/26258292/querystring-search-on-array-elements-in-elastic-search) that the query should look like this:

```js
{
  "query": {
    "nested": {
      "path": "authors",
      "query": {
        "bool": {
          "must": [
            { "match": {"authors.author": "john doe"}},
            { "match": {"authors.author": "mary jane"}}
          ]
        }
      }
    }
  }
}
```

How can I extend the `<DataSearch/>` component to search within each `authors.author` field?

**Reactivesearch version:** 2.6.2

**Browser:** Chrome XX

**Anything else:**
I tried having my `authors` field as an array of strings, and `<DataSearch/>` would not autosuggest after typing more than one character. E.g. typing 'j' would return:

```js
suggestions = [
    john doe
    jane doe
    mary jane
]
```

but typing 'ja' would not return any suggestions. However, submitting 'jane' would correctly return results with 'jane' in the `authors` field, even though `suggestions` was empty.

**Comment by siddharthlatest** [comment]
@aeronesto Can you share the mappings object of your `authors` field?

**Comment by aeronesto** [comment]
"mappings": {
      "doc": {
        "properties": {
          "authors": {
            "type": "nested",
            "properties": {
              "author": { "type": "text" }
            }
          },
        }
      }
    }

**Comment by aeronesto** [comment]
It looks like `dataField="authors.author"` doesn't work because [nested documents](https://www.elastic.co/guide/en/elasticsearch/reference/6.x/nested.html) need(?) to be 

> queried with the nested query. 

I changed `finalQuery` in DataSearch.js to the following returned query, and it did return the correct results when there was an exact field match (e.g. value === 'jane'), but returned no results for an incomplete match  (e.g. value === 'jan'). I tried replicating this by setting `customQuery` in `<DataSearch>` props, but it did not work:

```js
customQuery={ (value,props) => {
  return {
    "query": {
      "nested": {
        "path": "authors",
        "query": {
          "bool": {
            "must": [
              { "match": { "authors.author":  value }}
            ]
          }
        },
        "inner_hits": {
          "highlight": {
            "fields": {
              "authors.author": {}
            }
          }
        }
      }
    }
  }
}}
```

**Comment by siddharthlatest** [comment]
@aeronesto Can you remove the `query` key and just pass the object with the query starting from the `nested` key?

I am filing a separate issue for us to handle this at the library level going forward, as it can be confusing when and when not to include the query key.

**Comment by aeronesto** [comment]
Here is my `<DataSearch>` component with props. `dataField` is also set to "authors.author".

```js
<DataSearch // text
	componentId="authors"
	dataField="authors.author"
	defaultSelected={query.authors ? query.authors : ``}
	placeholder="Search authors"
	autosuggest={true}
	URLParams={true}
	customQuery={ (value,props) => {
	  console.log(value,props)
	  return {
	    "query": {
	      "nested": {
	        "path": "authors",
	        "query": {
	          "bool": {
	            "must": [
	              { "match": { "authors.author":  value }}
	            ]
	          }
	        },
	        "inner_hits": {
	          "highlight": {
	            "fields": {
	              "authors.author": {}
	            }
	          }
	        }
	      }
	    }
	  }
	}}
	react={{
		"and": ["searchbox", "topics"]
	}}
/>
```

**Comment by aeronesto** [comment]
However, it still has to be an exact field match as mentioned above, which is fine for my purpose. Partial matches (value="Joh") will not match `authors.author="John Doe"`. Autosuggest will also not work until it's an exact field match.

**Partial match:**
<img width="453" alt="screenshot 2018-06-28 09 01 53" src="https://user-images.githubusercontent.com/13804518/42042878-56f785a6-7ab2-11e8-98e2-ddc7f8bb6e66.png">

**Exact match:**
<img width="449" alt="screenshot 2018-06-28 09 02 05" src="https://user-images.githubusercontent.com/13804518/42042879-571a645e-7ab2-11e8-89af-6fa6b4982e97.png">

**Comment by siddharthlatest** [comment]
For it to work on partial search query, you should use an n-gram like mapping. You can read about it over here - https://opensource.appbase.io/reactive-manual/getting-started/data.html#custom-analyzers.

**Comment by davidkong0987** [comment]
Is simply adding the analyzers enough? How are these analyzers applied? 
My current issue is I cannot get autocomplete to suggest words with accents in them. I know these analyzers should be able to solve the problem but I don't know how to apply it.

**Comment by davidkong0987** [comment]
For example, I have the following mapping.
What tells reactivesearch to search in _name.ascii and _name.ascii2?
It seems like autosuggest works even when I don't have these two subfields.

```
"_name": {
                "type": "text",
                "fields": {
                    "keyword": {
                        "type": "keyword",
                        "ignore_above": 256
                    },
                    "ascii": {
                        "type": "text",
                        "analyzer": "autosuggest_analyzer"
                    },
                    "ascii2": {
                        "type": "text",
                        "analyzer": "ngram_analyzer"
                    }
                }
            },
```
