### ISSUE TITLE
BUG: MultiList throws exception in componentWillReceiveProps

### ISSUE THREAD

**Issue by csepulv** [appbaseio/reactivesearch#436]
I've run into a possible bug in `MultiList` and `MultiDropdownList`. (It might occur in other components as well.) 

I have situation with conditional rendering, where the parent of the filter component varies based on certain conditions. A simplified example of this would be
```
render(){
    return (
	        {someCondition &&
			<div id="parentA">
			  <SearchFilters />
			</div>}
		{!someCondition &&
			<div id="parentB">
			  <SearchFilters />
			</div>}
     )
}
```

I created a simple example of this at [https://github.com/csepulv/reactivesearch/tree/multi-list-bug](https://github.com/csepulv/reactivesearch/commit/4fcbc235f90f797bc0cc552dafb96e9ea8d4707b), by modifying the GitXplore demo app.

There is a button: "Toggle Filter Parent". Press it and you'll see the exceptions in the console, such as
```
index.js:66518 Uncaught TypeError: Cannot read property 'language.raw' of undefined
    at index.js:66518
    at checkPropChange (index.js:1015)
    at MultiDropdownList.componentWillReceiveProps (index.js:66516)
    at callComponentWillReceiveProps (index.js:41317)
    at updateClassInstance (index.js:41509)
    at updateClassComponent (index.js:42943)
    at beginWork (index.js:43614)
    at performUnitOfWork (index.js:45653)
    at workLoop (index.js:45692)
    at HTMLUnknownElement.callCallback (index.js:29890)
...
index.js:44016 The above error occurred in the <MultiDropdownList> component:
    in MultiDropdownList (created by Connect(MultiDropdownList))
    in Connect(MultiDropdownList) (created by SearchFilters)
    in div (created by Styled(div))
    in Styled(div) (created by SearchFilters)
    in div (created by Styled(div))
    in Styled(div) (created by SearchFilters)
    in SearchFilters (created by Header)
    in div (created by Header)
    in nav (created by Styled(nav))
    in Styled(nav) (created by Header)
    in Header (created by App)
    in div (created by Styled(div))
    in Styled(div) (created by App)
    in div (created by Styled(div))
    in Styled(div) (created by URLParamsProvider)
    in URLParamsProvider (created by Connect(URLParamsProvider))
    in Connect(URLParamsProvider) (created by ReactiveBase)
    in Provider (created by ReactiveBase)
    in ThemeProvider (created by ReactiveBase)
    in ReactiveBase (created by App)
    in section (created by Styled(section))
    in Styled(section) (created by App)
    in App

React will try to recreate this component tree from scratch using the error boundary you provided, ReactiveBase.
logCapturedError @ index.js:44016
logError @ index.js:44055
callback @ index.js:44737
callCallback @ index.js:40668
commitUpdateQueue @ index.js:40712
commitLifeCycles @ index.js:44167
commitAllLifeCycles @ index.js:45252
callCallback @ index.js:29890
invokeGuardedCallbackDev @ index.js:29928
invokeGuardedCallback @ index.js:29977
commitRoot @ index.js:45393
completeRoot @ index.js:46408
performWorkOnRoot @ index.js:46353
performWork @ index.js:46272
performSyncWork @ index.js:46244
interactiveUpdates$1 @ index.js:46509
interactiveUpdates @ index.js:31940
dispatchInteractiveEvent @ index.js:34322
index.js:47572 An error has occured. You're using Reactivesearch Version: 2.6.8. If you think this is a problem with Reactivesearch, please try updating to the latest version. If you're already at the latest version, please open an issue at https://github.com/appbaseio/reactivesearch/issues
```

I am looking into a workaround, but I am hoping there is an easy fix.

**Comment by metagrover** [comment]
The problem here seems to be with your arrangement. Here's what's happening with the code:

Since you're mounting and un-mounting the same component (due to conditional rendering logic here) in no particular order. At times, mount will be fired first and unmount later (based on the state) - these events control the addition and removal of components from the reactivesearch-redux-store.

Hence, if you are only planning on changing the container ids, you should use template literals to generate the container ids instead of conditional rendering to prevent the remounts:

```js
id={`${condition ? 'id-1' : 'id-2'}`}
```

Else, if you want to use the conditional rendering for any use-case, I suggest you to update the `componentId`s of all components present in the `SearchFilters` component - based on the parent component's state - in order to help the store track the mounting and un-mounting of these components.

**Comment by csepulv** [comment]
Sorry, I missed this. I will try having different componentIds and keeping them in sync with the various `react` properties of components that need to be kept in sync. 

I will close this and create a new ticket if I run into a problem with the approach above.
