### ISSUE TITLE
E-commerce: Dealing with Variable Product Attributes/Features

### ISSUE THREAD

**Issue by coommark** [appbaseio/reactivesearch#437]
I'm not sure if this is a question or a request for enhancement, I apologize if this belongs to StackOverflow. Kindly help point me in the right direction.

When developing e-commerce solutions, different categories or product have different attributes or features. For instance, **Computers** category would have "**RAM, ROM, Color, Processor Speed, etc**" whereas **Cars** category would have "**GearBox, Millage, FuelType, etc**". Now check [Dejavu Cars Index here](https://opensource.appbase.io/dejavu/live/#?input_state=XQAAAAJyAQAAAAAAAAA9iIqnY-B2BnTZGEQz6wkFsta-jK5IyCHPDQHd0vFqnW3IIPckWf81EYz6c9_C1aGQkSbGptS4zcGd_lZI2UVGi7gEHVqkGAZzrbpw4o5m3TwqV4NeFg28vpiRpym93H_qNbHlhW-E-rshKilAIbFuX55jxDMZbf1w2IFFu3E53Z94IWqIQNoph1e6eLSdgJayO4t1zKlFlbEXWQUNYT48uoqpx-FxjnA5b5u_2mSfoN7w7QvL8MMUiQ6k7M8_s8un_BT_mYTom-RLRXuewvRVZqxKaDi-EgijIKwT54HL06h-BAPzogs5BxY6GcKOsNUtXbad2CNhvnqCId5lMLYVgcuesUavs37XYzpwHBjLnGL_eSw8AA&editable=false), and note that all the car attributes are listed. 

My question is, in a scenario where you have different catogories of product - cars, clothes, phone, groceries, etc, what is the best or practical way to handle that in respect to ReactiveSearch? Create mappings for each and every possible attribute?

**Comment by divyanshu013** [comment]
I think one way to do this is have a field which contains all your attributes. For example, check the [GitXplore](https://appbaseio-apps.github.io/gitxplore-app/) app demo where all the repo topics reside in a single `topics` field and then I'm using a `MultiDropdownList` to display them.

**Comment by coommark** [comment]
@divyanshu013 Thank you! I had just discovered that after posting the question. Yes that's one practical way to take care of it. I'm also reading up on Elasticsearch to find if it is discouraged to have each attribute created in the index and just have them as null where not applicable. (I'm new to ES, my experience is with Lucene.) That way I can only use the relevant filters on the specific category pages. I really want to be able to use it as Vehicle Type filters as per the [E-commerce Demo](https://opensource.appbase.io/reactivesearch/demos/ecommerce/). Not sure the topics sample above can be easily displayed as checkboxes.

Thank you a million for the response!

**Comment by divyanshu013** [comment]
You're welcome. You can easily display the topics as checkboxes using `MultiList` instead of `MultiDropdownList` :)

**Comment by coommark** [comment]
Perfection! Let me start right away. This is the best!
