### ISSUE TITLE
Show PoweredBy logo on actuator on height condition

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivesearch#44]
We should only show "PoweredBy" logo on the actuator when component's current height >= 300px.

Reference: https://github.com/appbaseio/reactivebase/issues/72

**Comment by metagrover** [comment]
Fixed here: 83aa6541e086ff2a087241be12639e1ffa287aed, [f24e652](f24e652cf3b0c1d516d60ac3280b085c34a8528a) and [06eb468](06eb468008e00bd8178961fd4881b5292b03ecfb)
