### ISSUE TITLE
Feature: Add support for resultstats on ReactiveMap component

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivesearch#443]
**Issue Type:**

Enhancement

**Platform:**

Web

**Description:**

Add support for showing resultstats on ReactiveMap component.

**Reactivesearch version:** x.y.z

Latest

**Comment by yogesh27** [comment]
I am looking for this feature. Appreciate it.

**Comment by preritmohan** [comment]
Looking forward to this addition.

**Comment by bietkul** [comment]
We already support this behaviour in RS v3.x.
