### ISSUE TITLE
reset custom component input after clearing from SelectedFilters

### ISSUE THREAD

**Issue by yanis96** [appbaseio/reactivesearch#445]
**doc enhancement**
**Platform: web**

**Description:**

i added a custom reactive component 
`import React, { Component } from "react";
class ChildInput extends Component {
  setValue = value => {
    this.props.setQuery({
      query: this.props.query(value),
      value: value
    });
  };
  render() {
    return (
      <div className="custom-reactive-input">
        <input
          onChange={e => {
            if (e.target.value === "") {
              this.props.setQuery({
                query: { match_all: {} },
                value: ""
              });
            }
            if (e.target.value >= 0) {
              this.setValue(e.target.value, valueSuffixe);
            }
          }}
        />
      </div>
    );
  }
}

export default ChildInput;`
i wrapped the component inside a ReactiveComponent
and it works, it filters the results perfectly but i didn't find how to clear the input field after the clear on the SelectedFilters component is there an event for that ?

**Minimal reproduction of the problem with instructions:**

**Reactivesearch version:** 2.6.2"

**Anything else:** i suggest to add an event to the custom component like "onSelectedFiltersClear"

**Comment by axeff** [comment]
Since I might have the same issue, I created a [sandbox](https://codesandbox.io/s/kw42knjvor) to visualize my problem.
When using the ToggleButton I can check/uncheck them and of course reset the filter correctly.
Now I do have my own Reactive Component which works correctly when clicking on the stars, BUT will not be reset if you reset the filter.

**Comment by alexlle** [comment]
Hi @axeff 
I'm facing a similar issue.
I didn't get what dirty workaround you found. Could you explain more pls?

I use a CustomQuery for the DataSearch default component and it does NOT reset when I toggle the "clear all" filter button or when I press its own filter toggle button.

**Comment by metagrover** [comment]
Closing this issue because we support `onClear` event on SelectedFilters.

[Refer updated docs here](https://opensource.appbase.io/reactive-manual/base-components/selectedfilters.html).

**Comment by DustinKLo** [comment]
The docs only say:
`onClear` function [optional]
Gets triggered when the `clear all` button is clicked.

It's not very clear, and i don't see any examples of this `onClear` function

Can you point us to an example?

**Comment by metagrover** [comment]
You can use it as:

```js
<SelectedFilters onClear={(comp, val) => console.log(comp, val)} />
```

**Comment by dres-cifuentes** [comment]
@metagrover  does the `onClear` prop work on native? I noticed that the documentation for `SelectedFilters` for Native doesn't include everything that the Web version has

**Comment by metagrover** [comment]
@dres-cifuentes No, it isn't supported on native yet. It should be very similar to implement though. Open to accepting PR on this :)

**Comment by iseabock** [comment]
@metagrover FYI, the docs (here at least https://opensource.appbase.io/reactive-manual/base-components/selectedfilters.html) Make mention of an onChange, not an onClear

**Comment by bietkul** [comment]
@jyash97 Can you update the docs
