### ISSUE TITLE
autosuggestion not customizable in CategorySearch

### ISSUE THREAD

**Issue by yanis96** [appbaseio/reactivesearch#446]
**Issue Type:** Bug

**Platform:** Web

**Description:**

i added  onSuggestion event on CategorySearch but it still did not change the first 3 suggestions.
How could we for exmaple change the "in all categories" text

`<CategorySearch
        ...
        onSuggestion={suggestion => ({
          label: (
            <div>
              {suggestion._source.titre} dans: <span
                style={{ color: "dodgerblue", marginLeft: 5 }}
              >
                {suggestion.categorie}
              </span>
            </div>
          ),
          value: suggestion.titre
        })}
      />`
**Screenshots:**
![reactive search](https://user-images.githubusercontent.com/18577659/42724847-ade66b54-8771-11e8-896a-8f6032fd0e05.jpg)

**Reactivesearch version:** 2.6.2

**Browser:** all 

thank you for your support

**Comment by divyanshu013** [comment]
This is now possible with `renderSuggestions` prop. Please check the [docs](https://opensource.appbase.io/reactive-manual/advanced/customsuggestions.html) for custom suggestions.
