### ISSUE TITLE
DataSearch import error

### ISSUE THREAD

**Issue by FilipeCunhaRideways** [appbaseio/reactivesearch#447]
I was following the documentation examples and found a problem when trying to use DataSearch.

![image](https://user-images.githubusercontent.com/31856117/42728459-cb90c910-87b2-11e8-86d2-b50f827e8675.png)

This is my component, it's just a search bar. But when the site is rendered this error appear.

![image](https://user-images.githubusercontent.com/31856117/42728438-4e6875d2-87b2-11e8-8caa-4d8be12464fa.png)

I think I'm doing everything right, what can it be? Did I miss something? When I only import `ReactiveBase` everything works fine.

**Comment by siddharthlatest** [comment]
@FilipeCunhaRideways Yes, your `<DataSearch>` component should reside within the ReactiveBase component. (i.e. ReactiveBase should wrap all the ReactiveSearch components)
