### ISSUE TITLE
Setting a default value of interval prop in DynamicRangeSlider

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivesearch#45]
By default, the `interval` prop (for the number of histogram bars) should be set to ```Math.ceil((range.end - range.start) / 10)```. We already do this in RangeSlider component https://github.com/appbaseio/reactivebase/blob/dev/app/sensors/RangeSlider.js#L243.

**Comment by farhan687** [comment]
Range value is not predefined over here.
Here we execute histogram aggregation query to find the range.

In RangeSlider we already have the range values in prop so, this implementation is possible there only.

**Comment by farhan687** [comment]
Fixed here: 49c69ac6f732f66917c9e311ae4d022478dd4277

- Now we are executing 2 aggregation 
1. Get range values 
2. Execute histogram aggregation query.
