### ISSUE TITLE
Setting initial value  from a URLParam for ReactiveComponent

### ISSUE THREAD

**Issue by davkap92** [appbaseio/reactivesearch#452]
**Issue Type: Question**

**Platform:**

**Description:**
Hi, so I'm trying to replicate the same behaviour as other components such as SingleDropdownList i.e when page loads with a URLparam for that componentId it is set to that value. How would I go about this for a custom ReactiveComponent and Wrapper such as the ColorPicker example

**Minimal reproduction of the problem with instructions:**

**Reactivesearch version:** 2.6.8

**Comment by davkap92** [comment]
Sorry never mind, discovered I can get this from selectedValue of child component thanks :)

**Comment by DustinKLo** [comment]
Can you show me an example? I'm having trouble with this. thanks!

**Comment by metagrover** [comment]
Check the props of your child component (inside ReactiveComponent) - you will have access to the selectedValue prop there.
