### ISSUE TITLE
Passing dataset for visulization.

### ISSUE THREAD

**Issue by xs005** [appbaseio/reactivesearch#458]
Hi, 

I am using **reactivesearch v2**. After the searching, I can get the (data) or (res) using onData function to show the value of keys properly. Is it possible to **pass the dataset** to some other apps for visualization such as superset or redash. Should I make my own UI component? or is there an API to retrieve the dataset after searching?

Thanks,

Chris

**Comment by DustinKLo** [comment]
+1
