### ISSUE TITLE
SortOptions + showResultStats: Display Issue 

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivesearch#46]
When using **sortOptions** together with the **showResultStats** prop, there is a styles overlap. Also setting **showResultStats** prop to `false` has a side effect on the **sortOptions** prop's UI element.

![](https://i.imgur.com/YeSbWix.png)

Originally filed under ReactiveBase, but it couldn't be replicated over there - https://github.com/appbaseio/reactivebase/issues/98.

**Comment by farhan687** [comment]
Issue was related to example only. Fixed here: d46067f986a276c3093094b90de38110a11651da
