### ISSUE TITLE
Allow customising url params labels

### ISSUE THREAD

**Issue by metagrover** [appbaseio/reactivesearch#460]
**Issue Type:**
Enhancement

**Platform:**
Web

**Description:**
Currently, the url-params labels get set to the respective componentIds. We should support customising these labels by taking the necessary map of labels and componentId in the root component ~ to enable the pre-filling of store before mount.

This would allow us to prettify the url: `https://myapp.com?results-page=10` to `https://myapp.com?p=10`.

**Comment by davidklebanoff** [comment]
Sounds like a great idea to me! 👍

**Comment by metagrover** [comment]
Instead of adding a new prop to customise the url params, we have removed `-page` string from the result component. Hence, you can now set `p` or `page` as the componentId and expected results can be achieved. 🎉
