### ISSUE TITLE
maps: GeoDistanceDropdown Allow to set Google maps Restrictions by countries

### ISSUE THREAD

**Issue by durdenx** [appbaseio/reactivesearch#465]
**Enhancement:**
Currently autocompletion is global, allow to set Google maps Restriction to limit places autocompletion by countries for `GeoDistanceSlider`and `GeoDistanceDropdown`.

In gmaps doc: `autocomplete.setComponentRestrictions({'country': countries});`
see https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete-multiple-countries

**Platform:**
Web

**Comment by metagrover** [comment]
This is pretty neat. Open to accepting PRs on this, if you or anyone wants to take this up.

**Comment by metagrover** [comment]
This will be released in the upcoming release of maps (~ this week).

Props to @jyash97 for working on this 💯

**Comment by metagrover** [comment]
Released in `v2.0.0` 🎉
