### ISSUE TITLE
Typescript definition files (.d.ts) no present in npm package

### ISSUE THREAD

**Issue by TGMorais** [appbaseio/reactivesearch#466]
**Issue Type:**
Bug + Enhancement

**Platform:**
Web

**Description:**
I'm trying to use reactivesearch with a typescript project.  
Despite the documentation, and example provided in the docs, typescript definitions are not available.
The web package does not contain type definitions (.d.ts) files.
It seems that they are not being publish to npm.

**Minimal reproduction of the problem with instructions:**
Install the package:  
`npm install @appbaseio/reactivesearch`

Check `node_modules/@appbaseio/` contents. There are no .d.ts files.

**Reactivesearch version:** 2.6.12

**Anything else:**
The definitions files already exist in the repo, but most likely are not being publish along with the .js into npm

**Comment by metagrover** [comment]
Thanks for pointing this out. Will look into this 🐱

**Comment by TGMorais** [comment]
Hey @metagrover ,

I happen to have a quick look to the recent changes for the types and I think I spotted a typo.

This line:  
https://github.com/appbaseio/reactivesearch/commit/df6e60f2d0ef50c812507ddcff9f8931184d72c7#diff-5031fb28893c1bac4cdeb204bf6fe2eaR6

The files copied are only the`.d.ts` files, however some `.d.ts` reference a `types.ts` file.   
This file is not copied over when running `build:copy-types`, which will then cause problems cause the copied .d.ts files will not find `types.ts` in `/lib`

The solution would be to either copy the `types.ts to lib as well or rename `types.ts` to `types.d.ts` ( I think will work as well).

Cheers!

**Comment by metagrover** [comment]
oh yes, Will fix it. Thanks 😅
