### ISSUE TITLE
Pagination appears when no results are found

### ISSUE THREAD

**Issue by allendol** [appbaseio/reactivesearch#467]
**Issue Type:**

Question

**Platform:**

Web

**Description:**

I am using ResultList component with pagination={true}. But I don't want to view pagination where there is no result. How can I do it? Is there any property that I can use when there is no result so the pagination set to fasle?

**Screenshots:**

**Minimal reproduction of the problem with instructions:**

**Reactivesearch version:** x.y.z

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**

**Comment by divyanshu013** [comment]
Hi @allendol, I'm not able to reproduce this issue. Please check this sandbox where the pagination will be hidden in case of no results https://codesandbox.io/s/n0yywx8w2l

If you can reproduce this issue on this sandbox that would be great.

**Comment by allendol** [comment]
This ResultList still shows pagination when no record found:
<ResultList
    componentId="Result"
    dataField={sortByField}
    react={{
        and: 'q'
    }}
    pagination
    paginationAt="both"
    showResultStats={true}
    stream={false} 
    sortBy="desc"
    URLParams={false}
    onNoResults="No result found .."
    onData={(res) => {
        let lastModifieddisp = (res.lastModifieddisp === undefined) ? '' : ' - ' + res.lastModifieddisp;
        return {
            somthing
        }
    }}
/>
![resultlist](https://user-images.githubusercontent.com/40170767/43641586-47684cc2-96f2-11e8-8fc3-bdbb37a7e514.png)

**Comment by allendol** [comment]
I imported ResultList  from '@appbaseio/reactivesearch'; and now the pagination doesn't show when result is empty, however SortBy still shows. See the above image for Sort By. Again not displaying pagination is solved.
Following is SortBy constructor:

    constructor(props) {
        super(props)

        this.state = {
            selectedOption: { value: 'rel', label: 'Relevance'}
        };
    }
    handleChange = (selectedOption) => {
       this.setState({ selectedOption });
       //console.log('Option selected:', selectedOption);
   }
Any setting I can use to hide Sort By when no result is displayed?
