### ISSUE TITLE
Feature: Add showSearch prop for *DropdownList components

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivesearch#468]
**Issue Type:**

Enhancement

**Platform:**

ReactiveSearch for Web

**Description:**

Add a `showSearch` prop similar to *List components.

> showSearch Boolean [optional]
whether to show a searchbox to filter the list items locally. Defaults to true.

**Screenshots:**

**Minimal reproduction of the problem with instructions:**

**Reactivesearch version:** x.y.z

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**

**Comment by metagrover** [comment]
Added `showSearch` - [here](https://github.com/appbaseio/reactivesearch/commit/a02cf5329bf5c507e34fc45e907d0f4eac06c46e). Defaults to `false`.
