### ISSUE TITLE
The issue regarding the cursor moving to the end of the input if something is typed in the middle -  not solved

### ISSUE THREAD

**Issue by irinaapopi** [appbaseio/reactivesearch#470]
**Issue Type:**
bug

**Platform:**
Web

**Description:**
The cursor keeps moving to the front if the user types any new characters in the middle of the string. I have seen a similar post about this issue and I thought it had been solved, but I am running the latest version and the problem still occurs. 

Reactivesearch version: 2.6.12

**Comment by divyanshu013** [comment]
Hi @irinaapopi, we're tracking the issue at #394.

**Comment by irinaapopi** [comment]
Yes, but that issue appears to be closed - and it has not been fixed

**Comment by divyanshu013** [comment]
The issue is open, will keep the progress updated there.
