### ISSUE TITLE
Make Pagination component clickable with JS disabled in browser

### ISSUE THREAD

**Issue by aol-nnov** [appbaseio/reactivesearch#477]
As a followup for #441 it is proposed to add `href` parameters to `Button` in `Pagination` component.

For example, `?SearchResult=1`, `?SearchResult=2` and so on.

After this change, SSR enabled reactivesearch application will become fully crawlable by dummy crawlers (which do not execute js during crawling, but only follow urls)

**Comment by aol-nnov** [comment]
@metagrover please let me know, if it is the right way to add `href`s to `Pagination` `Button`s or there is some better approach I'm not aware of.

**Comment by metagrover** [comment]
Released in `v2.10.0` 🎉
