### ISSUE TITLE
Que: Is there any functionality like Lazy loader ???

### ISSUE THREAD

**Issue by ashwini987** [appbaseio/reactivesearch#479]
**Platform:**
 Web

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by divyanshu013** [comment]
Hi @ashwini987, currently we don't have lazy loading in any of the components. Which component are you thinking of using lazy loading in?

**Comment by ashwini987** [comment]
In ResultCard, ResultList, ReactiveList for Image Purpose.

**Comment by divyanshu013** [comment]
Agreed, lazy loading is a nice addition in all components. For showing results you could use `ReactiveList` for now and use some lazy image loader component IMO. Perhaps https://github.com/jasonslyvia/react-lazyload will help.

**Comment by divyanshu013** [comment]
Closing this as it can be achieved using `ReactiveList` and a custom render component. Please open a new issue if there's some problem in using it.
