### ISSUE TITLE
Native : SelectedFilters FontSize

### ISSUE THREAD

**Issue by aditya-rumbleon** [appbaseio/reactivesearch#481]
**Issue Type:**
The SelectedFilters result value is cut-off at the bottom on iOS when set to larger text in phone settings. Please refer to the screenshot.

**Platform:**
Native

**Description:**
![screen shot 2018-08-14 at 1 58 39 pm](https://user-images.githubusercontent.com/39170134/44112249-3243dc36-9fca-11e8-84ef-d6a1efcf1056.png)

I am only passing 
          <SelectedFilters style={{ alignSelf: 'flex-start' }} />

How to fix this issue ???? How can I adjust the font size?

**Comment by metagrover** [comment]
Thanks for bringing this up. 

It seems we missed out on `innerStyle` prop implementation in `SelectedFilters`. It should be trivial to implement (you can check other components for the same). Open to accepting PRs on this if you or anyone wants to take this up.

[Refer `innerStyle` usage here](https://opensource.appbase.io/reactive-manual/native/advanced/style.html#innerstyle).
