### ISSUE TITLE
How to customize the query before it send to ES

### ISSUE THREAD

**Issue by shili167** [appbaseio/reactivesearch#485]
Hi, 

Is there a way to grab the query before it send to Elastic Search server, and change the query? I need to add an "include", "exclude", and change the "highlight" part of the query. 

Thank you!

**Comment by metagrover** [comment]
Hello @shili167, we recently added support for `include` and `exclude` fields on the result components. [Check docs here](https://opensource.appbase.io/reactive-manual/result-components/reactivelist.html#props).

You can use `beforeSend` method on `ReactiveBase` to transform the network request before execution. [Refer docs here](https://opensource.appbase.io/reactive-manual/getting-started/reactivebase.html#props).

Hope that helps!

**Comment by shili167** [comment]
Thank you! I tried include and exclude in result, but the props didn't get inserted into the query (_source) that send to elastic search....maybe it is a new feature, I need to update the version of the library?

Do you have a quick sample for beforeSend function to retrieve the current query?
