### ISSUE TITLE
make inner_hits  available results onData callback

### ISSUE THREAD

**Issue by yytsui** [appbaseio/reactivesearch#486]
**Issue Type: enhancement**

**Platform: Web**

**Description: Results onData Support inner_hits **
Now in onData(res), we can only access the _source object, _id, _index from the search results. 
The [inner_hits](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-inner-hits.html) should also be available.

**Comment by siddharthlatest** [comment]
We can support this and it shouldn't be too difficult to add. @yytsui Do you want to take a stab at this?

**Comment by yytsui** [comment]
I tried to patch parseHits in [reactivecore](https://github.com/appbaseio/reactivecore), it seems work.
I will send a pull request tomorrow after more tests.

**Comment by metagrover** [comment]
@yytsui That'd be awesome 🕺 🎉

**Comment by marcelchastain** [comment]
@metagrover @siddharthlatest 
This is a great enhancement and it looks like it was straightforward to implement. I have a data set that's extremely reliant on  `inner_hits` so I'm very eager for this :)

Is this something we can merge in soon? 

(Also, if there's anything I can do to help (testing, cutting a new PR, etc) please let me know!)

**Comment by siddharthlatest** [comment]
@marcelchastain We will try to merge this in the next release.

**Comment by bietkul** [comment]
@marcelchastain Sure, it'll be helpful if you can create a new PR for the `next` branch.
We'll roll out it in the next version.

**Comment by allendol** [comment]
Now that the data is available, how do you access to inner_hits or highlight through the code.
Any example or tips?

**Comment by allendol** [comment]
I see the changes on helper.js but when I compare the helper.js that I have with one that was updated here, they are not the same. This is the code on the helper.js that  I have. FYI, I just reinstalled reactive search:
return _extends({ _id: data._id, _index: data._index, _type: data._type, _score: data._score, highlight: data.highlight || {} }, data._source, streamProps);
So how can I change this to:
-----
let result = Object.keys(data)
.filter(key => key !== '_source')
.reduce((obj, key) => {
	obj[key] = data[key];
	return obj;
},{
highlight: data.highlight || {},
	...data._source,
	...streamProps,
});
return result;
});
}
-----
When I change the code I am getting the following error:
----
You may need an appropriate loader to handle this file type.
|                 }, {
|                     highlight: data.highlight || {},
|                     ...data._source,
|                     ...streamProps,
|                 });
----

**Comment by marcelchastain** [comment]
@allendol I don't have an answer to your specific question (only using `inner_hits`, not `highlight`) but here's some example code that I use that might give you a sense of the data struct that's coming back.

Also for anyone else looking at this thread, this is a useful little utility function for dealing with returned `inner_hits` data:

```javascript
export const filterByInnerHits = (data, innerHitsKey) => {
  return data.map(item => {
    let filteredResults = [];
    if (item.inner_hits && item.inner_hits[innerHitsKey]) {
      filteredResults = item.inner_hits[innerHitsKey].hits.hits.map(hit => hit._source);
    } else {
      filteredResults = item[innerHitsKey];
    }

    return {
      ...item,
      [innerHitsKey]: filteredResults,
    }
  });
};
```
