### ISSUE TITLE
Enable Up and Down Arrow navigation on result component

### ISSUE THREAD

**Issue by irinaapopi** [appbaseio/reactivesearch#492]
I tried implementing arrow navigation on the result component but it does not work because the tabIndex does not seem to get picked up. Any ideas on how to get around this issue?

**Comment by metagrover** [comment]
You can use `onAllData` prop on `ReactiveList` to implement this accessibility requirement. `onAllData` allows you to render the container and result list items, giving full control to apply the necessary event handlers and state maintaining logic.

[Refer ReactiveList docs here](https://opensource.appbase.io/reactive-manual/result-components/reactivelist.html).

Hope that helps!

**Comment by rohit-sourcefuse** [comment]
@irinaapopi You get success in adding Arrow navigation feature? I am also struggling with the same. Can you please let me know if you get any success on this.

**Comment by divyanshu013** [comment]
Closing this as it can be implemented with `onAllData` prop. Please open a new issue if there's some other issue.
