### ISSUE TITLE
Display duplicate results for the same document: Our Elastic search has indexed URLs as they are case sensitive. So for the same document we have the following indexes: https://MyDocumentURL/Doc1.docx https://mydocumentURL/Doc1.docx https://MyDocumenturl/Doc1.docx https://mydocumenturl/Doc1.docx and do on. When we search Doc1.docx, we get several results because URLs are case sensitive. However they are pointing to the same document. How can we adjust query in DataSearch or adjust result in ResultList component so we see one URL for the same document?

### ISSUE THREAD

**Issue by allendol** [appbaseio/reactivesearch#494]
**Issue Type:**

**Platform:**

**Description:**

**Screenshots:**

**Minimal reproduction of the problem with instructions:**

**Reactivesearch version:** x.y.z

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**

**Comment by siddharthlatest** [comment]
Hey @allendol, not sure I understand the issue. Is this a request for help? Gitter channel would be a better place for that.

We can re-open if this is an issue with the library.

**Comment by allendol** [comment]
What is the URL Gitter channel?

**Comment by allendol** [comment]
@siddharthlatest what is the URL for Gitter channel?

**Comment by metagrover** [comment]
Here you go: [https://gitter.im/appbaseio/reactivesearch](https://gitter.im/appbaseio/reactivesearch).
