### ISSUE TITLE
Multilist does not React to ReactiveList?

### ISSUE THREAD

**Issue by coommark** [appbaseio/reactivesearch#495]
**Issue Type:**
Multilist not reacting to ReactiveList, Version 2.8.1 (latest)

**Platform:**
Web

**Description:**
Having infinitely enjoyed and being saved months of development by this awesome package, I implemented a ReactiveList to serve as a Category Page (enterprising, right?) of sorts with default query similar to this:

```
componentId="CatSearchResult"
defaultQuery={() => ({
      query: {
            term: {
                 category: 7
            }
       }
 })}
```
So I am all happy and feeling like a rock star, so I add a Multilist item like below:

```
<MultiList
	className="col widget py-3"
	componentId="RamSensor"
	dataField="ram.raw"
	title="RAM"
	react={{
		and: ['CatSearchResult']
	}}
/>
```
I was the hoping `RamSensor ` will "React" to the `CatSearchResult` ReactiveList above, but then nothing happens. The Multilist shows counts of the entire database, not the result in the ReactiveList.

Please is this the expected behavior? If so is there a way I can force the Multilist to react to the reactivelist? Or is this behavior unexpected?

**Comment by metagrover** [comment]
`defaultQuery` in Result components behave differently, it doesn't get leaked out to other components. I'd suggest you to use `ReactiveComponent` or `DataController` here.

Hope that helps!

**Comment by coommark** [comment]
I used `DataController `and it worked perfect. One quick question, is there a place we list websites using this awesome package? We'll soon go live and I will be proud to associate with ReactiveSearch.

Thanks

**Comment by divyanshu013** [comment]
Sure, would love to add a `Built with ReactiveSearch` section in the main readme :)

**Comment by siddharthlatest** [comment]
@coommark That's awesome 💯. Would you also be open to sharing your experience on building with ReactiveSearch? We would ❤️ to feature it as a testimonial / case study.

**Comment by coommark** [comment]
With all pleasure. We're less than 2 weeks to going live and I will be very happy to share my experience. I"m currently running it against more than a quarter million products and the results are most impressive. The ease with which I was able to build using ReactiveSearch is totally drop-dead amazing.
