### ISSUE TITLE
Cursors moves at the end of the text in DataSearch after each key pressed

### ISSUE THREAD

**Issue by rap2hpoutre** [appbaseio/reactivesearch#496]
**Issue Type:**
Not sure it's a bug, strange behavior though.

**Platform:**
Web

**Description:**

The problem occurs with DataSearch and can be reproduced on the demo provided by @appbaseio (ie: https://opensource.appbase.io/reactivesearch/demos/airbeds/) 

If I type "bar" then I want to type "foo" at the beginning of the string (let's say because I forgot to type it first), I could do: 
 - type "b", "a", "r"
 - then click at the beginning of the input field in order to type "foo".
 - type "f", "o", "o"

It results in:

```
fbaroo
```

Cursors moves at the end of the text in DataSearch after each key pressed, even if I want to type text at the beginning.

**Screenshots:**

📽️ Here is a video of the problem on the demo provided by appbaseio/reactivesearch: 

![output](https://user-images.githubusercontent.com/1575946/44665668-c2dbfe80-aa16-11e8-97a8-216ef6bd99c9.gif)

**Minimal reproduction of the problem with instructions:**

See above.

**Reactivesearch version:** the one on appbaseio demo website (there is no clue on the demo site)

**Browser:** Firefox latest (beta) | Chrome latest (stable)

**Comment by metagrover** [comment]
Hi @rap2hpoutre This has been [fixed here](https://github.com/appbaseio/reactivesearch/commit/3741c3d123928f19913e2ee85a60c3103254aa0a), but is currently unreleased. We will roll this out by the end of this week among other enhancements.

Cheers!

**Comment by rap2hpoutre** [comment]
Great! thanks!

**Comment by divyanshu013** [comment]
Available now in v2.8.2
