### ISSUE TITLE
URLParams not clearing up on removing the SelectedFilter

### ISSUE THREAD

**Issue by metagrover** [appbaseio/reactivesearch#497]
**Issue Type:**
Bug

**Platform:**
Web

**Description:**
URLParams stay intact even after removing the selected-value by interacting with `SelectedFilters`.

**Comment by ssswagatss** [comment]
Is the issue been fixed in the latest version ?

**Comment by divyanshu013** [comment]
This is still pending, it'll be closed when we've a fix out for it.
