### ISSUE TITLE
Que - Which mapping is use for A-Z and Z-A sorting ? 

### ISSUE THREAD

**Issue by ashwini987** [appbaseio/reactivesearch#498]
**Issue Type:**
I want to sort the products on my **"product_name"** field for A-Z and Z-A sort, which mapping or something is set for this field ??? 

**Platform:**
 Web

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by divyanshu013** [comment]
Hi @ashwini987 you could try the `sortBy` prop on result components. The `dataField` should be a non_analyzed field or a keyword. Then you can provide `sortyBy="asc"` for A->Z and `sortBy="desc"` for Z->A.

[Docs](https://opensource.appbase.io/reactive-manual/result-components/reactivelist.html#props)
