### ISSUE TITLE
Remove double quotes from URL for CategorySearch , MulitiList , DynamicRangeSilder Components

### ISSUE THREAD

**Issue by ashwini987** [appbaseio/reactivesearch#499]
**Issue Type:**
want to remove double quotes from URL for **CategorySearch** , **MulitiList** , **DynamicRangeSilder** Components

**Platform:**
Web

**Description:**
Right now the URL is like this as below : 
http://localhost:8001/?CategoryMultilist=%5B"All+Bag"%2C"All+Keyholder"%2C"Badge+Holder"%5D

i use MultiList component for that i want to remove double quotes form url like this
http://localhost:8001/?CategoryMultilist=%5BAll+Bags%2CAll+Keyholders%2CBadge+Reels%2FBadge+Holders%5D

How can i achieve this? Remove double quotes form URL for MultiList , CategorySearch , DynamicRangeSilder ???   

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by divyanshu013** [comment]
Duplicate #346.
