### ISSUE TITLE
New component: CategorySearch

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivesearch#5]
An extension of **Data Search** component meant to be used in e-commerce search settings.

### Component Props

- **componentId** `String`  
    component ID.
- **appbaseField** `String`  
    DB field to be mapped for the query.
- **categoryField** `String`
    DB field path for finding search results by category.
- **title** `String` [optional]  
    title of the component, optional.
- **size** `Number` [optional]
    total suggestions to be displayed, defaults to 10.
- **defaultSuggestions** `Object Array` [optional]  
    an array of objects with `value` as string and `label` as either string or HTML.
```
{[
  {"value": "breakfast", "label": {<p><i className="fa-icon">Breakfast</p>}}, 
  {"value": "lunch", "label": {<p><i className="fa-icon">Lunch</p>}}, 
  {"value": "dinner", "label": {<p><i className="fa-icon">Dinner</p>}}
]}
```
- **defaultSelected** `String` [optional]  
    pre-selected text by which search should happen.

**showSuggestions** prop is always set to be `true` for this component and not exposed in the props spec.

### CSS Styles API

`rbc-title-active`

For a selected item, there should be a `rbc-active` class.

### Stories

1. Basic story
2. With default suggestions applied
3. with dark theme
4. Playground.

**Comment by metagrover** [comment]
Added here: fdb318a2010ee2b2a93ea074e1d34150772fd8ba
