### ISSUE TITLE
NestedList: Support multiple nesting levels

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivesearch#50]
Current implementation of `NestedList` component supports up to two levels of aggregations. We should implement a generic aggregations query that can support 'n' levels --> and currently limit n to recurse to a depth of 10 (We will wait till the day an actual use-case needs more than that).

**Comment by Analect** [comment]
@siddharthlatest 
Was looking at this component today.  I assume this component will only work in a React app? ... or is there any prospect of it working within an angular app?

**Comment by farhan687** [comment]
@Analect yes reactivesearch is react library, so it will work only with react.

**Comment by farhan687** [comment]
Fixed here: 93b2fedbb65eec920c606c812f5fd63ea01a3b30
