### ISSUE TITLE
Have the option to call defaultQuery on ReactiveList only once initially?

### ISSUE THREAD

**Issue by carlopascual** [appbaseio/reactivesearch#504]
### Issue Type:
Enhancement

### Platform:
Web

### Description:
Thank you again guys for all the hard work!

I am trying to create a ReactiveList which is dependent on a DataSearch. I would like the ReactiveList to have no results when there is no value being searched. 

What I have so far:

**Inside the DataSearch:** I am using a `customQuery` to `match_none` if the search box becomes empty and returning the defaultSearch if otherwise.

**Inside the ReactiveList:** I am using the the `defaultQuery` parameter to `match_none` to have no default values inside the list.

### Problems

The `customQuery` on DataSearch handles every other case nicely, except for the initial render/search. Because the DataSearch has not yet run its query, ReactiveList will not yet react to anything and will then fully rely on its `defaultQuery`.

Because the `defaultQuery` parameter in the ReactiveList is always being injected in the final query, doing a `match_none` will make the final query return nothing. We have to `match_all` in the `defaultQuery` of the ReactiveList when the searchbox is filled in order to return the desired results. 

I have tried using  an external state to keep track of our current search value, but this reruns the `defaultQuery` on ReactiveList and temporarily runs a match_all before running the combined DataSearch and ReactiveList query. This results in a "no results found" -> flickering match_all result -> final result on the initial search.

### ReactiveSearch Version: 
2.8.2

### Browser:
All

### Anything else:

Another way this can be remedied is to provide a way to run the DataSearch query initially without having to set a `defaultSelected` prop.

**Comment by marcfielding1** [comment]
Is anything happening with this at all, I have [this](https://stackoverflow.com/questions/56778180/reactivesearch-how-to-stop-initial-query-on-load) question open on stack.

I've got a huge ES index(1 million items) ideally I don't want the component to initially run match_all - looks like we could add a prop noInitialQuery={true} and then modify the source [here](https://github.com/appbaseio/reactivesearch/blob/44b9752a81058ed3c694116f0bfb23f855ce3eb8/packages/native/src/components/search/DataSearch.js#L160) ?

**Comment by marcfielding1** [comment]
In fact, let me have a fiddle on a fork and I'll PR if it pans out.

**Comment by marcfielding1** [comment]
So after fiddling this you can actually do the following via state - basically you check if the search has a value if it doesn't you match_none - please see my answer [here](https://stackoverflow.com/questions/56778180/reactivesearch-how-to-stop-initial-query-on-load/56789346#56789346) - does seem a bit odd you can't turn off the initial query though!
