### ISSUE TITLE
SSR api improvements

### ISSUE THREAD

**Issue by divyanshu013** [appbaseio/reactivesearch#511]
**Issue Type:**

Enhancement

**Platform:**

Web

**Description:**

Currently the `initReactiveSearch` method takes some parameters which require us to know the type of component being passed (`source`). We don't need to take the `type` key in the list of components as it can be deciphered based on the `source`.

**Minimal reproduction of the problem with instructions:**

[API](https://opensource.appbase.io/reactive-manual/advanced/ssr.html)

**Reactivesearch version:** x.y.z

2.8.2

**Comment by metagrover** [comment]
We have removed `type` key from the SSR API. This will be available in reactivesearch `v3` upwards.
