### ISSUE TITLE
What is the best way to search accross 2 fields but using only one for suggestion

### ISSUE THREAD

**Issue by hemixam** [appbaseio/reactivesearch#521]
**Issue Type:**
Question

**Platform:**
Web

**Description:**
Using datasearch component I want to search on field A or field B

**Minimal reproduction of the problem with instructions:**
Assume I have `fieldA` and `fieldB` : how can I make datasearch component search on both fields but suggest only values from `fieldA`?

**Reactivesearch version:** 2.8.1

**Browser:** 
all

**Comment by skout90** [comment]
+1
