### ISSUE TITLE
Feature: Support for modifying query values in beforeValueChange

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivesearch#522]
**Issue Type:**

Enhancement

**Platform:**

ReactiveSearch for Web

**Description:**

Currently, we support a prop `beforeValueChange`[1] to let the user use the component's state value before it gets set (i.e. before the query is fired). It would be great if this method can allow the user to modify the value that is being set when resolving it in the response. An example use-case is for a user to sanitize the input of DataSearch.

This is how the usage can look:

```
beforeValueChange={(value) => {
      // called before the value is set
      const newValue = sanitize(value) // sanitize is a UDF
      // returns a promise
      return new Promise((resolve, reject) => {
        // update state or component props
        resolve(newValue)
        // or reject()
      })
    }
  }
```

This should be useful beyond DataSearch across components - allowing the user to sanitize, validate, enrich end-user inputs.

[1] https://opensource.appbase.io/reactive-manual/advanced/guides.html#beforevaluechange

**Reactivesearch version:** x.y.z

2.8.2

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

All

**Comment by metagrover** [comment]
Closing this issue because this use-case should be dealt via `customQuery` prop (in combination with component's static `defaultQuery()` if needed).
