### ISSUE TITLE
web: Filter suggestions which are passed via onSuggestion prop

### ISSUE THREAD

**Issue by divyanshu013** [appbaseio/reactivesearch#524]
**Issue Type:**

Enhancement/Bug

**Platform:**

Web

**Description:**

When using `onSuggestion` prop we currently pass all the suggestions. But since it's a render prop per suggestion, it's tricky to implement a custom parsing logic by the user. Also these suggestions may include duplicates which are therefore difficult to remove. We should send only the parsed suggestions in this prop. If someone is interested in using unfiltered suggestions, the `renderSuggestions` prop is more useful.

**Screenshots:**

https://imgur.com/a/tUte6nm

**Minimal reproduction of the problem with instructions:**

Use `onSuggestion` prop on a search component.

**Reactivesearch version:** x.y.z

2.8.2

**Comment by bietkul** [comment]
In 3.x we return both `parsed` & `unparsed` suggestions.
