### ISSUE TITLE
Need custom component's onClick to connect to ReactiveList but ReactiveComponent hangs up UI

### ISSUE THREAD

**Issue by nicholasfay** [appbaseio/reactivesearch#529]
Issue Type:
I want to hook up a custom component that contains complex D3 visualizations based on underlying data to my results list. I want to be able to trigger an onclick event which will query my local elasticsearch instance and update results list from this custom component with D3 in it. I have tried using ReactiveComponent but when wrapping ReactiveBase around this complex component, my search bar and UI freeze up when typing in to my DataSearch bar. What would be the best way to accomplish this?

Platform:
Web

Browser: Web Browser

**Comment by nicholasfay** [comment]
Hi @metagrover, I have expressed my inability to use the ReactiveComponent. The D3 visualizations in the component seem to be lagging the input of the search bar and the corresponding query results in the ReactiveList component. As when I wrap ReactiveBase around my CustomComponent and a DataSearch Component it is very laggy but with it just wrapped around my DataSearch Component it works very fast.

**Comment by metagrover** [comment]
Can you share a codesandbox replicating your use-case?

**Comment by nicholasfay** [comment]
Just fixed it and it was due to ReactiveBase causing unnecessary re rendering of my D3 visualizations. Therefore is more of a React + D3 problem. We can close this issue
