### ISSUE TITLE
Bug: Build fails after upgrading to ReactiveSearch 2.9.0

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivesearch#534]
**Issue Type:**

Bug

**Platform:**

Web

**Description:**

Build fails with the following error after upgrading to ReactiveSearch 2.9.0 which introduces the usage of `appbase-js:4.0.0-beta` package.

The failure is related tot he fact that the new appbase-js library doesn't transpile the code while publishing to NPM to ES 5, causing it to fail when using it with CRA (or a similar build script).

**Minimal reproduction of the problem with instructions:**

Init a CRA setup and add `@appbaseio/reactivesearch:2.9.0` package in it. Do a `npm build` or `yarn build` and you should see an error as follows:

```
> 10:11:33 PM: Creating an optimized production build...
10:11:46 PM: Failed to compile.
10:11:46 PM: Failed to minify the code from this file:
10:11:46 PM:      ./node_modules/appbase-js/dist/appbase-js.es.js:12
```

**Reactivesearch version:** x.y.z

2.9.0

**Anything else:**

The issue is described in the CRA repo, appbase-js should transpile to ES 5 syntax prior to being published on NPM: https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

**Comment by siddharthlatest** [comment]
Till we solve this, the recommendation is to stick your package.json file to use `@appbaseio/reactivesearch:2.8.2` package.

**Comment by bietkul** [comment]
Fixed in https://github.com/appbaseio/reactivesearch/commit/da8c974c8972538c208ee452f2246b04b3423fe9
