### ISSUE TITLE
ResultList and State

### ISSUE THREAD

**Issue by youssouf-dev** [appbaseio/reactivesearch#538]
**Issue Type:**

Enhancement Issue

**Platform:**

ReactiveSearch for Web

**Description:**

We need the ReactiveSearch to be able to setState.

**Screenshots:**

**Minimal reproduction of the problem with instructions:**

**Reactivesearch version:** x.y.z

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**

**Comment by divyanshu013** [comment]
Currently the props `onData` and `onAllData` for result components are render props (not event driven props). This is the reason why we're limited by not being able to use `setState` when using these props (as they would throw React in an infinite update loop).

The correct solution here would be to make these props as event driven and add different props for rendering data which also sound clearer for example `render` and `renderAll`.

As a workaround right now, you can try a couple of approaches depending upon what suits your needs better:

(i) Use `ReactiveList` and pass all the data to your component using the `onAllData` prop.

(ii) Do a `setState` in `onAllData` only after checking with the parent state before calling `setState`. Note that this is a hack but right now might be the only workaround. For example:

```js
class MyComponent extends Component {
  state = {
    results: null
  }
  render() {
    return (
      ...
      <ReactiveList
        ...
        onAllData={(listData) => {
          const { data } = this.state;
          // hack, can lead to unexpected results
          if (JSON.stringify(data) !== JSON.stringify(listData)) {
            this.setState({
              data: listData
            })
          }
          return null;  // since this is a render prop
        }}
      />
    )
  }
}
```

There's also a proposal to make components more extensible and have clearer semantics but its not being worked upon currently. You may check it out and add your inputs at https://github.com/appbaseio/reactivesearch/issues/355 :)

**Comment by pbbhopp** [comment]
If we make a list of movies, then when the user click one card we need to go to detail page. All these props of this card must goes to this page. What about if we want to use the onAllData props to make the detail page information?

**Comment by bietkul** [comment]
It is possible to set the state in 3.x by using controlled behavior.
