### ISSUE TITLE
Multiple Indices and Multiple Result Lists

### ISSUE THREAD

**Issue by csepulv** [appbaseio/reactivesearch#545]
I have the following need/use case:
* single "dashboard" page that shows results from different indices
* each index shares a common set of fields, which to be used for filtering
* show the results from each index in a different result list

I can specify indices in the `app` parameter to `ReactiveBase`. But this interleaves the results from the different indices and gives little control over ensuring I get results from each index. 

For example, if I have index A and B. Let's say each has a created timestamp. Say I have documents like
a1 - created today
a2 - created yesterday
b1 - created two days ago
a3 - created two weeks ago

If my filter limits results to 2 records, constrained to data in the last week (sorted by newest first), I will only get record `a1` and `a2`. But I would like to get 2 records per index, so I want `a1`, `a2`, and `b1`. 

I would show the A documents in one result list and the B documents in a different result list. As noted, I want them to share a common set of filters. (These filters could use aggregations based on the interleaved results and/or have provided data lists for the options -- I don't need accurate counts and I am not sure what those would even be given the multiple indices.)

I don't think I can use multiple `ReactiveBase` elements, or I can't use multiple `ReactiveBase` and have them share the filters. Is that right?

Any suggestions or pointers for how I might do this? 

For now, I've been providing `onAllData` handlers and multiple result lists, then post processing/filtering the results, by index, in the `onAllData` handlers. But it is hard to know how much data to fetch to ensure I get the results from the different indices. 

As a further note, I've tried to put all the data in a single index but that doesn't work for my case.

Thanks

**Comment by siddharthlatest** [comment]
@csepulv If we remove the constraint of ReactiveSearch, how would you do the above with Elasticsearch, i.e. return some results for each index? That might help think towards a solution within ReactiveSearch's context.

> I don't think I can use multiple ReactiveBase elements, or I can't use multiple ReactiveBase and have them share the filters. Is that right?

You can use multiple ReactiveBase components, but they can't share filters with each other.

**Comment by csepulv** [comment]
In Elasticsearch, I think the most straightforward way would be to issue a query per index. 

I was imagining a Kibana like approach, where each visualization can have its own index, but there is a global filter that applies to all visualizations in the dashboard. This depends on a common set of fields, but it does allow for heterogenous data.

In ReactiveSearch, if `ReactiveList` (and similar) where  could be tied to a particular index (or even indices, as is the case with `app` on `ReactiveBase`), then the `msearch` call could issue the various queries and ReactiveSearch would route the results to the appropriate component.

Is this something you think would ever be done in ReactiveSearch or appropriate for its design?

**Comment by csepulv** [comment]
Is there a way to access the `react` property and/or `SelectedFilters` programmatically? I am still going through the docs/code, but if I was able to programmatically change filters/react values, I could keep one `ReactiveBase` (and its controls, namely results) in sync with another (and only show filters for one). 

Related, is there a programatic way to trigger a refresh/reload of a control (like `ResultList')?

That might get me a lot of what I need.

Sorry if I am missing something that is already obvious in the docs.

**Comment by csepulv** [comment]
I was able to make this work using a combination of `ReactiveComponent` and `defaultQuery` on the result components. 

On `ReactiveBase`, I specify multiple indices and on the `ReactiveComponent`s or result lists, as needed, I set a term query in `defaultQuery` similar to
```
query: {
            term: {
              _index: "the individual index for this result"
            }
          }
```

It seems to work well enough, so I will close this issue.
