### ISSUE TITLE
showLoadMore breaks(?) list order

### ISSUE THREAD

**Issue by rap2hpoutre** [appbaseio/reactivesearch#550]
**Issue Type:**
bug

**Platform:**
Web

**Description:**
Using `showLoadMore` does not return the same ordered results. If I use this (without `showLoadMore`), it returns ordered list (by count number): 

```jsx
<MultiList
    componentId="domn"
    dataField="DOMN.keyword"
    title="Sous-Domaine"
    queryFormat="or"
    filterLabel="Domaine "
    className="filters"
    size={100}
    showSearch={true}
    showCheckbox={true}
    URLParams={true}
    placeholder="Rechercher"
    react={{
       and: FILTER
    }}
/>
```
But with `showLoadMore` it returns a list with another order (a-z, not count): 
```jsx
<MultiList
    componentId="domn"
    dataField="DOMN.keyword"
    title="Sous-Domaine"
    queryFormat="or"
    filterLabel="Domaine "
    className="filters"
    size={100}
    showSearch={true}
    showCheckbox={true}
    URLParams={true}
    placeholder="Rechercher"
    showLoadMore={true}
    react={{
       and: FILTER
    }}
/>
```
**Screenshots:**

Before :)

<img width="309" alt="capture d ecran 2018-10-03 a 12 25 29" src="https://user-images.githubusercontent.com/1575946/46405127-79fb2200-c707-11e8-816d-bb73a20b5bc5.png">

After :(

<img width="307" alt="capture d ecran 2018-10-03 a 12 25 09" src="https://user-images.githubusercontent.com/1575946/46405131-7cf61280-c707-11e8-8e9f-a8e1c19b9791.png">

**Minimal reproduction of the problem with instructions:**
Add `showLoadMore` in a multilist, and check the difference with and without the options.

**Reactivesearch version:** v2.10.3

**Browser:** all

**Comment by divyanshu013** [comment]
Hi @rap2hpoutre, `showLoadMore` switches to using [composite aggregations](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-composite-aggregation.html). Not sure if there is a way with composite aggs to sort by count as it would require ES to parse the entire dataset to figure out the doc counts.

Our best bet here (if what I think is correct and composite aggs can't handle sort by count) would be to do client side sort by count. However in that case the list items can jump when new items are loaded.
