### ISSUE TITLE
SelectedFilters Doesnt update the URL when unselect one element  on a custom component

### ISSUE THREAD

**Issue by goffle** [appbaseio/reactivesearch#552]
**Issue Type:**
Bug

**Platform:**
 ReactiveSearch for Web 

**Description:**
When I click delete for a specific filter which is link to a custom component with URL param, the URL is not reset

**Screenshots:**
CodePen below

**Minimal reproduction of the problem with instructions:**
https://codesandbox.io/s/zwoj9mmv6m

- Select a rating 
- The url has been modified with the filter -> https://zwoj9mmv6m.codesandbox.io/?myRating=3
- delete this filter ( dont do delete all)
- The url is still with the rating of 3 but the filter is not active anymore
->The url should also be update

**Reactivesearch version:** x.y.z
@appbaseio/reactivesearch": "^2.10.3",

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All 

**Anything else:**
Thanks for this great Framework !

**Comment by divyanshu013** [comment]
Duplicate #497 :)
