### ISSUE TITLE
Load data on initial load

### ISSUE THREAD

**Issue by vishalnathani17** [appbaseio/reactivesearch#560]
I have implemented the same code which you have given in Snack, but in my app it is showing blank screen with search bar 

Using on React Native

I want to load some data on the screen when I load it for the first time, before user start searching for the tutors. 
![screenshot at oct 06 16-08-21](https://user-images.githubusercontent.com/43237007/46570474-71fae680-c982-11e8-9097-01a236dcad1a.png)
![screenshot at oct 06 16-09-00](https://user-images.githubusercontent.com/43237007/46570475-72937d00-c982-11e8-86e4-e4b4eb485f97.png)

Dependancies: 
"dependencies": {
    "@appbaseio/reactivesearch-native": "^0.9.0",
    "@expo/videoplayer": "^0.4.0",
    "axios": "^0.18.0",
    "dateformat": "^3.0.3",
    "expo": "^30.0.0",
    "firebase": "^5.5.1-0",
    "native-base": "^2.8.0",
    "prop-types": "^15.6.2",
    "react": "^16.3.1",
    "react-bootstrap-sweetalert": "^4.4.1",
    "react-data-fetching": "^0.2.3",
    "react-dom": "^16.5.2",
    "react-native": "https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz",
    "react-native-animatable": "^1.3.0",
    "react-native-atoz-listview": "0.0.7",
    "react-native-awesome-alerts": "^1.1.1",
    "react-native-calendars": "^1.20.0",
    "react-native-keyboard-aware-scroll-view": "^0.7.2",
    "react-native-modal": "^6.5.0",
    "react-native-modal-datetime-picker": "^6.0.0",
    "react-native-read-more-text": "^1.1.0",
    "react-native-render-html": "^3.10.0",
    "react-native-search-box": "0.0.19",
    "react-native-search-filter": "^0.1.4",
    "react-native-star-rating": "^1.1.0",
    "react-native-sweet-alert": "^1.1.0",
    "react-native-view-more-text": "^2.0.1",
    "react-navigation": "2.0.1",
    "sweetalert-react": "^0.4.11",
    "video-react": "^0.13.0"

**Comment by vishalnathani17** [comment]
@metagrover please help or share the example

**Comment by davekedar** [comment]
I am facing the same issue too @metagrover

**Comment by metagrover** [comment]
Hey guys, you can check this [booksearch snack demo](https://snack.expo.io/@metagrover/booksearch).

If you're not able to figure out the issue with your apps, feel free to share them here, I will be happy to help!

**Comment by davekedar** [comment]
I have done the same, but it is still showing the blank screen unless I search something, I want to load data on initial screen loading please help 

if you want i can share the code

**Comment by metagrover** [comment]
That'd be great. Can you create a snack demo and share here?

**Comment by davekedar** [comment]
`import React, { Component } from "react";
import {
    View,
    Text,
    StyleSheet,
    SafeAreaView,
    ScrollView,
    TextInput,
    Platform,
    TouchableOpacity,
    AsyncStorage,
} from "react-native";
import { Button, Right, Left, Body, Card, CardItem, Thumbnail } from 'native-base';
import {
    ReactiveBase,
    DataSearch,
    ReactiveList,
} from '@appbaseio/reactivesearch-native'; // 0.5.0
import Icon1 from 'react-native-vector-icons/Ionicons'
import Icon2 from 'react-native-vector-icons/FontAwesome'
import axios from 'axios';
import Fonts from '../Theme/assets/Fonts';
import AwesomeAlert from 'react-native-awesome-alerts';

class SearchScreen extends Component {

    state = {
        tutors: [],
        student_id: null,
        bookmark: 'bookmark-o',
        showAlert: false,
        message: '',
        onData: null,
        showTheThing: true
    }

    componentWillMount = () => {
        this.loading();
        <ReactiveBase
            app="qp"
            credentials="jTlNh5TCo:158f2740-a132-48d8-8ad8-9e3928e4c48a">
            <ScrollView>
                <View style={styles.container}>
                    <DataSearch
                        componentId="searchbox"
                        dataField={[
                            'original_title',
                            'original_title.search',
                            'authors',
                            'authors.search',
                        ]}
                        placeholder="Search for books"
                        autosuggest={false}
                    />
                    <ReactiveList
                        componentId="results"
                        dataField="original_title"
                        size={7}
                        showResultStats={false}
                        pagination={true}
                        react={{
                            and: 'searchbox',
                        }}
                        onData={res => {

                            // <View style={styles.result}>
                            //     {/* <Image source={{ uri: res.image }} style={styles.image} /> */}
                            //     <View style={styles.item}>
                            //         <Text style={styles.title}>{res.first_name}</Text>
                            //         <Text>{res.last_name}</Text>
                            //         {/* <Text>{console.log(res)}</Text> */}

                            //     </View>
                            // </View>
                            return (

                                <Card key={res.tutor_id} style={{ borderColor: '#d91009' }}>


                                    <CardItem style={{ borderBottomWidth: 1, borderColor: '#d91009' }}>
                                        <Left>
                                            <Thumbnail source={{ uri: res.profile_image }} />
                                            <Body>
                                                <Text style={{ width: 220 }}>{res.first_name} {res.last_name}</Text>
                                                <Button style={{ padding: 10, backgroundColor: '#d91009', borderRadius: 40, height: 25 }}>
                                                    <Text style={{ fontSize: Fonts.moderateScale(10), color: '#fff' }}>{res.tutor_experties_category}</Text>
                                                </Button>

                                            </Body>
                                        </Left>
                                        <Right>
                                            <TouchableOpacity onPress={() => this.bookmark(res.tutor_id, this.state.student_id)}>
                                                <Icon2 name={res.is_favourite_tutor == 1 ? 'bookmark' : 'bookmark-o'} size={24} color='#d91009' />
                                            </TouchableOpacity>
                                        </Right>
                                    </CardItem>
                                    <CardItem cardBody style={{
                                        justifyContent: 'center',
                                        alignItems: 'center'
                                    }}>
                                        <Text style={{ padding: 10 }}>{res.tutor_experties}</Text>
                                    </CardItem>
                                    <CardItem>
                                        <Left>
                                            <Text>Private Tuition £{res.price_per_h}</Text>
                                        </Left>
                                        <Right>
                                            <View style={{ flexDirection: 'row' }}>
                                                <Button
                                                    style={{ padding: 10, backgroundColor: '#d91009' }}
                                                    onPress={() => this.props.navigation.navigate('SearchScreenCalender', {

                                                    })}>
                                                    <Text style={{ color: '#fff' }}>Book Now</Text>
                                                </Button>
                                                <Button
                                                    style={{ padding: 10, backgroundColor: '#d91009', marginLeft: 5 }}
                                                    onPress={() => this.props.navigation.navigate('TutorDetail', {
                                                        tutor_id: res.tutor_id
                                                    })}>
                                                    <Text style={{ color: '#fff' }}>View Profile</Text>
                                                </Button>
                                            </View>
                                        </Right>
                                    </CardItem>

                                </Card>

                            )
                        }}
                    />
                </View>
            </ScrollView>
        </ReactiveBase>

    }

    loading = async () => {
        const userid = await AsyncStorage.getItem('user_id');
        this.state.student_id = userid
        try {
            let { data } = await axios.post('https://chat.qualpros.com/api/get_tutor_list', {
                tutor_id: '0',
                student_id: userid
            })
                .then((response) => {

                    if (response.data.data.status === 'success') {
                        this.setState({ tutors: response.data.data.tutor_list_array })


                    } else {
                        console.log(response.data.data);





                    }
                })
        }
        catch (err) {
            console.log(err)

        }

    }

    bookmark = async (tutor_id, student_id) => {
        try {
            let { data } = await axios.post('https://chat.qualpros.com/api/make_as_favourite_tutor', {
                tutor_id,
                student_id,
            })
                .then((response) => {

                    if (response.data.data.status === 'success') {

                        this.setState({
                            message: response.data.data.message,
                            showAlert: true,
                        })
                        this.loading();


                    } else {
                        console.log(response.data.data);

                        alert(response.data.data.message)


                    }
                })
        } catch (err) {
            console.log(err)
        }

    }

    showAlert = () => {
        this.setState({
            showAlert: true
        });
    };

    hideAlert = () => {
        this.setState({
            showAlert: false
        });
    };






    render() {

        return (

            <SafeAreaView style={{ flex: 1 }}>
                <View style={{ flex: 1 }}>
                    {/* <View style={{
                        height: Platform.OS == 'android' ? 100 : 80, backgroundColor: 'white',
                        borderBottomColor: '#dddddd', borderBottomWidth: 1
                    }}>
                        <View style={{
                            flexDirection: 'row', padding: 10, backgroundColor: 'white', marginHorizontal: 20,
                            shadowOffset: { width: 0, height: 0 },
                            shadowColor: 'black',
                            shadowOpacity: 0.2,
                            elevation: 1,
                            marginTop: Platform.OS == 'android' ? 30 : 10
                        }}>
                            <Icon1 name="ios-search" size={20}>  </Icon1>
                            <TextInput underlineColorAndroid="transparent"
                                placeholder="Search Tutor"
                                placeholderTextColor="black"
                            />
                        </View>

                    </View> */}

                    <ReactiveBase
                        app="qp"
                        credentials="jTlNh5TCo:158f2740-a132-48d8-8ad8-9e3928e4c48a">
                        <DataSearch
                            componentId="searchbox"
                            dataField={[
                                'first_name',
                                'last_name',
                                'tutor_experties'

                            ]}
                            placeholder="Search for Tutors"
                            autosuggest={false}

                        />
                        


                        <ReactiveList
                                
                            style={{ height: 1400 }}
                            componentId="results"
                            dataField="first_name"
                            //size={25}
                            showResultStats={false}
                            pagination={false}
                            loader="Loading Results.."
                            react={{
                                and: 'searchbox',
                            }}
                            onData={res => (

                                <Card key={res.tutor_id} style={{ borderColor: '#d91009' }}>


                                    <CardItem style={{ borderBottomWidth: 1, borderColor: '#d91009' }}>
                                        <Left>
                                            <Thumbnail source={{ uri: res.profile_image }} />
                                            <Body>
                                                <Text style={{ width: 220 }}>{res.first_name} {res.last_name}</Text>
                                                <Button style={{ padding: 10, backgroundColor: '#d91009', borderRadius: 40, height: 25 }}>
                                                    <Text style={{ fontSize: Fonts.moderateScale(10), color: '#fff' }}>{res.tutor_experties_category}</Text>
                                                </Button>

                                            </Body>
                                        </Left>
                                        <Right>
                                            <TouchableOpacity onPress={() => this.bookmark(res.tutor_id, this.state.student_id)}>
                                                <Icon2 name={res.is_favourite_tutor == 1 ? 'bookmark' : 'bookmark-o'} size={24} color='#d91009' />
                                            </TouchableOpacity>
                                        </Right>
                                    </CardItem>
                                    <CardItem cardBody style={{
                                        justifyContent: 'center',
                                        alignItems: 'center'
                                    }}>
                                        <Text style={{ padding: 10 }}>{res.tutor_experties}</Text>
                                    </CardItem>
                                    <CardItem>
                                        <Left>
                                            <Text>Private Tuition £{res.price_per_h}</Text>
                                        </Left>
                                        <Right>
                                            <View style={{ flexDirection: 'row' }}>
                                                <Button
                                                    style={{ padding: 10, backgroundColor: '#d91009' }}
                                                    onPress={() => this.props.navigation.navigate('SearchScreenCalender', {

                                                    })}>
                                                    <Text style={{ color: '#fff' }}>Book Now</Text>
                                                </Button>
                                                <Button
                                                    style={{ padding: 10, backgroundColor: '#d91009', marginLeft: 5 }}
                                                    onPress={() => this.props.navigation.navigate('TutorDetail', {
                                                        tutor_id: res.tutor_id
                                                    })}>
                                                    <Text style={{ color: '#fff' }}>View Profile</Text>
                                                </Button>
                                            </View>
                                        </Right>
                                    </CardItem>

                                </Card>

                            )}
                        />

                    </ReactiveBase>



                    {/* <ScrollView>



                            {
                                this.state.tutors.map((tutor) => {
                                    return (

                                        <Card key={tutor.tutor_id} style={{ borderColor: '#d91009' }}>


                                            <CardItem style={{ borderBottomWidth: 1, borderColor: '#d91009' }}>
                                                <Left>
                                                    <Thumbnail source={{ uri: tutor.profile_image }} />
                                                    <Body>
                                                        <Text style={{ width: 220 }}>{tutor.first_name} {tutor.last_name}</Text>
                                                        <Button style={{ padding: 10, backgroundColor: '#d91009', borderRadius: 40, height: 25 }}>
                                                            <Text style={{ fontSize: Fonts.moderateScale(10), color: '#fff' }}>{tutor.tutor_experties_category}</Text>
                                                        </Button>

                                                    </Body>
                                                </Left>
                                                <Right>
                                                    <TouchableOpacity onPress={() => this.bookmark(tutor.tutor_id, this.state.student_id)}>
                                                        <Icon2 name={tutor.is_favourite_tutor == 1 ? 'bookmark' : 'bookmark-o'} size={24} color='#d91009' />
                                                    </TouchableOpacity>
                                                </Right>
                                            </CardItem>
                                            <CardItem cardBody style={{
                                                justifyContent: 'center',
                                                alignItems: 'center'
                                            }}>
                                                <Text style={{ padding: 10 }}>{tutor.tutor_experties}</Text>
                                            </CardItem>
                                            <CardItem>
                                                <Left>
                                                    <Text>Private Tuition £{tutor.price_per_h}</Text>
                                                </Left>
                                                <Right>
                                                    <View style={{ flexDirection: 'row' }}>
                                                        <Button
                                                            style={{ padding: 10, backgroundColor: '#d91009' }}
                                                            onPress={() => this.props.navigation.navigate('SearchScreenCalender', {

                                                            })}>
                                                            <Text style={{ color: '#fff' }}>Book Now</Text>
                                                        </Button>
                                                        <Button
                                                            style={{ padding: 10, backgroundColor: '#d91009', marginLeft: 5 }}
                                                            onPress={() => this.props.navigation.navigate('TutorDetail', {
                                                                tutor_id: tutor.tutor_id
                                                            })}>
                                                            <Text style={{ color: '#fff' }}>View Profile</Text>
                                                        </Button>
                                                    </View>
                                                </Right>
                                            </CardItem>

                                        </Card>

                                    )
                                })
                            }





                        </ScrollView> */}

                    }

                </View>

                <AwesomeAlert
                    show={this.state.showAlert}
                    showProgress={false}
                    title="QualPros!"
                    message={this.state.message}
                    closeOnTouchOutside={true}
                    closeOnHardwareBackPress={false}
                    showConfirmButton={true}
                    confirmText="Ok"
                    confirmButtonColor="#d91009"
                    onConfirmPressed={() => {
                        this.hideAlert();
                    }}
                />


            </SafeAreaView>
        );
    }
}
export default SearchScreen;

const styles = StyleSheet.create({
    container: {
        padding: 10,
        marginTop: 25,
    },
    image: {
        width: 100,
        //height: 100,
    },
    result: {
        flexDirection: 'row',
        width: '100%',
        margin: 5,
        alignItems: 'center',
    },
    item: {
        flexDirection: 'column',
        paddingLeft: 10,
    },
    title: {
        fontWeight: 'bold',
    },
});`

**Comment by davekedar** [comment]
https://snack.expo.io/@vishalnathani17/elastic-search-demo @metagrover

**Comment by metagrover** [comment]
Guys, the demo is non-functional. There were some fonts related issue which I resolved but I'm only seeing a check-pattern background on my screen.

Can you please make sure that the snack demo works and then ping here? I will check on the reactivesearch issue you are facing.

**Comment by davekedar** [comment]
Are you using android ? or iOS?

**Comment by metagrover** [comment]
Android. Does it work for you on iOS?

**Comment by davekedar** [comment]
kindly check it on iOS

**Comment by vishalnathani17** [comment]
no still not working

**Comment by vishalnathani17** [comment]
I have audited, after downgrading to 0.5.0 it will show you error, when you audit that you will get this 

![image](https://user-images.githubusercontent.com/43237007/46608086-1b77de80-cb21-11e8-91dd-f4023d4fe9f0.png)

**Comment by metagrover** [comment]
Oh alright, I will try to roll out the new reactivesearch-native release tomorrow with the fix.

**Comment by davekedar** [comment]
@metagrover

**Comment by metagrover** [comment]
Working on it. Had some internal complication regarding appbase-js which we use in reactivesearch-native. Will do a release in some time! Thanks for the patience on this.

**Comment by vishalnathani17** [comment]
@metagrover you guys are awesome and have done a great job by creating this lib

**Comment by metagrover** [comment]
Released `v0.10.0`. Can you guys please verify if things work smoothly for you?

**Comment by davekedar** [comment]
@metagrover it is working fantastically after last update `0.10.0`, thanks
