### ISSUE TITLE
Support refs on DataSearch / other components

### ISSUE THREAD

**Issue by carlopascual** [appbaseio/reactivesearch#573]
**Issue Type:**
Enhancement

**Platform:**
Web

**Description:**
It would be nice to support refs directly on the DataSearch component/ other components to be able to easily access the methods inside. 

One good use case would be if we wanted to set or clear the value in a DataSearch through an external component. DataSearch has its own state so using `innerRef` would not work for us.

Passing refs though does not bring us all the way to the DataSearch component but instead a ref to  React-Redux's `connect()`.

**Minimal reproduction of the problem with instructions:**
1. Pass a ref directly to the DataSearch component
2. Try to call a method found in the DataSearch component like `clearValue` through the ref (this fails)
3. console.log the ref to see that the it is being passed to the React-Redux's `connect()`

**Reactivesearch version:** 2.11.1

**Browser:** all

**Anything else:**
https://itnext.io/advanced-react-redux-techniques-how-to-use-refs-on-connected-components-e27b55c06e34 might be a solution

**Comment by metagrover** [comment]
Now available in 3.0 (alpha and above)

**Comment by joepio** [comment]
Perhaps I'm missing something, but I can't find either `innerRef`, `inputRef` or `myForwardedRef` prop in the [v3.0.0-rc.6 `DataSearch` component.](https://github.com/bietkul/reactivesearch/blob/next/packages/web/src/components/search/DataSearch.d.ts)

[This commit](https://github.com/bietkul/reactivesearch/commit/6dadb68ba34c820ecf629d4722b346d9041b25aa#diff-774c82cb65c430e7849fab1e3b9f8132) seems relevant.

**Comment by bietkul** [comment]
Just pass the `ref` prop and it should work, for example:

```
<DataSearch
  ref={(c) => { this.dataSearchRef = c; }}
/>
```
For some components which have an input element like `DataSearch` you get the input ref as the `_inputRef` property of the ref.
For example, `this.dataSearchRef._inputRef` will give you access to the input element.

**Comment by joepio** [comment]
Thanks for the quick reply! However, the `ref` property also does not exist on DataSearch, according to my typescript:

```
  Property 'ref' does not exist on type 'IntrinsicAttributes & DataSearchProps & { children?: ReactNode; }'.ts(2322)
```

It's present in the dev branch, but not in the latest v3.

**Comment by bietkul** [comment]
Thanks, @joepio for reporting the issue.
Please try with the latest version, it should work now.
