### ISSUE TITLE
Web: Installing from development branch

### ISSUE THREAD

**Issue by andreasasprou** [appbaseio/reactivesearch#579]
How do I install reactivesearch from the development branch via npm/yarn?

**Comment by amirasyraf** [comment]
I'm not familiar with this, but isn't the one from the quickstart guide installing from dev branch?

`create-react-app my-awesome-search && cd my-awesome-search`

`yarn add @appbaseio/reactivesearch` 
or
`npm install @appbaseio/reactivesearch`

https://opensource.appbase.io/reactive-manual/getting-started/reactivesearch.html

**Comment by andreasasprou** [comment]
I believe this describes how to install from the latest production version, not dev

**Comment by aol-nnov** [comment]
@andreasasprou did you try [npm link](https://docs.npmjs.com/cli/link)?

build reactivesearch from git, then `npm link` it and use it in your app.
