### ISSUE TITLE
ReactiveComponent SSR

### ISSUE THREAD

**Issue by spoobar** [appbaseio/reactivesearch#582]
**Issue Type:** enhancement (docs)

**Platform:** Web

**Description:** Hi, could not find any information about using a ReactiveComponent with SSR (next.js) in the docs. Is it possible? Where can I find an example? Thanks

**Reactivesearch version:** 2.12.1

**Comment by axeff** [comment]
I simply used DataController for those cases in getInitialProps.

**Comment by divyadeep-MT** [comment]
@axeff I know this is an old thread but I just got stuck at rendering ReactiveComponent on SSR. Could you point me in the right direction? I looked up **DataController** but couldn't find anything. Any help would be greatly appreciated. Thanks!
