### ISSUE TITLE
Working with floats

### ISSUE THREAD

**Issue by george-dotdev** [appbaseio/reactivesearch#583]
**Issue Type:**
Bug

**Platform:**
Web

**Description:**

![image](https://user-images.githubusercontent.com/41870207/47405586-f7153680-d79d-11e8-8064-d980560d027e.png)
The search is returning  a range of results between 0.3 and 8.27 and and I am trying to display them using the following component. I am assuming this is to do with the lack of floats in Javascript. Is there something I can do to resolve this?
```
                <DynamicRangeSlider
                  componentId="RangeSliderCarat"
                  dataField="weight"
                  showHistogram={false}
                  title="Carat"
                  snap={false}
                  step={1}
                  rangeLabels={function (min, max) {
                    const labels = {
                      start: `${min}`,
                      end: `${max}`,
                    }
                  	return labels
                  }}
                />
```

**Minimal reproduction of the problem with instructions:**
Render the following component with a floating point number.
```
                <DynamicRangeSlider
                  componentId="RangeSliderCarat"
                  dataField="weight"
                  showHistogram={false}
                  title="Carat"
                  snap={false}
                  step={1}
                  rangeLabels={function (min, max) {
                    const labels = {
                      start: `${min}`,
                      end: `${max}`,
                    }
                  	return labels
                  }}
                />

```
**Reactivesearch version:** 
`2.12.1`

**Browser:**
all

**Comment by metagrover** [comment]
I guess, you can use `defaultQuery` prop on `DynamicRangeSlider` wherein, you should get the range values in the params and you can round off the floating numbers there in the query. The query looks like this:

```js
defaultQuery = (value, props) => {
	if (Array.isArray(value) && value.length) {
		return {
			range: {
				[props.dataField]: {
					gte: value[0], // fix the floating point here
					lte: value[1], // fix the floating point here
					boost: 2.0,
				},
			},
		};
	}
	return null;
};
```

Let me know if this works.

**Comment by george-dotdev** [comment]
Hey @metagrover 
Thanks for the suggestion, unfortunately it doesn't work. Is `defaultQuery` definitely a prop of `DynamicRangeSlider` I could see it in the docs, and it doesn't seem to work at all. I couldn't even console.log the value.

**Comment by metagrover** [comment]
My bad, `customQuery` should work.

**Comment by vince83110** [comment]
@george-dotdev It would be amazing if you can share how you figured out :)
