### ISSUE TITLE
Loading information for ReactiveComponent?

### ISSUE THREAD

**Issue by csepulv** [appbaseio/reactivesearch#584]
I have multiple custom components that use `ReactiveComponent`. Is there a way to get `isLoading` information for these components? I tried to `connect` to the redux store, but I don't think anything but a `ReactiveList` gets `isLoading` info. 

I hope I am doing something wrong as I'd like a way to provide user feedback while the component is waiting on a query.

Thanks

**Comment by metagrover** [comment]
Thanks @csepulv! This is a known issue and will be included in `v3.0.0`

Related issues: https://github.com/appbaseio/reactivesearch/issues/227 https://github.com/appbaseio/reactivesearch/issues/250 https://github.com/appbaseio/reactivecore/issues/12

**Comment by csepulv** [comment]
Thanks. Sorry to have missed it. I can close this since the other issues track this, or leave it open till 3.0. (Let me know your preference)

**Comment by bietkul** [comment]
Check `isLoading` property in child component's props, it can be used to render a loader component.
https://opensource.appbase.io/reactive-manual/v3/advanced/reactivecomponent.html#child-component
