### ISSUE TITLE
Need to keep the selected items at the top of the Multilist filter

### ISSUE THREAD

**Issue by naibedya** [appbaseio/reactivesearch#593]
**Issue Type:** Enhancement

**Platform:** ReactiveSearch for Web

**Description:** Thanks a lot for the “Load More” button for the Multilist filter. It helps a lot. 
But it is not very easy to know what are the items being checked from the filter. Because once we select an item and the result loads, the selected items are again hidden unless we click the load more button to check those. 
  
So is it possible if keep the selected items always at the top of the facet control, irrespective of the sort order. 

**Screenshots:**
![imagae](https://user-images.githubusercontent.com/17491662/47715593-36dc9200-dc66-11e8-8da1-80cfc32a24d6.gif)

**Reactivesearch version:** 2.12.0

**Browser:** All Browsers

**Comment by metagrover** [comment]
You can use `transformData` prop to achieve this. It allows transforming the data to render inside the list. You can change the order of the items based on your preferences (i.e. keep the selected ones at the top). It provides the data as param which is an **array** of objects of shape {key: <string>, doc_count: <number>} and expects you to return the **array of objects** of same shape. For example:

```js
transformData={(items) => {
    const updatedItems = items.filter(...);
    return updatedItems; // returns the array
}}
```

Hope that helps.
