### ISSUE TITLE
Can we add another date format for DateRange component

### ISSUE THREAD

**Issue by iseabock** [appbaseio/reactivesearch#598]
**Issue Type:**
Date range query format doesnt support date format in my index

**Platform:**
Web

**Description:**
In my ES indexes I have date time in the following format: 2018-06-13T16:07:26.443000 and I'm trying to use the DateRange component but none of the query formats support that format. Is it possible to add it?

**Reactivesearch version:** x.y.z
2.12.1

**Browser:**
Chrome

**Comment by iseabock** [comment]
@aol-nnov @mateusfreira @siddharthlatest @mtxr Does this sound like something that can get done or should think about a different solution?

**Comment by aol-nnov** [comment]
@siddharthlatest it seems to me like an overkill here.. If one could override `formatInputDate` function, things might be a lot easier...

Anyway, it is not possible now and writing a custom query is the only solution for now...

**Comment by siddharthlatest** [comment]
I agree, we have an open issue for adding support for it - https://github.com/appbaseio/reactivesearch/issues/483.

**Comment by jyash97** [comment]
Fixed in #617
