### ISSUE TITLE
ViewSwitcher component story is not functional

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivesearch#6]
The view shows up as blank when switched. [Playground link](https://opensource.appbase.io/reactivesearch/playground/?selectedKind=ViewSwitcher&selectedStory=Basic&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-knobs)

Also from a UI perspective, there should be a way to display the current active view.

**Comment by metagrover** [comment]
Fixed here: f950ba04fd2690e677a1c3e946ad70c921fbc4a1 ea12074

**Comment by siddharthlatest** [comment]
@metagrover This issue currently exists in the playground story.
