### ISSUE TITLE
ssr with pagination: false broken

### ISSUE THREAD

**Issue by axeff** [appbaseio/reactivesearch#600]
**Issue Type:**
Bug

**Platform:**
Web

**Description:**
The pagination on scrolling does not work with ssr

**Minimal reproduction of the problem with instructions:**
Checkout https://github.com/appbaseio/reactivesearch/tree/dev/packages/web/examples/CategorySearch
and run. If I change to pagination: true it works, with pagination: false it doesn't.

**Reactivesearch version:**
2.13.0

**Browser:**
all|ssr

**Anything else:**
When removing `initialState` from `ReactiveBase`, of course SSR does not work anymore, but pagination works again

**Comment by axeff** [comment]
found workaround but I'm not sure if this won't brake something:
in src/components/result/ReactiveList's constructor set initial state `isLoading` to `false`

**Comment by metagrover** [comment]
Verified with `v3.0.0-beta.7`. Works!
