### ISSUE TITLE
Unable to properly install reactivesearch-native

### ISSUE THREAD

**Issue by gabzon** [appbaseio/reactivesearch#604]
Unable to properly install reactivesearch-native. 
When I run npm install it says: 
found 1 high severity vulnerability in 39193 scanned packages
1 vulnerability requires manual review. See the full report for details.

Here is the npm audit: 

npm audit security report
Manual Review                                 
Some vulnerabilities require your attention to resolve                                                                                    
Visit https://go.npm.me/audit-guide for additional guidance          
High          Denial of Service                                            
Package        ws                                                           
Patched in     >= 1.1.5 <2.0.0 || >=3.3.1                                   
Dependency of  @appbaseio/reactivesearch-native                             
Path          @appbaseio/reactivesearch-native > appbase-js > ws
More info     https://nodesecurity.io/advisories/550

**Comment by bietkul** [comment]
@gabzon Regarding the `ws` vulnerability, It seems like the issue is with `react-devtools`.
Lmk if it helps you https://github.com/websockets/ws/issues/1455#issuecomment-428651039

**Comment by metagrover** [comment]
@bietkul the path seems to be at `appbase-js > ws`. I think we should upgrade `ws` in `appbase-js` to fix this.

**Comment by metagrover** [comment]
Fixed. Please update to 0.11.0 to get things rolling 🎉
