### ISSUE TITLE
ReactiveList onNoResults wraps content in a paragraph

### ISSUE THREAD

**Issue by thebuilder** [appbaseio/reactivesearch#606]
**Issue Type:**
bug

**Platform:**
web
**Description:**
`<ReactiveList>` onNoResults wraps the children in a `<p>`. This makes sense if you just wan't to list a simple text message, but it prevents us from rendering a more detailed description. 
Nesting other block elements inside the paragraph makes the DOM invalid HTML. So for example you can't have a `<h2>` and `<p>` tag inside it. In my usecase i'd like to render rich text, with multiple paragraphs and headers.

https://github.com/appbaseio/reactivesearch/blob/7a9fb9bd39213bf4fde0f5268d4c9350ac4bedaa/packages/web/src/components/result/ReactiveList.js#L426

**Anything else:**

I'd recommend using a `<React.Fragment>` for rendering the output instead, keeping it open. This would be a breaking change for people using the class. 
You could also change the `<p>` to a `<div>`, keeping the css class. This would keep it as a block element, but making it easier to work with.

Another solution would be to allow us to specify the wrapper element, so we can use a `<div>` instead.

**Comment by metagrover** [comment]
We will be releasing support for `renderResultStats` and `onResultStats` props in the upcoming `v3.0.0` which should improve the custom rendering in this case - https://github.com/appbaseio/reactivesearch/pull/461

- `on<>` props will only expose the data for the user to consume and use (custom render from the parent) as they like.
- `render<>` props will handle the default rendering.
