### ISSUE TITLE
When unselecting the NestedList value from the SelectedFilter component, the selection doesn't work

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivesearch#61]
When unselecting the NestedList value from the SelectedFilter component, the NestedList selections stop working.

**Comment by siddharthlatest** [comment]
@metagrover commit sha?

**Comment by metagrover** [comment]
@siddharthlatest Fixed here: 662498cb211ff553e834899a4078240942b5885b

btw I referred the issue in the commit already.
