### ISSUE TITLE
Question about multiple indices and the scalability?

### ISSUE THREAD

**Issue by nicholasfay** [appbaseio/reactivesearch#614]
Is there anyway to supply multiple indices to a reactiveBase and only pull results from a specific index within a reactive component. If not, I don't see how this could be scalable if you want to use many indices and poll specific indices using for example a term query on the _index field of a document it would have to check across extra documents.

**Comment by metagrover** [comment]
Hi @nicholasfay, `app` can take multiple indexes: you have to separate them by comma:

```js
<ReactiveBase
  app="index1,index2"
  ...
>
  ...
</ReactiveBase>
```

You can use `customQuery` prop for modifying the query of a component to target a particular `index`. Related: https://github.com/appbaseio/reactivesearch/issues/545

**Comment by siddharthlatest** [comment]
Closing this issue, I have filed #616 which talks about an enhancement to support this out of the box. This is on our `3.x` roadmap, so it might be a while before we actually have this out.

@nicholasfay If you want to take a stab at a PR for one of the components, feel free to.

**Comment by nicholasfay** [comment]
> Hi @nicholasfay, `app` can take multiple indexes: you have to separate them by comma:
> 
> ```js
> <ReactiveBase
>   app="index1,index2"
>   ...
> >
>   ...
> </ReactiveBase>
> ```
> 
> You can use `customQuery` prop for modifying the query of a component to target a particular `index`. Related: #545

A scenario I have is: A one page dashboard where I want to switch searching contexts based on the dashboard context that is set. If I put in multiple indices into the ReactiveBase and only want to search through one of them using the CustomQuery prop (As they have vastly different fields), would this accomplish this? Essentially I don't want my hotel search to be looking through my movie index as well and returning the ones that match "_index" == hotel.
