### ISSUE TITLE
DynamicRangeSlider: Empty aggs causes a 400 query error

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivesearch#62]
In **DynamicRangeSlider** component, when `showHistogram` prop is set as *false*, an empty ``aggs`` array is passed. This causes a bad query exception.

Do not pass the aggs object when a histogram query isn't needed.

**Comment by metagrover** [comment]
Fixed here: 09e099ba15b6f28d0333ce257618ab296ac553ad and https://github.com/appbaseio/reactivebase/commit/f9fb7de70fc34413bf8f502049e0fc7be69cedf9
