### ISSUE TITLE
Running ReactiveSearch in Windows

### ISSUE THREAD

**Issue by divyanshu-rawat** [appbaseio/reactivesearch#624]
**Issue Type: BUG** 

**Platform:**
Widnows 10

**Description:**
Running ``` yarn dev:web ``` will not work.

**Screenshots:**
![capture](https://user-images.githubusercontent.com/13464678/48918767-bf8ccd80-eeb4-11e8-8335-1483c81d51ba.PNG)

**Minimal reproduction of the problem with instructions:**
After setting up the development enviroment in Windows 10 by following instructions mentioned here https://github.com/appbaseio/reactivesearch/blob/dev/.github/CONTRIBUTING.md, try running ``` yarn dev:web``` it will throw an `err` ``` 'BABEL_ENV' is not recognized as an internal or external command```. 

**Reactivesearch version:** 
"version": "2.14.1"

**Browser:**
Google Chrome Version 70.0.3538.110 (Official Build) (64-bit)

**Anything else:**
Please find attached snapshot for more details @metagrover , this issue can be fixed by using https://www.npmjs.com/package/cross-env npm package  as a dependency.

And by replacing following lines in ```package.json```, by appending ```cross-env``` .

```
"build:commonjs": "cross-env BABEL_ENV=commonjs babel --ignore __tests__ src --out-dir lib",
"build:es": "cross-env BABEL_ENV=es babel src/index.js --out-file lib/index.es.js",
"build:umd": "cross-env BABEL_ENV=commonjs webpack --progress -p --config webpack.config.umd.js"
```
Let me know your thoughts in it.

**Comment by metagrover** [comment]
We should use `cross-env`. @divyanshu-rawat Can you propose a PR to fix this? 😅

**Comment by divyanshu-rawat** [comment]
@metagrover sure will do that.
