### ISSUE TITLE
getting error in ReactiveSearch

### ISSUE THREAD

**Issue by allendol** [appbaseio/reactivesearch#627]
I am getting the following error when I am running Reactivesearch using DataSearch, DateRange and ReactiveList components:

REACTIVESEARCH - An error occured while parsing the URL state. SyntaxError: Unexpected token e in JSON at position 1
    at Object.parse (<anonymous>)
    at ReactiveBase.js:147

With this error the application is still working in Google Chrome

**Comment by metagrover** [comment]
Related #607
