### ISSUE TITLE
Pagination customization: get last page

### ISSUE THREAD

**Issue by rap2hpoutre** [appbaseio/reactivesearch#633]
**Issue Type:** enhancement

**Platform:** web

**Description+Screenshots:**
Currently, the pagination only displays the N first page (and not the last one) : 

<img width="390" alt="capture d ecran 2018-11-28 a 16 12 56" src="https://user-images.githubusercontent.com/1575946/49161123-7f03d880-f328-11e8-9cbf-9c9eb628d235.png">

It could be great if we could display something like this (with the last page): 

![zrjowucfrgwclsvoxhzbdw](https://user-images.githubusercontent.com/1575946/49161191-9fcc2e00-f328-11e8-9a97-9a43b5550bb5.png)

**Reactivesearch version:** 2.11.0

**Comment by davidklebanoff** [comment]
I understand that some websites do this, but can you provide a use case when this would be a desired feature? I can't think of a compelling case, and it seems is presence would harm usability.

**Comment by siddharthlatest** [comment]
I second @davidklebanoff's point. What's a good use-case for showing the last page? I think it can be useful for testing purposes, but not anywhere else.

**Comment by janaka120** [comment]
Any update on this one @rap2hpoutre

**Comment by siddharthlatest** [comment]
@janaka120 We haven't added support for this yet, but are open to. Feel free to create a PR, or we will leave this open for now.

**Comment by anshumanv** [comment]
Picking this up ✨
