### ISSUE TITLE
Examples of request caching?

### ISSUE THREAD

**Issue by cooperka** [appbaseio/reactivesearch#634]
**Issue Type:** Docs

**Summary:** I couldn't find any existing docs on how to set up a local (client-side) caching layer for requests. I could write something myself, but I'm sure others have been there before and may have good advice. I'd love to contribute these docs.

As I navigate page to page, add/remove filters, etc. I often see the same query hitting the network over and over. A cache would help tremendously. Is this on the roadmap at all?

I imagine using a cusom [`transformRequest`](https://opensource.appbase.io/reactive-manual/getting-started/reactivebase.html#props) prop on `ReactiveBase` would be the place to start. The docs say "this is an experimental API and will likely change in the future" but I can't see anywhere else to put it.

I'm willing to help contribute to these docs if/when I come up with a working solution, and in the meantime, if anyone else has accompilshed this I'd love to see examples. Cheers!

**Comment by siddharthlatest** [comment]
Hey @cooperka, Elasticsearch already maintains a cache of the most frequent queries - https://www.elastic.co/guide/en/elasticsearch/reference/current/shard-request-cache.html.

That said, there can be scenarios where some caching on your own could be useful. If you use your own middleware proxy, that could be a good place to cache the query request and responses. You can see how to setup one here - https://github.com/appbaseio-apps/reactivesearch-proxy-server. 

While `transformRequest` allows control over the request, it doesn't handle responses. That would have to happen from one of the `onAllData` props. Using a middleware proxy of your own is the cleanest way I can imagine doing this.

**Comment by cooperka** [comment]
Hi @siddharthlatest, I realize my original post was ambiguous -- I'm specifically looking for a local (client-side) cache. I want to prevent the request from firing at all if it already has the data locally. `onAllData` will probably help, thanks.

**Comment by gaving** [comment]
@cooperka Don't suppose you got anywhere with this?

We've a similar requirement here to limit network traffic, we've some audit middleware auditing every request and it's looking a bit confusing since loads of these requests are being fired on every component interaction!

**Comment by cooperka** [comment]
@gaving nope, we ended up coding our own filters from scratch because of this and other issues we kept running into.

**Comment by gaving** [comment]
@cooperka Ah. Sounds about right (and painful!), thanks for getting back.

**Comment by cooperka** [comment]
[not stale]
