### ISSUE TITLE
Elasticsearch Cluster requests are failing for demos

### ISSUE THREAD

**Issue by atMari** [appbaseio/reactivesearch#654]
**Issue Type:**
This is a bug

**Platform:**
Web

**Description:**
I was showing a friend the [airbeds demo](https://opensource.appbase.io/reactivesearch/demos/airbeds/) yesterday, and they thought it was really cool.  We checked it out again today, and it looks like the Elasticsearch cluster may be down.  The requests are failing.

**Screenshots:**
<img width="1437" alt="screen shot 2018-12-04 at 10 18 15 am" src="https://user-images.githubusercontent.com/4072305/49456137-1dbb8980-f7ae-11e8-86cb-679c6fb44219.png">
<img width="1280" alt="screen shot 2018-12-04 at 10 19 10 am" src="https://user-images.githubusercontent.com/4072305/49456138-1dbb8980-f7ae-11e8-8951-ac1fd53a4d29.png">

**Minimal reproduction of the problem with instructions:**
Visit the [airbeds demo](https://opensource.appbase.io/reactivesearch/demos/airbeds/) 

**Reactivesearch version:**
latest

**Browser:**
all

**Anything else:**
Thank you for all of your work on this library. It's fantastic.

**Comment by metagrover** [comment]
Hello, our servers are currently under maintenance, hence some apps are non-functional at the moment. It should be back shortly. Sorry for the inconvenience 🐱

**Comment by atMari** [comment]
All good, @metagrover ! Thanks for the heads up 👍
