### ISSUE TITLE
Support controlled behavior on suggestion select in search components

### ISSUE THREAD

**Issue by metagrover** [appbaseio/reactivesearch#665]
**Issue Type:**
Enhancement

**Platform:**
Web - React

**Description:**
Search components should support `onChange` trigger when user selects a suggestion from the auto-suggest list. Currently, it bypasses the `onChange` and sets the value on suggestion select.

**Minimal reproduction of the problem with instructions:**
1. Set `value` prop on the search component.
2. Set `onChange` handler on the search component.
3. Type something and select a suggestion - you will see that `onChange` was not triggered on suggestion select.

**Reactivesearch version:** x.y.z
This is only applicable to next (version `3.0.0`).

**Comment by metagrover** [comment]
@jyash97 Please refer [this commit](https://github.com/appbaseio/reactivesearch/commit/4ffee7c0dfddbe8b5df0d5b4d1a0a2b7a7dacfe2) for `DataSearch` component upgrades and you can replicate the same behavior for `CategorySearch`.

**Comment by metagrover** [comment]
@jyash97 can you verify this and close if it works properly?

**Comment by jyash97** [comment]
Works properly 💯
