### ISSUE TITLE
0.10.0 of reactivesearch-native depends on vue, http-proxy-middleware example does not work for native

### ISSUE THREAD

**Issue by bpkennedy** [appbaseio/reactivesearch#676]
**Issue Type:**
Documentation

**Platform:**
Native

**Description:**
Improve your docs.

1). 0.10.0 of the React Native has dependencies on Vue (which I assume is a "whoops" as someone wrote reactivecore for the web version first).  I had to roll back to 0.9.0, and I don't know what all bugs I experience from this point forward were fixed from 0.9.0 to 0.10.0, which leads to....

2). In the React Native section of your docs, you list examples of how to proxy http requests using middleware and **you link to examples that use React for Web** (verified by the package.json that brings in `react-dom`) and do *not* work correctly in react-native.  In the iOS simulator, I get these errors:  `Failed prop type: Invalid prop `name` of value `ios-search-outline`` (this for a slew of icons). 
 This also appears to be dependency-related and something not getting bundled with the package's distribution.  Are these errors because React Web vs React Native?  Are they because I am now using 0.9.0 and were already fixed?  Are they an issue in 0.10.0?

Thanks for what you're trying to do here, but I have limited time to work on side projects (a few hours a week), and I just spent them all trying to get reactivesearch to simply stand up.  I'll be using a different library or rolling my own.

**Comment by metagrover** [comment]
Sorry about this. We will be doing a reactivesearch-native release today to fix the vue-dependency issue.

The other issue that you are seeing seems to be pointing to missing icons package from nativebase. I will check on this and update the docs accordingly. The proxy example is platform agnostic, your proxy server should work the same with web and native.

**Comment by metagrover** [comment]
Fixed. Please update to `0.11.0` to get things rolling 🎉
