### ISSUE TITLE
DataRange cannot easily select or type the wide date range

### ISSUE THREAD

**Issue by allendol** [appbaseio/reactivesearch#677]
The user wants to select or type date range from 1/1/2010 to 1/1/2020.
User cannot type the date range. Only has to select 1/1/2017 from the calendar and go sequentially back month by month to date 1/1/2017 and then for the end date, has to click the calendar month by month to get to 1/1/2020.
There is no other easy way to select data range.

**Comment by metagrover** [comment]
Related PR: https://github.com/appbaseio/reactivesearch/pull/563
