### ISSUE TITLE
DateRange Component is hard to use for wide date range

### ISSUE THREAD

**Issue by allendol** [appbaseio/reactivesearch#680]
We have developed the interface using ReactiveSearch. We are using DateRange component.
User wants to select Date range from 1/1/2007 to 1/1/2020. The only way to do this, is to navigate sequentially and go back month by month to 1/1/2007 for Date Start and then go forward sequentially month by month  to 1/1/2020.
I don't think any user likes this. Please provide real alternative or an interrum solution. This is show stopper.

**Comment by metagrover** [comment]
Repeated: #677
PR to fix this: https://github.com/appbaseio/reactivesearch/pull/563
