### ISSUE TITLE
Allow customisation of endpoint URL (/app_name/_msearch)

### ISSUE THREAD

**Issue by maijs** [appbaseio/reactivesearch#683]
**Issue Type:**
Enhancement

**Platform:**
ReactiveSearch for Web

**Description:**
ReactiveBase has [`url`](https://opensource.appbase.io/reactive-manual/getting-started/reactivebase.html#props) prop which allows setting the URL for the Elasticsearch cluster. Reactive search seems to be very opinionated in terms of endpoint URL where request with query is sent, as it appends `/[app_name]/_msearch` to the URL provided with the prop, and does not allow the full endpoint URL to be changed.

My current project requires handling all the Reactive search requests through a single proxy resource (`search.php`) and it's not possible to customise the actual endpoint URL where query requests are sent.

This issue is similar to https://github.com/appbaseio/reactivesearch/issues/471.

**Reactivesearch version:** 2.14.1

**Browser:** all

**Comment by siddharthlatest** [comment]
Hey @maijs, we are working on this in the new `v3.0.0` release. It should address customization of  URI / request body / use of GraphQL instead of REST.

I am closing this since we already have #471 open and there is an active discussion over there. And we will keep that updated instead.
