### ISSUE TITLE
Unable to resolve "vue" from "node_modules/vue-types/dist/utils.js"

### ISSUE THREAD

**Issue by gabzon** [appbaseio/reactivesearch#688]
**Issue Type**: BUG
**Platform**: Native
**Description**:
I'm getting the following Error message: 

_Unable to resolve "vue" from "node_modules/vue-types/dist/utils.js"_

I am trying to follow the tutorial **ReactiveSearch Quickstart** https://opensource.appbase.io/reactive-manual/native/getting-started/reactivesearch.html

This is what I did: 
`expo init myproject`
cd myproject
`yarn add @appbaseio/reactivesearch-native`
Copied the following code in the Apps.js as explained in the tutorial

`import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { ReactiveBase } from '@appbaseio/reactivesearch-native';

export default class App extends React.Component {
  render() {
    return (
      <ReactiveBase
        app="good-books-ds"
        credentials="nY6NNTZZ6:27b76b9f-18ea-456c-bc5e-3a5263ebc63d"
      >
        <View style={styles.container}>
            <Text>Hello ReactiveSearch!</Text>
        </View>
      </ReactiveBase>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
});`

Then
`yarn start`

and I get the error message!

To be honest I am not a react expert, but I didn't put one single line of my code. I only followed 3 steps of the tutorial. 

Do I need to change react, node, expo version?

**Screenshots:**
![screenshot 2018-12-13 at 18 26 37](https://user-images.githubusercontent.com/142036/49956101-b5368000-ff04-11e8-92db-b62d21392667.jpg)

**Comment by metagrover** [comment]
Sorry about this. This is a known issue and we will be doing a release early tomorrow to fix this.

**Comment by metagrover** [comment]
Fixed. Please update to `0.11.0` to get things rolling 🎉
