### ISSUE TITLE
transformRequest does not work  with SSR

### ISSUE THREAD

**Issue by willopez** [appbaseio/reactivesearch#696]
Issue: Bug

**Platform:**
Web

**Description:**
I am using ReactiveSearch web, with Next.JS. Attempting to implement SSR with `transformRequest` provided in settings like so: 
```
const settings = {
  app: ...,
  transformRequest: (request) => { console.log("transformRequest"); return request; },
  url: ...
};
```
The provided transform function does not get executed on the server. Looking at this line: https://github.com/appbaseio/reactivesearch/blob/dev/packages/web/src/server/index.js#L271

It's obvious that the transform function provided in `settings` is ignored. 

Can SSR support for `transformRequest` be added?

**Comment by willopez** [comment]
@metagrover Please checkout my proposed implementation

**Comment by metagrover** [comment]
Thank you for the contribution. We will roll this out in the upcoming release 🎉
