### ISSUE TITLE
Guidance needed for showing results on a separate results page

### ISSUE THREAD

**Issue by object505** [appbaseio/reactivesearch#705]
**Platform:**
ReactiveSearch for Web

**Description:**
I was checking the docs and couldn't find any way to initialize a search on a separate page using a link generated with ReactRouter 4.
The link is something like this: example.com/search?category="documentary"
It should go to the search results page and show all results from the category "documentary". Currently it goes to the search page and shows all results (I am using ReactiveList to show the results).
Is this doable at all?

Also, I have another issue. I have a search form on the home page. When the user fills the search input and submits the form, I would like to go to the search page and show the results for that search input.
It goes to the search result (the url is like this example.com/search?query="some search value", but it just shows all the results, just like with the previous link issue.
I am using DataSearch component on the search page. Also I have set URLParams to true. 
I've noticed that when I have the DataSearch in the header and I add some text there and then from the form I make the redirect it works, it takes the input from DataSearch and it show the relevant results.
But, how to do it with a different input? How to fill/set the value in DataSearch? 
Am I missing something? Can you give me some advice how to handle this?

**Comment by metagrover** [comment]
[You can check this answer to achieve the desired implementation.](https://stackoverflow.com/questions/51910986/reactivesearch-search-from-any-route/51915054#51915054)

Notice how we are using the same `componentId` for DataSearch in both pages. That manages everything for you. You won't have to write any manual code/query to achieve what you're looking for.

Hope this helps.
