### ISSUE TITLE
Apply global CustomQuery for all components

### ISSUE THREAD

**Issue by mauxtin** [appbaseio/reactivesearch#715]
This is not an issue but I found other people having the [same](https://stackoverflow.com/questions/53818777/how-to-filter-initial-response-in-reactivesearch) [question](https://stackoverflow.com/questions/53842011/reactivesearch-customquery) so I thought it would be a good idea to post it here as well. (Feel free to close this.)

I am looking for a way to add a predefined selected value when the page loads.

Specifically on page load I am looking for a way to only show cars of a particular manufacturer.

e.g. when the url is /manufacturers/bmw (id: 1) I need to add customQuery with that value.

This is what I tried but it doesn't seem to have any effect. (I still see unfiltered items)

```
<ReactiveBase
...
  >
    <ReactiveList
      ...
      :react="{and: ['colors', 'manufacturers']}"
      component-id="SearchResult"
      data-field="id"
      :custom-query="
        () => {
          return {
            'match': { 'manufacturer_id': 1 }
          }
      }"
    >
    </ReactiveList>
</ReactiveBase>
```

Note that this must be a global thing since filters should also respect the same query.

Also, the network request **does not** include the query I entered so this is possibly a bug in the vue package? Or am I doing something wrong?

**Comment by mauxtin** [comment]
Seems to be somewhat related to this #705 however doing it with `url-params` is not an option for us.

**Comment by metagrover** [comment]
You can utilise `defaultSelected` prop for this. Say you want to select `Item A` from SingleList component on load. Just use `defaultSelected={"Item A"}` to achieve this. Now, considering your `ReactiveList`'s react prop includes the SingleList component, it will consider this selected value while generating its result query.

Using customQuery here, comes with the weight of managing the removal of the customQuery later on when you don't need `Item A` based query. With the above approach, you can render a `SelectedFilter` and user can easily remove `Item A` from selection when required.

[Refer this comment for more info](https://github.com/appbaseio/reactivesearch/issues/705#issuecomment-449010200).

**Comment by mauxtin** [comment]
Hello @metagrover and thanks for taking the time to address this.

The only problem with this approach is that it requires that I have a SingleList component in the page with the categories which is not the case.

When visiting  `/manufacturers/bmw` it doesn't make sense to have a manufacturers SingleList component in the page since I expect to only display the results of this specific manufacturer. No other manufacturer should exist in the first place.

It seems like a reasonable and simple thing which makes me wonder how others are handling this use case.

The fact that the `customQuery` requires the removal of the `customQuery` seems reasonable to me since when the user navigates to a different page a different `customQuery` should be applied (with a different manufacturer perhaps.).

There is no use case for me that requires me to display all results of my index on page load. All pages must have a custom query on page load which must, of course, take effect on filters, pagination etc.

**Comment by metagrover** [comment]
Got it! For your usecase, `defaultQuery` prop on `ReactiveList` component makes perfect sense. It allows appending your desired query say `{ query: { 'match': { 'manufacturer_id': 1 } } }` with the existing ReactiveList component's query (which includes `size`, `from` and other defaults which the component provides).

**Comment by mauxtin** [comment]
That doesn't seem to have any effect on the filters however. Is there any way I could possibly apply the `defaultQuery` to ReactiveBase so that it becomes global?

**Comment by metagrover** [comment]
Oh I see what you mean. [Check `DataController` component](https://opensource.appbase.io/reactive-manual/base-components/datacontroller.html). It's a simple component with no/custom UI. If you set the desired `{ query: { 'match': { 'manufacturer_id': 1 } } }` query on this component's `customQuery` prop and add its `componentId` to the `react` prop of all the filters and `ReactiveList`, everything should work properly and in this case, you can remove the query prop from the `ReactiveList` as well.

Conceptually, you are creating a component with no UI (but a query) which all the filters and result components are watching. Hope this helps!

**Comment by mauxtin** [comment]
The `customQuery` prop on DataController doesn't seem to have any effect :/ 

I created a sandbox for this: https://codesandbox.io/s/zq87l7mr2m

**Comment by metagrover** [comment]
Sorry about that. We don't support this in the `vue` library yet (It's only available for `react` and `react-native`). @bietkul should be able to help you with ReactiveComponent implementation for the same with the vue library.

**Comment by bietkul** [comment]
@mauxtin Check this working example with `ReactiveComponent` https://codesandbox.io/s/94l1mvwxqy

**Comment by mauxtin** [comment]
Thanks @bietkul! 👍 This seems to work for my use case even if it's a bit hackish. 

(Not sure if you want to close this or leave it open until a less-hackish way is found :) - Feel free to close it.)

**Comment by metagrover** [comment]
@bietkul We should add support for `DataController` component here to improve the usability.

**Comment by allendol** [comment]
I see following as a sample of using custom-query
        :custom-query="
          () => {
            return {
              match: { 'item.original_publication_year': **2012** }
            };
          }
        "
How can we make the value **2012** dynamic? How can we get this value from the **interface**?
