### ISSUE TITLE
Feature: Allow for sortByKey prop in ReactiveList

### ISSUE THREAD

**Issue by mauxtin** [appbaseio/reactivesearch#719]
I noticed that there is a `sortBy` prop but no way of setting the key to be sorted with and the results are being sorted based on the `dataField` prop which only makes sense if you are ordering alphabetically.

It would be nice to have a way of setting the key prop, something like `sortByKey`.

Of course, you can use sortOptions and do something 

```
    :sort-options="[
        {
          label: "Best match",
          dataField: '_score',
          sortBy: 'desc'
        }
     ]"
```

But that limits you in terms of how the UI is rendered.

Anyway, I think it is reasonable to have a way of changing the key that the results are being sorted with.

**Comment by siddharthlatest** [comment]
@mauxtin In a ReactiveList, the primary use of `dataField` is to apply the sorting order, it acts as a proxy for the `sortByKey` functionality you are proposing. Do you see any limitations with using it?

**Comment by mauxtin** [comment]
Hi @siddharthlatest, I didn't know that the `dataField` is meant only for this use case. 

I haven't seen any limitations with it but consider changing its name to something close to what I proposed so that it is more clear what it is intended for :)

Thanks for the clarification :)

**Comment by siddharthlatest** [comment]
Great, in a result component, sorting is the primary use-case for it. We should make this more clear in the docs. cc @jyash97

**Comment by bietkul** [comment]
You can find the updated docs [here](https://opensource.appbase.io/reactive-manual/vue/result-components/reactivelist.html).
