### ISSUE TITLE
Feature: Add realtime prop to DataSearch

### ISSUE THREAD

**Issue by mauxtin** [appbaseio/reactivesearch#720]
A boolean prop on the `DataSearch` component that will basically allow for realtime search as the user types in the searchbox.

Example:
```
<data-search
  componentId="SearchSensor"
  title="Search"
  :realtime="true"
/>
```

This will allow for a much better User Experience since now the user must press enter in order to search.

**Comment by siddharthlatest** [comment]
@mauxtin This is already possible via the `autosuggest` prop, you can set it to `false` to get a search as you type behavior. I noticed that our docs didn't list this. I have updated them to reflect the change.

**Comment by mauxtin** [comment]
Ah! I thought `autosuggest` prop was only for displaying the suggestion list or not. 

Shouldn't this be in a different prop since someone may want to display suggestions as well as having the realtime search at the same time? (Not my use case but the prop seems to do two completely different things right now.)

Anyway thanks, that works for me 👍
