### ISSUE TITLE
Vue: Allow customization of RangeSlider

### ISSUE THREAD

**Issue by mauxtin** [appbaseio/reactivesearch#721]
It would be nice to have more options for `RangeSlider`, [here](https://github.com/appbaseio/reactivesearch/blob/dev/packages/vue/src/components/range/RangeSlider.jsx#L164-L175).

Ideally, this can be a single prop `sliderOptions` which will accept an object and `v-bind` it on vue-slider.

Possibly something like this, instead of the reference code above.

```
<vue-slider
   ref="slider"
   v-bind="sliderOptions"
   ...
/>
```

This will allow for maximum customization of the component and cleaner code in the library.

**Comment by siddharthlatest** [comment]
@mauxtin I love the feedback, keep it coming. What is a good customization use-case here?

**Comment by mauxtin** [comment]
One good use case would be the `formatter` prop.

It allows you to display the numbers with some customization.

For example instead of using the `rangeLabels` like this 
```
 :range-labels="{
      start: '€0',
      end: '€50000'
 }"
```

We can simply set a formatter which (in this case) will add the euro sign automatically to the tooltips. 

```
formatter: '€{value}',
```

Some other ones that I use are `bgStyle`, `tooltipStyle` and `processStyle` but the props are too many so `v-bind`ing this might be the approach here.

**Comment by jyash97** [comment]
Thanks for the feedback @mauxtin 
`sliderOptions` prop is added in the latest release. You can check the docs [here](https://opensource.appbase.io/reactive-manual/vue/range-components/rangeslider.html#props).
