### ISSUE TITLE
Feature: Aggregate min and max in RangeSlider

### ISSUE THREAD

**Issue by mauxtin** [appbaseio/reactivesearch#722]
Not sure if I am missing something or if it is developed in the react libraries and not in Vue but it would be awesome if the `RangeSlider` could aggregate the min and max values of the field that was passed automatically.

This would mean that the min and max values are not needed anymore.

There are no docs for that component so I am not 100% sure but I couldn't find anything related to that [in the code](https://github.com/appbaseio/reactivesearch/blob/dev/packages/vue/src/components/range/RangeSlider.jsx).

**Comment by metagrover** [comment]
@bietkul We need to add support for `DynamicRangeSlider` in the vue libarary. It should be trivial to implement since it's an aggs based abstraction over the RangeSlider component.

**Comment by mauxtin** [comment]
Closing as it seems like this has been implemented.
