### ISSUE TITLE
Vue SelectedFilters slot-scope bug

### ISSUE THREAD

**Issue by mauxtin** [appbaseio/reactivesearch#723]
I think there is a bug (or I am doing something wrong) with using `slot-scope` on the SelectedFilters component. 

(I am not very familiar with slots, so let me know if I am doing something wrong)

When no slot is given the selected filters are shown fine but when trying to add some customization on them with a slot nothing is being displayed.

```
          <selected-filters
            :show-clear-all="true"
            clear-all-label="Clear filters"
          >
            <div slot-scope="{ data }">
              {{ data }}
            </div>
          </selected-filters>
```

What I am trying to achieve is fix this:
![screenshot_1](https://user-images.githubusercontent.com/40521145/50319086-12ff3500-04ce-11e9-81f1-dab59151513f.png)

So that instead of price_range I display "Price range" and convert the rest of the filters to Capitalized Case (i.e. colors => Colors)

**Comment by metagrover** [comment]
You can use `filterLabel` prop to achieve this. Feel free to reopen if that doesn't work for you 🐱
