### ISSUE TITLE
currency comma delimited RangeSlider

### ISSUE THREAD

**Issue by sebolek** [appbaseio/reactivesearch#728]
**Issue Type:**
enhancement

**Platform:**
Web, Vue

**Description:**
How can I format the range numbers to be comma delimited? Basically I need to format it as currency for example 1000999  should look like $1,000,999 on the 'tool tip' on the RangeSlider?

<img width="310" alt="screen shot 2018-12-23 at 7 57 44 am" src="https://user-images.githubusercontent.com/6601508/50385324-b136fa80-0688-11e9-9c02-cb823cea9aa8.png">

**Comment by metagrover** [comment]
You can use `renderTooltipData` prop for the same. [Refer docs here](https://opensource.appbase.io/reactive-manual/range-components/rangeslider.html).

**Comment by metagrover** [comment]
Sorry, we don't support it in vue yet. The aforementioned prop only works in react library. Thanks for filing this.

**Comment by jyash97** [comment]
@sebolek You can now use `sliderOptions` prop to customize the value. 

usage:
```js
          :sliderOptions="{
            tooltip: 'hover',
            formatter: function(value) {
              return '$' + value;
            }
          }"
```

You can read more about this [here](https://opensource.appbase.io/reactive-manual/vue/range-components/rangeslider.html#props)

**Comment by sebolek** [comment]
Awesome, Thanks! Keep up the good work.
