### ISSUE TITLE
Show loader on each query execution

### ISSUE THREAD

**Issue by Arvind6353** [appbaseio/reactivesearch#733]
Hi , 

I have a scenario where , am using sortOptions with sorting on _score and date fields.

By default the sorting is on _score .

If the user selects the sort option to sort by date , then the results are sorting by date .

And if the user performs another query , the sort option retains on date and results are shown in date order instead of relevance. 

I can manually change the sort options to _score but its triggering another query in the backend . 

I am using NProgress to show loader during query execution .

I am triggering NProgress.show() in onValueChange prop of DataSearch and NProgress.done() on the OnResultStats prop of ResultList..

This works fine in normal scenarios . But in case when I manually trigger Sorting back to _score , 2 queries are executing simultaneously. 

sorting query executes fast and this onResultStats gets called and am closing the loader but the original search query is still executing in the background and it is giving a wrong user experience .

Any suggestions on how to handle this sort options scenario 
.

**Comment by metagrover** [comment]
Can you please add more details here? We do support `loader` props on the result components.

**Comment by Arvind6353** [comment]
Hi ,

I have a scenario where , am using sortOptions with sorting on _score and date fields.

By default the sorting is on _score .

If the user selects the sort option to sort by date , then the results are sorting by date .

And if the user performs another query , the sort option retains on date and results are shown in date order instead of relevance.

I can manually change the sort options to _score but its triggering another query in the backend .

I am using NProgress to show loader during query execution .

I am triggering NProgress.show() in onValueChange prop of DataSearch and NProgress.done() on the OnResultStats prop of ResultList..

This works fine in normal scenarios . But in case when I manually trigger Sorting back to _score , 2 queries are executing simultaneously.

sorting query executes fast and this onResultStats gets called and am closing the loader but the original search query is still executing in the background and it is giving a wrong user experience .

Any suggestions on how to handle this sort options scenario

**Comment by metagrover** [comment]
Interesting. We currently don't support events to expose the start and end of loading. Can you try accommodating your implementation to use the `loader` prop instead? It accepts a `JSX` and renders it when loading is in progress.

**Comment by Arvind6353** [comment]
Okay. The Prob I have is that I have to rest the sorting field to _score
before doing the search if the user had changed the sorting to date before.

In that case I am manually triggering the click event on the sort options
dropdown to select score As a option and also execute the new query.

And there is a single place where am able to find the query finish in on
Resultstats callback and am closing the loader.

2 queries running simultaneously and sorting query ending faster than the
original query is the Prob

**Comment by metagrover** [comment]
Okay, I think I fairly understood your problem. It seems the only optimal solution to this problem would be to implement request cancellation at the libarary level i.e. cancelling the stale pending queries of a component when new queries are fired, but we don't support it at the moment and it's not on our upcoming timeline either. So, instead of programmatically changing the sort options on `onValueChange` of search component, how about you remount the result component? This would ensure that the default sort prop will come into play and it will pick the latest interaction from your search or filters.

---

Please note that - remounting a reactivesearch component is tricky (since a lot of cleanup happens asynchronously because of the way `componentWillUnmount` behaves), you may have to change the `componentId` of the result component to achieve best results in the simplest way.

**Comment by Arvind6353** [comment]
OK got it. What do u mean by remount? Rerender the component?. I would have
to force Re-render right?.

Do u have any small snippet for that?

**Comment by metagrover** [comment]
Changing any component's `key` prop remounts the component. For your case, you will have to change the `componentId` as well. Please note that you only have to remount when there is a change in sort "programmatically", otherwise it can affect the user experience.
