### ISSUE TITLE
Removing a tag wrapper from ReactiveCard 

### ISSUE THREAD

**Issue by gabzon** [appbaseio/reactivesearch#738]
**Issue Type:**
Bug or config issue

**Platform:**
ReactiveSearch for Web (ReactiveCard)

**Description:**
I'm trying to develop a SPA using ReactiveCard. This is what I did
![screenshot 2018-12-28 at 11 01 50](https://user-images.githubusercontent.com/142036/50512052-52122500-0a90-11e9-83ac-622b3920bd5d.jpg)

The problem I have is that a `<Styled(a)>` component it's been generated for every item in the list, and inside this component I have an `<a>` tag (with the url parameter) wrapping all the content of the card. 
So in theory the app is working, but 
1) I'm trying to build a SPA, therefore an `<a>` tag reloads the page when clicked, so I need to remove it. Here is a screenshot of the result page and the generated code
![screenshot 2018-12-28 at 11 17 22](https://user-images.githubusercontent.com/142036/50512473-635c3100-0a92-11e9-895d-6894a5bd48e5.jpg)

![screenshot 2018-12-28 at 10 56 08](https://user-images.githubusercontent.com/142036/50512300-9ce06c80-0a91-11e9-94e2-d6dc8770bceb.jpg)

2) Since the `<a>` is wrapping the whole content, I thought I just need to remove the url property, but as soon as I removed the url  from the code, the result page becomes empty.  Here is a screenshot of the code without the url and another screenshot of the result page
![screenshot 2018-12-28 at 11 29 28](https://user-images.githubusercontent.com/142036/50512749-08c3d480-0a94-11e9-8150-bdad8de57002.jpg)

![screenshot 2018-12-28 at 11 20 48](https://user-images.githubusercontent.com/142036/50512519-aa4a2680-0a92-11e9-8b09-510a98cf255b.jpg)

I checked in your sample projects like Airbeds and the getting started, and
- they don't add the url property, so I guess is possible  
- The generated content is not the same for ReactiveCard (I guess this are old versions)

Therefore, I don't know if this is a bug, or is just configuration. I read the docs of ReactiveCard and I couldn't find an option for preventing an "a" tag to be generated wrapping the content. Any ideas? thx!

**Comment by metagrover** [comment]
It seems to be working for me - [Check this codesandbox using ResultCard with no `url`](https://codesandbox.io/s/81j8p2mv3l).

I'd suggest you to check the DOM of your app and see if there is any CSS issue.

Let me know if you need any further assistance.

**Comment by gabzon** [comment]
hi @metagrover I created a brand new project using create-reactp-app 
I added RS  `yarn add @appbaseio/reactivesearch`
The version is: **^3.0.0-alpha.4**
I copied and pasted the code from your sandbox you gave me and it doesn't work.
I checked the version of ReactiveSearch in the codesandbox example and is **2.12.1**
I downgraded the version of reactivesearch in my project to 2.12.1 and it worked and you said. 
Should I use the version 2.12.1? do you know if there is a more recent stable version of RS ?
Thanks a lot for the help

**Comment by metagrover** [comment]
Yes, I tested it with `2.15.0`. 

v3 is in alpha right now. We are fixing docs + making breaking changes. If you want to give it a spin with `3.0.0-alpha.x`, rename `onData` prop to `renderData` and it should work.

**Comment by gabzon** [comment]
Great, it worked with renderData. Thx
