### ISSUE TITLE
DynamicRangeSlider breaks search when no results found

### ISSUE THREAD

**Issue by bietkul** [appbaseio/reactivesearch#739]
**Issue Type:**
Bug

**Platform:**
Web

**Description:**
DynamicRangeSlider adds an unnecessary filter with min & max value as `0` when there no results present for the search keyword.
It breaks the search completely until I refresh the page.

**Screenshots:**
![alt text](https://i.imgur.com/mjhnGZk.png)

**Minimal reproduction of the problem with instructions:**
Use DynamicRangeSlider component & try to search something for which there no results present.

**Reactivesearch version:** x.y.z

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**

**Comment by janus-reith** [comment]
Any news regarding this issue?
