### ISSUE TITLE
Objects are not valid as react child

### ISSUE THREAD

**Issue by ilkerceng** [appbaseio/reactivesearch#751]
**Issue Type:**

bug
**Platform:**

Native
**Description:**

**Screenshots:**

![reactive_search_native](https://user-images.githubusercontent.com/4923344/50582910-0936e380-0e77-11e9-8025-23d4f472debd.JPG)

**Minimal reproduction of the problem with instructions:**

**Reactivesearch version:** x.y.z

^0.11.1
**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Android
**Anything else:**

package.json
```
{
  "name": "hello_reactive_search",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "@appbaseio/reactivesearch-native": "^0.11.1",
    "react": "16.6.3",
    "react-native": "0.57.8"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.51.1",
    "react-test-renderer": "16.6.3"
  },
  "jest": {
    "preset": "react-native"
  }
}
```
I have created a react-native using `react-native init hello_reactive_search` and run `yarn add @appbaseio/reactivesearch-native` . And then i have only imported ReactiveBase for simple example. `import { ReactiveBase } from '@appbaseio/reactivesearch-native';` But it gives the error on the screenshot. Is there any suggestion on that? The simple code is also here: 

```
import React, {Component} from 'react';
import {StyleSheet, Text, View} from 'react-native';
import { ReactiveBase } from '@appbaseio/reactivesearch-native';

export default class App extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>Welcome to React Native!</Text>
      </View>
    );
  }
}


const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },

});

```

**Comment by metagrover** [comment]
Hi @ilkerceng thanks for pointing this out. Although this doesn't seem like a reactivesearch-native issue, but there are definitely some icon-fonts related issues that I ran into while building an app with react-native-cli. I'm looking into this and will fix all the setup issues in this week.

For now, I'd recommend you to build an app with [`expo-cli`](https://facebook.github.io/react-native/docs/getting-started). In my experience, everything works smoothly when built with expo-cli.

I created a [starter app here for your reference](https://github.com/appbaseio-apps/react-native-bookstore/).

Let me know if you see any further issues.

**Comment by ilkerceng** [comment]
Hi @metagrover thank you so much.  i really didn't try expo until tody, but i will try, thank you so much, i will try [your repo](https://github.com/appbaseio-apps/react-native-bookstore/) just now.

**Comment by ilkerceng** [comment]
@metagrover which react-native version installed in global should i use?

**Comment by metagrover** [comment]
Expo maintains their own fork of react-native: https://github.com/expo/react-native/ which will be used automatically if you run `expo init myproject`. (Make sure you have latest expo installed: `npm install -g expo-cli`).

[For this starter app](https://github.com/appbaseio-apps/react-native-bookstore/), running `yarn` will install the [relevant react-native fork](https://github.com/appbaseio-apps/react-native-bookstore/blob/master/package.json#L13). You can then run `yarn start` to get things rolling.

**Comment by ilkerceng** [comment]
@metagrover i had installed before react-native@0.57.1. now i have also installed expo-cli, started [the app](https://github.com/appbaseio-apps/react-native-bookstore/) with yarn start, but it gives error:  `React-Native Version Mismatch Javascript Version 0.57.1 Native version: 0.55.2` and a warning `This version of the Expo app is out of date. Uninstall the app and run again to upgrade.`

**Comment by metagrover** [comment]
Okay, it seems your expo on the simulator is out of date. You need to uninstall expo app from your simulator and install it again to get the app working:

Press `Shift-CMD-H` to get the home screen, then delete the Expo App followed by a `yarn start` which will run the metro bundler and will install the latest Expo app on the simulator to run your project.

**Comment by ilkerceng** [comment]
@metagrover Thank you very much, it works just now. 💯

**Comment by ilkerceng** [comment]
Hi @metagrover i am getting this error when i use elasticsearch locally

```
[03:31:38] Response {
  "_bodyBlob": Blob {
    "_data": Object {
      "blobId": "f47735ee-17f2-4a28-bcc9-3b95f857fb3b",
      "offset": 0,
      "size": 99,
    },
  },
  "_bodyInit": Blob {
    "_data": Object {
      "blobId": "f47735ee-17f2-4a28-bcc9-3b95f857fb3b",
      "offset": 0,
      "size": 99,
    },
  },
  "bodyUsed": true,
  "headers": Headers {
    "map": Object {
      "access-control-allow-credentials": "true",
      "cache-control": "public, max-age=0",
      "content-type": "application/json; charset=UTF-8",
    },
  },
  "ok": false,
  "status": 406,
  "statusText": undefined,
  "type": "default",
  "url": "http://192.168.1.39:9200/${index_name}/${doc_type}/_msearch?",
}
- node_modules\react-native\Libraries\YellowBox\YellowBox.js:59:8 in error
- node_modules\@appbaseio\reactivecore\lib\actions\query.js:1:5163 in _callee$
- ... 18 more stack frames from framework internals
```

**Comment by metagrover** [comment]
I'm not sure what's wrong with your local elasticsearch config but you can check the [documentation here](https://opensource.appbase.io/reactive-manual/getting-started/reactivebase.html#connect-to-elasticsearch) to see if everything is in place.
