### ISSUE TITLE
Highlight problem with composed fields

### ISSUE THREAD

**Issue by contifra** [appbaseio/reactivesearch#756]
**Issue Type:**
bug

**Platform:**
Web

**Description:**
Highlight seems have problems with composed fields in datasearch component:

<DataSearch componentId="searchbox" highlight={true}
                    showClear={true}
                    dataField={["A", "B", "C.subject" ]}
                    queryFormat="and" placeholder="Press enter to search" />

For "A", "B" fields i have the results highlighted. For C.subject not working.

**Reactivesearch version:** x.y.z
2.16.1

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by metagrover** [comment]
We have addressed this issue here - https://github.com/appbaseio/reactivesearch/issues/357

You should be able to access the `highlight` object in the response and can use the same to enable highlighted rendering of results.

**Comment by lakhansamani** [comment]
@contifra you can try accessing composed highlighted field as string.

**Instead of rendering result in following manner**

```
onData=((res) => (
	<div dangerouslySetInnerHtml={{ __html: res.c.subject }} />
))
```
**you can rendering in follwing manner**

```
// this should render highlighted part
onData=((res) => (
	<div dangerouslySetInnerHtml={{ __html: res['c.subject'] }} /> 
))
```
