### ISSUE TITLE
DateRange: specifying default selected causes error

### ISSUE THREAD

**Issue by jwchia1** [appbaseio/reactivesearch#757]
**Issue Type:** bug

**Platform:** reactivesearch

**Description:**
I'm specifying defaultSelected on the dateRange component and it's fine on display.
The error pops up when I try to modify the dates by clicking on either of the start or end date.

**Minimal reproduction of the problem with instructions:**
modified the demo slightly
https://codesandbox.io/s/m7x7qloj29

**Reactivesearch version:** 2.16.1

**Browser:** ChromeVersion 71.0.3578.98 (Official Build) (64-bit)

**Comment by jyash97** [comment]
Hey @jwchia1 

Pass `date` object in start & end key of defaultSelected. For eg: 

```
<DateRange
   ...
   defaultSelected={{
       start: new Date("2017-05-05"),
       end: new Date("2017-05-17")
   }}
/>
```

Check this example [here](https://codesandbox.io/s/1oo070q2vq) I have modified the keys for you.
Do let me know if you face other issues.

**Comment by jwchia1** [comment]
> Hey @jwchia1
> 
> Pass `date` object in start & end key of defaultSelected. For eg:
> 
> ```
> <DateRange
>    ...
>    defaultSelected={{
>        start: new Date("2017-05-05"),
>        end: new Date("2017-05-17")
>    }}
> />
> ```
> Check this example [here](https://codesandbox.io/s/1oo070q2vq) I have modified the keys for you.
> Do let me know if you face other issues.

Yup. It works fine now. Thanks for updating the documentation too!
