### ISSUE TITLE
Custom query with sorting

### ISSUE THREAD

**Issue by Arvind6353** [appbaseio/reactivesearch#761]
Am currently using sortOptions with ResultList with 2 values , date and score 

I would want to introduce one more sort option say recency which has to run a custom query to bring the documents sorted by both relevance and date (am using a function score here).

I would like to implement an option like this with sort options . 

Can u help with this use case?

@metagrover @siddharthlatest

**Comment by metagrover** [comment]
One option would be to create a separate react dropdown component to handle sort query. On selection of any option from the dropdown, you can update the `defaultQuery` of the result component to apply relevant sort.

This is the most flexible way to add any kind of sort behavior to result components.

**Comment by Arvind6353** [comment]
Cool . It worked :). Thank you
