### ISSUE TITLE
Default Sort Option

### ISSUE THREAD

**Issue by yashanandan** [appbaseio/reactivesearch#762]
**Issue Type:**
Question

**Platform:**
Web

**Description:**
I am trying to set the default sort option for my ResultCard. The sortOptions are:
`sortOptions={[
{
dataField: "launchDateEpoch",
sortBy: "desc",
label: "SORT BY : LAUNCH DATE"
},
{
dataField: "popularity",
sortBy: "desc",
label: "SORT BY : POPULARITY"
},
{
dataField: "name",
sortBy: "asc",
label: "SORT BY : ALPHABETICAL"
}
]}`

Now I want to set the default sort option for the result. How to set a default option, something like this

`sortOptions={[
{
dataField: "launchDateEpoch",
sortBy: "desc",
label: "SORT BY : LAUNCH DATE",
default: true
},
{
dataField: "popularity",
sortBy: "desc",
label: "SORT BY : POPULARITY",
default: false
},
{
dataField: "name",
sortBy: "asc",
label: "SORT BY : ALPHABETICAL",
default: false
}
]}`

**Reactivesearch version:2.14.1**

**Comment by metagrover** [comment]
Hi @yashanandan, as per our current spec, we take the first item in the `sortOptions` array prop as the selected (default) sort.

Let me know if you are seeing any issues with the same.

**Comment by yashanandan** [comment]
Hi @metagrover, no I don't face issue with respect to that but then each of my pages have a custom sort order then the whole sort drop down shuffles. I want to preserve the sortOptions order and still select a default sortOption. Any idea ?

**Comment by metagrover** [comment]
I understand. For this usecase, it would be best if we can introduce an optional prop - `defaultSortOption <string>` which when set - will take the label of the desired option from `sortOptions` array as the default sort.

This should be a trivial enhancement if you or anyone else wants to take this up.

Code reference: https://github.com/appbaseio/reactivesearch/blob/dev/packages/web/src/components/result/ReactiveList.js#L62

**Comment by yashanandan** [comment]
Sure, we can do for the Web version but for other versions ?

**Comment by metagrover** [comment]
Awesome, we will take care of the rest 🐱
