### ISSUE TITLE
undefined is not an object (evaluating 'window.navigator.userAgent.toLowerCase')

### ISSUE THREAD

**Issue by berpcor** [appbaseio/reactivesearch#769]
I get error on android only when debugger is turned off: 

`undefined is not an object (evaluating 'window.navigator.userAgent.toLowerCase')`

I found that - https://stackoverflow.com/questions/49798615/app-crashes-on-start-when-remote-debugging-is-disabled

It is said there:

> Rule of thumb: React Native is not a browser. Don't use any of the globals that you would normally use when doing web development and you'll avoid most of these types of gotcha errors.

This is full error text: 

> undefined is not an object (evaluating 'window.navigator.userAgent.toLowerCase')
> <unknown>
>     vue.runtime.common.js:490:49
> loadModuleImplementation
>     require.js:320:6
> guardedLoadModule
>     require.js:214:36
> metroRequire
>     require.js:136:24
> <unknown>
>     utils.js:8:41
> loadModuleImplementation
>     require.js:320:6
> guardedLoadModule
>     require.js:214:36
> metroRequire
>     require.js:136:24
> <unknown>
>     index.js:8:20
> loadModuleImplementation
>     require.js:320:6
> guardedLoadModule
>     require.js:214:36
> metroRequire
>     require.js:136:24
> <unknown>
>     index.cjs.js:3:24
> loadModuleImplementation
>     require.js:320:6
> guardedLoadModule
>     require.js:214:36
> metroRequire
>     require.js:136:24
> <unknown>
>     vueTypes.js:1:78
> loadModuleImplementation
>     require.js:320:6
> guardedLoadModule
>     require.js:214:36
> metroRequire
>     require.js:136:24
> <unknown>
>     index.js:1:339
> loadModuleImplementation
>     require.js:320:6
> guardedLoadModule
>     require.js:214:36
> metroRequire
>     require.js:136:24
> <unknown>
>     ReactiveBase.js:6
> loadModuleImplementation
>     require.js:320:6
> guardedLoadModule
>     require.js:214:36
> metroRequire
>     require.js:136:24
> <unknown>
>     index.js:2
> loadModuleImplementation
>     require.js:320:6
> guardedLoadModule
>     require.js:214:36
> metroRequire
>     require.js:136:24
> <unknown>
>     Tab5.js:3
> loadModuleImplementation
>     require.js:320:6
> guardedLoadModule
>     require.js:214:36
> metroRequire
>     require.js:136:24
> <unknown>
>     Router.js:15
> loadModuleImplementation
>     require.js:320:6
> guardedLoadModule
>     require.js:214:36
> metroRequire
>     require.js:136:24
> <unknown>
>     App1.js:8
> loadModuleImplementation
>     require.js:320:6
> guardedLoadModule
>     require.js:214:36
> metroRequire
>     require.js:136:24
> <unknown>
>     index.js:14
> loadModuleImplementation
>     require.js:320:6
> guardedLoadModule
>     require.js:207:45
> metroRequire
>     require.js:136:24
> global code
    
As you can see the problem starts from ReactiveBase.
I suppose, that something wrong with it. Can you check it please.
P.S. Here - https://github.com/apollographql/apollo-client/pull/3975 - was the same problem. I think, that if you have the same problem of incorrect using of globals, you can see idea of solution there.

**Comment by metagrover** [comment]
Which version of `reactivesearch-native` are you using?

**Comment by berpcor** [comment]
```
"@appbaseio/reactivesearch": "^2.14.1",
"@appbaseio/reactivesearch-native": "^0.10.0",
```

**Comment by metagrover** [comment]
I think you are importing `ReactiveBase` from `@appbaseio/reactivesearch` - which won't work on react-native. If you are using reactivesearch on react-native, you only need to install `@appbaseio/reactivesearch-native`.

Please refer to the getting started guide for further details: https://opensource.appbase.io/reactive-manual/native/getting-started/reactivesearch.html
