### ISSUE TITLE
How to add custom filter in reactiveSearch query ?

### ISSUE THREAD

**Issue by alexandre033** [appbaseio/reactivesearch#774]
**Issue Type:**

**Platform:**
Reactive search for web

**Description:**
Hello,
I try to implement some customs filters according to user parameter. For example if a user is "protected" i want him to see only data with  protected filter and have always the possibility to use reactivesearch filters.

So how to use transformRequest to modify the body of the request ?

Thanks for your help

PS: When i parse the body of the request i have this error "SyntaxError: Unexpected token { in JSON at position 24" so i can't had some extra filter

**Comment by cedricium** [comment]
Hey @alexandre033, any luck figuring this out? Sounds like I have a similar use-case and I'm wondering how to do the same thing.

**Comment by metagrover** [comment]
Please find the usage [docs here](https://opensource.appbase.io/reactive-manual/v3/getting-started/reactivebase.html). You can use `transformRequest` and `transformResponse` in combination to achieve any level of request/response customisation.

**Comment by alexandre033** [comment]
hi  @cedricium like @metagrover said check the doc, but i think the best way is to filter in the backend or inject custom query in reactive list

**Comment by metagrover** [comment]
I highly recommend giving `customQuery` prop a try if it is related to modifying request body. For most usecases, `customQuery` should do, but if you wish to update the request headers or other request data, you can use `transformRequest`.

**Comment by metagrover** [comment]
Feel free to reopen if you have any further questions.

**Comment by cedricium** [comment]
Thanks for the help everyone. What I actually needed was to extend the default query by applying a match and there was already an API for that (`defaultQuery`), keep up the great work!
