### ISSUE TITLE
Send queries to custom server and call elasticsearch from the custom server

### ISSUE THREAD

**Issue by Arvind6353** [appbaseio/reactivesearch#775]
I would like send the queries to my own node express server and would like to execute the _msearch from my express server . 

Is it possible ?

 <ReactiveBase app="index_name" url="**http://elastisearchserver:9200**"/>

Instead of pointing to elastic search url directly , can I Point to my own server ?

@metagrover @siddharthlatest

**Comment by siddharthlatest** [comment]
This is possible. Refer to the docs here https://opensource.appbase.io/reactive-manual/getting-started/reactivebase.html#connect-to-elasticsearch.

**Comment by Arvind6353** [comment]
@siddharthlatest . Are you talking about using proxy server ?

**Comment by Dionnelektra** [comment]
@Arvind6353 Hi. Were you able to connect your own server? I am also trying to connect mine
