### ISSUE TITLE
Disable checkbox

### ISSUE THREAD

**Issue by alexandre033** [appbaseio/reactivesearch#776]
**Description:**
It is possible to disable checkbox if count == 0 and not erase the label from the multilist ?

Thanks a lot

**Comment by jwchia1** [comment]
I've a related question but it's not regarding the checkbox.
Say, I have a gender selection multi-list and the options "Male", "Female", "Unknown" (for null, empty values). 
I'm saving the selected options and setting them again as default when the user wishes to view the selected options.
In this scenario, I've selected "Male" and "Unknown" but there are only results from "Male".
If I save it and set them again, I'll only get the "Male" option shown in multi-list but in my filter, "Male" and "Unknown" are defined.
Is there a way to retain the options in multi-list even if there are no results for them?
