### ISSUE TITLE
DateRangeSensor fails to get results when start & end dates are the same

### ISSUE THREAD

**Issue by alexlle** [appbaseio/reactivesearch#782]
**Issue Type:**
bug

**Platform:**
ReactiveSearch for Web

**Description:**

**Screenshots:**
![imagen](https://user-images.githubusercontent.com/17745866/51059620-8f67ce00-15cb-11e9-9a14-818bd00086f6.png)

**Minimal reproduction of the problem with instructions:**
When I filter through DateRangeSensor and set the same day for start date & end date, It's doesn't respond with any results. But there are items for that particular date.
If I try that date and beyond, I do get the results.

**Comment by metagrover** [comment]
Hi @jyash97, can you give this a spin and check what could possibly be an issue here?

**Comment by jyash97** [comment]
Hey @alexislorenzo @metagrover 

I tried this, but I wasn't able to replicate the issue. Check this demo I am getting results on same `start` & `end` date: 
![daterange- same start end date](https://user-images.githubusercontent.com/22376783/51165907-b3772800-18c7-11e9-94ff-775a6b314309.gif)

Also I am getting results in `dejavu`
![image](https://user-images.githubusercontent.com/22376783/51166027-2ed8d980-18c8-11e9-8966-6b0a16154ae7.png)

**Comment by metagrover** [comment]
Hi @alexislorenzo, if you can share a codesandbox replication of your issue, we can help you debug.

---

@jyash97 It would be best if you can also share the code for the above working demo for reference.

**Comment by jyash97** [comment]
Sure, Check the [link](https://codesandbox.io/s/383x3rnl11) for the above demo.

**Comment by alexlle** [comment]
Hi, thanks for responding.
I'll try to upload a replica to codesandbox.
Meanwhile, I think it may have something to do with date format.
I'm using date_time_no_millis because that's the date format of the source
Is there a way to transform the date format before it's used by the datafield parameter in the DateRange component?

**Comment by alexlle** [comment]
Finally, I got a kind of workaround.
I updated every single doc and added a **text field** based on the original date field for each doc, with the format YYYYmmdd, so the datafield for the component is this new one with format basic_date.
