### ISSUE TITLE
customQuery + aggs

### ISSUE THREAD

**Issue by alexandre033** [appbaseio/reactivesearch#790]
When i use customQuery and add aggs like this 

`{
  "query": {
    "match_all": {}
  },
  "aggs": {
    "genres_data.raw": {
      "terms": {
        "field": "genres_data.raw",
        "min_doc_count": 0
      }
    }
  }
}`

The aggregation is not updated. I have the header request instead
`  "aggs": {
    "genres_data.raw": {
      "terms": {
        "field": "genres_data.raw",
        "size": 20,
        "order": {
          "_term": "asc"
        },
        "missing": "N/A"
      }
    }
  }`

**Comment by metagrover** [comment]
This should be feasible with version 3.0 which is currently in alpha. You will need to use `defaultQuery` to modify aggs query. We have briefly covered this here - https://opensource.appbase.io/reactive-manual/v3/advanced/migrationguide.html#standardized-usage-of-custom-and-default-queries

**Comment by alexandre033** [comment]
Thanks for your help. But i also have an error with the results component: **Uncaught TypeError: _this.props.renderData is not a function**

i can't show any results

**Comment by metagrover** [comment]
Please refer the migration guide. We have renamed methods like `onData` to `renderData`. [We have covered all these changes here](https://opensource.appbase.io/reactive-manual/v3/advanced/migrationguide.html).

**Comment by alexandre033** [comment]
Yes i found thanks a lot

**Comment by alexandre033** [comment]
And how can i disable checkbox in multilist ?

**Comment by metagrover** [comment]
I suppose you're referring to #776, we don't support disabling checkbox at the moment. But I think this can be supported with customQuery + render props combination in v3.0. I will check on this and update you on issue #776.
