### ISSUE TITLE
_this.props.renderData is not a function

### ISSUE THREAD

**Issue by alexandre033** [appbaseio/reactivesearch#791]
**Description:**
i switch to reactivesearch 3.0.0-alpha.10 and i have this error : "_this.props.renderData is not a function"
with the 2.0 version all works fine

and i also have this error in the network console on chrome : "**message: "Rate limit exceeded."
status: 429**"

**Reactivesearch version:** 3.0.0-alpha.10

**Comment by metagrover** [comment]
Please refer to this migration guide - https://opensource.appbase.io/reactive-manual/v3/advanced/migrationguide.html

**Comment by metagrover** [comment]
If you're seeing issues regarding rate limits, that's because of recent plan changes for free appbase users. Please visit https://appbase.io/pricing/ for more details.
