### ISSUE TITLE
Limit the max results to display

### ISSUE THREAD

**Issue by richardhuili** [appbaseio/reactivesearch#792]
**Issue Type:**

Enhancement

**Platform:**

Web

**Description:**

I want to display only a limited number of results despite the total number of results returned by the query. For example, I want the first 100 results (10 pages with 10 per page) are displayed and accessible, while the total are 26443 results. 

Ideally there is a prop setting in the Result component (limit={100}) so only the first 100 results are showed. 

One important reason for this is that without limitation, a crawler can easily crawl and download all 26443 results in one go, in above example.

**Screenshots:**

**Minimal reproduction of the problem with instructions:**

**Reactivesearch version:** x.y.z

2.16.1

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all

**Anything else:**

**Comment by metagrover** [comment]
@siddharthlatest thoughts on this?

**Comment by siddharthlatest** [comment]
A crawler can still go and download all results. Such an enforcement should be done from the backend.  For instance, you can use a middleware along with ReactiveSearch that caps the max results for any search query or puts an IP based rate limit. We offer this as a security option on hosted appbase.io apps and clusters.

**Comment by richardhuili** [comment]
I see, thanks. We currently host our own ES cluster on AWS. Is there a way to specify the context like { "from" : 0, "size" : 3 } to cap the returned number of results?

**Comment by siddharthlatest** [comment]
`size` prop lets you set the size. The *from* parameter is controlled via the `pagination` prop indirectly, but the generated query itself can be manipulated by setting a `defaultQuery` or `customQuery` prop.

**Comment by richardhuili** [comment]
I tried to add the following to the Result component 
			defaultQuery={(value, props) => ({
        "from" : 0, "size" : 100,
				"query": {
		        "match_all": {}
		    }
 			})}

but it did not work. Still return the full results. The query works on ES directly.

**Comment by alexandre033** [comment]
I need the same thing to avoid the overload of the results. I create this issue #798 and you can try to use react virtualized

**Comment by davidkong0987** [comment]
> **Issue Type:**
> 
> Enhancement
> 
> **Platform:**
> 
> Web
> 
> **Description:**
> 
> I want to display only a limited number of results despite the total number of results returned by the query. For example, I want the first 100 results (10 pages with 10 per page) are displayed and accessible, while the total are 26443 results.
> 
> Ideally there is a prop setting in the Result component (limit={100}) so only the first 100 results are showed.
> 
> One important reason for this is that without limitation, a crawler can easily crawl and download all 26443 results in one go, in above example.
> 
> **Screenshots:**
> 
> **Minimal reproduction of the problem with instructions:**
> 
> **Reactivesearch version:** x.y.z
> 
> 2.16.1
> 
> **Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
> 
> all
> 
> **Anything else:**

How would a crawler do this? How would it navigate to a page that you don't have (page 11 in your example)?
