### ISSUE TITLE
Vue pagination UX problem

### ISSUE THREAD

**Issue by mauxtin** [appbaseio/reactivesearch#801]
Current outcome when current page is 5 and there are more than 5 pages

Prev 1 2 3 4 **5** Next
![image](https://user-images.githubusercontent.com/40521145/51532811-cc448800-1e49-11e9-84d2-f9975d5d51fb.png)

Expected outcome when current page is 5 (Show that there are more than 5 pages)
Prev 1 ... 4 **5** 6 7 ... Next

Of course the Next button goes to sixth page as expected but it should somehow indicate to the user that there more pages to navigate after the fifth.

**Comment by metagrover** [comment]
Thanks for bringing this up. This enhancement can also be applied to react library as well.

**Comment by bietkul** [comment]
Something like that might be a better option

![image](https://i.imgur.com/jNVvxuf.png)

Reference: https://ant.design/components/pagination/

**Comment by mauxtin** [comment]
Closing this since it has been implemented.
