### ISSUE TITLE
Query by id

### ISSUE THREAD

**Issue by alexandre033** [appbaseio/reactivesearch#804]
Hello,

in defaultQuery, how can i request by ids to retrieve few ids. I try this :

`{
            "query": {
                "ids": {
                    "values": ['293450']
                }
            }
 }`

But it return no results. Thanks for your help

**Comment by metagrover** [comment]
You can do a `terms` query on the `id` field:

```js
defaultQuery={() => ({
    query: {
        terms: {
            'id': [1,2,3,4,5],
        },
    },
})}
```

Refer elasticsearch docs for more details: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-terms-query.html

**Comment by alexandre033** [comment]
Thanks i founded the solution :)

**Comment by aikodeio** [comment]
@alexandre033 hello, in which component is the function added defaultQuery  ?? in ReactiveBase ?
