### ISSUE TITLE
Connection to localhost results in a blank page

### ISSUE THREAD

**Issue by Danelicious** [appbaseio/reactivesearch#806]
Hello,

I am trying to connect reactivesearch to my ES instance on a localhost. When I turn off ES, I can see the whole App I created in the browser. When I run ES, I suddenly get a blank page when opening my App in the browser. Actually, it does show everything for like a ms (including the loader="Loading Results.."  - function) but afterwards the page remains blank. If I change the ReactiveBase value to something random, it does show everything again, so the connection must be there, just not working. 

What am I doing wrong here?

Those are my settings in App.js:

`<ReactiveBase app="my_ES_index" url="http://localhost:9200">`  

And in elasticsearch.yml

http.cors.enabled : true
http.cors.allow-credentials: true
http.cors.allow-origin : "http://localhost:3000"
http.cors.allow-headers : X-Requested-With,X-Auth-Token,Content-Type, Content-Length, Authorization, Access-Control-Allow-Headers, Accept

**Comment by metagrover** [comment]
Please [refer the docs here](https://opensource.appbase.io/reactive-manual/getting-started/reactivebase.html#connect-to-elasticsearch).

**Comment by Danelicious** [comment]
Well, that's where I started and according to the docs I can't find the mistake. I e.g. also changed to `http.cors.allow-origin : /https?:\/\/(localhost)?(127.0.0.1)?(:[0-9]+)?/`, which doesn't change anything (still a blank page unless I turn off ES).

**Comment by metagrover** [comment]
Are you seeing any errors in console?

**Comment by Danelicious** [comment]
Yes, 4 errors.

(1) Uncaught TypeError: _this.props.renderData is not a function
--> a bunch of functions are following, e.g. "at ResultList._this.renderAsListItem"

(2) Warning: ReactiveBase: Error boundaries should implement getDerivedStateFromError(). In that method, return a state update to display an error message or fallback UI.

(3) Connect.push../node_modules/react/cjs/react.development.js.Component.setState (react.development.js:356)

(4) The above error occurred in the <ReactiveList> component:
--> a bunch of argument following, e.g. "in ReactiveList" or "in Unknown (created by Connect(Component))"

I am really new to react and I might miss something very essential. But I followed several tutorials and just don't understand why I can see everything when ES is turned off, but not when it's turned on (or when I enter random ES credentials).

**Comment by metagrover** [comment]
This is not ES problem. We recently released a new version of reactivesearch (currently in alpha) which has some breaking changes from our widely used release. Instead of `onData` prop in the result component, you should be using `renderData` prop. Please [refer to this migration guide](https://opensource.appbase.io/reactive-manual/v3/advanced/migrationguide.html) and [new docs here](https://opensource.appbase.io/reactive-manual/v3/getting-started/reactivesearch.html) (notice v3 version in the url).

**Comment by metagrover** [comment]
You can also browse component-wise examples here: https://github.com/appbaseio/reactivesearch/tree/next/packages/web/examples

**Comment by Danelicious** [comment]
Thank you so much! This solved my problem. I will go through the migration guides, as well as the new docs. But for now changing to `renderData` did the "trick". Cheers and great work btw!
