### ISSUE TITLE
onData does not support passing a React element as a template to render result items

### ISSUE THREAD

**Issue by willopez** [appbaseio/reactivesearch#809]
**Issue Type:** enhancement

**Platform:** web

**Description:** I am attempting to render a custom React element as seen in the `ssr-with-react-dom` example, specifically I would like to do pass a custom React element to the `onData` prop as seen here; https://github.com/appbaseio/reactivesearch/blob/5a4a0141b5a000ad1dcfe81f7828bbb59f3996db/packages/web/examples/ssr-with-react-dom/client/index.js#L36

The example renders correctly, (NOTE: it's using v2.12.1, and I am using v2.16.1), however, in my project nothing renders. 

Looking at the current implementation of the`ResultCard` it's obvious that it does not allow for rendering a custom element: https://github.com/appbaseio/reactivesearch/blob/dev/packages/web/src/components/result/ResultCard.js

**Feature Request Request**: add functionality to support using a React element as the template for rendering result items.

**Screenshots:**

**Minimal reproduction of the problem with instructions:**
Run the example found at `reactivesearch/packages/web/examples/ssr-with-react-dom`

**Reactivesearch version:** v2.16.1

**Browser:** [Chrome 71  ]

**Comment by metagrover** [comment]
This example uses `ReactiveList` component, not `ResultList`. If you want to add custom React elements in the results - you should use `ReactiveList`.

Hope that helps
