### ISSUE TITLE
Dynamically update highlight in CategorySearch

### ISSUE THREAD

**Issue by divyanshu013** [appbaseio/reactivesearch#81]
Currently the changes in `highlight` prop are not reflected in the results until the search query changes. [Reference example](https://opensource.appbase.io/playground/?knob-highlight=true&selectedKind=search%2FCategorySearch&selectedStory=With%20highlight&full=0&down=1&left=1&panelRight=0&downPanel=storybooks%2Fstorybook-addon-knobs).

**Comment by siddharthlatest** [comment]
@divyanshu013 Can you update what the issue is about?

**Comment by divyanshu013** [comment]
Updated the description. This is similar to the issue with DataSearch https://github.com/appbaseio/reactivebase/issues/198

**Comment by divyanshu013** [comment]
Resolved in reactivesearch v2
