### ISSUE TITLE
Jest testing

### ISSUE THREAD

**Issue by willopez** [appbaseio/reactivesearch#813]
**Issue Type:** Enhancement

**Platform:** web

**Description:** I have searched the docs and issues looking for instructions on how to test Reactive Search and have not found anything. How can I test ReactiveSearch with Jest? It seems that a MockProvider similar to what `react-apollo` provides would be necessary. https://www.apollographql.com/docs/react/recipes/testing.html#MockedProvider

**Minimal reproduction of the problem with instructions:**

**Reactivesearch version:** 2.16.1

**Browser:** [all ]

**Comment by metagrover** [comment]
Sounds good. Open to accepting PRs on this.

**Comment by mprandot** [comment]
@metagrover @willopez  Hello guys!!
I'm trying to find some info about testing the ReactiveSearch stack, but find nothing...
Do guys have some news about this item? I think that this is very important.

**Comment by kirankalyan5** [comment]
Hi there, are there any guides for adding tests using react-testing-library?
Thanks in advance.
