### ISSUE TITLE
Avoid dangerouslySetInnerHtml with highlight

### ISSUE THREAD

**Issue by rap2hpoutre** [appbaseio/reactivesearch#816]
**Issue Type:**
enhancement

**Platform:**
Web

**Description:**
Reading the docs and the demos (example: https://opensource.appbase.io/reactivesearch/demos/technews/), currently, ReactiveSearch needs `dangerouslySetInnerHtml` in order to highlight result. It's a problem because text is not protected and XSS injection can occurs. Still, it could have returned something like `return <React.fragment>My <mark>highlighted</mark> text</React.fragment>` (so an React element instead of a string). With this behavior, it could work without `dangerouslySetInnerHtml`.

**Screenshots:**

**Minimal reproduction of the problem with instructions:**
Create a DataSearch with `highlight` and enable `highlight`: it fails to render highlighting if it does not use `dangerouslySetInnerHtml`.

**Reactivesearch version:** the one which is used in documentation and examples.

**Browser:** all

**Anything else:**
Feel free to ask for more info, I will edit my question!

**Comment by metagrover** [comment]
Sounds good. I will try it out and get back to you. Thanks for the input 👍

**Comment by metagrover** [comment]
On a careful try, it doesn't seem like it will be possible:

We get the `string` data from elasticsearch with `<mark>text</mark>` tags as strings. We don't do this on front-end. And, the only way to parse this is to use `dangerouslySetInnerHtml`. If you think this can be done, we would be open to accepting PRs on this.
