### ISSUE TITLE
two main demo apps are not working

### ISSUE THREAD

**Issue by gcloeval** [appbaseio/reactivesearch#818]
**Issue Type:**
bug

**Platform:**
web

**Description:**
hi, just wanted to let you know the following 2 demos linked from your main github demos page dont show any results:
https://opensource.appbase.io/reactivesearch/demos/producthunt/
https://opensource.appbase.io/reactivesearch/demos/ecommerce/

Its a good library, but this can give a wrong impression, Cheers

**Comment by metagrover** [comment]
Thanks for pointing it out @gcloeval. Just deployed the fix. It was a build issue and may need a hard refresh to fetch the new build.
