### ISSUE TITLE
React component Read-More-Less semi-working

### ISSUE THREAD

**Issue by Danelicious** [appbaseio/reactivesearch#826]
Hi, I am really struggling with an issue. I am trying to call data from my local ES instance, which works like a charm in general. But the descriptions I call are very long. So I want to have a "Read More" link and found this: [ReadMoreAndLess](https://www.npmjs.com/package/react-read-more-less). It works perfectly when I use it like this: 

`ReadMoreAndLess
      className="read-more-content"
      charLimit={25}
      readMoreText="Read more"
      readLessText="Read less"
    >
     Some random text here.
    </ReadMoreAndLess>`

But as soon as I call data from ES (instead of inserting some random text), I only get the whole description without any Read More or Read Less link, e.g. like this:

`ReadMoreAndLess
      className="read-more-content"
      charLimit={25}
      readMoreText="Read more"
      readLessText="Read less"
    >
      {data.description}
    </ReadMoreAndLess>`

If I wrap it around e.g. a `<div>`, I will see the whole description and a Read Less link, which won't work, it's just there. Can anybody help me to use this component within ReactiveSearch? What am I doing wrong here? Do I have to use "ReactiveComponent" in this case? Appreciate any help, I am bloody new to React and ReactiveSearch, but like to "fool around" with it and learn more.

**Comment by metagrover** [comment]
If you can create a [codesandbox](https://codesandbox.io) for this, it would be a little easier to understand the issue and help you better :)

In any case, if this is about the result component, you can always use [ReactiveList](https://github.com/appbaseio/reactive-manual/blob/v3/content/docs/result-components/ReactiveList.md). 

---

[I'd recommend you to start here](https://github.com/appbaseio/reactive-manual/blob/v3/content/getting-started/reactivesearch.md), if you are new to reactivesearch.

**Comment by Danelicious** [comment]
@metagrover Thanks for your response and sorry that I didn't make myself clear :). To make things easier, I stick with the example I learned from: [GitXplore](https://codesandbox.io/s/github/appbaseio-apps/gitxplore-app/tree/master/)  by @divyanshu013   😄 

In the file `Result.js ` I would like to apply the above mentioned component "ReadMoreAndLess" to line 24:
`<div className="m10-0">{data.description}</div>`

Let's say the descriptions stored are long pieces of text, but I only want to display a portion of it. That is why I want to use a Read More link in the ResultList. It works fine when I put random text into the "ReadMoreAndLess"-Component, but not when I call data from `data.description`. Then it will still show me the whole description stored in ES. 

If this is an issue of "basic understanding" (which I believe), I am willing to start from scratch. But I would appreciate a little hint as well 😆. Thanks for your time. 🙇

**Comment by metagrover** [comment]
Okay, I see. You should be able to customise the `line 24` as:

```
<div className="m10-0"><ReadMoreAndLess>{data.description}</ReadMoreAndLess></div>
```

If that's not working, I'd recommend you to check the final-css getting applied to the `div` container and `ReadMoreAndLess` injected DOM - you will get some clues from there.

---

If this doesn't help, shoot a link to codesandbox here and I will dive into it :)

**Comment by Danelicious** [comment]
Thank you. Actually, that is exactly what I tried and it didn't work for me. However, when I apply it to the existing example in codesandbox (thanks for the hint), it works. See [here](https://codesandbox.io/s/n0z29rj21m). So I assume it must have something to do with the data structure in ES!?

**Comment by metagrover** [comment]
Possibly. Check if you are getting a proper string. You can easily browse your ES data with [dejavu](http://dejavu.appbase.io/).

**Comment by Danelicious** [comment]
Ok, this is weird. It only works in one case for me. I have 3 fields: title, title_alt and description. All are mapped like this:

`"title" : {
            "type" : "text"
          },
          "title_alt" : {
            "type" : "text"
          },
 "description" : {
            "type" : "text"
          }`

I get my data by a crawler and feed it directly into ES. When there is no "title_alt" (alternative title), I will put a default "none" in the field. In this case, it will show the Read More link. Otherwise no chance. At least now I know that it should work and it has to do with the ES data structure. Thanks for leading me to it. ReactiveSearch rules! 😃

**Comment by metagrover** [comment]
Happy to help!
