### ISSUE TITLE
Hoping improvements of RangeSlider

### ISSUE THREAD

**Issue by AlloVince** [appbaseio/reactivesearch#837]
**Issue Type:** enhancement

**Platform:** Web

**Description:**
As I mentioned in #836, I'm tring to migrate from searchkit to reactivesearch,  the searchkit has some good features I think RangeSlider is really needed

First I think when sliding, the range of `start`, and the `end`, should allow same value, it is a useful search, it not allow same value, I have to add a new SingleRange component to do this kind of search

Then when dragging the slider handler, I think its really necessary to show a tooltip of current value, as same as  searchkit does. If the range of RangeSlider have many values, I've no idea which value it is now, it make this component really hard to use.

<img width="249" alt="2019-02-18 5 34 51" src="https://user-images.githubusercontent.com/176019/52941445-c5a32500-33a3-11e9-8c93-028519c0bcf1.png">

**Comment by metagrover** [comment]
@jyash97 didn't we add this?

**Comment by jyash97** [comment]
Hey @AlloVince 
You can show tooltip by using prop `tooltipTrigger="always"`. Check this example [here](https://codesandbox.io/s/23llp4kw1r).

**Comment by AlloVince** [comment]
> Hey @AlloVince
> You can show tooltip by using prop `tooltipTrigger="always"`. Check this example [here](https://codesandbox.io/s/23llp4kw1r).

Great! it works. it is better to add this param to docs and typescript definition, I didn't find it in both.

Also please consider my start/end suggestion, it is also an important feature.

**Comment by metagrover** [comment]
hey @AlloVince, we support rendering start/end values on the range slider.

Can you expand on the issue you're seeing with start/end?

**Comment by AlloVince** [comment]
> hey @AlloVince, we support rendering start/end values on the range slider.
> 
> Can you expand on the issue you're seeing with start/end?

What I want is allow start and end with same value, for example, here is a Year slider, range from [2002, 2019]

In searchkit component, I could slide to Year range [2019, 2019] 

<img width="302" alt="2019-02-19 9 30 06" src="https://user-images.githubusercontent.com/176019/53018947-9a493480-348e-11e9-849e-4771d6d63130.png">

But in reactivesearch, the Year range could only be [2018, 2019],  [2019, 2019] is not allowed

<img width="275" alt="2019-02-19 9 30 19" src="https://user-images.githubusercontent.com/176019/53018966-a8975080-348e-11e9-8aec-5c733602cd05.png">

**Comment by metagrover** [comment]
Got it! @jyash97 can you take a look at this?

**Comment by rgb-panda** [comment]
Hi @metagrover, was there any solution to have the same start-end for RangeSlider? At the moment I can only do it with RangeInput, and doing it manually inside start-end input fields but not on the slider
