### ISSUE TITLE
List component style bug: longer elements labels that wrap

### ISSUE THREAD

**Issue by psorensen** [appbaseio/reactivesearch#841]
**Issue Type:**
Bug

**Platform:**
Web

**Description:**
When elements in list components wrap to next line, styling is off.

**Screenshots:**
![screen shot 2019-02-18 at 7 11 06 am](https://user-images.githubusercontent.com/6152801/52960087-d4aab880-334c-11e9-9c54-a52b63ab7086.png)

**Minimal reproduction of the problem with instructions:**
```
<SingleDataList
    componentId="CitySensor"
    dataField="post_type.raw"
    title="Article Type"
    showSearch={false}
    data={[
        { label: 'News', value: 'news-article' },
        { label: 'This label is super long and wraps to the next line', value: 'long-value' },
        { label: 'Bulletin', value: 'bulletin' },
    ]}
/>
```

**Reactivesearch version:** 2.16.1

**Browser:** [**all** | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by nathan-ca** [comment]
I'm not sure if it's the same bug. For a long data list, I'm trying to limit the height of this SingleDataList, so it will show a scroll bar for user. It's not working for whatever css I tried.

**Comment by metagrover** [comment]
@nathan-ca that sounds like a css specifity issue. Please inspect the css application order in your browser to fix that behavior
