### ISSUE TITLE
ResultList.onResultStats not work in 3.0.0-beta.3

### ISSUE THREAD

**Issue by AlloVince** [appbaseio/reactivesearch#842]
**Issue Type:** bug

**Platform:** web

**Description:**
As title, I set onResultStats as

```js
                  <ResultList
                    onResultStats={stats => `foo ${stats.totalResults} bar ${stats.time} ms`}
                  />
```

but the UI still use default message

**Comment by metagrover** [comment]
The prop is now called `renderResultStats`. [Refer docs here](https://opensource.appbase.io/reactive-manual/v3/result-components/resultlist.html#props).

**Comment by metagrover** [comment]
`on<Event>` props are now event callbacks in v3. Custom rendering is supported by `render<>` props.

**Comment by AlloVince** [comment]
Got it. docs and typescript definition require update

**Comment by metagrover** [comment]
Both seem fine to me:

TS definitions: https://github.com/appbaseio/reactivesearch/blob/1aa9dcc711a497c00bf6cd0ec90985a6525bab16/packages/web/src/components/result/ReactiveList.d.ts#L19

Docs: Make sure you're checking v3 docs:

<img width="306" alt="image" src="https://user-images.githubusercontent.com/9116042/52995677-54b24a80-3441-11e9-9ee3-e28a15cc9e03.png">

**Comment by AlloVince** [comment]
For me, it looks like docs not updated yet on website
https://opensource.appbase.io/reactive-manual/v3/result-components/resultlist.html

<img width="968" alt="2019-02-19 2 58 03" src="https://user-images.githubusercontent.com/176019/52995913-f1cbae00-3456-11e9-93bb-e8476f591b8f.png">

**Comment by metagrover** [comment]
@lakhansamani can you check on the `renderResultStats` and `onResultStats` docs please? Feel free to close this issue after updating the docs 🐱

**Comment by lakhansamani** [comment]
Sure 👍

**Comment by AlloVince** [comment]
sorry, my misunderstanding, renderResultStats is a new param, not a replacement of onResultStats
