### ISSUE TITLE
SingleDropdownList query on nested field generate incorrect query

### ISSUE THREAD

**Issue by nathan-ca** [appbaseio/reactivesearch#845]
**Issue Type:**

bug

**Platform:**

web

**Description:**

SingleDropdownList component generate incorrect query

**Screenshots:**

**Minimal reproduction of the problem with instructions:**

Here is the component definition (ommiting other fields):
<SingleDropdownList
              dataField="userIdentity.arn"
              nestedField="userIdentity"
.../>

Generated http call payload is:
{"query":{"match_all":{}},"size":0,"aggs":{"reactivesearch_nested":{"nested":{"path":"userIdentity"},"aggs":{"userIdentity.arn":{"terms":{"field":"userIdentity.arn","size":100,"order":{"_term":"asc"}}}},"size":0}}}

es center returned 400 (bad request)

The error is the last "size":0 parameter in the query.

**Reactivesearch version:** x.y.z

3.0.0-beta.3

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**

**Comment by metagrover** [comment]
This fix will be released in `3.0.0-beta.8`. Thanks for the patience on this!

**Comment by felubra** [comment]
I'm having the same problem with the vue package `1.0.0-beta.9`: https://codesandbox.io/s/r5z6y1x8yn?expanddevtools=1&fontsize=14

**Comment by elektracodes** [comment]
Same here! Please re-open the issue
