### ISSUE TITLE
Updating MultiList defaultValue does not trigger re-render

### ISSUE THREAD

**Issue by ThunderDev1** [appbaseio/reactivesearch#847]
**Issue Type:** Question
**Platform:** Web
**Reactivesearch version:** 3.0.0-beta.3

**Description:**

I need to load a default value asynchronously, however in the following example, the MultiList is not updated. Is this the normal behaviour ? Thanks :smile: 

```
state = {
  defaultValue: []
};

componentDidMount() {
  this.setState({defaultValue: ['Comedy']});
}

render() {

  return(
    <ReactiveBase
      app={indexForElastic}
      credentials={credentialsForElastic}>
        <MultiList
	  componentId={"MultiList1"}
	  dataField={"genres_data.raw"}
	  defaultValue={this.state.defaultValue}
        />
    </ReactiveBase>
}
```

**Comment by ThunderDev1** [comment]
I also tried using `defaultQuery` instead

```
defaultQuery={(value, props) => {
  return {
	query: {
	  bool: {must: [{bool: {must: [{match: {original_title: 'test'}}, {range: {vote_average: {gte: 0, lte: 10, boost: 2}}}]}}]}
	},
	size: 0,
	aggs: {'genres_data.raw': {terms: {field: 'genres_data.raw', size: 100, order: {_count: 'asc'}}}}
  };
}}
```

The `aggs` part is working, but the query part seems to be ignored.
Would love to have your input on this problem ;)

**Comment by metagrover** [comment]
Yes, it's an expected behavior. You should use `value` prop if you wish to update the component value dynamically.

Read more about controlled and uncontrolled behavior here: https://opensource.appbase.io/reactive-manual/v3/advanced/componentsusage.html

**Comment by metagrover** [comment]
This migration guide will come handy: https://opensource.appbase.io/reactive-manual/v3/advanced/migrationguide.html
