### ISSUE TITLE
web: renderNoResults parent component in ReactiveList

### ISSUE THREAD

**Issue by jyash97** [appbaseio/reactivesearch#848]
**Issue Type:**
Bug

**Platform:**
Web

**Description:**
When we pass a `div` in renderNoResults in ReactiveList we get invalid DOM nesting error because of this line https://github.com/appbaseio/reactivesearch/blob/next/packages/web/src/components/result/ReactiveList.js#L500

**Screenshots:**
![image](https://user-images.githubusercontent.com/22376783/53238851-7705cb80-36c0-11e9-923a-51ee5a1931f9.png)

**Reactivesearch version:**
^3.0.0-beta.3

**Browser:** 
72.0.3626.119 (Official Build) (64-bit)

**Anything else:**
We can do a check if renderNoResults is string then pass text in `p` else we can call the function.

**Comment by metagrover** [comment]
or we can always render a `div`?
