### ISSUE TITLE
Add support for renderAllItems in the list components

### ISSUE THREAD

**Issue by metagrover** [appbaseio/reactivesearch#849]
**Issue Type:**
Enhancement

**Platform:**
Web

**Description:**
This enhancement will allow us to perform data transformation and rendering at one place - which can significantly improve the development experience in some cases.

Please note that we will have to expose `itemProps` for individual list items to avail click handlers and other prop injections that the library does to every item in the list for the components like `SingleList`, `MultiList`, `SingleDropdownList`, `MultiDropdownList` and `TagCloud`.

Using this prop, we are essentially combining the capabilities of `transformData` and `renderItem` together in one prop.

**Comment by bietkul** [comment]
@metagrover Should we implement it now or just wait for the changes proposed in #843?

**Comment by metagrover** [comment]
@bietkul We can go ahead with this, and follow the spec at #843. What do you think?

**Comment by metagrover** [comment]
Implemented with new render props in #843
