### ISSUE TITLE
`defaultQuery` in MultiList component is not getting executed

### ISSUE THREAD

**Issue by lakhansamani** [appbaseio/reactivesearch#852]
**Issue Type:**
bug

**Platform:**
ReactiveSearch for Web

**Description:**
In Aggregation network request, `defaultQuery` prop value is not appended.

**Minimal reproduction of the problem with instructions:**
https://codesandbox.io/s/32koxx9n0p?fontsize=14

**Reactivesearch version:** 
`3.0.0-beta.4`

**Browser:**
all

**Comment by cedricium** [comment]
Until this is fixed, is there any workaround for this?

For some background info, I use `defaultQuery` to filter out results by requiring them to match a specific id.

**Comment by allendol** [comment]
Same problem exists on  SingleDropdownList.
Just go to https://codesandbox.io/s/32koxx9n0p?fontsize=14 and change the MultiList to SingleDropdownList
Same problem exist.
