### ISSUE TITLE
showSearch filter should ignore diacritics

### ISSUE THREAD

**Issue by scotthooker** [appbaseio/reactivesearch#856]
**Issue Type:**
enhancement

**Platform:**
Web

**Description:**
showSearch filter should ignore diacritics

**Comment by metagrover** [comment]
Can you add more details to this issue with relevant example usage? I'm not completely sure about the context here.

**Comment by scotthooker** [comment]
If you index Elasticsearch with a filter such as 

`        'my_ascii_folding' => [
          'type' => 'asciifolding',
          'preserve_original' => TRUE,
        ],`

The search results from submitting a search rightly ignore diacritics such as ö or ô but the list filters or auto complete suggestions do not. 

On reactivesearch filters that appear with showSearch they rightly ignore case but should also ignore special characters such as ö and ô
