### ISSUE TITLE
onValueSelected prop's source argument changes based on which dataField value was used for option's query

### ISSUE THREAD

**Issue by Jokinen** [appbaseio/reactivesearch#857]
**Issue Type:**

Enhancement/Bug depending on your view on the issue

**Platform:**

Web

**Description:**

In `<DataSearch />` in the `onValueSelected(_, _, source)` prop the `source` parameter varies based on `dataField` values when you could expect the source to always return the root entity.

**Minimal reproduction of the problem with instructions:**

Sorry, don't know the lib well enough to set up a minimal demo, but here is an example of my usecase which I find to cause unexpected results.

Index
```jsx
[
  { id: '1234', anotherEntity: { id: '4321'} },
]
```
```jsx
<DataSearch 
  dataField={['anotherEntity.id',]}
  onValueSelected={(value, _, source) => {
    // value: '4321'
    // source: { id: '4321'}
  }}
/>
```
```jsx
<DataSearch 
  dataField={['id',]}
  onValueSelected={(value, _, source) => {
    // value: '1234'
    // source: { id: '1234', anotherEntity: { id: '4321'} }
  }}
/>
```

To met it seems that always returning the root entity would make sense. I'm not very fluent with elasticsearch though so I would not know if this was a design choice and if the current behaviour is in fact more convenient for some cases.

It can cause issues when there are multiple sources:
```jsx
<DataSearch 
  dataField={['id', 'anotherEntity.id]}
  onValueSelected={(_, _, source) => {
    // value: '1234'
    // source: { id: '1234', anotherEntity: { id: '4321'} }
  }}
/>
```

You'd need to create a check in order to find out what the source contains. My usecase, in more detail, is that I am trying to use `<DataSearch />` as a means to find and then attach end existing entity into another entity by its `id`. E.g. I'm trying to find an `id` to create a many-to-one relationship. The name for the entity is a level deeper than its id. So when I search the name, the `id` I need won't be returned in the `source` argument.

**Reactivesearch version:** 3.0.0-beta.7

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome

**Anything else:**

**Comment by metagrover** [comment]
This seems like a bug. `source` should always reflect what elasticsearch returns.
