### ISSUE TITLE
[Vue] Vue-emotion dependency breaks reactivesearch after version 0.4.28

### ISSUE THREAD

**Issue by mauxtin** [appbaseio/reactivesearch#859]
**Issue Type:**
Bug

**Platform:**
Vue

**Description:**
After running `yarn upgrade` `vue-emotion` has been updated to version 0.4.28 and shows this warning when running `yarn run dev`
```
WARN  Compiled with 1 warnings
WARN  in ./node_modules/vue-emotion/dist/vue-emotion.es.js
"export 'cache' was not found in 'emotion'
READY  Server listening on http://127.0.0.1:3000
```

As a result, the reactivesearch components **no longer work** _at all_.

Browser error: 
```
TypeError: "emotion__WEBPACK_IMPORTED_MODULE_4__.cache is undefined"
    render vue-emotion.es.js:119 createFunctionalComponent83VueJS
    run es6.promise.js:75 notify es6.promise.js:92 flush _microtask.js:18 
```

**Comment by mauxtin** [comment]
Adding to this, `yarn install` shows this
```
[3/4] Linking dependencies...
warning "@appbaseio/reactivesearch-vue > vue-emotion@0.4.28" has incorrect peer dependency "emotion@^10.0.0".
warning "@appbaseio/reactivesearch-vue > vue-emotion > @vue/cli-service@3.4.1" has unmet peer dependency "vue-template-compiler@^2.0.0".
```

**Comment by joergac** [comment]
I had some weird problems after deploying an updated yarn.lock. Sadly just reverting the yarn.lock commit did not work. Even with the reverted yarn.lock I was getting errors..

Now I am using this during deployment which seems to work.
```
yarn install --frozen-lockfile
```

Hope this helps for anyone having a similar problem just a couple of hours before the weekend 😃

**Comment by mauxtin** [comment]
@joergac Will try your solution however this basically prevents us for updating our dependencies _at all_. Unless you want to dig into yarn.lock and remove any related changes, this shouldn't be anything but a temporary solution. 😕

**Comment by wehrlock** [comment]
My temporary fix was to manually install the vue-emotion peer dependency with a fixed version.

`npm install --save-exact vue-emotion@0.4.2`

And also manually install the emotion peer dependency.

`npm install emotion@9.2.0`

**Comment by metagrover** [comment]
@bietkul can you please roll out a release fixing the deps?

**Comment by mauxtin** [comment]
Not sure why it works for you guys but for me even if I manually install both packages like this, it does not work.

```
// package.json
"emotion": "9.2.12",
"vue-emotion": "0.4.2",
```

`yarn` also pulls the version requested by `reactivesearch` (ofc) which results in the above error.
```
//yarn.lock
vue-emotion@0.4.2:
  version "0.4.2"
  resolved "https://registry.yarnpkg.com/vue-emotion/-/vue-emotion-0.4.2.tgz#df97359aadd49cc476eb23ba44b7d2962a669ced"
  dependencies:
    emotion-utils "^9.1.0"
    nano-assign "^1.0.0"

vue-emotion@^0.4.2:
  version "0.4.28"
  resolved "https://registry.yarnpkg.com/vue-emotion/-/vue-emotion-0.4.28.tgz#ce7adfa82f31be9a7b9e11c874748b42f04919bf"
  dependencies:
    "@emotion/cache" "10.0.0"
    "@emotion/is-prop-valid" "0.7.3"
    "@emotion/utils" "0.11.1"
    "@vue/cli-service" "^3.2.0"
    nano-assign "^1.0.0"
```

Can we push a beta release with just the dependency fix instead of waiting for the library to be completely stable for a release?
