### ISSUE TITLE
Include index/meta fields in DataSearch

### ISSUE THREAD

**Issue by jrock17** [appbaseio/reactivesearch#860]
**Issue Type:**
Enhancement

**Platform:**
Web

**Description:**
Currently only source fields are exposed in DataSearch. It would be useful to also have access to the _index when searching across multiple indexes. That way we can apply conditional logic or formatting based on the index each item is returning from. ReactiveList currently gives you access to _index and _type but DataSearch does not.

**Minimal reproduction of the problem with instructions:**
Only _source data is supplied for DataSearch...
```<DataSearch
  ...
  renderSuggestion={(suggestion) => ({
    label: (
        <div>
            {suggestion._source.original_title} by
            <span style={{ color: 'dodgerblue', marginLeft: 5 }}>
                {suggestion._source.authors}
            </span>
        </div>
    ),
    value: suggestion._source.original_title,
    source: suggestion._source  // for onValueSelected to work with renderSuggestion
  })}
/>
```

**Reactivesearch version:** x.y.z
3.0.0-beta.7

**Browser:** 
All

**Anything else:**
Should be an easy fix. Just need to expose the extra data. Thanks you guys rock!

**Comment by bietkul** [comment]
`_index` is present inside `_source` object.
By the way, `renderSuggestion` has been changed to `parseSuggestion` in `rc` version.
