### ISSUE TITLE
MultiDataList/ToggleButton loses defaultValue on re-render

### ISSUE THREAD

**Issue by jrock17** [appbaseio/reactivesearch#861]
**Issue Type:**
Bug

**Platform:**
Web

**Description:**
When specifying defaultValue on MultiDataList or ToggleButton, it works on the first load. But if you change the search term in DataSearch, then the defaultValues are lost and resets to an all unselected state.

These buttons should retain their previous state at best, and at worst reset to the defaultValues on a new search.

**Minimal reproduction of the problem with instructions:**
See video demo of the issue: https://www.dropbox.com/s/fmq6lkfka82xlr3/defaults-bug.mp4?dl=0

**Reactivesearch version:** x.y.z
3.0.0-beta.7

**Browser:** 
All

**Comment by metagrover** [comment]
You should use `value` prop if you want controlled behavior. Refer controlled vs uncontrolled approach docs here - https://opensource.appbase.io/reactive-manual/v3/advanced/componentsusage.html
