### ISSUE TITLE
react-virtualized usage for multi dropdown list components

### ISSUE THREAD

**Issue by srujanponnur** [appbaseio/reactivesearch#864]
**Issue Type:**

Enhancement
**Platform:**

Web
**Description:**

can you please provide the usage of the package react-virtualized for the multi or single drop down list as mentioned in issue #185  
**Screenshots:**

**Minimal reproduction of the problem with instructions:**

**Reactivesearch version:** x.y.z

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**

**Comment by metagrover** [comment]
We currently do not support rendering "all items" in the list components. This will be supported via #849

Once that supported it is added, you can utilise `renderAllItems` prop to take control of rendering with `react-virtualised`.

**Comment by srujanponnur** [comment]
can I please know when would this prop be available for usage as I have an immediate requirement,
Thank you.

**Comment by scotthooker** [comment]
Hi!

I also wonder if this is possible similar to the extension done here for a reactive list https://github.com/appbaseio/reactivesearch/issues/798 

Key issue being a site with lots of "facets" can't load them all into the multi dropdown list if there are say 500+
