### ISSUE TITLE
onChange on SelectedFilter

### ISSUE THREAD

**Issue by alexandre033** [appbaseio/reactivesearch#865]
Hi, I saw the new feature in the beta 8 that allows us to save the selected value with the selectedFilter. The onChange method give an object, but how can we reuse this object to pre-fill the multilist component ?

thanks a lot for your help :smile: 
Good job for this lib :+1:

**Comment by metagrover** [comment]
The object via `onChange` will give you the current state of selected-values for the active components - which you can save for later use. 

Say if you wish to use the saved state, you can:

- use it in combination with `defaultValue` or `value` prop on the desired multilist component.

- use it with ssr via `searchState` param in `initReactivesearch()` method

- use it to set the urlparams with necessary ids - such that the component can pick up the state on load.


Hope that helps!
