### ISSUE TITLE
Vue demos doesn work

### ISSUE THREAD

**Issue by joergac** [appbaseio/reactivesearch#868]
Just found this package and it seems really nice. The ui is great! - Thanks for open sourcing this.

It seems like every vue demo I checked shows this error
```
Could not fetch dependencies, please try again in a couple seconds: 
Could not fetch version for @appbaseio/reactivesearch-vue@1.0.0-alpha: 
No matching version found for @appbaseio/reactivesearch-vue@1.0.0-alpha
```

https://opensource.appbase.io/reactive-manual/vue/list-components/multilist.html#demo
https://opensource.appbase.io/reactive-manual/vue/list-components/singlelist.html#demo
etc.

**Comment by bietkul** [comment]
Fixed it.
