### ISSUE TITLE
ReactiveBase - Allow relative url

### ISSUE THREAD

**Issue by jrock17** [appbaseio/reactivesearch#870]
**Issue Type:**
Enhancement

**Platform:**
Web

**Description:**
I've got a proxy setup for my url value for security purposes. But the url param will only let me use a full url.

Example:
   url="http://localhost:8081/searchProxy"

I want to be able to just use:
   url="/searchProxy"

This way I can use the same url on local, staging, and production and my relative environment will use the correct url. Currently, I get an error saying I need to use a full url.

**Reactivesearch version:**
3.0.0-beta.7

**Browser:** 
All

**Comment by metagrover** [comment]
Open to accepting PRs on this.
