### ISSUE TITLE
Non linear steps

### ISSUE THREAD

**Issue by ghost** [appbaseio/reactivesearch#871]
**Issue Type:**
Enhancement

**Platform:**
Web

**Description:**
I would like the ability to increment then steps of the slider in a non linear way. For example on a slider ranging from 1 to 1000. I want like 1 - 500 to take up 85% of the width of the slider because this is where most of the values are.

See an example here:
https://refreshless.com/nouislider/slider-values/#section-non-linear-step

**Comment by metagrover** [comment]
Looks good! Open to accepting PRs on this.

**Comment by ghost** [comment]
Will take a swing at this one.
