### ISSUE TITLE
Changing dataField on ReactiveList can cause old value of from to be set on next query

### ISSUE THREAD

**Issue by pparke** [appbaseio/reactivesearch#873]
**Issue Type:**
Possible Bug

**Platform:**
ReactiveSearch for Web (React)

**Description:**
Changing the `dataField` prop of `ReactiveSearch` component triggers a new query with the old query options to be fired from `componentWillReceiveProps`.  This results in the `from` field of the query retaining its old value resulting in the next search results being offset from the start.  This is happening when I set the `react` prop to watch a `DataController` that creates the query to use and then change the query and the `dataField` prop at the same time.  I think it has to do with the following code in `ReactiveList` since when I stop changing the `dataField` prop the bug stops happening.

```javascript
componentWillReceiveProps(nextProps) {
		if (
			!isEqual(this.props.sortOptions, nextProps.sortOptions)
			|| this.props.sortBy !== nextProps.sortBy
			|| this.props.size !== nextProps.size
			|| !isEqual(this.props.dataField, nextProps.dataField) // <---- will be different
			|| !isEqual(this.props.includeFields, nextProps.includeFields)
			|| !isEqual(this.props.excludeFields, nextProps.excludeFields)
		) {
			const options = getQueryOptions(nextProps);
			options.from = this.state.from; // <---- old from value
                         // ... <snip>
                         this.props.setQueryOptions(this.props.componentId, options, true); // <---- sets query options and dispatches executeQuery since last param is true, see https://github.com/appbaseio/reactivecore/blob/137832d516f36481671478c7081176badae32ade/src/actions/query.js#L398
		}
```

I lose track of it after it gets into reactivecore and `setQueryOptions` and `executeQuery`.

The solution I've come up with is to set the `sort` clause of the query in the `defaultQuery` prop instead of using `dataField` and `sortBy`.  This seems to work well and avoids the weird state I was getting into.

**Minimal reproduction of the problem with instructions:**
The above information should be enough to duplicate

**Reactivesearch version:** x.y.z
^2.16.1

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all

**Anything else:**
See description

**Comment by anakinkinsey** [comment]
This bug is still around, your workaround worked perfectly though, thanks!
