### ISSUE TITLE
Toggle on or off a ReactiveSearch Component with a checkbox

### ISSUE THREAD

**Issue by danielsnider** [appbaseio/reactivesearch#877]
**Issue Type:**
Question 

It's been two weeks and I'm eager for help. Can I please ask you for help with my short question on StackOverflow? https://stackoverflow.com/questions/54852930/how-to-toggle-on-or-off-a-reactivesearch-component-with-a-checkbox

I've included my question below for your convenience.

**Question:**
My ReactiveSearch project looks like this [demo](https://woy8013rj7.codesandbox.io/). I can't figure out how to use Javascript to temporarily hide the UI of a [ReactiveSearch Component](https://opensource.appbase.io/reactive-manual/base-components/textfield.html) and its **effect on the search results**, using a check box toggle switch.

```
<div>
   <input type="checkbox" onChange={ this.handleChecked }/>
</div>
{show_rangeSliderAge === 'checked' &&
  <RangeSlider {...components.rangeSliderAge} />
}
```
My strategy to remove the ReactiveSearch component with an "if === 'checked'" block hides the component but doesn't change the search results. Any ideas? Thanks!!

**Comment by metagrover** [comment]
The code looks okay to me. Please check the state in react-devtools to ensure that `show_rangeSliderAge` holds the correct value.

**Comment by danielsnider** [comment]
Thanks @metagrover. Yes, `show_rangeSliderAge` shows the correct value. But the search results don't reload. ResultsList need to reload somehow to get the effect of not having the RangeSlider filter. Any suggestions on how to update the results?

**Comment by metagrover** [comment]
I see, can you try updating the `key` and `componentId` of the result component whenever there is a change in `show_rangeSliderAge` value? Given how the component unmount cleanup works asynchronously, result list will reload asynchronously. Changing these props on the result component ensure the instant reload.

**Comment by danielsnider** [comment]
Thanks! Changing the "react" field of the ResultsList gets the results to
update properly.

Issue closed.
