### ISSUE TITLE
web: Is there any way to catch _msearch errors in ReactiveMap component?

### ISSUE THREAD

**Issue by bietkul** [appbaseio/reactivesearch#879]
**Issue Type:**
Feature

**Platform:**
Web

**Description:**
ReactiveMap should have something like `onError` prop to support error handling.

**Screenshots:**

**Minimal reproduction of the problem with instructions:**

**Reactivesearch version:** x.y.z

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**

**Comment by metagrover** [comment]
We support this in reactivecore but need to upgrade this w.r.t. v3 changes to support this behavior.
