### ISSUE TITLE
React ecommerce demo doesn't work

### ISSUE THREAD

**Issue by Dmitry-Kucher** [appbaseio/reactivesearch#885]
**Issue Type:**
'bug'

**Platform:**
ReactiveSearch for Web

**Description:**
There is no any kind of `*.lock` files, so demo sites doesn't work. Trying to start in development mode and getting blank page [vehicle-store](https://github.com/appbaseio/reactivesearch/tree/next/site/demos/ecommerce)

**Minimal reproduction of the problem with instructions:**

- Clone repo
- Navigate to demo path (`cd site/demos/ecommerce/dist/`)
- Run npm/yarn installation command (`npm install`)
- Run development mode of application (`npm run start`)

**Browser:**
All

**Anything else:**
The first issue which I facing with is replacing react-emotion package with "@emotion/styled"

I made the changes to install pre 10 version of package (i.e. hardcoded latest pre 10 version of react-emotion in package.json "react-emotion": "9.2.12"), reinstall npm modules
The second issue is:
```
Uncaught TypeError: _this.props.renderData is not a function
    at ResultCard._this.renderAsCard (ResultCard.js:52)
```
See attachment:

<img width="1433" alt="Screenshot 2019-03-18 at 23 11 41" src="https://user-images.githubusercontent.com/2552032/54560370-453c0800-49d3-11e9-8865-baec2ac421d9.png">

Unfortunately I have no enough time to make PR to improve this behaviour, but hope that my issue is helping to identify and prevent the problem

Recommendation: Please, include `package-lock.json` or `yarn-lock.json` to prevent such issues

Thank you for your help

**Comment by metagrover** [comment]
Thanks for filing this @Dmitry-Kucher - they all seem like version mismatch issues.

@jyash97 Can you take this up? We will need to update the `render<X>` methods as per `v3.0` and add `yarn.lock` files in every demo. I believe they are missing due to the project being a yarn workspace - so nobody ran `yarn` inside demos.

**Comment by lcalcagni** [comment]
How Can I add the lock files to make my projects work? I get the same errors as Dmitry

**Comment by metagrover** [comment]
You can run it with reactivesearch - `v2.x`, we haven't updated the demo examples' code for `3.0-beta` yet. Please try with this - https://github.com/appbaseio/reactivesearch/tree/dev/site/demos/ecommerce

Run `yarn && yarn start` in the ecommerce directory to get started.

**Comment by bietkul** [comment]
Please try now, it should work now.
