### ISSUE TITLE
Edge scrollTo error

### ISSUE THREAD

**Issue by ghost** [appbaseio/reactivesearch#886]
**Issue Type:**
Bug

**Platform:**
Web

**Description:**
The ReactiveList component uses scrollTo to endless scroll more items when pagination is false. Edge has a bug that means scrollTo is not working correctly. See this SO issue for more information.

https://stackoverflow.com/questions/51517324/scrollto-method-doesnt-work-in-edge

**Minimal reproduction of the problem with instructions:**
Create a ReactiveList component which has pagination set to false. Use a filtering element to change the results.

**Reactivesearch version:** 2.16.1

**Browser:**  Edge

**Anything else:**

![image](https://user-images.githubusercontent.com/41870207/54578018-203aaa00-4a52-11e9-9d4c-f6bfbcfeabf7.png)

```
	if (this.props.pagination) {
			// called when page is changed
			if (this.props.isLoading && (this.props.hits || nextProps.hits)) {
				if (nextProps.onPageChange) {
					nextProps.onPageChange(this.state.currentPage + 1, totalPages);
				} else {
					this.domNode.scrollTo(0, 0);
				}
			}

			if (
				this.props.currentPage !== nextProps.currentPage
				&& nextProps.currentPage > 0
				&& nextProps.currentPage <= totalPages
			) {
				this.setPage(nextProps.currentPage - 1);
			}
		}

		if (!nextProps.pagination) {
			if (this.props.hits && nextProps.hits) {
				if (
					this.props.hits.length !== nextProps.hits.length
					|| nextProps.hits.length === nextProps.total
				) {
					if (nextProps.hits.length < this.props.hits.length) {
						// query has changed
						this.domNode.scrollTo(0, 0);
						this.setState({
							from: 0,
						});
					}
				}
			}
		}
```

**Comment by jyash97** [comment]
Fixed in #1031
