### ISSUE TITLE
why reactive search required es:ESHttpPost for normal search operation

### ISSUE THREAD

**Issue by pandeybk** [appbaseio/reactivesearch#887]
**Issue Type:**
General question

**Platform:**
Web

**Description:**
I am trying to use reactive search with aws elastic search. I don't have any authentication method configured on ES. Just using aws IAM role policies to restrict access. I added role `es:ESHttpGet`, but looks like reactive search module required `es:ESHttpPost` access also. Any reason for that. Can I make it work without allowing `POST` operation for public search?

**Comment by siddharthlatest** [comment]
@pandeybk We currently use `POST` for the search requests. I am not sure if there can be any side effects if we switch to GET, but it's worth considering 🤔 

In the meanwhile, you can restrict the resource to the `/_msearch` endpoints of the particular index configured with ReactiveSearch and that should help with an effective security role.

An example may look like this:

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": [
          "arn:aws:iam::123456789012:user/test-user"
        ]
      },
      "Action": [
        "es:ESHttpPost"
      ],
      "Resource": "arn:aws:es:us-west-1:987654321098:domain/test-domain/test-index/_msearch"
    }
  ]
}
```

**Comment by pandeybk** [comment]
This is awesome, thank you for quick response.
