### ISSUE TITLE
renderNoResults prop missing in MultiList, but present in docs

### ISSUE THREAD

**Issue by joepio** [appbaseio/reactivesearch#889]
**Issue Type:**
bug / documentation problem

**Platform:**
Web

**Description:**
The `renderNoResults` property no longer exists in [MultiList for React](https://github.com/appbaseio/reactivesearch/blob/dev/packages/web/src/components/list/MultiList.js) in v3, but [is still documented](https://opensource.appbase.io/reactive-manual/v3/list-components/multilist.html#props).

**Reactivesearch version:** 3.0.0-beta.8

**Comment by bietkul** [comment]
Hey, we have `renderNoResults` implementation in code too, can you please share how you're using it.
https://github.com/appbaseio/reactivesearch/blob/next/packages/web/src/components/list/MultiList.js#L554

**Comment by joepio** [comment]
I'd like to render a react component in the Multilist to communicate to the user that his search does not match any items. I can't show how I'm using it, because the application can't compile if the property does not exist in 3.0.0-beta.8. For some reason it has been removed, I think.
