### ISSUE TITLE
MultiList crashes when showLoadMore is true

### ISSUE THREAD

**Issue by joepio** [appbaseio/reactivesearch#893]
**Issue Type:**
When `showLoadMore` is set to `true` in a `MultiList` component, the component does not render. The following appears in the browser console:

`Warning: Can't call setState on a component that is not yet mounted. This is a no-op, but it might indicate a bug in your application. Instead, assign to `this.state` directly or define a `state = {};` class property with the desired state in the MultiList component.`

**Platform:**
Web

**Minimal reproduction of the problem with instructions:**
```
      <MultiList
        componentId="someId"
        dataField="someField"
        showLoadMore={true}
      />
```

**Reactivesearch version:** ^3.0.0-beta.8

**Browser:** Latest chrome & firefox

**Comment by jyash97** [comment]
Hey @joepio 
Thanks for reporting this. Can you confirm the app you are using is above ElasticSearch version 6 ?

Check docs [here](https://opensource.appbase.io/reactive-manual/v3/list-components/multilist.html#props)

**Comment by joepio** [comment]
Yep, it's 6! It's running here: http://ori.argu.co
Sourcecode here: https://github.com/ontola/ori-search

**Comment by joepio** [comment]
Seems to be fixed in the current `next` branch.
