### ISSUE TITLE
ReactiveGoogleMap : onPopoverClick on the custom renderData ?

### ISSUE THREAD

**Issue by ilostit** [appbaseio/reactivesearch#894]
Hello,

When i add my custom marker the onPopOverClick not working ?

any idea ?

my code :

renderData={result => ({
custom: (

<FontAwesomeIcon icon={['fa', 'map-marker']} size="3x" />

)
})}

**Comment by ilostit** [comment]
In fact i would like a dynamic pin map based on a category something like this : 

       renderData={result => ({
                custom: (
                  <FontAwesomeIcon icon={['fa', 'result.MYCATEGORY']} size="2x" />
                )
              })}

but i'm not sure is the best approach, because i would like to replace the pin of the map with this dynamic icon.....

**Comment by metagrover** [comment]
This used to work with 2.x. @lakhansamani can you check if it is functional with 3.x as well?

**Comment by lakhansamani** [comment]
Sure I will check this today 👍

**Comment by lakhansamani** [comment]
Fixed here: [558d741](https://github.com/appbaseio/reactivesearch/commit/558d7414e9aba1526ea2617b9a462d05fe91bb9b) 🎉 

@ilostit for reference you can check https://codesandbox.io/s/k57v0qmy0v

**Comment by ilostit** [comment]
> 558d741

Thanks :)
