### ISSUE TITLE
ResultList nested objets not showing

### ISSUE THREAD

**Issue by alekseiancheruk** [appbaseio/reactivesearch#896]
**Issue Type:**
enhancement

**Platform:**
ReactiveSearch for Web

**Description:**
I'm building my search platform with the latest ElasticSearch and reactivesearch. My first document from my *.json file looks like this:
`[{
    "Reactor_type": [
        "EPR",
        "PWR"
    ],
    "Safty_authority": [],
    "System": [
        "SEP",
        "SAT",
        "SEI",
        "SAR"
    ],
    "FileName": "test.pdf",
    "Label": [
        "cable"
    ],
    "FileLocation": "home/test.pdf",
    "Language": [
        "Eng"
    ],
    "Text": [
        {
            "sentence": "This is a sentence.",
            "component": [
                "component1",
                "component2"
            ]
        },
        {
            "sentence": "This is another sentence.",
            "component": [
                "component3",
                "component4"
            ]
        }]}],`  

So I have a `Text` object which has an array of other json objects. When I'm using `DataSearch` everything seems to be working with `dataField={[
            'Text.sentence',
            'Text.sentence.keyword'
          ]}`, it even shows me suggested sentences.

Despite that, when I want to visualize the sentences that match my query with `ResultList`, It shows me nothing and res.Text.sentence doesn't work here. Here is a piece of my `App.js`:

<ResultList
    componentId="result"
    title="Results"
    dataField="FileName.raw"
    react={{
		or: ["gl_search","searchbox_1","searchbox_2"]
							}}
    onData={(res) => {
		return {
                  title: res.FileName,
                  description: (
                    <div>
                        <div>{res.FileLocation}</div>
                        <div>{res.Text.sentence}</div>
                    </div>
                ),
		}
			}}
						/>

How can I show all my matched sentences in result ?

**Reactivesearch version:** ^2.18.0

**Browser:** 
Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by metagrover** [comment]
`Text` is an array as per you result. So try `res.Text[0].sentence`? You can simply map over your `Text` array and also concatenate the `sentence` values in the desired JSX format.

**Comment by alekseiancheruk** [comment]
> `Text` is an array as per you result. So try `res.Text[0].sentence`? You can simply map over your `Text` array and also concatenate the `sentence` values in the desired JSX format.

Already tried `res.Text[0].sentence`, it's not quite what I want...

I want to have a global search on all `Text.sentence` objects which works already. I also want a faceted search within `Text` using `Text.component`. So when I type "cables" in global search, choose system type and component, the search should give me **all the matched documents** with their names and **all the matched sentences within these documents that speak about cables**. Is it possibible to implement with reactivesearch ?


![Screenshot from 2019-03-26 16-33-47](https://user-images.githubusercontent.com/32813010/55010930-6a3d0600-4fe5-11e9-889a-8983b2aa6345.png)

**Comment by metagrover** [comment]
Okay, you can set the `dataField` of DataSearch component to be an array of all the fields you want the search to work on, and you can also set the desired field weights to apply search preferences on desired fields. Check docs here - https://opensource.appbase.io/reactive-manual/v3/search-components/datasearch.html#props

If you wish to get the highlighted search values in your results to find the exact match of the string in your document, you can set `highlight={true}`. Is this what you're looking for?

**Comment by alekseiancheruk** [comment]
> Okay, you can set the `dataField` of DataSearch component to be an array of all the fields you want the search to work on, and you can also set the desired field weights to apply search preferences on desired fields. Check docs here - https://opensource.appbase.io/reactive-manual/v3/search-components/datasearch.html#props
> 
> If you wish to get the highlighted search values in your results to find the exact match of the string in your document, you can set `highlight={true}`. Is this what you're looking for?

Maybe I was not clear enough, sorry. The problem is that when I search globally in `Text.sentence`, `ResultList` doesn't update accordingly... I want it to return a name of the document from `FileName` and  an array of matched phrases after searching "cables" in `DataSearch` field and specifying `Text.component` within this very doc. For now, `ResultList` just gives me my doc name and plain text within, I want this text to be filtered as well...

**Comment by metagrover** [comment]
ResultList only renders what it gets from Elasticsearch hits. So, please check if your Elasticsearch query looks good (in the networks-panel `_msearch` request), and then see if the hits are coming as expected.

If you think there is some issue with rendering those hits values with ResultList - give `ReactiveList` a try, it allows full customization in the UI.
