### ISSUE TITLE
`UpdateQuery` when `CustomQuery` changes

### ISSUE THREAD

**Issue by nadrane** [appbaseio/reactivesearch#900]
**Issue Type:**
Enhancement

**Platform:**
web

**Description:**
I've run into quite a few scenarios now where I have a Reactivesearch component that is is wrapped in an outer component that maintains its own state. The Reactivesearch's custom query is driven based on the state inside the outer component.

The problem with custom queries today is that the query does not update/execute when the custom query changes; the query only updates/executes when the `value` prop changes. But what should I do when the custom query is driven by both the value and some piece of state or prop maintained in an outer component?

Today, inside the `componentDidUpdate` lifecycle hook of each (many?) Reactivesearch component, we check if the `value` prop has changed, and if it has, then we update the query. I'm proposing that in cases where a custom query is used, we also check to see if the `customQuery` has deeply changed between re-renders and if it has, update the query. This behavior change would allow Reactivesearch components to behave far more flexibly.

What are people's thoughts? I'd be happy to implement this.

**Comment by metagrover** [comment]
We used to have this functionality (in v2)

@bietkul -  can you please check on this? I think it stopped working after we changed the spec for customQuery prop.
