### ISSUE TITLE
Clearing a single filter in a custom component?

### ISSUE THREAD

**Issue by dres-cifuentes** [appbaseio/reactivesearch#902]
**Issue Type:**

Not sure if bug or enhancement issue. 

**Platform:**
Native

**Description:**
Created custom ReactiveComponent and having trouble clearing the single filter

**Screenshots:**

**Minimal reproduction of the problem with instructions:**

I believe the issue has to do with the `setQuery` props.
I'm setting `setQuery` within my `setValue` function. If the value has been selected, I'm passing in `undefined` in order to uncheck my checkbox icon. 

```
setValue(value) {
    const { setQuery, searchType } = this.props;

    setQuery({
      query: {
        term: {
          [searchType]: value,
        },
      },
      value,
    });
  }
```

I read elsewhere that if the query doesn't exist, to pass in null, but I'm not getting any changes in the filters displayed when I do so. The way I'm passing in null is `setQuery(null)` . Is there a proper way to clear a single filter other than the `Clear All` prop in the `SelectedFilters` component?

**Reactivesearch version:** 0.11.1

**Browser:** [iOS]

**Anything else:**

**Comment by DustinKLo** [comment]
+1
