### ISSUE TITLE
SingleList/MultiList incorrectly rendering list items

### ISSUE THREAD

**Issue by moritzlang** [appbaseio/reactivesearch#908]
**Issue Type:**
Bug

**Platform:**
Web

**Description:**
My elasticsearch index has a 'attributes' field which is an array of strings e.g.
`["Trusted user", "Fast response", "Video chat"]`
I want to use these to filter my search results using a MultiList. The filtering works, but the MultiList is rendered weird. It seems like the strings are split on the whitespace. The same problem appears using the SingleList.

**Screenshots:**
<img width="212" alt="Bildschirmfoto 2019-04-02 um 21 58 16" src="https://user-images.githubusercontent.com/19893634/55432203-97b02380-5592-11e9-9eb2-d8744be2c836.png">

**Reactivesearch version:**
3.0.0

**Browser:**
all

**Anything else:**
I am using Elasticsearch 2.3.5

**Comment by siddharthlatest** [comment]
Hi @moritzlang, it's a mapping issue in your ES index. Prior to v5 in ES, you need to explicity set your mapping to a not_analyzed string for it to pick the string as is. This isn't a ReactiveSearch issue. Hope this helps!

**Comment by moritzlang** [comment]
> Hi @moritzlang, it's a mapping issue in your ES index. Prior to v5 in ES, you need to explicity set your mapping to a not_analyzed string for it to pick the string as is. This isn't a ReactiveSearch issue. Hope this helps!

Thank you so much @siddharthlatest it is working now!
