### ISSUE TITLE
[Vue] Custom component and clear filter doesn't work

### ISSUE THREAD

**Issue by javialon26** [appbaseio/reactivesearch#912]
**Issue Type:**
Enhancement/Bug

**Platform:**
Vue

**Description:**
Use selected filters component with a custom reactive search component and try to clear all filters or remove the custom filter.

Current behavior: The result list remains without changes. (with the last custom filter applied)
Expected behavior: The result list must be updated.

**Minimal reproduction of the problem with instructions:**
https://codesandbox.io/embed/z33kl8p1ml?fontsize=14

**Reactivesearch version:** 1.0.0-beta9

**Comment by bietkul** [comment]
@metagrover Any idea how to do that? I was also getting the same issue.

**Comment by metagrover** [comment]
Since it's a custom component, you will have to manually check for the updated `selectedValue` (which should be `null`) in props, and then fire a null query via given `setQuery` method in your child component.

**Comment by javialon26** [comment]
@metagrover I think this is a workaround. I achieve the same behavior with the clean event in the selected filter component but in the react example this works out of the box.

See: https://opensource.appbase.io/reactive-manual/advanced/reactivecomponent.html#examples

**Comment by metagrover** [comment]
@bietkul can you check on this? Both variants should be consistent.

**Comment by bietkul** [comment]
@javialon26 It is working with Vue too.
https://codesandbox.io/embed/z33kl8p1ml?fontsize=14

**Comment by davidkong0987** [comment]
Is it just me or does this no longer work? or perhaps I'm on an old version

**Comment by dominicpedro** [comment]
This is still not working, clearing the filters is not resetting the custom components query.
the query-changed event does not fire and in fact no events fire when clearing on the reactive-component.
