### ISSUE TITLE
Print query sent to the elasticsearch

### ISSUE THREAD

**Issue by ansuaggarwal** [appbaseio/reactivesearch#915]
**Issue Type:** Question

**Platform:** ReactiveSearch for web

**Description:** I have implemented ReactiveSearch and connected it with my own elasticsearch implementation. But I can see that total number of result found from the custom query in Reactivesearch is different from what I am getting it from elasticsearch directly .

I want to see the query that is being sent to the elasticsearch.

Below is the reactive component I am using.

<CategorySearch
	componentId="searchbox"
	placeholder="Search for products"
	highlight={true}
	highlightField="name"
	style={{
		padding: "5px",
		marginTop: "10px"
	}}
	customQuery={
	function(value, props) {
		
	  return {									
			  query: {
				bool: {
				  should: [
					{
					  multi_match: {
						query: value,
						fields: [
						  "name^10",
						  "productTitle^7",
						],
						operator: "and"
					  }
					}
				  ],
				  minimum_should_match: "1"
				}
			  }
			}
	}
  }
/>

Can anyone help me in debugging the same.

Thanks in Advance.

**Reactivesearch version:** 2.12.1

**Browser:** all

**Anything else:** NA

**Comment by metagrover** [comment]
You can check the query in the browser's network panel: look out for `_msearch` requests.

<img width="1185" alt="image" src="https://user-images.githubusercontent.com/9116042/55483413-25981700-5644-11e9-807b-0649d07d957f.png">

Hope that helps!

Feel free to reopen if you have any further questions.

**Comment by DustinKLo** [comment]
Is there a way to extract it into a variable?
I may need the raw query to use in another page

**Comment by DustinKLo** [comment]
i noticed you can parse the stringify'd JSON with the `transformRequest` function 

```
<ReactiveBase
          app={ES_INDICES}
          url={ES_URL}
          transformRequest={(e) => console.log(e.body.split('\n')[1])}
        >
```

but it brings up a 400 (Bad Request) error.
not sure how to use the `transformRequest` function without breaking anything

**Comment by siddharthlatest** [comment]
@DustinKLo You also have to return the updated request. It's failing as you don't return anything back.

**Comment by DustinKLo** [comment]
@siddharthlatest  thank you for the clarification, works great 👍

**Comment by DevMaster921** [comment]
Hi, @DustinKLo, @siddharthlatest  Nice to meet you.
Could you let me know how I can fix this issue?

**Comment by DevMaster921** [comment]
Hi, @siddharthlatest 
Could you let me know how to avoid multi-search in ReactiveBase?
