### ISSUE TITLE
How to save the queried data in a state?

### ISSUE THREAD

**Issue by DustinKLo** [appbaseio/reactivesearch#922]
**Issue Type:** Feature

**Platform:** Web

**Description:** I want to save the queried data so that i can render the results in customized visualizations
 

**Reactivesearch version:** 3.0.0-beta

**Browser:** Chrome

**Comment by lakhansamani** [comment]
@DustinKLo 
You can use `ReactiveList` component here,
it has render prop, which will allow you to pass data to any child component
https://opensource.appbase.io/reactive-manual/v3/result-components/reactivelist.html#extending

Also if you want to store data / query state in state / redux store
you can use `onData` prop, it returns the data with change in each query state.
