### ISSUE TITLE
Attempted import error: 'TextField' is not exported from '@appbaseio/reactivesearch'

### ISSUE THREAD

**Issue by eef** [appbaseio/reactivesearch#925]
**Issue Type:** Bug

**Platform:** Web

**Description:** When importing TextField I get the error
```
Failed to compile.

./src/App.js
Attempted import error: 'TextField' is not exported from '@appbaseio/reactivesearch'.
```

**Minimal reproduction of the problem with instructions:**  I have included code under "Anything else".  This example does not work.

**Reactivesearch version:** 3.0.0-rc.0

**Browser:** all

**Anything else:**

```
import React, { Component } from 'react';
import { ReactiveBase, TextField } from '@appbaseio/reactivesearch';

class App extends Component {
  render() {
    return (
      <React.Fragment>
        <ReactiveBase
          app="users_development"
          url='https://asdasdasdasdasdasdasd.us-east-1.es.amazonaws.com'
        >
          <TextField dataField="name" componentId="UserSensor" />
        </ReactiveBase>
      </React.Fragment>
    );
  }
}

export default App;
```

**Comment by metagrover** [comment]
Hello @eef, we have removed support for TextField component - we are also updating our docs to reflect this. Please consider using `DataSearch` instead of `TextField`.
