### ISSUE TITLE
App crash on IE11 due to popstate event

### ISSUE THREAD

**Issue by willopez** [appbaseio/reactivesearch#926]
**Issue Type:**
Bug

**Platform:**

web V3-beta8

**Description:**
On IE11, ReactiveSearch crashes when changing from one page to another. The root cause is the following command: 
```
window.dispatchEvent(new Event('popstate'));
```
on IE11 it causes the following error: 
```
Object does't support this action
```
ReactiveSearch is using the `popstate` event here:

https://github.com/appbaseio/reactivesearch/blob/next/packages/web/src/components/basic/URLParamsProvider.js#L126

**Screenshots:**

![ei11](https://user-images.githubusercontent.com/486340/55651126-7fabf000-579c-11e9-8a04-36f557c843e1.png)

**Minimal reproduction of the problem with instructions:**

**Reactivesearch version: v3-beta.8

**Browser:** IE11

**Comment by jyash97** [comment]
Hey @willopez 
Thanks for filing this. It looks like `new Event` is not supported in `IE11`. I will take a look at this.

**Comment by willopez** [comment]
Hi @jyash97 thanks for looking at this issue. I believe adding this will fix the issue: 
```
let event;
if (typeof(Event) === 'function') {
    event = new Event('popstate');
} else {
    event = document.createEvent('Event');
    event.initEvent('popstate', true, true);
}

window.dispatchEvent(event);
```

**Comment by willopez** [comment]
@jyash97 I have created a PR to fix this issue: #928

**Comment by jyash97** [comment]
Fixed [here](https://github.com/appbaseio/reactivecore/pull/35)

**Comment by lakhansamani** [comment]
@willopez we added new release `3.0.0-rc.1` which includes above fix

**Comment by willopez** [comment]
great! thanks
