### ISSUE TITLE
Combining multiple values into one label on SingleDataList

### ISSUE THREAD

**Issue by DavidRamsdale** [appbaseio/reactivesearch#927]
Issue Type: I believe enhancement

Platform: Web

I am trying to combine label values in the SingleDataList on reactive search. Using the example they provide below:

                        <SingleDataList
                            title="SingleDataList"
                            componentId="CitySensor"
                            dataField="group.group_topics.topic_name_raw.raw"
                            data={[
                                { label: 'Open Source', value: 'Open Source' },
                                { label: 'Social', value: 'Social' },
                                { label: 'Adventure', value: 'Adventure' },
                                { label: 'Music', value: 'Music' },
                            ]}
                        />

My question is if its possible to combine the values of Social and Adventure into another label called "Social+Adventure" for example?

Would there be any way that this is possible in the SingleDataLList component?

Browser: Chrome

**Comment by lakhansamani** [comment]
@DavidRamsdale it depends on how you are storing value of `Social+Adventure` in elasticsearch.
Can you share an example of how the value will look like for combination of 2 labels?
