### ISSUE TITLE
vue: Server Side Rendering

### ISSUE THREAD

**Issue by mauxtin** [appbaseio/reactivesearch#931]
I have been using this package for a long time so thanks for open sourcing it! 😃 

We live in a time where SEO is crucial for many businesses. I'd would be amazing to have SSR support for the Vue package similar to what the react currently has.

I couldn't find anything in the docs so I suppose it is not supported, please correct me if I am wrong.

**Comment by bietkul** [comment]
Currently we do not support it in `vue`, we will add this feature soon.

**Comment by mauxtin** [comment]
Awesome! Thanks @bietkul for letting me know :)

**Comment by bietkul** [comment]
Added in the latest version.
https://opensource.appbase.io/reactive-manual/vue/advanced/ssr.html

**Comment by mauxtin** [comment]
🎉 🎉 🎉
