### ISSUE TITLE
Question: "remote control" the search input of DataSearch

### ISSUE THREAD

**Issue by vermario** [appbaseio/reactivesearch#935]
**Issue Type:**
inquiry
**Platform:**
Web

**Description:**
I am trying to find out if it's possible via another component to trigger the updating of the state of the DataSearch component (or similar component). I would like to have a way by pressing a button or interacting with a custom component to set the value of the input and to trigger a new search.  

I think this is what the UrlParamsProvider component does (at least conceptually), do you think this could be achievable with a custom component?

I did manage to get to the search input via the inner ref prop: but updating the value of the input does not trigger a new search.

Any ideas would be very welcome! thanks!

**Reactivesearch version:** 2.1.8

**Comment by apiel** [comment]
Need the same here

**Comment by bietkul** [comment]
One solution can be the use of controlled behavior of DataSearch component ( > 3.0 ), use the `value` prop with `onChange` to handle the selected value at a particular time.
Note: Now the `value` will be a reactive property, change it whenever you want and it will update the query.

**Comment by apiel** [comment]
Actually after playing around for hours, I think the right way to go is to use reactive component https://opensource.appbase.io/reactive-manual/advanced/reactivecomponent.html
