### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by joergac** [appbaseio/reactivesearch#940]
The company I work for, is considering moving from Algolia to Elasticsearch and Appbase. We saw the [pricing ](https://appbase.io/pricing/) appbase offers and seems like a great deal for us.

However after testing the Vue library we realized that it stills is in beta mode (although functional) and we were wondering if there is Vue Roadmap you could share.

Algolia's Vue library is pretty mature and we wouldn't want to go a step pack instead of forward. They invest a great deal in their packages and we'd like to know if this is the case with Appbase too.

Thanks

**Comment by KrishnaPG** [comment]
Wondering the same about the Vue support, and future
