### ISSUE TITLE
If Multiple Indices in ReactiveBase,how to access individual records in ReactiveList

### ISSUE THREAD

**Issue by srujanponnur** [appbaseio/reactivesearch#941]
**Issue Type:**

Enhancement

**Platform:**

Web
**Description:**

I just Wanted a little clarification on the accessibility of the second Index mentioned in the ReactiveBase with in a single ReactiveList onalldata prop, is it possible to do that? or is there an other way other than self querying another index inside Reactive List.

**Screenshots:**

**Minimal reproduction of the problem with instructions:**

**Reactivesearch version:** x.y.z

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**

**Comment by lakhansamani** [comment]
@srujanponnur 

you can add `ReactiveComponent` from `@appbaseio/reactivesearch`, where the `customQuery/defaultQuery` could be index query and then you can pass that `componentId` to the `react` prop of `ReactiveList`

example

```
const query = {
	query: {
		term: {
			_index: 'index2',
		},
	},
};

<ReactiveComponent
	customQuery={() => query}
	componentId="baseQuery"
/>

<ReactiveList
   componentId="result"
   react={{
      and: ['baseQuery']
   }}
   ....
/>
 
````

**Comment by srujanponnur** [comment]
Yes,I know this way and this is the same as `<ReactiveBase app="index1,index2" url="">` right?
What I wanted was , is there a way to access individual records in ReactiveList in onAllData prop
` <ReactiveList onAllData={function(Data)}`
Here Data has records including both the indexes,I wanted a way to seperate them.

**Comment by srujanponnur** [comment]
@lakhansamani 

Yes,I know this way and this is the same as `<ReactiveBase app="index1,index2" url=""> ` right?
What I wanted was , is there a way to access individual records in ReactiveList in onAllData prop
`<ReactiveList onAllData={function(Data)}`
Here Data has records including both the indexes,I wanted a way to separate them.

**Comment by lakhansamani** [comment]
Yes, your `ReactiveBase` seems correct.

You can have 2 `ReactiveList` and 2 `ReactiveComponents` where 1 responds to data from `index1` and another responds to data from `index2`.

Else you can filter it on the client side but that might add some problems with pagination.

**Comment by srujanponnur** [comment]
@lakhansamani 

I understand what you are saying but my use case is ,I don't want to render index2 records i just want to access index2 records while rendering index1 records as there is some data dependency like this  `<ReactiveList onAllData={function(Data)}` so, using two `ReactiveList` doesn't really solve my problem,currently what I am doing is while rendering records from `index1` I am manually querying `index2` and rendering it dynamically but this creates a huge delay as I am waiting for the query every single time.

**Comment by lakhansamani** [comment]
@srujanponnur 
Didn't get last part of your use case.
But can you share the version of `ReactiveSearch` that you are using?

Also if there is no-co-relation between data of index1 and index2 then you can just get the data via `ReactiveComponent` / `ReactiveList` and store it in state of your application for manipulation of data.

**Comment by srujanponnur** [comment]
@lakhansamani 

This is my version `reactivesearch-2.16.1`

Okay got it, just a rookie question if you wouldn't mind, storing Millions of Records Prior to my usage, wouldn't it effect the sites performance.

**Comment by lakhansamani** [comment]
Thanks @srujanponnur for sharing version.

So above logic should work and to answer your question, yes it will affect the site performance.
