### ISSUE TITLE
vue: Access reactivesearch current values

### ISSUE THREAD

**Issue by mauxtin** [appbaseio/reactivesearch#952]
Is there a way of accessing the current values of the reactivesearch components?

For example I'd like to know that there are results shown on the page and if not, show something else. This would really improve the UX since when the user set some filters (dynamic range slider, multi list etc) and ended up with no results, I'd like to show something else, maybe an image saying something etc.

I also noticed the `renderNoResults` prop but couldn't find a demo on how that works and check if its fits my case here. Could that be used to display my own no-results component?

These are basically two different issues which are currently connected for me.
1) Access reactivesearch store
2) Display custom no results component

Let me know if it's better to open a new issue for the second one :)

**Comment by bietkul** [comment]
1. It is not possible to access reactivesearch store for now.
You can definitely create a new issue for it.

2. You can use `slot` to show the custom no results component under the `ReactiveList` component.
for example
```
<div slot="renderNoResults">No results to display</div>
``` 
Check docs [here](https://opensource.appbase.io/reactive-manual/vue/result-components/reactivelist.html)
