### ISSUE TITLE
ReactiveBase headers encodeURI on Authorization Basic 

### ISSUE THREAD

**Issue by jianglin101** [appbaseio/reactivesearch#958]
**Issue Type:**
bug

**Platform:**
ReactiveSearch for Web 

**Description:**
https://github.com/appbaseio/appbase-js/commit/54d796bb1f6b8e69bfe14304af64973bf38e08e5#diff-1fdf421c05c1140f6d71444ea2b27638 
appbase-js added shouldEncode default true for headers, which encodes
```
<ReactiveBase
      app="some-app"
      url="some-url"
      type="_doc"
      headers={{ Authorization: `Basic xxxxxxxx` }}
 >
```
then request headers become
 authorization: Basic%20xxxxxxxx

Is there a way to set not to encode headers from ReactiveBase?

**Comment by JoeDevGeeeee** [comment]
Having the same problem. Anyone found a solution yet?

**Comment by arcxyz** [comment]
Same problem here using the Vue components.

**Comment by siddharthlatest** [comment]
If you are trying to use Basic Authentication, you can use the `credentials` prop of ReactiveBase, which accepts a `username:password` format (i.e. not base64 encoded).

**Comment by arcxyz** [comment]
As a temporary solution for my use case (elasticsearch proxy with express+jwt) I'm going to decode the header on server before extracting the token from request

**Comment by jianglin101** [comment]
solution by @siddharthlatest works.   ReactiveBase [documentation](https://opensource.appbase.io/reactive-manual/getting-started/reactivebase.html): 'If you are not using an appbase.io app, credentials may not be necessary'.  So basically, prop credentials can be used for appbase.io app AND non-appbase Basic Authentication, prop headers is default encoded in appbase-js v4 beta

**Comment by bietkul** [comment]
It is best to use `transformRequest` prop to set the headers which you don't want to encode.

For example:

```js
<ReactiveBase
    transformRequest={
        request => ({
			...request,
			headers: {
				...request.headers,
                                 // Reactivesearch will not encode this header
				my-header: 'Basic xxxxxxxx',
			},
		})
    }
>
</ReactiveBse>
```

**Comment by siddharthlatest** [comment]
Further update: Since ReactiveSearch v3.2.2, we no longer encode headers passed in the `headers` prop. If a user requires to encode the headers, we expect that they would do this on their end or utilize `transformRequest` prop for complete control

**Comment by andereb081** [comment]
So basically something like this if your are using base64 encoded API key:
1. After generating your API key
2. On your terminal run `echo -n KEY_ID:API_KEY_VALUE | base64` to get your base64 encoded API Key
3. Then on ReactiveSearch add it this way as mentioned by @bietkul 
    
```
<ReactiveBase
    transformRequest={
        request => ({
	  ...request,
	  headers: {
		  ...request.headers,
                                 // Reactivesearch will not encode this header
		  Authorization: 'ApiKey: THE_ENCODED_KEY_IN_STEP_2',
	  },
        })
     }
      >
</ReactiveBase>
```
