### ISSUE TITLE
MultiList and DataController (v.2) migration to Multilist with defaultQuery (v.3)

### ISSUE THREAD

**Issue by antekai** [appbaseio/reactivesearch#961]
**Issue Type:**
Bug (?)

**Platform:**
ReactiveSearch for Web

**Expected behaviour**: MultiList - defaultQuery prop allows full control of the listed-options query   
**Actual behaviour**: MultiList - defaultQuery prop allows partial control of the listed-options query

**Description:**
I am not sure if this is a bug or expected behaviour. I try to control the listed-options of MultiList. At ReactiveSearch v.2, I used DataController-customQuery to control the listed-options of MultiLis (via react prop). I try to migrate to v.3 but I cannot pass or override anything inside "query" of defaultQuery. 

**Minimal reproduction of the problem with instructions:**
Examples: 
MultiList(v.3 - `query: { match_none: {} }` is not passed):  
 https://codesandbox.io/s/p067kyvl0
MultiList+DataController (v.2 - `query: { match_none: {} }` is passed = no option is rendered):  
 https://codesandbox.io/s/v64m06yy70

```js
// MultiList defaultQuery
defaultQuery={() => ({
                query: { match_none: {} }, // cannot pass this
                timeout: "9s" // can pass this
              })}
```

```js
// example ElasticSearch-result query with MultiList  and defaultQuery prop
{
  "query": { "match_all": {} }, // cannot change or override this by defaultQuery
  "size": 0, // can change this by defaultQuery
  "aggs": { // can change this by defaultQuery
    "original_series.raw": {
      "terms": {
        "field": "original_series.raw",
        "size": 50,
        "order": { "_count": "desc" }
      }
    }
  },
  "timeout": "1s" // can change this by defaultQuery
}
```

**Reactivesearch version:** 3.0.0

**Browser:** [all ]

**Anything else:**
related issues: https://github.com/appbaseio/reactivesearch/issues/852

**Comment by bietkul** [comment]
Can you please update to the latest `rc` version, we have fixed it recently.

**Comment by antekai** [comment]
> Can you please update to the latest `rc` version, we have fixed it recently.

Updating to latest resolves the issue. Thank you!
