### ISSUE TITLE
Looking for a very simple example of @valueChange on DataSearch

### ISSUE THREAD

**Issue by rjacques** [appbaseio/reactivesearch#964]
Hi,

I am looking for a simple implementation of @valueChange in a DataSearch component for Vue.
Apologies, I have looked far and wide but just can't find any examples.

I have a code example here: https://codesandbox.io/s/8yqy5l8jvj

I just want to implement a @valueChange event that does anything, even if it just alerts or logs something to the console.

Thanks!

**Comment by bietkul** [comment]
Check it
https://codesandbox.io/s/j0x6rp3r3

**Comment by rjacques** [comment]
Brilliant, thank you very much!
