### ISSUE TITLE
URLParams value not in sync with Component when using Vue Router

### ISSUE THREAD

**Issue by jyash97** [appbaseio/reactivesearch#965]
**Issue Type:**
**Bug** but needs investigation as I am not sure if I've done some mistake while implementing.

**Platform:**
Vue

**Description:**
There are two  related issues :
1. When reloading the page the `URLParams` value is not in sync with the component.
2. When we change the route and send the param the component is not in sync.

**Minimal reproduction of the problem with instructions:**
1. https://codesandbox.io/s/vvwqqw85z5
2. https://codesandbox.io/s/lpwjxm4609

**Reactivesearch Vue version:** x.y.z
`1.0.0-beta.13`

**Comment by bietkul** [comment]
@jyash97 The issue is with your configuration of Vue Router, it is adding an extra hash at the end of the URL.
Check the working example [here](https://codesandbox.io/s/vue-template-5meoz)
