### ISSUE TITLE
In Getting Started Guide, links in components overview/results components get 404s

### ISSUE THREAD

**Issue by zguillen** [appbaseio/reactivesearch#966]
**Issue Type:**
 Bug

**Platform:**
ReactiveSearch for Web 

**Description:**
On this page https://opensource.appbase.io/reactive-manual/getting-started/componentsindex.html#4-result-components the links to ReativeList, ResultList, etc. all result in 404 responses. 

**Minimal reproduction of the problem with instructions:**
go to https://opensource.appbase.io/reactive-manual/getting-started/componentsindex.html#4-result-components
click on ReativeList, ResultList, etc. links

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all

**Comment by bietkul** [comment]
Thanks for reporting the issue, it has been fixed now.
