### ISSUE TITLE
How to use DataSearch as controlled component ?

### ISSUE THREAD

**Issue by chloesun** [appbaseio/reactivesearch#968]
**Issue Type:**
Sorry to post this issue here, I was hoping to get some help.
Here is my question on StackOverflow: https://stackoverflow.com/questions/55976186/how-to-use-datasearch-as-controlled-component-from-reactivesearch

**Platform:**
ReactiveSearch for Web 

**Description:**
I'm new to ReactiveSearch library, and I implemented the DataSearch component with autosuggestion as my in-site SearchBar. I added `value` and `onChange` to in order to store the input value as a state, but as soon as I added the value prop, I can't type in the search bar anymore. What's wrong?

I also want to know what kind of callback function can I use when I click one of the suggestions to trigger some event, I tried `onClick`, but it didn't work. Here is my code, any help is appreciated!
```
import * as React from 'react';
import {
  ReactiveBase,
  DataSearch,
} from '@appbaseio/reactivesearch';

import './SearchBar.scss';

export default class SearchBar extends React.Component {
  constructor(props) {
    super(props);
    this.state = { searchTerm: '' };
  }

  handleInputChange = (event) => {
    this.setState({ searchTerm: event.target.value });
  };

  handleSearch = () => {
  // do something...
  };

  public render() {
    return (
      <React.Fragment>
        <ReactiveBase
          app="rooms,floors,assets"
          url="http://localhost:9200"
          headers={{
            'Access-Control-Allow-Origin': '*'
          }}
          style={{ display: 'inline' }}
        >
          <DataSearch
            componentId="SearchRoom"
            dataField={['roomName', 'roomNumber', 'floorName', 'assetName']}
            placeholder="Search for rooms or assets"
            style={{ width: 500, display: 'inline-block' }}
            fuzziness={1}
            value={this.state.searchTerm}
            onChange={this.handleInputChange}
            //how to trigger handleSearch when I click one of the suggestions?
          />
        </ReactiveBase>
      </React.Fragment>
    );
  }
}
```

**Browser:** 
Chrome

**Comment by bietkul** [comment]
Can you please tell the ReactiveSearch version?
FYI we don't support this in 2.0.

**Comment by chloesun** [comment]
"@appbaseio/reactivesearch": "^3.0.0-rc.4"

**Comment by jyash97** [comment]
`onChange` returns the updated value it does not return a `Synthetic Event`. I have updated the Demo of DataSearch component from the docs to use controlled behavior. 

I have also added a callback which would get called when you select any suggestion. You can make use of `downShiftProps` to achieve this. 

Check the app [here](https://codesandbox.io/s/ommkkyv2y). You can also read more about this props [here](https://opensource.appbase.io/reactive-manual/search-components/datasearch.html).

**Comment by chloesun** [comment]
@jyash97  Thank you so much! This clarifies a lot!

**Comment by chloesun** [comment]
@jyash97 Thanks for your previous update! I notice this works perfectly when I select an option from the drop-down selection list, but it doesn't trigger the event when my input matches exactly one of the selections and I just click "Enter" on keyboard. How to trigger the event when I either click "Enter' or manually select a suggestion from the drop-down list? Thanks a lot!!

**Comment by jyash97** [comment]
You can use `onValueSelected` prop in `DataSearch`  it provides the cause of event like `ENTER_PRESS ` or `SUGGESTION_SELECT`, or you can add `onKeyDown` method on `DataSearch`. Read more [here](https://opensource.appbase.io/reactive-manual/search-components/datasearch.html#extending).
