### ISSUE TITLE
Clear DataSearch input element without the clear text icon (Vue)

### ISSUE THREAD

**Issue by rjacques** [appbaseio/reactivesearch#970]
Hi,

Is there a way or a method that I can call to clear the DataSearch input element without clicking the clear text icon. 

For my implementation I would like to clear the input when a user clicks outside. 

Thanks!

**Comment by bietkul** [comment]
For now, there is no straight way to do that.
You can check this workaround https://codesandbox.io/s/43mo5xv32x

**Comment by bietkul** [comment]
We'll track it here #971
