### ISSUE TITLE
Bug: Not Excluding Fields From Suggestions

### ISSUE THREAD

**Issue by dajinchu** [appbaseio/reactivesearch#975]
**Issue Type:**
Bug

Related to #417 

**Platform:**
Web

**Description:**
Include/excludeFields don't apply to suggestion queries. I have extremely large fields in my documents that I need to exclude for network performance, but while setting excludeFields inside ReactiveList will exclude the fields when searching, the requests being sent to get suggestions do not exclude.

**Minimal reproduction of the problem with instructions:**

```
const App = () => (
  <ReactiveBase app="sites" url="http://localhost:3000">
    <DataSearch
      componentId="searchbox"
      dataField={["title"]}
      autosuggest={true}
    />
    <ReactiveList
      componentId="searchresult"
      dataField="title"
      excludeFields={["content"]}
      react={{
        and: ["searchbox"]
      }}
    />
  </ReactiveBase>
);
```

**Reactivesearch version:** 3.0.0-rc.6

**Browser:** all

**Potential fix:**

This line in ReactiveList is what pulls in the includeFields/excludeFields prop: https://github.com/appbaseio/reactivesearch/blob/2e67607b336fdbec2fcdec3ef3206b0453b6491a/packages/web/src/components/result/ReactiveList.js#L84

Maybe it needs to be added to DataSearch somewhere here: https://github.com/appbaseio/reactivesearch/blob/2e67607b336fdbec2fcdec3ef3206b0453b6491a/packages/web/src/components/search/DataSearch.js#L51 ?

**Comment by dajinchu** [comment]
My current workaround is to add 
```
      defaultQuery={() => {
        return {
          _source: { includes: ["*"], excludes: ["content"] }
        };
      }}
```
to the DataSearch component.

**Comment by bietkul** [comment]
Yes, for suggestions it won't work because it executes the internal query.
And `defaultQuery` is the right way to do that.

**Comment by dajinchu** [comment]
Okay. I would also like to prevent the suggestion query from doing other things like highlighting and aggregating filters. I see how in defaultQuery, I can add options to the query, but is it possible to remove options like `highlight` and `aggs` ?

**Comment by bietkul** [comment]
You can set `highlight` as `false` and override the `aggs` by using `defaultQuery`.

**Comment by rgb-panda** [comment]
@dajinchu your workaround for me only works on the first search, anything beyond that seems to revert to the original default query with includes * and size 100

Were you able to figure it out?
