### ISSUE TITLE
Highlight and Custom Highlight in Vue

### ISSUE THREAD

**Issue by rjacques** [appbaseio/reactivesearch#976]
Hi Everyone,

I'm trying to get highlighting to work in Vue, but I'm stuck.
I see that there is an example here: https://reactivesearch-vue-playground.netlify.com/?selectedKind=Search%20Components%2FDataSearch&selectedStory=With%20highlight&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs

But it doesn't seem to work. 

I tried to implement the custom highlight solution from the docs in my app, but none of the arrow function/template literal examples from the docs seem to work in my app. 

Thanks!

**Comment by rjacques** [comment]
I tried the following: https://codesandbox.io/s/m4w5poo8pj

**Comment by bietkul** [comment]
Fixed in the latest version.

**Comment by rjacques** [comment]
Thanks guys. I now get `<mark></mark>` escaped in my highlighting. It seems to want to work, but the highlighting syntax is not interpreted as HTML. Example here: https://codesandbox.io/s/reactive-list-e3n02
Thanks!

**Comment by rjacques** [comment]
When I replace `<div class="book-header">{{ item.original_title }}</div>` with`<div class="book-header" v-html="item.original_title"></div>` the highlighting works. But I am not sure if this expected behaviour.
