### ISSUE TITLE
bug: onQueryChange listener stops

### ISSUE THREAD

**Issue by lakhansamani** [appbaseio/reactivesearch#978]
**Issue Type:**
bug

**Platform:**
Web

**Description:**
If we pass `key` prop to `ReactiveList` component and update that prop for force re-rendering of component, `onQueryChange` prop stops working

**Screenshots:**

**Minimal reproduction of the problem with instructions:**
* Demo: https://codesandbox.io/s/n7xv5p6vj0
* Open the console, try to search and hit enter, result component will be rendered and `onQueryChange` will be called. Then click `update key` button and try to follow the same procedure, ReactiveList will re-render but it will stop listening to `onQueryChange`, so there won't be any console logs after you change key.

**Reactivesearch version:** 3.0.0-rc.8

**Browser:** all

**Comment by bietkul** [comment]
#667

**Comment by kvin97** [comment]
Shall I work on this bug...I have to contribute to an open source project as an assignment in university. Can you assign this to me?
