### ISSUE TITLE
ReactiveList does not display paging control

### ISSUE THREAD

**Issue by vincepich** [appbaseio/reactivesearch#985]
**Issue Type:**
bug

**Platform:**
Web

**Description:**
ReactiveList component with the pagination = {true} setting does not display page numbers by returning this error to the console:
index.js: 1375 Warning: Failed prop type: Invalid `total` of type` object` supplied to `ReactiveList`, expected` number`.
I'm using elasticsearch 7.0.1

**Screenshots:**

**Reactivesearch version:** 3.0.0-rc9

**Browser:** all

**Comment by jyash97** [comment]
Related #948

**Comment by scottmont** [comment]
Why is this closed ?

**Comment by vincepich** [comment]
> Why is this closed ?

Because in v3.0.0-rc10 is fixed!

**Comment by scottmont** [comment]
You are amazing!! Thank you so much I have been struggling with this.

**Comment by scottmont** [comment]
heads up i installed rc12 and get this  ( using node v10.15.3  / react 16.2.0 ) 

TypeError: _react2.default.forwardRef is not a function

./node_modules/@appbaseio/reactivesearch/lib/components/basic/URLParamsProvider.js
```
exports.default = _react2.default.forwardRef(function (props, ref) {
 	return _react2.default.createElement(ConnectedComponent, _extends({}, props, { myForwardedRef: ref }));
 });
```

**Comment by scottmont** [comment]
Can disregard that using latest react everything works great.  16.8.6 - react
