### ISSUE TITLE
DataSearch on enter event

### ISSUE THREAD

**Issue by joergac** [appbaseio/reactivesearch#992]
**Issue Type:**
enhancement

**Platform:**
Web

**Description:**
I am looking of a way to handle the enter event on DataSearch. 

When the user writes something and hits enter I'd like to redirect him to a search page. 

I am not talking about the suggestions though.

I am already handling the case where the user hits enter on a suggestion. I only want to redirect the user to the search page if he just writes something and hits enter without selecting a suggestion.

**Reactivesearch version:** 3.0.0-rc10

**Comment by bietkul** [comment]
You can use `onKeyDown` prop from `DataSearch` to check if the enter key is being pressed.
```
handleKeyDown = (e) => {
    if (e.key === 'Enter') {
      console.log('do something');
    }
  }
```

**Comment by joergac** [comment]
Using `onKeyDown` (I suppose it got changed in version 3.0.x) worked! Thanks @bietkul!
